### ISSUE TITLE
Can I add a simple GUI graphic for now?

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#10]
I want to represent a tempo sync on/off button with a symbol. Is there an ok way to do it now without you having implemented an advanced gui system?

**Comment by RobinSchmidt** [comment]
hmm...i think, maybe you could subclass my RButton class and override the paint() method

**Comment by elanhickler** [comment]
Could you give me an example code to use? Add your time to a future bill for me.

**Comment by RobinSchmidt** [comment]
ok - maybe just tell me which button in which of your projects i should replace.
