### ISSUE TITLE
trying to build TestJuraPlugin for Mac for Jamal, build error.

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#101]
Trying to build TestJuraPlugin for Mac for Jamal, getting this error:

Unknown type name AutomatableWidget in jura_AutomatableWidget.h

line 19
line 74

strange.

Edit: Also, where are your waveforms for the Straightliner? That's what Jamal wants to check out.
Edit: Actaully, Jamal has his own waveforms he wants to use.

**Comment by RobinSchmidt** [comment]
ok, i'll look into this tomorrow. for the support files (waveforms, presets, colorschemes, etc.) - they can be used from the original download archive on my website. but i think, i'll prepare a support-file package for the chainer (including all the presets for all the plugins). ...but on mac, we are not allowed to drop the support files into subfolders of the actual plugin, right?

**Comment by elanhickler** [comment]
correct, because the plugin will have two subfolders, one VST version one AU version, so like my previous ideas, I say compile these default things with the binary, embed it... at least for presets. That way factory presets are never changeable and always easily found by the program, no need to have confusing factory preset files on the computer that can be modified.... If you have large files you want to include then there's a specific folder for that, and so you'll really need an installer or a locator function in the program so the USER can tell the program where it is.

**Comment by RobinSchmidt** [comment]
ok, the build issue should be fixed. i also fixed a most of the mac specific compiler warnings

**Comment by elanhickler** [comment]
We need AU version, and build universal, not 64 bit. I can't build the AU version due to some missing AU file. Can you build AU?

**Comment by RobinSchmidt** [comment]
i just emailed with jamal. i think tomorrow, i will need some time to work on a mac version of chainer. i have close to zero experience with building (or even using) audio plugins on mac. ...new stuff to learn...

**Comment by elanhickler** [comment]
my problem is I'm getting error exit code 3 something to do with missing AU rez file or something. Lorcan has solved this problem easily, don't know what he did.

related: https://forum.juce.com/t/problems-getting-started-rez-auresources-r/9054/2

**Comment by RobinSchmidt** [comment]
hmm...i have just updated my repo to 

1) build the projucer (works)
2) build the plugin host (works)

when i now build the plugin host and the TestPlugInJura and then launch the plugin host and then "update the list of available plugins", my chainer plugin appears in the list (which i also had built previously). i can plug it in, but the gradients on the gui are messed up (wtf? is this bug that will be fixed by updating juce?) and it doesn't produce sound (tried with acidevil, which doesn't use samples). using the AUMidiSynth produces sound

hmm...apparently the osx project dumps the compiled files into some default mac plugin folder, right? otherwise the plugin host wouldn't have found my plugin without pointing it to the appropriate folder.

how do you test on mac? what host do you use? i'm not getting this au rez file nonsense over here. mac is a pita indeed as the forum thread says

**Comment by elanhickler** [comment]
im using REAPER http://reaper.fm/

location for XCode builds: 
/Users/elan/Library/Audio/Plug-ins/VST
/Users/elan/Library/Audio/Plug-ins/Components

that Library folder is hidden, the only way to ge there is with command + shift + G

the proper location for installing to is 
Library/Audio/Plug-Ins/VST
Library/Audio/Plug-Ins/Components

e-mail me the AU file so i can test.

Right-click and compress the file before sending, .vst and .component files are actually folders in disguise.

**Comment by RobinSchmidt** [comment]
ok...i have found them in the hidden folder (again - hidden folder: wtf?!) and zipped the .component and .vst. i have put them on my server:

www.rs-met.com/temp/TestPluginJURA.component.zip
www.rs-met.com/temp/TestPluginJURA.vst.zip

the "component" is the au, right? and to properly install them, these files should be copied into the folders:

Library/Audio/Plug-Ins/VST
Library/Audio/Plug-Ins/Components

as you said?

**Comment by RobinSchmidt** [comment]
btw. where in xcode can i choose between debug and release build? i found no option for that. i don't even know, if these builds above are debug or release

**Comment by RobinSchmidt** [comment]
oh - i have just seen that in my jucer file all the OSX fields are empty (base sdk, deployment target, architecture) ...i guess, it will use some default settings then. do you mean, i should set them explicitly?

**Comment by RobinSchmidt** [comment]
> location for XCode builds

seems like you can set this up in the jucer file: there are options for vst and au binary location.

....ooohhh....but it seems these fields are not editable

**Comment by RobinSchmidt** [comment]
>>on mac, we are not allowed to drop the support files into subfolders of the actual plugin, right?
> correct, because the plugin will have two subfolders, one VST version one AU version

is this the only reason? in this case, i'd say, we can drop the files just in either one of the two folders - say AU, because that's the default format on mac - and then let the other plugin format refer to that folder, too. relative paths also include the option to go up one level...

**Comment by RobinSchmidt** [comment]
```cpp
if(this->isNotAU())
  presetFolder = "../Components/MySynthPresets";
else
  presetFolder = "MySynthPresets";
```
...or something

**Comment by elanhickler** [comment]
Product --> Scheme --> Edit Scheme --> Run --> Build Confirguation --> Release

to build: Product --> Build

**Comment by elanhickler** [comment]
yes, try OSX deployment target 10.9 and OSX architechture universal binary at least for release.

universal means 1 file for 32/64 bit. Will save you a lot of headache.

**Comment by elanhickler** [comment]
user presets go in:

"~/Library/Audio/Presets/Company/Product/example_user_preset.xml"
~ means user folder.

Let's do away with factory preset folder and just include it in the binary, a lot less headache. Also, we should do a little edit to your framework so we can provide an init patch in the binary, do away with all the junk about setting init patch in code. We should set that via the actual synth gui, save an init path, easy. Then in code you just connect that binary to the variable "use this xml file for init patch"

hmm, not sure how to programmatically make a list of factory preset binary though.

**Comment by RobinSchmidt** [comment]
> Product --> Scheme --> Edit Scheme --> Run --> Build Confirguation --> Release

ahh - ok done: i built a new component in release setting, universal binary and sdk/target 10.11 (10.9 and 10.10 didn't work):

www.rs-met.com/temp/TestPluginJURA.componentRelease.zip

strangely, the VST folder seems to have disappeared..

also, i noticed, when you hold the play/run button you can select which of the schemes gets built. there are Run, Profile, etc. however, in "Edit Scheme" there is one more: "Release", which seems not available on click-and-hold.

**Comment by RobinSchmidt** [comment]
> Let's do away with factory preset folder and just include it in the binary, a lot less headache.

well, i wouldn't know how to do that without a lot of headache

**Comment by RobinSchmidt** [comment]
you'll probably have to deal with such nasty stuff as binary resource files or something

**Comment by elanhickler** [comment]
juce makes it easy, not a headache at all to manage binary resources.

> well, i wouldn't know how to do that without a lot of headache
whatever, one step at a time. First thing you need to do is separate user/factory presets. Use files/folders if you want. It will be simple to switch over to binary after you get that working, I will switch to binary, you don't have to. It may require little to no editing of whatever you come up with to separate user/factory.

**Comment by RobinSchmidt** [comment]
first thing i need to do is to get a working version of chainer on mac...

**Comment by elanhickler** [comment]
Jamal has Mac version 10.11, and 10.9 definitely works. You are doing something wrong. I'll test on my 10.11 computer.

**Comment by RobinSchmidt** [comment]
> 10.9 definitely works. You are doing something wrong

it's probably the separate SDK that has to be installed for targeting 10.9 which i don't have installed

**Comment by elanhickler** [comment]
I didn't have to do anything special to make it work.

**Comment by elanhickler** [comment]
your au plugin works on REAPER, but Jamal can't test until you get your version down to 10.10, but I would aim for 10.9.

**Comment by elanhickler** [comment]
I'll get your latest commit and look at the jucer... and try to build.

**Comment by elanhickler** [comment]
first problem: don't set an OSX base SDK version, I can't test to see if this would actually make it build for you, but I'd put "default" for that and try again.

**Comment by elanhickler** [comment]
ok yes, now I am getting an error that you perhaps got: "no SDK with name or path" when trying to use SDK 10.9, so yes, set the SDK version to default, but your TARGET version can be anything.

**Comment by elanhickler** [comment]
Jamal will probably tell you this, but just want to be clear what he is looking for, so that you're on the same page. He eventually wants this:

3 modes of wavetable synthesis:

1. single cycle (like how Straightliner works now) [wavetable contains 1 cylcle]
2. single cycle with morph parameter to fade to other cycles [wavetable contains multiple cycles]
3. wavetable contains multiple cycles, but you iterate through every cycle one after the next, i.e., standard looping sample playback.

But anyway, get your JURAPlugin built for 10.9 and that's the first step, Jamal will play with Straightliner, and he will then probably start tell you his needs and you can talk to him about cost.

btw, the way Straightliner tries to find the path of the .wav file is completely messed up :) you'll have to load the wavetable in every time you start up Straightliner because it records the wrong path (on windows even!).

**Comment by RobinSchmidt** [comment]
i will continue with this tomorrow. for now, i have added the 
```
if(numChannels != 2)
  return;
```
thing to my chainer processBlock to prevent it from crashing when some host tries to use it with mono or more-than-2 channels

**Comment by RobinSchmidt** [comment]
> the way Straightliner tries to find the path of the .wav file is completely messed up :) you'll have to load the wavetable in every time you start up Straightliner because it records the wrong path (on windows even!)

it records the wrong path? you mean, in the preset .xml, the saved path is wrong?

**Comment by elanhickler** [comment]
![image](https://user-images.githubusercontent.com/9116575/31846879-7618f8ea-b5c6-11e7-8cbf-a6220d00f940.png)

**Comment by RobinSchmidt** [comment]
:-O this is really weird! what path is stored in the preset xml file? it's an attribute of an Osc object with name "AudioFileRelativePath"

**Comment by elanhickler** [comment]
```xml
  <OscSection PatchFormat="1">
    <Osc1 PatchFormat="1" AudioFileRelativePath="Z:\GospelMusicians\Waves.zip wavetable test\cycles\49_Digital_6-Aminus1_single.wav !error!"
          Mute="0" Level="0" LevelByKey="0" LevelByVel="0" Pan="0" MidSideRatio="0.5"
          StartPhase="0" StartPhaseByKey="0" StartPhaseByVel="0" TimeReverse="0"
          PolarityInvert="0" FullWavePhaseWarp="0" HalfWavePhaseWarp="0"
          CombHarmonic="1" CombAmount="0" Tune="0" DetuneHz="0" StereoDetuneSemitones="0"
          StereoDetuneHz="0" PitchModulationDepth="0" SpectralContrast="1"
          SpectralSlope="0" HighestHarmonicToKeep="1024" LowestHarmonicToKeep="1"
          PhaseScale="1" PhaseShift="0" EvenOddRatio="0.5" EvenOddPhaseShift="0"
          StereoPhaseShift="0" EvenOddStereoPhaseShift="0"/>
    <Osc2 PatchFormat="1" Tune="-36" AudioFileRelativePath="67_Stuff_2-Aminus1[1].wav !error!"
          Mute="1" Level="0" LevelByKey="0" LevelByVel="0" Pan="0" MidSideRatio="0.5"
          StartPhase="0" StartPhaseByKey="0" StartPhaseByVel="0" TimeReverse="0"
          PolarityInvert="0" FullWavePhaseWarp="0" HalfWavePhaseWarp="0"
          CombHarmonic="1" CombAmount="0" DetuneHz="0" StereoDetuneSemitones="0"
          StereoDetuneHz="0" PitchModulationDepth="0" SpectralContrast="1"
          SpectralSlope="0" HighestHarmonicToKeep="1024" LowestHarmonicToKeep="1"
          PhaseScale="1" PhaseShift="0" EvenOddRatio="0.5" EvenOddPhaseShift="0"
          StereoPhaseShift="0" EvenOddStereoPhaseShift="0"/>
    <Osc3 PatchFormat="1" Tune="-36" PitchModulationDepth="1.1799999999999997158"
          AudioFileRelativePath="Z:\GospelMusicians\Waves.zip wavetable test\SY99_Analog_Saw_2-Aminus1[2].wav !error! !error! !error!"
          Mute="1" Level="0" LevelByKey="0" LevelByVel="0" Pan="0" MidSideRatio="0.5"
          StartPhase="0" StartPhaseByKey="0" StartPhaseByVel="0" TimeReverse="0"
          PolarityInvert="0" FullWavePhaseWarp="0" HalfWavePhaseWarp="0"
          CombHarmonic="1" CombAmount="0" DetuneHz="0" StereoDetuneSemitones="0"
          StereoDetuneHz="0" SpectralContrast="1" SpectralSlope="0" HighestHarmonicToKeep="1024"
          LowestHarmonicToKeep="1" PhaseScale="1" PhaseShift="0" EvenOddRatio="0.5"
          EvenOddPhaseShift="0" StereoPhaseShift="0" EvenOddStereoPhaseShift="0"/>
    <Osc4 PatchFormat="1" Tune="-36" AudioFileRelativePath="Z:\GospelMusicians\Waves.zip wavetable test\Triangle_Fdbk_5-Aminus1[2].wav !error! !error! !error!"
          Mute="1" Level="0" LevelByKey="0" LevelByVel="0" Pan="0" MidSideRatio="0.5"
          StartPhase="0" StartPhaseByKey="0" StartPhaseByVel="0" TimeReverse="0"
          PolarityInvert="0" FullWavePhaseWarp="0" HalfWavePhaseWarp="0"
          CombHarmonic="1" CombAmount="0" DetuneHz="0" StereoDetuneSemitones="0"
          StereoDetuneHz="0" PitchModulationDepth="0" SpectralContrast="1"
          SpectralSlope="0" HighestHarmonicToKeep="1024" LowestHarmonicToKeep="1"
          PhaseScale="1" PhaseShift="0" EvenOddRatio="0.5" EvenOddPhaseShift="0"
          StereoPhaseShift="0" EvenOddStereoPhaseShift="0"/>
  </OscSection>
```

**Comment by RobinSchmidt** [comment]
maybe it has problems with the whitespaces in the folder name? ...but that wouldn't explain the strange alert box which apparently prepends the plugin dll location

WAIT! that's it! it interprets the Z:\GospelMusicians\Waves.zip wavetable test\cycles\49_Digital_6-Aminus1_single.wav as RELATIVE path! and it's apparently on another drive! we need an absolute path!

**Comment by RobinSchmidt** [comment]
at the time i wrote this, i was just assuming all samples sit in a subfolder of the plugin anyway

**Comment by RobinSchmidt** [comment]
i also realize that the oscs apparently save all the parameters, even when they are at their default settings. actually, my intention was to keep preset files lean and store parameters only when they are not at their default/reset value. neutral settings such as `Tune="0" DetuneHz="0" StereoDetuneSemitones="0"` should actually not be written into the file. ...another thing to check out. ...but that's off topic

**Comment by elanhickler** [comment]
what is the benefit of a lean preset?

**Comment by RobinSchmidt** [comment]
it doesn't take much space and doesn't have any irrelevant data

**Comment by RobinSchmidt** [comment]
i kinda despise bloat

**Comment by RobinSchmidt** [comment]
it's also about readability of the xml. imagine how much easier it would be to read, if all the "do-nothing" values would just not be there

**Comment by elanhickler** [comment]
I'd rather have bloat + maintainability, no one is going to read the XML. But oh well! So far I've been breaking all my presets with any update I make. Can't seem to avoid it. Maybe I'll learn eventually.

**Comment by RobinSchmidt** [comment]
we may sometimes disagree on what is the best way to do things. in these cases, maybe i can make things optional in my framework or maybe you can just override these things in your derived framework

btw. making progress with the build. chainer does now actually produce sound (in the juce plugin host) :-)

**Comment by RobinSchmidt** [comment]
i have made some release packages for the chainer for mac and windows:

www.rs-met.com/software/freebies/ChainerWindowsX64_v17.10.zip
www.rs-met.com/software/freebies/ChainerMacAU_v17.10.zip

> the proper location for installing to is
> Library/Audio/Plug-Ins/Components

hmm...i have dropped the .component file there (and also the folders with the support files), but the plugin isn't seen by tracktion ...it is seen by the juce plugin-host, though. weird. and there's a whole long list of plugins provided by apple - but i don't see them in this folder. where are they?

...and my sample-paths don't work. apparently, the application location is not the location of the .component but somewhere inside the component (as you said, it's actually a folder in disguise, this makes sense). ...and my paths in the xml presets use backslashes. i think, i will need to batch convert all the presets to use forward slashes

**Comment by elanhickler** [comment]
Well, I would just follow the paths I've given you and don't worry about traction. If you want, you could ask a questions here or start a new thread: https://www.kvraudio.com/forum/viewtopic.php?f=33&t=485068

Also, why don't you have a VST for Mac? XCode will build both VST and AU together.

Also, I know how to create an installer for Mac, but you have to be ready to put application files in the proper place. Here's a bunch of path ideas I just put together:

Manual, Non-user-specific files:
	`/Library/Application Support/Vendor/Product`

	OR

	`/Library/Audio/Presets/Soundemote/` (non-user-specific version of presets folder)

User files examples:
	use this for user-specific preferences:
		`~/Library/Application Support/Vendor/Product`

		OR

		`~/Library/Audio/Presets/Soundemote/PrettyScope/Preferences/example_user_preference.xml`

		OR 

		you could remove the extra Preferences/ part
		Anything goes inside /Soundemote. It's whatever you want.

	use this for presets
		`~/Library/Audio/Presets/Soundemote/PrettyScope/Presets/example_user_preset.xml`
		`~/Library/Audio/Presets/Soundemote/PrettyScope/Colormaps/example_user_colormap.xml`

		OR

		if you don't need to organize presets into differet types you can remove a subfolder.

**Comment by RobinSchmidt** [comment]
> I would just follow the paths I've given you 

 but that's what i did. i put it into Library/Audio/Plug-Ins/Components
...is this where you put your stuff, too? and can we have a vendor subfolder there?

>and don't worry about traction

tracktion is actually my favorite DAW and i'd like to use it! but anyway, eventually, i need my chainer work with any host anyway. 

i didn't include a vst - because - why have both? isn't that needlessly redundant? 

i don't really like the idea of scattering the files all over the place. but maybe that's the standard on mac and users expect these files there?

**Comment by elanhickler** [comment]
I'm saying, don't worry that traction points to the wrong folder, just add an audio plugin folder to it. Can't a user do that?

I gave you plenty of examples of what you could do. You need at least TWO locations. One for user-specific, one for non-user-specific. That's not scatting files all over the place.

I'll find out whether there's a point in offering both VST and AU for mac users.

**Comment by RobinSchmidt** [comment]
> just add an audio plugin folder to it. Can't a user do that?

well, i didn't find this option on the gui page where the plugins are configured. so i figured, it may be impossible on mac because it's well defined where the plugins should be. but i have no idea. maybe the option is hidden somewhere and need to look closer

**Comment by RobinSchmidt** [comment]
> That's not scatting files all over the place.

i said scattERing! haha :-D

**Comment by elanhickler** [comment]
😞

**Comment by RobinSchmidt** [comment]
the gradients work now on mac ...and also look better on windows. and i think, they are more efficient to draw as well. opening a gui window feels more snappy, at least (you, know, i normally use debug builds and also have not the fastest machines).

..will look into the path issues and your other issues tomorrow

**Comment by elanhickler** [comment]
yayyyy

**Comment by RobinSchmidt** [comment]
ok, i updated the archive:

www.rs-met.com/software/freebies/ChainerMacAU_v17.10.zip

if the content of this archive is dropped into:

Library/Audio/Plug-Ins/Components

the chainer was found by tracktion (but i think, it's not allowed to put it into a subfolder). also, Straightliner finds its presets and waveforms now. it's probably not good practice to simply drop the presets, samples etc. into that folder. perhaps they should go somewhere into Users/UserName/Documents so the user has write access as well. but that then would call for making an installer. how is this done on mac? is this easy?

**Comment by elanhickler** [comment]
installer on mac is easy, 

Also, I didn't list User/Username/Documents as a possible path, I wouldn't use it. See https://github.com/RobinSchmidt/RS-MET/issues/101#issuecomment-339162306 for available paths.

**Comment by RobinSchmidt** [comment]
why not? /Library/Audio has no write access for the user. i assume the same goes for /Library/Application Support/

**Comment by elanhickler** [comment]
download this to make an installer: https://sourceforge.net/projects/macpkg/

It does have write access for user.

**Comment by RobinSchmidt** [comment]
not on my machine. right-click -> get info -> "you can only read". for both folders

**Comment by elanhickler** [comment]
I'm telling you the folders that I was told to use when I asked on KVR, and people seemed in agreement, I wouldn't go against that advice.

What happens when you try to put a file in there? It asks for password, right? It's fine.

Anyway, point is, you can't put stuff next to the .component and .vst. Once you allow to have files elsewhere, it will solve a big problem for my plugins, I can make presets automatically "findable" but the plugin.

**Comment by RobinSchmidt** [comment]
> It asks for password, right? It's fine.

no. that's not fine. i want to use it for user presets, too. i don't like the idea of having distinct factory and user preset. ...then that would be already 3 folders. total file-scattering mayhem! :-P

**Comment by elanhickler** [comment]
But you HAVE to separate factory and user presets! Even on windows. Factory Presets should be uneditable, and completely locked away.

**Comment by RobinSchmidt** [comment]
why? i'm not really sold on this idea...

**Comment by RobinSchmidt** [comment]
it just makes everything more complicated with no real benefit

**Comment by elanhickler** [comment]
Ok, but could you allow me to do that?

Factory presets are something that is created by me the developer for the user. The user can then make their own presets, save them, and the presets of all his plugins are in one place, not mixed in with factory presets.

If user is allowed to mess up his factory presets, he will have to re-install to get those back.

**Comment by RobinSchmidt** [comment]
i must first put some infrastructure in place to allow custom preset folders at all. currently, i have more or less hardcoded the plugin dll folder as root-folders for the presets. ...maybe a member-function AudioModule::getPresetFolder() ...that you can override in your subclass and then return either the factory or user-preset folder? ...i must think about, how that can be done best. first i need to make it customizable at all - i'll try to keep this in mind for later extensibility

**Comment by elanhickler** [comment]
Do you have a link to the chainer Windows version? You only posted "ChainerMacAU_v17.10.zip"

**Comment by RobinSchmidt** [comment]
somewhere above, i posted both links - here they are again:

www.rs-met.com/software/freebies/ChainerWindowsX64_v17.10.zip
www.rs-met.com/software/freebies/ChainerMacAU_v17.10.zip

but the windows-version is not yet updated

**Comment by elanhickler** [comment]
can I post those links here for this person?: https://www.kvraudio.com/forum/viewtopic.php?p=6906297#p6906297

**Comment by RobinSchmidt** [comment]
ok - but note that this is a total pre-alpha build, so please link only with this qualification well understood. ...actually, my plan is to release the chainer as freebie to christmas and not make much noise before, so it comes as sort of a surprise gift

**Comment by elanhickler** [comment]
an easy to implement preset selection system

gif: https://puu.sh/yaIKn/909f005c49.gif

https://puu.sh/yaIMh/d94f406f2a.png
![image](https://user-images.githubusercontent.com/9116575/32179566-f5355244-bd4c-11e7-8970-b64048751d44.png)

**Comment by RobinSchmidt** [comment]
what synth is this? the gui graphics look good. nice small and sharp font

**Comment by elanhickler** [comment]
Native Instruments Massive

**Comment by elanhickler** [comment]
no longer relevant
