### ISSUE TITLE
Potential Customer looking for multi-band compressor and EQ

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#103]
I have a guy, he says he has a $1000 budget, and needs Protools/AU/VST. Some of that is going to protools publishing, installer, and any other  unexpected requirements.

He needs a multiband compressor and EQ.

I don't know if it's enough to pay your library license fees and pay for my time creating the plugin. The GUI can actually use your default look (actually the GUI won't even be shown to the user, essentially there's little to no GUI work to do), so that's why the budget is low on this project.

I propose $300 of this go to you so that I can create this product using your EQs and compressors. I know it's not $500 to $2000, but I'm not sure this project can even move forward if you are asking that much. I mean, it's possible $500 could go to you. I need to know more about his ACTUAL DSP budget, which is not $1000.

**Comment by RobinSchmidt** [comment]
who is it? what company? would he be willing to open source it? (in this case, i'd charge nothing)? i think 1000$ for custom development of 2 products, all in, is a very low budget. how would actually your hourly rate come out with this? wouldn't you be selling yourself short? the gui won't be shown? why is that? is it just for personal use?

**Comment by elanhickler** [comment]
it's 1 product, that requires multiband compressor and EQ, the GUI is not shown because all the GUI needs for the end user is a preset selector. It's pretty simple.

I think I would charge $30 an hour. All I have is this: https://youtu.be/xBsarkMKYjw

here's the juce thread: https://forum.juce.com/t/seeking-juce-dev-for-custom-eq-multiband-compression/24422

**Comment by RobinSchmidt** [comment]
ok, then go ahead, if you think, this will reasonably pay for your time investment. i think, 300 for the license is fine in this case.

how are you planning to go about multiband eq? linkwitz-riley based band-splitting and using a compressor on each band and recombine? i tend to think that dynamic eq would be the cleaner solution (less allpass artifacts). ...however

**Comment by elanhickler** [comment]
redundant thread
