### ISSUE TITLE
Defaults are no longer loaded

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#107]
Not sure when it started happening, but my JerobeamMushroom synth no longer loads defaults. For some reason it seems to be loading the max values for all parameters.

Edit: Important detail: For example, the highpass filter is set to max value when you load a fresh instance, yet the slider shows as if it's at it's actual default value. All sliders have are at max, but appear to be at default value.

**Comment by RobinSchmidt** [comment]
hmm - starnge. are you sure this is my bug? i don't see it happening in chainer

> Not sure when it started happening

can you try to figure this out?

**Comment by elanhickler** [comment]
clue: if I save an init patch (after loading a fresh copy of spiral generator), then load that init patch on to a fresh copy of spiral generator, it's fine.

I would prefer to use a binary init patch file to initialize fresh spiral generators. I'll see if I can find any more info on why it's not loading defaults. Seems to only affect some parameters.

**Comment by RobinSchmidt** [comment]
i usually just set the parameters to their default values when i create them in the constructor of the audio module. and these default settings then *are* my init patch

**Comment by elanhickler** [comment]
robin, that's not good enough 😞 

There's RESET values, there's DEFAULT values, there's INIT values, and then there's the center marker value, that all needs to be separate. I just haven't complained about it yet, but eventually I will.

**Comment by RobinSchmidt** [comment]
then why not just call setValue right after the parameter has been created and the callbacks have been wired up?

**Comment by elanhickler** [comment]
ok example. LFO gain.

reset value = 1
marked value = 0
init value = 1

**Comment by RobinSchmidt** [comment]
no - the marked value is the reset value (i call it default value but whatever), i thought, we already agreed on that:

> Edit: Hmm, actually, no, reset value == slider marked value

**Comment by RobinSchmidt** [comment]
if you want your init value different from the default/reset/marked value, just call setValue on the parameter right after creation (and setting up the callback and mapper). i don't see the problem

**Comment by elanhickler** [comment]
damnit... this is confusing. All I know is that I want to set init values with an xml patch. Using a GUI is better, and you can even set default modulation settings. Reset values do not always equal default values.

**Comment by elanhickler** [comment]
I can't think right now, trying to f***ing solve this stupid bug where parameters are not being set on init.

**Comment by RobinSchmidt** [comment]
> I want to set init values with an xml patch

ahh, now that's a different story. in straighliner, i load an init patch in the constructor, for example

**Comment by elanhickler** [comment]
ok, let me do that, how's it done?

**Comment by elanhickler** [comment]
Oh my god it will be SO MUCH f***ing easier to set default modulation ranges and settings and all that crap with the GUI and an init xml patch.

**Comment by elanhickler** [comment]
ok i solved my problem:

![image](https://user-images.githubusercontent.com/9116575/31845206-4ddfff6c-b5b3-11e7-8f3a-67719f762fcb.png)

just f***ing FORCE your framework to call setvalue on everything... no idea if it's a bug with your framework, but I really don't know what else it could be, how could I have managed to stop your framework from calling the set value?

**Comment by RobinSchmidt** [comment]
i had to look it up...it's all soo long ago. so, in straightliner i override this:

```cpp
  virtual juce::String getDefaultPresetLocation() override 
  { 
    return getApplicationDirectory() 
      + juce::String("/StraightlinerPresets/000-InitPatchSawtooth.xml");
  }
```

it's a method inherited form AudioModule. then, somehow AudioModule::loadDefaultPreset() gets called. i call it explicity in chaine when i create the module. i guess, you could call it at the end of the constructor of your module. ...or in the plugin creation function (that thing that creates the AudioModule, wraps it into an AudioPlugin, etc).

then, when a file with given name exists, it will be loaded on init (if the file doesn't exist, nothing happens)

**Comment by RobinSchmidt** [comment]
> just f***ing FORCE your framework to call setvalue on everything... no idea if it's a bug with your framework, but I really don't know what else it could be, how could I have managed to stop your framework from calling the set value?

what? i don't get that. if you create a parameter, it gets initialized to the default value. you are free to set it to any other value thereafter, if you need an init value different from the default/reset value. what's wrong with that?

**Comment by elanhickler** [comment]
some how setValue is not being called automatically when I load a fresh value of Mushroom Generator.

I set the default slider value for highpass filter to .1hz. The filter never gets that value.

**Comment by RobinSchmidt** [comment]
> I set the default slider value for highpass filter to .1hz. The filter never gets that value.

is the callback already wired up at that point?

**Comment by elanhickler** [comment]
We are talking about your framework right now, meaning, that's a question you should be asking yourself. I think you're misunderstanding the issue.

In other words, after I setup the callback, I do this to make sure the callback is actually called on init.
![image](https://user-images.githubusercontent.com/9116575/31845372-df20aed0-b5b4-11e7-9d60-cea31008858b.png)

same code as above, but made clearer for you, because ptr is jura::Parameter, so I'm using your functions directly.

his is how I set default value for slider:

![image](https://user-images.githubusercontent.com/9116575/31845405-1ec8e50c-b5b5-11e7-8b80-fbd0cde33be9.png)

for some reason, your framework is not setting the slider to that default value on init.

**Comment by elanhickler** [comment]
example:
![image](https://user-images.githubusercontent.com/9116575/31845423-5f540bd8-b5b5-11e7-8b09-5e9e1de3e879.png)

this slider appears to be set to 0.1, but it's actually set to max value, 24000

**Comment by RobinSchmidt** [comment]
> We are talking about your framework right now, meaning, that's a question you should be asking yourself. 

no, wiring up the value change callback to the parameter is the responsibility of client code

> after I setup the callback, I do this to make sure the callback is actually called on init.

yes, that's right. you need to call setValue on the parameter AFTER you have wired up the callback. otherwise, the core object will not be updated. ...hmm...i guess, it would make to calll the callback myself in the very moment, you wire it up. 

but then,...it seemed to work before

**Comment by RobinSchmidt** [comment]
yeaaahhh...i think, it makes sense to call the callback with the current value in setValueChangeCallback

**Comment by RobinSchmidt** [comment]
ok, done (not yet tested)

**Comment by elanhickler** [comment]
ok, testing (not yet done)

**Comment by elanhickler** [comment]
It's possible that I've been always setting my default slider values to the default values of all my DSP objects, by habit, but then maybe it JUST FINALLY became apparent that I had a few default DSP values that weren't the same as my audio plugin values.

ok, tested (not yet profited)

WORKS.

**Comment by RobinSchmidt** [comment]
phew! finally!

**Comment by elanhickler** [comment]
close this motha-junka.
