### ISSUE TITLE
1D mode and 2D mode tabs for PrettyScope

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#11]
How would you go about adding tabs to the PrettyScope GUI so we can switch between 1D and 2D mode and show separate controls for each?

**Comment by RobinSchmidt** [comment]
you mean like the tabs in chaosfly? you need to create a button for each tab and make your editor a subclass of RButtonListener - then register your editor as listener to the tab buttons and override rButtonClicked callback. inside this function, you figure out which button has been clicked and show/hide certain gui elements according to the on/off states of the various tab buttons

**Comment by elanhickler** [comment]
i learned how to do this somewhat, now. Still a little confusing at times.
