### ISSUE TITLE
serious issue with modulation system GUI mac, cannot release Mushroom Generator

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#111]
The modulation menu appears behind the plugin GUI, making it unusable.

Can't you just spawn the menu in the gui itself, not as a separate window? It should work exactly like your setup button. Setup button spawns the menu locked to the current GUI. Separate window also has similar issues on windows. If your window is set to "always on top" the modulation menu appears behind.

You should also not automatically close the modulation menu. Sometimes you want to adjust the parameter and the modulation amount at the same time. Wouldn't that also allow the user to have multiple modulation menus open at once? That would be a muuuuuch better user experience.

Ultimately I'd much rather have a modulation menu that's open at all times, or a modulation tab or something that shows all modulation connections at once, but I can make that later. I just need the basic functionality working now.

**Comment by RobinSchmidt** [comment]
> Can't you just spawn the menu in the gui itself, not as a separate window

hmm...i actually like it that it appears right under the slider that is going to be modulated - which may be impossible to do inside the window, if the slider is near the bottom. maybe i can try to use the "always-on-top" option for the modulation menu, too - such that it stays on top of windows that are themselves always on top? might be worth a try.

> You should also not automatically close the modulation menu. Sometimes you want to adjust the parameter and the modulation amount at the same time

ok, good point

**Comment by elanhickler** [comment]
yeah try something, ill test.

**Comment by RobinSchmidt** [comment]
ok, done. i've tried here also and it seems to work

**Comment by RobinSchmidt** [comment]
> Ultimately I'd much rather have a modulation menu that's open at all times, or a modulation tab or something that shows all modulation connections at once

yes that would be nice and is probably not too hard. we would just have to acquire a pointer to the ModulationManager and that could return an array with pointers to the ModulationConnections. i just see, the function for this is already there: getModulationConnections()

**Comment by RobinSchmidt** [comment]
oh, nice! thank you. i can build au, too and it seems to work. however - the gradients on the gui are messed up (blocky). do you have this issue, too? tomorrow, i want to make a nice package with chainer and all the support files for mac

**Comment by elanhickler** [comment]
I have the same issue with the gradient. No one's going to complain though.

**Comment by RobinSchmidt** [comment]
it's butt ugly (not that it's particularly beautiful anyway - but not *that* bad, especially when some color is added). i'll try to do something about his

**Comment by elanhickler** [comment]
you should create a system of passing vector files to your stuff rather than have to code everything, rather than specifying color and shape and all of that junk. You could use a vector file for the background. The vector file could specify the gradient.

**Comment by elanhickler** [comment]
also, if you can create "always on top" windows, can't you help me make a full screen mode for prettyscope? :)

**Comment by RobinSchmidt** [comment]
i never tried it, but i would try this:

https://www.juce.com/doc/classDesktop#a8fa4033714b5a9cd0714c9b9633b3366

call it with the scopeDisplay...or something

**Comment by RobinSchmidt** [comment]
> I have the same issue with the gradient.

i'm currently using juce's image rescaling with a 4 pixel image that contains the colors for the 4 corners. that should actually linearly interpolate when being scaled up to the window size. and on non-mac computers, that seems to work. although it seems a bit nonlinear to me. i formerly had some pixel algorithm doing it myself but that stopped to work when updating my code to the new juce. but i think, i know how to make it work again

**Comment by elanhickler** [comment]
![image](https://user-images.githubusercontent.com/9116575/31980169-97805b4a-b8ff-11e7-9bfd-7762d5ac8e4a.png)

Now that we can have multiple windows open, I would have modulations widget say Modulations: Mirror or just "Mirror"

This is probably the last request I'll make for the current modulation UI. After this I'll see if I can design a completely new approach.

**Comment by RobinSchmidt** [comment]
hmmm...i actually placed the modulation menu directly under the slider, specifically so you can read the slider text "Mirror" directly above the "Modulations" popup headline. don't you think, that connection is obvious enough? ...or are you talking about moving around the Modulations popups (currently not possible anyway, but maybe it wouldn't be too difficult ...but i don't know - i would have look into the juce docs

**Comment by RobinSchmidt** [comment]
...or maybe we could somehow frame the slider into the modulation menu....such that it visually becomes part of it

**Comment by elanhickler** [comment]
well, then the other issue is that you can move the synth gui, but then modulation widget does not follow, so you'll have this lovely effect: 😄 

![image](https://user-images.githubusercontent.com/9116575/31980896-7b244006-b904-11e7-9c23-dda367c9868d.png)

**Comment by RobinSchmidt** [comment]
yes, i know....these modulation menus were actually initially conceived as short, temporary popups. it's probably (almost certainly) possible to have them move along when you move the gui. i would just have to figure out how in the juce docs

**Comment by RobinSchmidt** [comment]
> The slider name on the modulation widget would be a nice fix for now.

hmmm...as said...i actually think, that would be redundant, if the very same text is also a couple of pixels above and the connection is obvious. i'd rather avoid such clutter - more words to read, no additional information. why do you think it is needed?

**Comment by elanhickler** [comment]
because you can't always see the name of the slider: https://puu.sh/y6zpa/c8badb57e7.gif

**Comment by RobinSchmidt** [comment]
ok, done

**Comment by elanhickler** [comment]
CLOSE
