### ISSUE TITLE
13 instances of Mushroom Generator takes 3 gigs of ram

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#112]
wtf...................................

The only thing I can think of that uses ram is the noise generator. Each one has 14 instances of your noise generator class.

**Comment by elanhickler** [comment]
![image](https://user-images.githubusercontent.com/9116575/31917277-773d53dc-b80b-11e7-83bb-43ed9d6b0918.png)

i set this to 10, and it solved the issue, but... despite the 14 * 13 * 262144 doubles used for noise, it still doesn't justify 3 gigs... or am I doing my math wrong? I think it should still be well under a gig.

**Comment by RobinSchmidt** [comment]
ok - so 14 * 13 * 262144 is the number of samples. times 64 gives the number of bits. then divide by 8 to go to bytes, by 1024 to kilobytes, again to get megabytes and again to get gigabytes. gives:

(14 * 13 * 262144 * 64) / (8 * 1024 * 1024 * 1024) = 0.355...

...should be around 355 MB, if i'm not mistaken

**Comment by elanhickler** [comment]
I just created my own noise generator, super-simple:


```cpp
class NoiseGenerator
{
public:

	NoiseGenerator() = default;
	~NoiseGenerator() = default;

	void setSeed(int v);

	void reset();

	double getSample();

protected:

	int seed = 39047;
	unsigned long state = 0;
};

void NoiseGenerator::setSeed(int v)
{
	seed = v;
	reset();
}

void NoiseGenerator::reset()
{
	state = seed;
}

double NoiseGenerator::getSample()
{
	state = 1664525*state + 1013904223;
	return 1.0/4294967296.0 * state;
}
```

**Comment by RobinSchmidt** [comment]
well, i have that:

```cpp
INLINE double randomUniform(double min, double max, int seed)
{
  static unsigned long state = 0;
  if(seed >= 0)
    state = seed;                                        // initialization, if desired
  state = 1664525*state + 1013904223;                    // mod implicitely by integer overflow
  return min + (max-min) * ((1.0/4294967296.0) * state); // transform to desired range
}
```

hmm...looking at the numbers, i guess, yo took the code from there? but you probably mean, i should put it in a class, so it has its own state? yeah. i think, for the rapt library there has to be such a thing.

btw. if you want to make colored noise from that, take a look at rosic::SlopeFilter

**Comment by RobinSchmidt** [comment]
btw.: the numbers are taken from this book, page 284:

http://www.cec.uchile.cl/cinetica/pcordero/MC_libros/NumericalRecipesinC.pdf

...awesome book, generally

**Comment by RobinSchmidt** [comment]
all this new c++11 mersenne-twister random number stuff is probably total overkill for audio applications

**Comment by RobinSchmidt** [comment]
and i wouldn't trust a language/library provided prng anyway, in terms of reproducibility ...who knows where they get their seed from...maybe from the system clock

**Comment by RobinSchmidt** [comment]
i would just provide a slope slider. maybe from -6 to +6 dB/oct

**Comment by elanhickler** [comment]
What if you saved the coefficients in a table for all needed slopes and linear-interpolated between the coefficients for efficient slope modulation?

**Comment by RobinSchmidt** [comment]
do you think, the recomputation is too expensive?

**Comment by elanhickler** [comment]
don't know, haven't tested. Just thought it was an interesting idea.

**Comment by RobinSchmidt** [comment]
hmmm...well...it's the cost of computing the coeffs of two (rbj-cookbook) shelving filters. ok, it has a few math function calls, but i think it's not such a big deal. just try it. if you find it too expensive, we may consider it again

**Comment by elanhickler** [comment]
what about something like this

```cpp
class SmootherManager
{
public:
	Array<Smoother *> smoothersCurrentlyActive;

	void addForSmoothing(Smoother * smoother)
	{
		if (!smoother->wasAlreadyAdded)
			smoothersCurrentlyActive.push(smoother);
	}	
};

class Monosynth
{
public:
	SmootherManager * smootherManagr;

	Smoother pitchSmoother;

	void frequencyChanged()
	{
		smootherManager->addForSmoothing(pitchSmoother);
	}

	updateFrequency()
	{

	}

	void processPerSample()
	{
		if (pitchSmoother.valueHasChanged())
			updateFrequency();
	}
};
```

**Comment by RobinSchmidt** [comment]
in order to halfway properly interpolate filter coeffs, i would probably convert to poles/zeros and interpolate them in polar coordinates. ...but this involves also math-function calls, so you can as well re-compute the coeffs from scratch, i guess

**Comment by RobinSchmidt** [comment]
wrong thread - that smoother code?

**Comment by elanhickler** [comment]
CLOSE.
