### ISSUE TITLE
When loading preset we need to call resized

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#113]
Presets change things that the GUI needs to know about. Call resized when preset is changed.

**Comment by elanhickler** [comment]
Robin, I am SO CLOSE to being able to release Mushroom Generator. All I need is a few bug fixes, they are all related to the plugin not updating properly:

- GUI is not updated when changing presets, causing these problems: Breakpoints do not visibly update on patch load, and when loading a patch with Midi CC selected, the midi CC dropdown does not show. Manually resizing the window fixes the problem. (reported here)
- Metaparameter connections only update if plugin is re-loaded or automation is sent to MG. (reported in the meta parameter name change thread)
- Crashes due to improper modulation setup when changing presets and trying to remove a modulation via GUI conection that does not exist. (reported in the modulation discussion thread)

**Comment by RobinSchmidt** [comment]
need to make a debug session tomorrow. i didn't see the crash over here, though - but some other strange thing. calling resized from state recall is not feasible, however - since the state recall happens in the audiomodule and resized is a gui thing - and the audiomodule doesn't (and shouldn't) have a reference to the gui. ...there are other notification/update mechanism in place, however. for example, the sliders receive the parameterChaneged callbacks. maybe the update of the breakpoint gui is broken somewhere - wel'll see

**Comment by RobinSchmidt** [comment]
i think, i solved number two (can you confirm this?). 

and will now look into this:

> I'm getting crashes due to changing presets and modulation not updating correctly. The modulation connection exists according to the GUI, but not according to the modulaion system, so removing a connection causes crash. I think it happens the other way around too.
> 
> Try going from DancingShroom to GhostDance presets, and the other way around too. Here are the presets:
> 
> http://www.elanhickler.com/transfer/Soundemote/temp_shroom_presets
> 
> Load DancingShroom preset
> Switch to GhostDance
> Try to remove a connection from Stereo Rotate slider using the Remove button

however, doing these steps doesn't cause a crash here. however, when i manually remove the connection and then reload one of the presets,, the slider turns red again (indicating modulation) but when i then open the mod-menu, i don't see the depth slider. when i then use the "Remove" button, i see something in the list that pops up. when i then select that for removal, i get the crash. is this what you mean. anyway - both should not happen

**Comment by elanhickler** [comment]
>  get the crash. is this what you mean? anyway - both should not happen
metaparameter bug fixed. But this isn't, I still get crashes.

**Comment by elanhickler** [comment]
https://puu.sh/yastR/ba552bd08b.gif

**Comment by RobinSchmidt** [comment]
oh yes - when switching presets, the content of the menu becomes invalid. maybe i should close it ...or better: update. at the moment i'm getting build errors with mushroom of the kind:

JerobeamMushroomModule.cpp(486): error C2660: 'jura::BreakpointModulatorAudioModule::noteOn': function does not take 3 arguments

...i think, i'll temporarily fix them here by deleting the 1st argument

**Comment by RobinSchmidt** [comment]
ooookayyy - try now. i'm now updating the whole menu whenever the connection setup changes - be it due to the user adding a connection or switching presets. it seeeeems to work

**Comment by RobinSchmidt** [comment]
ok, i think, i have now also fixed the update of the breakpoint-editor on preset load. 

i sometimes got access violations on startup in ParamSmoother.h when needsSmoothing gets called

**Comment by RobinSchmidt** [comment]
so, if all bugs are fixed...i have a request from Nikolas Herz (from www.bigtone.de) - he seems interested in the synth and asked me for a preview version. can he have one? and/or are you going to release it now anyway?

**Comment by RobinSchmidt** [comment]
> when loading a patch with Midi CC selected, the midi CC dropdown does not show. Manually resizing the window fixes the problem.

oh wait - what it this? i don't quite get it. can you make me a gif of that, too?

**Comment by elanhickler** [comment]
> he seems interested in the synth and asked me for a preview version. can he have one?
of course. Let me build a new version and give you link complete with presets. Presets are important.

**Comment by elanhickler** [comment]
> JerobeamMushroomModule.cpp(486): error C2660: 'jura::BreakpointModulatorAudioModule::noteOn': function does not take 3 arguments

I needed access to the bool (first argument) startFromCurrentLevel for the breakpoint modulator, so I added an overloaded noteOn function for it.

**Comment by elanhickler** [comment]
problem with midi CC dropdown not showing on preset change: https://puu.sh/yaDnO/0ab613f689.gif

**Comment by elanhickler** [comment]
NEW BUILD: http://www.elanhickler.com/transfer/Soundemote/Soundemote%20-%20Mushroom%20Generator%20beta.zip
he could sign up to be a beta tester if he wants, he automatically gets a download link and all updates: http://eepurl.com/cVN_5r

**Comment by RobinSchmidt** [comment]
ok, thanks - i've sent him the links. i've also looked into it myself. some really cool presets there!

i'll look into the other bugs tomorrow. a friend who needs some place to sleep tonight will soon arrive, so i can't work today anymore. the grid settings are actually not really supposed to be saved - they are a actually gui state thing. but i guess, i could add it to the audiomodule state. sync setting should certainly be saved, though. i guess the smoother issue will have to be fixed in your code, but i may look into it anyway

**Comment by elanhickler** [comment]
> i guess the smoother issue will have to be fixed in your code, but i may look into it anyway

It's not my smoother, it's the fact that we are trying to combine your modulation system with my smoother. My smoother by itself works very well.

And yes, please allow saving of grid systems. When a user intends to use breakpoint as a rhythmic sequencer, those grid settings should be re-loaded with the preset, makes for a very nice user experience.

**Comment by RobinSchmidt** [comment]
> My smoother by itself works very well.

so does my mod-system :-P i guess, if it jumps to the value for one sample, somewhere the original setValue functions gets called and only then the smoother kicks in for the next sample...or something. we'll see...

**Comment by RobinSchmidt** [comment]
> some really cool presets there!

CHORD_Victory2!!!! ...Harmonic Multiply....i need that feature in my next synth!

**Comment by elanhickler** [comment]
Robin... robin robin robin... when will you learn...

I have many more ideas that you will say that exact thing.

**Comment by elanhickler** [comment]
ok... for example:

I want, instead of harmonic multiply, a scale system where... say... you can enable/disable keys on a scale. Combine that with pseduo-random or chaotic modulation, you can get instant awesome melodies. Add in some quantizing features, you have yourself algorithmic music, melodies and rhythms at a click of a button.

**Comment by RobinSchmidt** [comment]
yes! that sounds like a cool idea!

**Comment by RobinSchmidt** [comment]
maybe it could be realized as a midi plugin so it can drive any synth you like

**Comment by elanhickler** [comment]
yes, sure, but part of the beauty of having it inside a synth is that you can abuse this kind of thing at audio rate... hmm, not sure how that'd sound with a scale system. It works well with harmonic series.

**Comment by elanhickler** [comment]
solved
