### ISSUE TITLE
I've had to take noteOn and noteOff callbacks into 4 more callbacks

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#114]
in parenthesis I have example questions that the code answers: 

noteOn/Attack (do we reset envelope or just retrigger attack?)
noteOn/NoteOnLegato (do we reset envelope now?)
noteOff/NoteOffLegato (is this really a note ON to a previously held note?)
noteOff/Release (ok, now we can trigger the real actual release for things)

I'm going to start putting all these callbacks in all my synth objects. Crucial for allowing the user to choose how they want resets to behave for a proper functioning synth that may be used for percussion or lead sounds or whatever.

Just making a note of this for you just in case (your classes don't have these kinds of callbacks so I thought I'd let you know), this is crucial. This needs to be in every synth tutorial, this is fundamental stuff.

example code

```cpp
void JerobeamMushroomModule::noteOn(int noteNumber, int velocity)
{
	jbMushroomCore.noteOn(noteNumber, velocity);

        // i think you can replace this if with (jbMushroomCore.UserHeldNotes.size() > 1)
	if (jbMushroomCore.isNoteTied())
		triggerNoteOnLegato(noteNumber, velocity);
	else
		triggerAttack(noteNumber, velocity);
}

void JerobeamMushroomModule::noteOff(int noteNumber)
{
	jbMushroomCore.noteOff(noteNumber);

	if (jbMushroomCore.UserHeldNotes.size() > 0)
		triggerNoteOffLegato(noteNumber, jbMushroomCore.getCurrentVelocity());
	else
		triggerRelease(noteNumber);
}
```

sometimes you want to trigger a new attack every legato on or off. Sometimes you just want to trigger an attack for note on/attack and note on/legato (for percussion).

Wow, I just had an epiphany: What I'm doing is seriously perfecting the monosynth concept. There's still a few issues that need to be perfected, such as when resetting envelope to avoid clicks (have some smoothing speed [at the user's discretion] perhaps based on release or attack time or some separate slider). I'm almost there to a perfect mono synth voice handling.

Once I have a perfect monosynth, I can move on to polysynth, which having a good monosynth voice handling will make it that much better. I'd like to look into spreading unison voices across keys, for example you have a bank of 8 voices. You play 4 keys at once. 2 voices per key. 1 key? 8 voices per key. 8 keys? 1 voice per key.

**Comment by RobinSchmidt** [comment]
> Once I have a perfect monosynth, I can move on to polysynth

...polysynth is something i'm also currently thinking about. i mean, i have already made a polysynth in my life (straightliner). but i think the design is not optimal. i want to make a polysynth in a way that my library dsp modules can be used conveniently polyphonically. that's a design challenge for the library

**Comment by RobinSchmidt** [comment]
so you want to have 4 noteOn/Off callbacks...hmmm well, of course, you can do this in a subclass, as you do in the code above. you can always override my library functions (mostly, unless they are non-virtual in which case you can ask me to make them so). you could make a baseclass for all your audiomodules that does all these things..like

`void ElansAudioModule::noteOn(int noteNumber, int velocity)`

which do the dispatch, and derive all you modules from that.  and if i like it, i may include it into the jura library too. but yeah, maybe i should have this dispatch in my library, too. ...whatever, sorry...i'm drunk...cheers!

**Comment by elanhickler** [comment]
![image](https://user-images.githubusercontent.com/9116575/32144814-94d2101c-bc7b-11e7-9f23-17445370fc96.png)

you have a bug here. isAllNotesOff will never be hit, because allNotesOff is also "isController", so you need to put that allNotesOff statement first, or make one inside isController.

**Comment by RobinSchmidt** [comment]
ok, thanks - fixed. i also put the noteOn/Off first in the dispatcher chain so the most common events get handled first. really? ...all-notes-off is a controller message?

**Comment by elanhickler** [comment]
yep: http://www.nortonmusic.com/midi_cc.html

cc 123 value 0

**Comment by RobinSchmidt** [comment]
interesting. actually, noteOff is a noteOn, too, right? just with 0 velocity. or is that just one possible representation of noteOff and there's a "proper" noteOff messgae, too? have to look that up..

**Comment by elanhickler** [comment]
yes, noteOff is noteOn at 0 velocity

**Comment by RobinSchmidt** [comment]
from juce::MidiMessage:

```cpp
    /** Returns true if this message is a 'key-up' event.

        If returnTrueForNoteOnVelocity0 is true, then his will also return true
        for a note-on event with a velocity of 0.

        @see isNoteOn, getNoteNumber, getVelocity, noteOff
    */
    bool isNoteOff (bool returnTrueForNoteOnVelocity0 = true) const noexcept;
```

soo, it seems that noteOn with velocity zero is just one representation of noteOff. so i think, i should keep my noteOff-branch here:

```cpp
  if( message.isNoteOn() )
    noteOn(message.getNoteNumber(), message.getVelocity());
  else if( message.isNoteOff() )
    noteOff(message.getNoteNumber());
```
because otherwise i might miss the "proper" note-off messages

**Comment by RobinSchmidt** [comment]
if all note-off messages would be represented as noteOn with velocity zero, the 2nd branch would also never get hit, but we can't be sure about that because of the possible other representation of note-off

**Comment by RobinSchmidt** [comment]
well...yes - there must be something liek a proper noteOff, because some synths also support note-off velocity right? maybe i should support that, too

**Comment by elanhickler** [comment]
old discussion
