### ISSUE TITLE
Noise generator doesn't work on Mac

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#115]
whyyyyyyyyyyyyyyyyyyy 😭 

Edit: I think the output of the noise generator is always 1. I didn't check in the debugger, but figured this is some weird compiler issue where your noise generator technique doesn't work cross-platform.

**Comment by RobinSchmidt** [comment]
hmm...i guess on mac maybe the unsigned int datatype is 64 bit and 32 on pc, so the implicit-mod-by-overflow doesn't work anymore? just guessing... in this case, you could do the mod explicitly. so, instead of:
```
double NoiseGenerator::getSample()
{
	state = 1664525*state + 1013904223;
	return 1.0/4294967296.0 * state;
}
```
you could try this:
```
double NoiseGenerator::getSample()
{
	state = (1664525*state + 1013904223) %  4294967296;
	return 1.0/4294967296.0 * state;
}
```
maybe with an #ifdef. or try to force mac using a 32 bit integer (but i don't know how - you need to look that up)

**Comment by RobinSchmidt** [comment]
using 32 bit integer is probably preferable in terms of efficiency. maybe.

**Comment by RobinSchmidt** [comment]
but i wouldn't be so sure about that when 64 bit is the native type and the mod-by-power-of-two can be optimized by the compiler by bitmasking (but i'm not sure, if the compiler does this - or if that's even possible math-wise, but i think so)

**Comment by RobinSchmidt** [comment]
hmm..if i'm not mistaken, i think this bitmask should also do the modulo operation:
`state = (1664525*state + 1013904223) & 4294967296;`
but no warranties - needs to be tested

**Comment by elanhickler** [comment]
I was thinking of just using juce_Random class, seems slightly more effecient...? Also I think you mean "not guarantees" not "no warranties" 😿 

![image](https://user-images.githubusercontent.com/9116575/32170218-fe4feb80-bd30-11e7-9115-a4983af6f9a5.png)

**Comment by RobinSchmidt** [comment]
> I think you mean "not guarantees" not "no warranties"

isn't that the same?

**Comment by RobinSchmidt** [comment]
> I was thinking of just using juce_Random class, seems slightly more efficient...?

don't know. the only way to find out is to actually measure. but i don't think, it doesn't get any simpler than my algorithm

**Comment by elanhickler** [comment]
"no warranties" is saying I'm not allowed to get my money (or some valuable thing) back if it doesn't work. "no gaurantees" means you're just saying it may not work.

**Comment by RobinSchmidt** [comment]
haha! both!

**Comment by RobinSchmidt** [comment]
i actually think, it should work. it's a trick that is used all the time with delaylines (i just didn't remember that)

**Comment by elanhickler** [comment]
ok testing!

**Comment by elanhickler** [comment]
works!
