### ISSUE TITLE
SmoothingManager causes preset loading problems

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#119]
Smoothing causes sliders to transition to their values slowly while preset is loading, however this transition is halted immaturely and so sliders are set to strange values upon loading a preset.

Repeated attempts to load the same preset will eventually get sliders to their correct values, because apparently smoothing is going on during preset load but stops after preset is finished loading or something.

........mushroom generator release is delayed........

**Comment by RobinSchmidt** [comment]
do you have the latest commit, where i already built in a smoothing-bypass on preset load?

**Comment by elanhickler** [comment]
checking............

**Comment by RobinSchmidt** [comment]
there may be some other places where it's probably best to switch the smoothing off...such as during construction

**Comment by elanhickler** [comment]
WORKS.

**Comment by RobinSchmidt** [comment]
ok, good - i think, i'll need some more tests and refinements (mostly temporary bypasses) anyway
