### ISSUE TITLE
We need two locations for presets, USER and FACTORY

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#12]
For apple, please see this thread:
https://www.kvraudio.com/forum/viewtopic.php?f=33&t=485068&p=6792487#p6792487

It is best if we separate presets into User and Factory. We need this to work GUI wise where we have a more robust browsing system so we can select user or factory folders.

For now, I will direct Spiral Generator and PrettyScope to look for presets here for Mac: /Library/Application Support/Soundemote/Spiral Generator/Presets

**Comment by RobinSchmidt** [comment]
i think, that would imply that we can't use the standard file loading dialog box anymore and instead have to write a custom dialog box. is this what you mean when you say "We need this to work GUI wise"? ...or do you mean some kind of preset-directory selection menu (or pair of radio-buttons)? ...well...that would be easier to implement.

**Comment by elanhickler** [comment]
Yes, a custom dialog box. You can use the current operating system dialog box just to put in a path for user or factory presets, but after that you need a "preset browser". I guess it would be nice to have an "add/remove" for preset folders, and those folders would then show up in a preset browser. Not sure what you mean by a pair of radio buttons.

**Comment by elanhickler** [comment]
I solved this for myself
