### ISSUE TITLE
Edited Keygenerator and keys are no longer valid

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#122]
### old
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Keyfile Key="WTLUGPCOBNSJSELNETMCLBKZELASRKPZQQHECYBFUPMKVRKTKDMATEVWNJKTIOBD" Serial="ILMIOOPM" Address="gyestegie@hotmail.com" Email="" Licensee="Jean St" Product="MushroomGenerator"/>
```
### new
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Keyfile Key="WTLUGPCOBNSJSELNETMCLBKZELASRKPZQQHECYBFUPMKVRKTKDMATEVWNJKTIOBD" Serial="ILMIOOPM" Address="" Email="gyestegie@hotmail.com" Licensee="Jean St" Product="MushroomGenerator"/>
```

why would this make a difference? I can't test at the moment, but maybe soon. I'm in the process of moving.

the difference is address vs email. the key is exactly the same

**Comment by RobinSchmidt** [comment]
that's kind of the point of the keyfiles: you can't change them without breaking them. if you want to change the Address field, say, you need to generate a new key. address, name, email - that is all part of the personalization. if it would be possible to edit that data, some guy may change these fields (for example, empty them) and share the key...or even publish it.

**Comment by elanhickler** [comment]
oh i found the issue in how the key file is read. i can figure this out.

**Comment by RobinSchmidt** [comment]
the idea is that the key only works in combination with given name, address, etc. so it's not shareable

**Comment by elanhickler** [comment]
im just changing it so it uses email instead of address, I think I know what to do. Also this would make all past keys invalid....... ill figure it out.

**Comment by RobinSchmidt** [comment]
so you want to leave the address field empty? my idea behind writing the licensee's address into the keyfile (in clear text) was to have a strong deterrent from sharing the file. juts using email might be much weaker of a deterrent because it can easily be faked

**Comment by elanhickler** [comment]
I get that, but let's say somehow their key gets leaked, then the address becomes a punishment for the user. Anyway this is all not very important.

I think I should move to key silos, it would be easy to automate. I could pre-generate 1000 keys, put it in the plugin's lookup for valid keys when building, then have SendOwl (my cart system) send their key... but I need a dialog box for the user to copy/paste that key............

Maybe if I can edit the "demo version dialog box" to have an input box.........

**Comment by RobinSchmidt** [comment]
> let's say somehow their key gets leaked, then the address becomes a punishment for the user. 

yes, exactly - that's the point ;-). it's the user's responsibility to protect the keyfile. but ok, if you want to handle that differently, it's up to you :-)

**Comment by elanhickler** [comment]
..............like I said, I don't care, I just need an automated process, I don't even have easy access to the user's address, that's the reason I use email.

**Comment by RobinSchmidt** [comment]
alright, no problem. i was using PayPal exclusively for sales, which always gave me the user's (verified) address

**Comment by elanhickler** [comment]
right, i get that to... but... then that's having to check two e-mails OR... maybe I could just check one e-mail, but my assistant doesn't get my paypal emails, my assistant is responsible for sending out licenses, I don't have time for sending licesnes, gotta focus on programming.

**Comment by RobinSchmidt** [comment]
hmm...maybe you can just install a forwarder in your mail client...or server...or something? ..dunno, whatever, it's up to you

**Comment by elanhickler** [comment]
"it's up to me" haha... ROBIN... I don't know how! I mean, what I was thinking is to eventually have a server running keygen, and the sales e-mail gets sent to the server, server provides info to keygen, keygen spits out a file, server e-mails file.

**Comment by RobinSchmidt** [comment]
yes, indeed. at some point i was thinking about that, too - but i'm lacking the required web-programming skills and and didn't care enough to acquire them. i want to focus on dsp. the keygen itself can probably rather easily be turned into a command-line driven application that may be run on a server...but how to integrate such stuff, i don't know

**Comment by RobinSchmidt** [comment]
> I'm in the process of moving.

where are you moving to?

**Comment by elanhickler** [comment]
Phoenix to Mesa, just one city over.
