### ISSUE TITLE
How do you stop parameter from saving/recalling?

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#124]
I tried setSaveAndRecall thing, didn't work.

**Comment by elanhickler** [comment]
Couldn't figure out the difference between presets after removing save/load. Found the difference with winmerge.  The problem is that the metaparameter state is recalled....... hmmm.... I think the solution is to simply make the parameter NOT be adjusted by the metaparameter setting on startup / preset load. The VST host can still send a modulation message to the VST for that parameter with host automation. In other words, the metaparameter value should be ignored (initially).

![image](https://user-images.githubusercontent.com/9116575/33048264-396bdaca-ce17-11e7-8549-1478508fc0e0.png)

**Comment by RobinSchmidt** [comment]
> I think the solution is to simply make the parameter NOT be adjusted by the metaparameter setting on startup / preset load.

hmm.. when the AudioModule recalls a preset, it calls `recallMetaValuesFromXml` which in turn loops through the metas and calls `setMetaValue` on each. this, in turn, loops the through the meta's dependent parameters and set them up according to the meta value. ...yeah...and inside this loop, the stateSaveAndRecall flag is not checked, so the values gets set. ...if i would remove the call to `recallMetaValuesFromXml`, meta values might be intitially inconsistent with parameter values - mayb not such a good idea, but might at the moment be inconsequential. maybe i could set the meta-value without looping through the dependents....hmm...dunno....what is this actually good for? why would one want to enforce an inconsistency between a parameter and its meta after preset load?

**Comment by elanhickler** [comment]
ok, better idea, I need to not automatically connect those parameters. In prettyscope I automatically connect them... but eventually I will remove this automatic connection feature because PrettyScope will become a lot more complicated in the near future.

**Comment by RobinSchmidt** [comment]
ok, so nothing for me to worry about here, right?

**Comment by elanhickler** [comment]
incorrect, how do I stop connect a few parameters? Could you do this: don't connect parameters which have "do not recall state" flag when using the "automatically connect all parameters" thing.

**Comment by RobinSchmidt** [comment]
couldn't you just call detachFromMetaParameter() after the auto-connect on those parameters which should not be connected? i don't really think, it's a good idea to bypass the auto-connection as hidden side-effect of setting the recall flag false. this could lead to a lot of confusion and weird subtle bugs a few years later down the road. it might be suitable in this particular application, but in general?

**Comment by elanhickler** [comment]
ok, i didn't know I could do that.

**Comment by RobinSchmidt** [comment]
yeah - it's the same mechanism that gets invoked when you detach it via the gui

**Comment by elanhickler** [comment]
resolvd.
