### ISSUE TITLE
X Y Z Rotation?

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#125]
Hey Robin, I tried to implement an X / Y / Z rotation like one would find in a 3D modelling program, but I couldn't figure it out.

I tried to do it like this, and just having 3D rotation allows 3D rotation, but the problem is that rotating one axis also causes the other axes to change their rotation effect. In other words, for example, if you rotate X (horizontal rotation), then rotate Y (vertical rotation) then rotate X again, X might now be controlling vertical rotation. So this is a working implementation, but a bad one. I need the right 3D rotation formula.

```cpp
void rotate3D(double inX, double inY, double inZ, 
	double rotX_sin, double rotX_cos, 
	double rotY_sin, double rotY_cos, 
	double * outL, double * outR)
{
	double x1 = inX*rotX_cos - inY*rotX_sin;
	double y1 = inX*rotX_sin + inY*rotX_cos;

	double x2 = x1*rotY_cos - inZ*rotY_sin;
	//double y2 = x1*rotY_sin + inZ*rotY_cos;

	*outL = x2;
	*outR = y1;
}
void rotate2D(double sin, double cos, double * X, double * Y)
{
	double x = *X, y = *Y;
	*X = x * cos - y * sin;
	*Y = x * sin + y * cos;
}
void ScopeAudioBuffer::doXYTransformation(double x, double y, double * out_x, double * out_y)
{
	rotate3D(x, y, 0, rotationX_sin, rotationX_cos, rotationY_sin, rotationY_cos, &x, &y);
	rotate2D(rotation_sin, rotation_cos, &x, &y);
	*out_x = x * zoom * scaleX + shiftX;
	*out_y = y * zoom * scaleY+ shiftY;
}
```

Any change you could figure it out?

**Comment by elanhickler** [comment]
results: https://i.imgur.com/bY0SfS3.mp4 (works, but the control scheme is bad)

**Comment by RobinSchmidt** [comment]
i have added a function to rapt `rsRotateXYZ` which is rather analogous to your `rotate2D` function. i obtained the formulas by multiplying together the 3 basic rotation matrices around the x,y,z axes:

https://en.wikipedia.org/wiki/Rotation_matrix#Basic_rotations

in that order. it makes a difference, if you rotate around x-axis first, then y then z or the other way around or any other re-ordering because, mathematically speaking, matrix multiplication is not commutative. but you can also clarify this yourself geometrically, just imagine a coffee-pot rotate it around one axis and the the other and then do the same rotations in reverse order - you end up with a different orientation, in general.

i have not yet tested my rotation function because i have no context to do so. as i did the matrix multiplies by hand, there's some chance that i made a mistake. maybe you can try or i can try it in your context.

**Comment by RobinSchmidt** [comment]
your rotate3D function seems to have a 3D input and 2D output - so you are already trying to combine the rotation and subsequent projection onto 2D? maybe it's more straightforward to do the rotation in 3D first and only after that do the projection. my function does only the rotation.

**Comment by RobinSchmidt** [comment]
on the wiki page, they multiply together the matrices in revers order...maybe that's more standard? no idea. i could also write a function `rsRotateZYX` which does that. i don't know which way is better

**Comment by RobinSchmidt** [comment]
> if you rotate X (horizontal rotation), then rotate Y (vertical rotation) then rotate X again, X might now be controlling vertical rotation.

yes, that's expected because after a rotation about the y-axis, the object's x-axis does not align with the world's x-axis anymore. we always rotate around the x-axis of our "world" - you want to rotate around an x-axis relative to the object again? i guess the most convenient way would be to start fresh and specify a different angle for the x-axis rotation

**Comment by RobinSchmidt** [comment]
ah - no - wait: the rightmost matrix is actually the one, which is applied first, so the order in which wikipedia multiplies the matrices together corresponds to rotate around x first - and my function actually rotates around z first

**Comment by RobinSchmidt** [comment]
ok, i changed it - now it should be the XYZ rotation indeed (instead of a ZYX rotation)

**Comment by elanhickler** [comment]
I like it!

Although because you defined your template function in the cpp file I couldn't built. Fixed it and built, tested, works!

**Comment by RobinSchmidt** [comment]
ok, good - so no mistakes in my pencil-and-paper matrix multiplications? i actually double checked everything, but who knows...

yeaa...it has to be instantiated somewhere. that's the problem with writing template libraries. i think, i will organize my audio dsp libraries in two layers. the lower layer is template based and the higher level layer uses particular datatypes (such as double) and is more convenient to use. rapt shall be is the lower layer (template based, for number crunching algorithms) and rosic shall instantiate the templates for double and clients don't need to worry. now that i have dragged all my IIR filter stuff into rapt and templatized everything (along with some other changes), i think, the (now redundant) rosic classes should be made instantiations of the rapt templates

**Comment by RobinSchmidt** [comment]
what do you think about wrapping it into a class with functions like setAngleX, setAngleY, setAngleZ and apply(T* x, T* y, T* z)? it could be used to avoid redundant recomputations of the matrix coeffs if if the same rotation is applied repeatedly to various vectors

**Comment by elanhickler** [comment]
yeah, I actually already implemented that, but a class might be better.

**Comment by RobinSchmidt** [comment]
ok, done

**Comment by elanhickler** [comment]
implented. can we close!? :)

**Comment by RobinSchmidt** [comment]
yes. i think, as soon as time permits, i'll use this as a basis for a 3D version of the xoxos osc. i already have a quite definite plan in my mind what i would have to do

**Comment by RobinSchmidt** [comment]
-obtain a new vector on the unit-sphere by rotation (the 3 rotation angles of the class object determine 3 frequencies)
-transform unit-sphere vector to ellipsoid (3 shifts, 3 scales)
-maybe rotate the ellipsoid (another rotation)
-renormalize vector length to unity
-project onto any of the 3 axes to obtain an output signal (i.e. select x, y or z)

**Comment by RobinSchmidt** [comment]
before selecting, we could apply yet another rotation and we could select x for left and y for a right channel signal to produce stereo signal. i think, the 2D version could also easily be extended to produce stereo output

**Comment by elanhickler** [comment]
I had to edit your code to make it compile and then edit it to make it work....... your choices of coding are confusing me at the moment.

**Comment by RobinSchmidt** [comment]
ok, i couldn't test it so far. what were your changes, so i can incorporate them into the library?

...yeah, i have sort of dropped using sinCos because on 64 bit build, it doesn't make a difference. it's relevant only for 32 bit builds and i think, that's going to phase out anyway. but maybe i should change that.

**Comment by RobinSchmidt** [comment]
> your choices of coding are confusing me at the moment.

what exactly do you mean? maybe i can come up with a good justification...

**Comment by elanhickler** [comment]
Your `updateCoeffs()` function uses local variables instead of member variables, so... it's non-working code.

**Comment by RobinSchmidt** [comment]
ah - yes! fixed. thanks. that's the kind of error that happens when you copy/paste/edit existing code

**Comment by elanhickler** [comment]
ok, how about the fact that it doesn't compile due to template functions being in cpp? I have to fix that... are you going to make a rosic version soon?

**Comment by RobinSchmidt** [comment]
hmmm....maybe when i do the 3D xoxos osc, but there's a lot of other stuff to do before.

it's a general problem with templates. if you put the definitions into cpp files, you tpyically have to do some explicit instantiaiton somewhere (i have some in rapt.cpp). i could add one for the rotation there. ...but actually, the instantiation is some thing i'd like to defer to client code (which, in this case, could be the rosic library). if you put definition into header files, on the other hand, you'll often get "multiple definition" linker errors - unless the functions are inlined - but can't inline everything.

what did you do? explicit instantiation in your codebase?

**Comment by elanhickler** [comment]
...better question, how do I get it to compile without changing your code?

**Comment by RobinSchmidt** [comment]
i just added an explicit instantiation:

template class RAPT::rsRotationXYZ<double>;

to rapt.cpp. that should fix it. what did you do?

**Comment by RobinSchmidt** [comment]
eventually, i will have to think about a better way to instantiate the templates

**Comment by elanhickler** [comment]
I put all your code in .h file and the .cpp is left blank. That's how I thought one should do template functions always.

I think you're trying to separate definition and implemention with templates, I think that's possible... I thikn you're doing it wrong, see: https://stackoverflow.com/questions/495021/why-can-templates-only-be-implemented-in-the-header-file

**Comment by elanhickler** [comment]
after your changes:


Error	C2333	'RAPT::rsRotationXYZ<double>::apply': error in function declaration; skipping function body (compiling source file ..\..\JuceLibraryCode\rapt.cpp)	PrettyScope	16	d:\_programming\rs-met\libraries\juce\modules\rapt\math\Geometry\GeometricTransformations.h	

Error	C2333	'RAPT::rsRotationXYZ<double>::updateCoeffs': error in function declaration; skipping function body (compiling source file ..\..\JuceLibraryCode\rapt.cpp)	PrettyScope	51	d:\_programming\rs-met\libraries\juce\modules\rapt\math\Geometry\GeometricTransformations.h	

Error	C2995	'void RAPT::rsRotationXYZ<T>::apply(T *,T *,T *)': function template has already been defined (compiling source file ..\..\JuceLibraryCode\rapt.cpp)	PrettyScope	13	d:\_programming\rs-met\libraries\juce\modules\rapt\math\Geometry\GeometricTransformations.cpp	

Error	C2995	'void RAPT::rsRotationXYZ<T>::updateCoeffs(void)': function template has already been defined (compiling source file ..\..\JuceLibraryCode\rapt.cpp)	PrettyScope	33	d:\_programming\rs-met\libraries\juce\modules\rapt\math\Geometry\GeometricTransformations.cpp

**Comment by RobinSchmidt** [comment]
whoa! i'm not getting these errors when building chainer! is the rapt .cpp file included in more than one compilation units? it shouldn't be.

> I put all your code in .h file and the .cpp is left blank. That's how I thought one should do template functions always.

as said - this will only work if the function bodies get inlined. if they don't get inlined and you include the header in several compilation units, you'll get "multiple definition" errors. and as soon as the function bodies become more complicated, you don't want to inline them (the compiler may even refuse to do so)

**Comment by RobinSchmidt** [comment]
> Another solution is to keep the implementation separated, and explicitly instantiate all the template instances you'll need

yep - that's what i'm doing

**Comment by elanhickler** [comment]
> is the rapt .cpp file included in more than one compilation units?
i wouldn't do that.

**Comment by RobinSchmidt** [comment]
ok - let me try to fix it in your codebase. what project should i build? prettyscope?

**Comment by elanhickler** [comment]
yes prettyscope

**Comment by RobinSchmidt** [comment]
...where is it?

**Comment by elanhickler** [comment]
Soundemote\AudioPlugins\Source\PrettyScopePlugin

**Comment by RobinSchmidt** [comment]
ahh - ok - i wans't expecting project files in a folder named "Source"...ok...let's see...

**Comment by elanhickler** [comment]
i am meaning to move it soon.

**Comment by RobinSchmidt** [comment]
hmmm...
```
1>------ Build started: Project: PrettyScope, Configuration: Debug Win32 ------

...lots of warnings...

========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by RobinSchmidt** [comment]
did you remove your changes to my code?

**Comment by elanhickler** [comment]
giiiiiiiiiiiiiiiiiiit! WTFFFFFFFFFFFFFFFFFFFFF IS GOING ON....

please accept my pull request, git is doing something very wrong.

**Comment by RobinSchmidt** [comment]
ok, merged.

**Comment by elanhickler** [comment]
for some reason when I merge RS-MET master branch to my personal branch, it's not giving me the changes for rotationXYZ, very strange. No idea what's going on. I just manually made the corrections, hopefully this isn't a problem now.

**Comment by RobinSchmidt** [comment]
hmm... i don't know. i'm not very experienced with git
