### ISSUE TITLE
PrettyScope smoother is acting very strange

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#127]
see animation: https://puu.sh/ys3Hy/587ccf72d9.gif

1. Put smoothing speed all the way up (bug happens with any amount of smoothing)
2. Move any slider that has smoothing enabled (all sliders have it enabled except for smoothing amount). You will see the slider jump around randomly.

Rotation is a good slider to test because all it does is control an audio rate parameter simply, like any of my other plugins.

No idea what's going on.

**Comment by RobinSchmidt** [comment]
ok, i'll look into it tomorrow. is prettyscope now doing 3D manipulations?

**Comment by elanhickler** [comment]
yes, Z is just 0 though, but you can actually make something 3d by... do something... some kind of modulation.

**Comment by RobinSchmidt** [comment]
i would imagine that it now just looks like you are 3D rotating a flat image? maybe prettyscope should have 3 input channels for true 3D visualization. ...but then you would also need some 3D/3-channel signal source

**Comment by elanhickler** [comment]
yeah, I will be adding a 3rd input eventually. And yes, it looks like you're rotating a flat image. But if you twist it a little bit in the Z axis (?) somehow, then you get a cool 3D effect... like a twisted piece of paper I guess.

**Comment by RobinSchmidt** [comment]
is this "twisted-paper" effect what i'm seeing here?
https://imgur.com/bY0SfS3
...hmmm...yesss...when i think about it, it makes sense. if you rotate about x, points higher above are pushed further into the back. ...but i'm not sure about my geometric intuition here, why this should give the twist effect

are the mushrooms actually originally 3D objects?

**Comment by RobinSchmidt** [comment]
...or wait...maybe the twist is due to rotation about the y-axis (assuming the shroom ist originally upright)?

**Comment by elanhickler** [comment]
What I did, if I remember correctly, is... something like sin(X) for the Z input, so I just made up a Z input out of one of the X/Y inputs.

**Comment by elanhickler** [comment]
Oh, and we could actually make mushroom 3D by having an additional sin function for the spiral part, not sure exactly where to insert that into the formula...

**Comment by RobinSchmidt** [comment]
>  I just made up a Z input out of one of the X/Y inputs.

what about x*y?

> Oh, and we could actually make mushroom 3D by having an additional sin function for the spiral part, not sure exactly where to insert that into the formula...

ok, i don't know hwat formulas mushroom uses anyway.

i guess the first thing i'd try for 3D signals is 3D lissajous figures:
```
x(t) = sin(kx*w*t);
y(t) = sin(ky*w*t);
z(t) = sin(kz*w*t);
```
where kx, ky, kz are integers (harmonic multipliers) and w is the basic radian frequency

**Comment by RobinSchmidt** [comment]
https://media.giphy.com/media/l0ExayL8BbmqsQBY4/giphy.gif

**Comment by elanhickler** [comment]
yeah, could try that, if you want to try things when you look at the prettyscope smoothing issue:

ScopeAudioBuffer.cpp:
![image](https://user-images.githubusercontent.com/9116575/33194191-5d73d7d0-d08b-11e7-93f7-7909e4c135b6.png)

**Comment by RobinSchmidt** [comment]
> what about x*y?

...thinking about it...it would make in-phase signals (with high correlation) come into the foreground and push out-of-phase signals into the background. if you use some brightness multiplier depending on the z-value making far away points darker, it could even be useful for signal analysis

**Comment by elanhickler** [comment]
Ok I figured it out again, z = x * y * 4 for the mushroom twist effect.

**Comment by RobinSchmidt** [comment]
aaahh - ok - i guess that explains the twist:
http://www.wolframalpha.com/input/?i=z+%3D+x*y

**Comment by RobinSchmidt** [comment]
hmm - yes - i can see the bug. is this behavior specific to prettyscope or does it happen in all plugins?

**Comment by elanhickler** [comment]
Seems like it's specific to PrettyScope. Yeah, so maybe I did something wrong, but I just really need help figuring it out. This bug is stopping me from moving forward with PrettyScope update and other things.

**Comment by elanhickler** [comment]
so many damn smoothing threads! finally closing them all!
