### ISSUE TITLE
Time to upgrade JUCE & Discussion

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#129]
Really need to fix the retina display bug.

I'll upgrade and see if I can create a list of problems for you to fix, maybe that will help move things.

Ok, let this be the discussion thread.

**Comment by RobinSchmidt** [comment]
yeaahh...sooner or later it has to happen anyway

**Comment by elanhickler** [comment]
These errors appeared a number of times (54 errors in my prettyscope project), but I condensed it down to one error for each kind of error:


jura::ColourizableBitmap': cannot inherit from 'juce::Image' as it has been declared as 'final' (compiling source file ..\..\JuceLibraryCode\include_jura_processors.cpp) | 11 | d:\_programming\rs-met\libraries\juce\modules\jura_framework\gui\graphics\jura_ColourizableBitmap.h
-- | -- | --
jura::AudioPlugin::setPreferredBusArrangement': method with override specifier 'override' did not override any base class methods (compiling source file ..\..\JuceLibraryCode\include_jura_framework.cpp) | 120 | d:\_programming\rs-met\libraries\juce\modules\jura_framework\audio\jura_AudioPlugin.h
swapVariables': identifier not found (compiling source file ..\..\JuceLibraryCode\include_jura_framework.cpp) | 366 | d:\_programming\rs-met\libraries\juce\modules\jura_framework\gui\widgets\jura_RTextField.cpp
setPreferredBusArrangement': is not a member of 'juce::AudioProcessor' (compiling source file ..\..\JuceLibraryCode\include_jura_framework.cpp) | 239 | d:\_programming\rs-met\libraries\juce\modules\jura_framework\audio\jura_AudioPlugin.cpp
setPixel': is not a member of 'juce::Graphics' (compiling source file ..\..\JuceLibraryCode\include_jura_processors.cpp) | 2408 | d:\_programming\rs-met\libraries\juce\modules\jura_processors\instruments\jura_Liberty.cpp
type 'char' unexpected (compiling source file ..\..\JuceLibraryCode\include_se_framework.cpp) | 289 | d:\_programming\juce\modules\juce_gui_extra\misc\juce_PushNotifications.h
type': unexpected token, expected either '}' or a ',' (compiling source file ..\..\JuceLibraryCode\include_se_framework.cpp) | 289 | d:\_programming\juce\modules\juce_gui_extra\misc\juce_PushNotifications.h
large': undeclared identifier (compiling source file ..\..\JuceLibraryCode\include_se_framework.cpp) | 293 | d:\_programming\juce\modules\juce_gui_extra\misc\juce_PushNotifications.h

I think you just need to create a little test space for yourself, test all this on a copy of your code, upgrade your JUCE version, and see if the errors are manageable.

**Comment by RobinSchmidt** [comment]
ouh...the first one could be a problem...maybe i'll have to tinker with the juce::Image class - we'll see. i'm just implementing the 3D version of the xoxos osc. ...some nice and easy recreational programming task for the sunday afternoon :-)

**Comment by elanhickler** [comment]
ok no more recreational drugs! err I mean programming... I need you to get a bunch of things done. The deadline for the multiband compressor is like December 10.

I got people complaining about retina bug.

Garageband users can't use my license keys because until we have a user dialog for the user to say where the key is.

There's so much to do! It's sink or swim for me, I gotta get my products more polished so my business can grow faster.

I need to have a section where it shows a list of modulation connections and metaparameter assignments, that would be nice as well.

**Comment by RobinSchmidt** [comment]
i actually needed the larger chunk of yesterday to get the halpern and gaussian prototype filter designs to work. there were some unexpected stumbling blocks, but now it looks good, so we could now look into filterbank design.

the result of my explorations is actually pretty cool though - you can try the new Oscillator3D in Chainer (in sources). try to set up some little frequency offsets between x,y,z and use renormalization - and enjoy instant dubstep'ish wobbles

**Comment by elanhickler** [comment]
your 3d oscillator is 3 completely uncorrelated oscillators. :(

that's no fun.

You need cross modulation / feedback modulation and filtering for those modulations.

**Comment by RobinSchmidt** [comment]
> your 3d oscillator is 3 completely uncorrelated oscillators. :( that's no fun.

that's the way, you produce 3D lissajous figures. for example, set freq-scales for x,y,z to 2,3,5. but when you then have some slight freq-offsets from the integer relationship, the patterns move. when you then add renormalization, you'll some buzziness that phases in and out which i find pretty cool. so, my idea of having independent frequencies was that you can lock the movements in the 3 dimensions together (when there's and exact integer relationship) but don't have to. it add another degree of freedom. could be added to 2D xoxos osc as well. when the two frequencies (for x,y) are equal and the oscs are 90° out of phase, you would recover the original xoxos osc algorithm

> You need cross modulation / feedback modulation and modulation filtering.

yes, i was thinking about a phase-mod matrix already

**Comment by RobinSchmidt** [comment]
but i guess further explorations have to be postponed and now the filter bank should get top priority

**Comment by elanhickler** [comment]
question: what filter bank?

closing! feel free to reply though.
