### ISSUE TITLE
How do I change the location to look for the license file per product?

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#13]
Robin, what do I need to do to create a variable per product for the location of the preset?

I need a different location per product or per system Mac/Win/Linux potentially.

I can't tell what's going on here with the #if

```
#if JUCE_MSVC
  // retrieve the directory in which the plugIn resides:
  File         thisPlugInAsFile      = File::getSpecialLocation(juce::File::currentExecutableFile);
  File         keyDirectoryAsFile   = thisPlugInAsFile.getParentDirectory();
#else
	
	// Most correct path would be /~/Library/Application Support/Soundemote/ but it's a hassle for the user to find this,
	// so we fallback to ~/Documents/Soundemote/
	
#if 1
	File userDocuments = File::getSpecialLocation(juce::File::userDocumentsDirectory);
	File keyDirectoryAsFile = File(File::addTrailingSeparator(File::addTrailingSeparator(userDocuments.getFullPathName()) + plugInVendor));
#else
	File userAppData = File::getSpecialLocation(juce::File::userApplicationDataDirectory);
	File keyDirectoryAsFile = File(File::addTrailingSeparator(File::addTrailingSeparator(userAppData.getFullPathName()) + plugInVendor) + plugInName);
#endif // 1
	
#endif // JUCE_MSVC
```

Why isn't 
```
#ifdef _WIN32
#elif __APPLE__
#endif 
```
being used?

**Comment by RobinSchmidt** [comment]
presets or license files? because these two types of files are handled by different classes. the license check is handled by the class PaywareAudioPlugIn. preset files are handled by my AudioModule class. that's a kind of lower level "pseudo-plugin" class that handles presets, parameters, states, etc. but an AudioModule can be simply wrapped into a plugin (payware or not) by the call (i use the TestPlugin as example):

```
AudioProcessor* JUCE_CALLTYPE createPluginFilter()
{
  TestAudioModule *dummy = nullptr; 
  //return createPluginWithMidi(dummy);
  return createPaywarePlugin(dummy, TESTPLUGIN, 3);
}
```
 
you could introduce a juce::String member variable in the class PaywareAudioPlugIn and set it up like:
```
AudioProcessor* JUCE_CALLTYPE createPluginFilter()
{
  TestAudioModule *dummy = nullptr; 
  AudioPlugin* plugin = createPaywarePlugin(dummy, TESTPLUGIN, 3);
  plugin->setLicenseDirectory([insert license file directory string here]);
  return plugin;
}
```

you would then also have to implement the function setLicenseDirectory which should...well...do the obviuos thing...and then use that string in the key-checking function

**Comment by RobinSchmidt** [comment]
presets on the other hand are handled by the AudioModule class, which all of your products are subclases of. somewhere in the constructor you have: `setActiveDirectory(getApplicationDirectory() + "/TestPlugin");`. you would just need to replace this call to change the (default) preset directory

**Comment by RobinSchmidt** [comment]
by the way, the purpose of this AudioModule/AudioPlugin wrapping business is to be able to combine several "Modules" into a single "Plugin" (without having all the host/plugin communication overhead in each module) - like a filter is a module which can be used inside a synth plugin project - but also be wrapped into a plugin by itself - if one so wishes.

**Comment by RobinSchmidt** [comment]
...it also enables hierarchical preset management which is a cool thing for more complex plugins. ...load/save preset for the filter, osc-section, envelope-settings separately, etc.

**Comment by RobinSchmidt** [comment]
...wait no... that `plugin->setLicenseDirectory` won't work because at this time it might be too late to set it. i have to think about that

**Comment by elanhickler** [comment]
ok, as soon as you can, tell me how I could customize the license directory per operating system per product
