### ISSUE TITLE
Need to change string conversion function during runtime

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#132]
I get a thread lock crash or something trying to assign string conversion function.

I want to have a slider be quantized or not quantized and change the number from decimal to integer.

**Comment by RobinSchmidt** [comment]
uh...what does your code look like and how/where does it get called? maybe you are trying to replace it while it's in use or something. maybe i need to acquire the mutex lock of the underlying parameter in `RSlider::setStringConversionFunction`

**Comment by elanhickler** [comment]
calling setStringConversionFunction in the slider value change callback

**Comment by RobinSchmidt** [comment]
> slider value change callback

what do you mean by that? `RSlider::setValue`? or are you talking about the value change callback in the Parameter class?

**Comment by elanhickler** [comment]
std::function set value change callback

**Comment by elanhickler** [comment]
no longer relevant / old thread
