### ISSUE TITLE
cant get background image to work

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#133]
![image](https://user-images.githubusercontent.com/9116575/33702625-b2256414-dae1-11e7-9fc8-5eaada2d9b2c.png)

![image](https://user-images.githubusercontent.com/9116575/33702563-715b4e6c-dae1-11e7-84ba-1abfbe94d9d4.png)

![image](https://user-images.githubusercontent.com/9116575/33702541-5628d6e6-dae1-11e7-9f56-ff6295e44b93.png)

any ideas?

**Comment by elanhickler** [comment]
also my client needs that multiband compressor asap!

**Comment by RobinSchmidt** [comment]
hmm...why do you subclass it from RWidget and not just use a juce::Image? i think, if it doesn't appear it may be due the fact that it is a subclass of juce::Component and you may need something like addAndMakeVisible? but as said, i'd probably not bother with RWidget at all and instead just override paint() in your editor subclass and draw the image there

> also my client needs that multiband compressor asap!

deadline is 10th, right? i'm trying to meet it. it's actually just all the stupid bring grunt work of getting the AudioModule and gui-editor infrastruture done. ...but i need to think a little how to organize the gui even if it's just a basic one

**Comment by elanhickler** [comment]
Can't get the plugin to work, getting a nullptr with xml state loading.

Also, why doesn't the compressor have a processSampleFrame function?

**Comment by elanhickler** [comment]
hmm, the error doesn't happen with another project I have, I think I will just copy/paste the working project and replace the non working one.

**Comment by elanhickler** [comment]
got bg image working
