### ISSUE TITLE
Need help finishing up M-Ref

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#134]
Need to create a dropdown menu for M-Ref (user version) where the callback is to load a specific preset (the preset will be in binary format). So I need to somehow call the preset loading function from the dropdown menu callback.

There's a dev version and user version. User version is just to load a set number of presets. Dev version is finished for now.

Edit: Also, why is GUI so laggy? Well it's not so much that it's laggy, but if you, for example, move the position of an EQ point  with mouse at a certain speed, gui stops updating while mouse is moving.

**Comment by RobinSchmidt** [comment]
is "m-ref" the eq multiband-comp for your client? i have not yet seen that product in action. laggy gui....well...i guess it's a performance issue. if you move a node in an eq plot, a lot of things happen. a complete new curve has to be calculated, passed to the juce graphics engine and drawn. and i'm using the standard juce drawing functions (Graphics::drawLine, etc.) there without any hardware acceleration. maybe that's the bottleneck. maybe it can be optimized. i remember that one day you pointed me to a juce forum thread where someone suggested how to enable open-gl acceleration for all the basic juce drawing functions. maybe we should try that

**Comment by elanhickler** [comment]
can I call this from a dropdown menu?

![image](https://user-images.githubusercontent.com/9116575/33806427-50dc728c-dd85-11e7-8537-823a5bb7576e.png)

**Comment by RobinSchmidt** [comment]
yes, i think so. i can't see why not

**Comment by elanhickler** [comment]
M-ref project is over, will remain incomplete due to abandonment.
