### ISSUE TITLE
Soundemote TODO List for Robin (2017-12-10)

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#135]
1. * [ ] GUI needs update on preset change: #113
1. * [ ] Smoothing is buggy, sliders/values jump around, etc.
1. * [ ] upsampling filter for prettyscope
1. * [ ] Greg from OrangeTreeSamples needs that frequency locking tuner phase drift problem fixed
1. * [ ] macro parameters

**Comment by RobinSchmidt** [comment]
(1) i think, you can call StateFileManager::loadStateFromXmlFile (it's a baseclass of AudioModule)
(4) did you try Desktop::setKioskModeComponent with the scope-display as i suggested somewhere else?

i think, i'll look into the 2 remaining Mushroom Generator needs next and then into the other things.

btw. i crossed the 1000€ mark again, so may i send a new invoice soon?

**Comment by elanhickler** [comment]
can't figure out where to call `juce::Desktop::setKioskModeComponent`, says it must be a non-static member, no idea what class derives `Desktop`

**Comment by RobinSchmidt** [comment]
aahh - i see - you need to acquire an actual object of class Desktop, because it's a non-static member function. i guess, you should use that: 

https://juce.com/doc/classDesktop#a15ebe474aab368cff35578b8f7bec6c1

i suppose, the class follows the singleton design pattern:

https://sourcemaking.com/design_patterns/singleton

as said, just guessing - i never used the class myself so far. but it seems a pretty obvious case for singleton

**Comment by elanhickler** [comment]
![image](https://user-images.githubusercontent.com/9116575/33810672-ef91172c-ddc4-11e7-9d38-ecad87ab4a63.png)

Are you somehow overriding this stuff with your library? I wanted native title bar, it's set to true. No cigar. Also, when using kiosk mode, the standalone options/title bar is still visible. Also, I think I need to resize and set position of window to make it ACTUALLY full screen.

**Comment by elanhickler** [comment]
wait maybe the standalone is just useing a different main.cpp

ok, plugin doesn't do full screen either. wtf............

**Comment by RobinSchmidt** [comment]
i don't think, i'm overriding any of these. but isn't your scope-display class derived from juce::Component anyway? or is it a subclass of some class in my library? ...also - what is a cigar in this context? :-O

**Comment by elanhickler** [comment]
what are you talking about cigar?

also, it's called OpenGLCanvas, not scopedisplayOpenGL, I renamed classes and did significant code cleanup.

OpenGLCanvas is a MainContentComponent

**Comment by elanhickler** [comment]
error, needs to be on desktop.

![image](https://user-images.githubusercontent.com/9116575/33810959-5f66438e-ddc9-11e7-807c-6d1e096e67ab.png)

**Comment by RobinSchmidt** [comment]
you said:

>  I wanted native title bar, it's set to true. No cigar. 

and i was like: wtf? :-D

hmm...maybe you need to call this before on the canvas: https://juce.com/doc/classComponent#ad717da76012d971197fd8cf943f3e721
..yeah -  i'm not up to date with the code changes you made meanwhile. ...but you know what i mean. i think, this "MainContentComponent" is a class that jim wrote in the very beginning to figure out juce-opengl stuff and should probably renamed into something more meaningful as well (i think the name comes form the default juce-names when creating a new application project)

**Comment by elanhickler** [comment]
no cigar means "it didn't work" or "i didn't get something I was trying to get" or "failed!"

**Comment by RobinSchmidt** [comment]
aaah...ok! haha. i didn't know this

**Comment by elanhickler** [comment]
god damnit, i have a opengl error when trying to do fullscreen, may have to get lorcan involved to make this work.

**Comment by RobinSchmidt** [comment]
yeah - opengl stuff is his domain of expertise

**Comment by RobinSchmidt** [comment]
big fucking water damage in the house - again. i was carrying the water bucket-wise out of my kitchen. living room is also affected. :-( sooo, i was not able to do any work today and probably tomorrow as well

**Comment by elanhickler** [comment]
dam. you have a bad roof?

**Comment by elanhickler** [comment]
also why are you cursing in american? don't you like german curses?

**Comment by RobinSchmidt** [comment]
> don't you like german curses?

of course i do! so eine scheiße! it's not the roof - it comes from the water conduits. some connection got broken in the 3rd floor (i'm in the 1st). now some neighbours and also the facility caretaker and the plumbing company guys (who were here an hour ago) told me, that actually all the armored tubes in the house need to be replaced. they are rusty or something. ...and because i'm the flat owner, i have to pay for such a replacement myself (700€) ...sometime next year maybe. i don't have to do it, but if the same things happens in my flat, i guess, i'll be held responsible for any damage to other flats (or my liability insurance at least). fortunately, all the painter work that needs to be done now (soon, sometime) here will be covered by some other insurance (either of the house and/or the guy in the 3rd floor)

**Comment by elanhickler** [comment]
good to hear!.

hey, need help with this:

![image](https://user-images.githubusercontent.com/9116575/33916385-b49d17b8-df65-11e7-8447-2ba8d467d437.png)

**Comment by elanhickler** [comment]
I think I figured it out, but now I'm getting crash because smoothingManager is nullptr, wtf?

**Comment by elanhickler** [comment]
ok now I added a check for smoothingmanager being nullptr;

![image](https://user-images.githubusercontent.com/9116575/33917471-b78b5254-df6b-11e7-88a5-e00e2db33cb5.png)

now the dropdown menu isn't calling this function, the breakpoint is never hit WHY WTF WHY IS EVERYTHING SO DIFFICULT.

**Comment by RobinSchmidt** [comment]
we have this function here:
```cpp
void AudioPlugin::setAudioModuleToWrap(AudioModule* moduleToWrap)
{
  jassert(moduleToWrap != nullptr); // you must pass a valid object here
  wrappedAudioModule = moduleToWrap;
  wrappedAudioModule->setSmoothingManager(&smoothingManager);
  wrappedAudioModule->setMetaParameterManager(&metaParaManager);
}
```
which should actually get called some time early in the startup process. after that, the smoothingManager should not be a nullptr anymore. does your function somehow get called before the smoothingManager is set up? is your MRefDesignerModule the top-level module, i.e. the one that is directly wrapped into a plugin?

**Comment by RobinSchmidt** [comment]
the smoothingManager and metaManager are objects that exist once on the plugin level and are shared between all AudioModules and their child-modules that make up the plugin. the AudioModule class holds only a pointer which is set up as soon as it is wrapped into an AudioPlugin. child-modules should actually also receive the pointer whenever they are added. hmm...hard to say off the cuff, whyt's wrong here - but a nullptr for smoothingManager should actually not happen, i think

**Comment by elanhickler** [comment]
yeah it's the top level editor

**Comment by elanhickler** [comment]
the project in question is Soundemote\M-Ref\Mref User in case you were planning on trying to build.

**Comment by RobinSchmidt** [comment]
ok - i can build it and load the dummy preset form Installer/Presets ...nothing seems to happen (i don't see the preset name file appear in the box). no crash either

**Comment by RobinSchmidt** [comment]
btw - i get a memory leak alert on shutdown related to juce::DrawableImage

**Comment by elanhickler** [comment]
What do you mean you can load the dummy preset? Are you using the dropdown? This is what the whole thing is about, using a dropdown to load presets.

No idea about memory leaks.

**Comment by RobinSchmidt** [comment]
what dropdown? i see only a preset loader widget.
![image](https://user-images.githubusercontent.com/1833099/33960627-9b0374b4-e04b-11e7-849c-c608a596b0e1.png)

> No idea about memory leaks.

you probably create an object somewhere via new and have forgotten the corresponding delete. if you test/debug with juce host, you'll trigger an "jassert". that's the leak detection mechanism i mentioned when we were talking about pros and cons of smart-pointers

**Comment by elanhickler** [comment]
I don't know why or how to deal with memory leaks, I'm not doing anything special.

oh what the f*** I never committed the changes.

**Comment by RobinSchmidt** [comment]
btw, i added the missing processStereoFrame to MultiComp - so you can use that instead of unprotecting the core object

**Comment by RobinSchmidt** [comment]
ok, check in your updates. i guess i can fix that memory leak easily for you

**Comment by elanhickler** [comment]
......ok..... well, I'll definitely see how you fixed it so I know what not to do.

**Comment by RobinSchmidt** [comment]
it's basically, for every "new" you have somewhere in the code, you need a corresponding "delete" somewhere else. if you forget the delete, the dynamically allocated memory never gets freed and you have what is called a memory leak. smart-pointers automate that deletion

**Comment by elanhickler** [comment]
I understand it that much, but I don't remember using a new anywhere.

I do need to learn to use smart pointers.

**Comment by RobinSchmidt** [comment]
ok, tell me when the repo is ready for me to grab

**Comment by elanhickler** [comment]
now

**Comment by RobinSchmidt** [comment]
hmmm...actually, it seems you area already using smart-pointers, like in `ScopedPointer<Drawable> drawable;` in RImage. my initialy suspicion was that you forgot the delete for a raw pointer. i also get memory leaks for XmlElements now. could it be somehow related to how the binary data resources are used? ...not as easy as i thought

however, i don't get any crashes when switching the presets via the dropdown.

i changed your code to use compressorModule->processStereoFrame now, so the core object needs not to be unprotected.

hmm - don't know what to do

**Comment by elanhickler** [comment]
![image](https://user-images.githubusercontent.com/9116575/33963561-922d413c-e012-11e7-8c66-0afd0680bf49.png)

**Comment by elanhickler** [comment]
also, do you even know if the callback is being called?! Put a breakpoint to make sure!

![image](https://user-images.githubusercontent.com/9116575/33963582-ac528d06-e012-11e7-86b5-967818bf33c6.png)

**Comment by RobinSchmidt** [comment]
i just added a deletion of an XmlElement - but i still get the xml-leak warning. however, that delete i just added should certainly be there, i think

**Comment by elanhickler** [comment]
Remember the other problem I was having is that for some reason, callbacks are not being called because some variable is set to false. see: https://github.com/RobinSchmidt/RS-MET/issues/135#issuecomment-351253690

**Comment by RobinSchmidt** [comment]
warning without my added delete: 

Leaked objects detected: 30 instance(s) of class XmlElement

warning with my added delete:

Leaked objects detected: 15 instance(s) of class XmlElement

..soo, i have catched only half of them

**Comment by RobinSchmidt** [comment]
...ok - fixed the other xml leak

**Comment by RobinSchmidt** [comment]
xml.parse and xml.getDocumentElement return pointers to XmlElement that the caller must delete

**Comment by elanhickler** [comment]
so what about the crashes?... does fixing the memory leak fix crashes or something?

**Comment by RobinSchmidt** [comment]
i don't have any crashes here, but i just fixed the remaining leak related to Drawable

**Comment by RobinSchmidt** [comment]
tried now also in reaper - still no crash. switching through Preset 1-3, again and again back and forth. nothing crashy happens

**Comment by RobinSchmidt** [comment]
aahh -  i know now why the smoothingManager is initially a nullptr. we would have to change the constructor

MRefDesignerModule(juce::CriticalSection *lockToUse, jura::MetaParameterManager* metaManagerToUse);

to take a SmoothingManager pointer as additional argument to change that.

**Comment by RobinSchmidt** [comment]
...hmm...but i guess it's better to leave it as is

**Comment by elanhickler** [comment]
have you verified that the preset is actually being changed, i.e. is the callback being called?

**Comment by RobinSchmidt** [comment]
oh - no. it's not being called. why not?

**Comment by elanhickler** [comment]
Ok, just discovered a hint to this issue. If you load a preset via dropdown THEN load a preset with the load/save, we get the same crash. WTFFFFFFFF??????????? That means loading a preset with the dropdown creates some issue where ANY preset loading activity will crash next time it occurs. More specifically, it crashes inside the JUCE XML parser.........wat......

**Comment by elanhickler** [comment]
> oh - no. it's not being called. why not?
see: #135 (comment), I made sure to set that condition to always be true just for testing... and yeah, no idea why it's false.

**Comment by elanhickler** [comment]
edit: I'm going to try some different code, there's some code examples in the document. Will try to follow that,

**Comment by RobinSchmidt** [comment]
i switched off smoothing for the underlying parameter. now it gets called

**Comment by RobinSchmidt** [comment]
it's because in the `rsSmoothableParameter` class, i override `setValue` such that the callback does not get called immediately but calls to the callback are deferred to when the smoothed-value gets updated

```cpp
void rsSmoothableParameter::setValue(double newValue, bool sendNotification, bool callCallbacks)
{
  if(value == newValue)
    return;
  if(smoothingTime == 0.0 || smoothingManager == nullptr)
    Parameter::setValue(newValue, sendNotification, callCallbacks);
  else
  {
    double oldValue = getValue();
    Parameter::setValue(newValue, sendNotification, false);
    smoothingManager->addSmootherFor(this, newValue, oldValue);
  }
}
```

**Comment by RobinSchmidt** [comment]
...still no crash, though

**Comment by elanhickler** [comment]
ok, i disabled smoothing for dropdowns (removed your code to disable it locally)

**Comment by elanhickler** [comment]
ok no more crash................ you fixed it.

**Comment by elanhickler** [comment]
...but the gain slider callback breakpoint is not getting hit when moving the slider...

![image](https://user-images.githubusercontent.com/9116575/33973537-a8c324b0-e040-11e7-83d0-04228cd66e29.png)

...unless I set smoothing time to 0??? WHAT? WHY ROBIN...

**Comment by RobinSchmidt** [comment]
because in your processBlock function, you are not doing the smoothing updates ...i guess

**Comment by elanhickler** [comment]
OHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH... FFFFFFFFFFFFF*************************


sorry.

**Comment by RobinSchmidt** [comment]
no problem. 4 eyes see more than 2

**Comment by elanhickler** [comment]
It might be nice to disable smoothing by default. Your smoothing value is set to 0 by default... or did you already disable it by default? Maybe I'm enabling it by default somewhere.

**Comment by RobinSchmidt** [comment]
btw: is your client satisfied by the multiband compressor, sound-wise?

**Comment by elanhickler** [comment]
still no word from him about that. i told him to start using it... maybe now that i got the dropdown working he will use it

**Comment by elanhickler** [comment]
Ok one other little issue...

The plugin's name for creating presets is "M-Ref Dev" which is illegal in xml, i.e.

`<M-Ref Dev PatchFormat="1">`

the space between Ref and Def is illegal.

Can't think of a fix other than renaming the plugin, no idea how your preset creation system works. I'd like to keep the space for example:

![image](https://user-images.githubusercontent.com/9116575/33974555-566aedaa-e046-11e7-9641-56153fb3259d.png)

**Comment by RobinSchmidt** [comment]
is this the moduleName member of AudioModule? i think, i could just remove spaces (and perhaps all xml-illegal characters) when creating the xml

**Comment by elanhickler** [comment]
yes please do that! That was my idea for a fix but I didn't know if your "recall presets" function relied on perfect character match of the plugin name or not... but then it seems if the plugin name doesn't match with the `PatchFormat` name, it still loads the preset??? i dunno. It's nice that it still tries to load the preset even if the name doesn't match, I think it has worked like that.

**Comment by RobinSchmidt** [comment]
>  I didn't know if your "recall presets" function relied on perfect character match of the plugin name or not

well, it does - but should not be a problem, since so far we apparently used legal xml-names for module names. hmm...but actually, it seems, you don't need to keep the moduleName but rather the plugInName (member of AudioPlugin) you could use the name with spaces for the pluginName and the version without spaces for the moduleName. i'd rather avoid all these string-manipulations and checks in preset creation and recall, if possible (it may slow down the code)

**Comment by RobinSchmidt** [comment]
uuuh...i just wonder where the host gets the plugin name from anyway. the plugInName member is an empty string :-O ...have to figure that out....

**Comment by RobinSchmidt** [comment]
> It uses the plugin's name somewhere (as specified in the jucer file / probably references a macro). I'd like to keep the space for example

ahhh - i think, it uses the "Binary name" in the jucer file M-Ref ($(PlatformTarget)) -  so when you rename the moduleName to something without spaces, this should not be affected

**Comment by RobinSchmidt** [comment]
just change the line:
 `moduleName = JucePlugin_Name; // correct name is vital for licensing system`
in the constructor to use some xml-valid string instead of the macro

**Comment by elanhickler** [comment]
in your framework or my code?

**Comment by RobinSchmidt** [comment]
in MRefDesignerModule::MRefDesignerModule

**Comment by elanhickler** [comment]
still waiting for commit.

I'll have to take what you did there and make a more all-encompassing solution for myself.

**Comment by RobinSchmidt** [comment]
what? i don't get that. what are you waiting for?

**Comment by elanhickler** [comment]
the changes... pushed changes?

**Comment by elanhickler** [comment]
......misread... you said change not changed.

**Comment by RobinSchmidt** [comment]
aaaahhh...ok...i see. yes, i was meaning you have to do that
