### ISSUE TITLE
An easy addition to modulation right click menu to show what is connected

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#137]
Can you do this quickly:

Add an asterisk to the mod menu for things that have a connection? Like this. It would be super helpful!

![image](https://user-images.githubusercontent.com/9116575/34070032-8eb2c950-e21a-11e7-8d5a-35989b6b0c1f.png)

**Comment by RobinSchmidt** [comment]
done.

**Comment by elanhickler** [comment]
YAYYYY!!! Thanks! I was going to do it myself, but I was looking at your code and I found it was probably easy to do but there wasn't an obvious way to do it, you would have done it differently that I would have done perhaps... you did it similar to what I was thinking.

**Comment by RobinSchmidt** [comment]
just have a look at my changes. should be pretty obvious. i had something very similar for ModulationTarget (the hasModulation() function). i just needed to copy/paste/edit that code to the ModulationSource class also. and i renamed the hasModulation function, such that the names of these two "sibling" functions are consistent

**Comment by elanhickler** [comment]
Why is this helpful? Because when I'm creating a patch I need to know what LFO or modulator is free, so I can assign a fresh modulator. Also, it tells me what is connected in general.
