### ISSUE TITLE
Quirky FM behavior due to allowing infinite frequency

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#138]
So, I've been limiting the frequency of my oscillators to equal to samplerate. It turns out that this limitations prevents the ability to get quirky FM behavior, but I am very confused by this phenomenon because the quirky behavior is only apparent when you do this:

```
LFO output of extreme amplitude at audio rate (tracking the oscillator frequency for classic/in-tune FM) -> 
-> heavy lowpass filtering ->
-> oscillator linear FM input.
```

Example: https://youtu.be/_E3SLrFej3Y

The lowpass filter should be removing enough amplitude so that the frequency never actually goes beyond samplerate frequency... or that's what I think should be the case... so the limitation should never be hit... so why does removing the limitation create this wonderful quirky behavior? The growls of low notes, the human-like vibrato of high notes, and the chaotic unstable tuning of the mid-range notes is ALL because of this modulation. It's awesome! It does so much.

I know that the quirky unstable tuning behavior seems to follow the undersampling artifacts that are produced the oscillator is made to go above and below nyquist at high rate. The only thing I can think of is that, maybe, if you undersample the LFO, you can get the quirky behavior while still imposing frequency limit on oscillators.

...My goal with this is to understand how to get the quirky behavior without removing the frequency limit, so we could get even more quirky behavior and combine that quirk in other places to create more organic or chaotic modulation, or in general, have more control over the behavior.

**Comment by RobinSchmidt** [comment]
> The lowpass filter should be removing enough amplitude so that the frequency never actually goes beyond samplerate frequency

why do you assume that? and what do you mean by "heavy" lowpass filtering? is the lowpass cutoff tuned far below the fundamental frequency of the wave you are filtering? only then it will remove amplitude, otherwise it will only remove overtones

btw: you should limit not at the sample-rate but at *half* the sample-rate. that's the highest representable frequency. anything above that will be aliased.

**Comment by RobinSchmidt** [comment]
> My goal with this is to understand how to get the quirky behavior without removing the frequency limit, so we could get even more quirky behavior and combine that quirk in other places to create more organic or chaotic modulation, or in general, have more control over the behavior.

maybe we should experiment with using fixed (and adjustable) internal sample-rates and resample to host-sample-rate only as final step. something that may be generally useful anyway (having an internal sample-rate). we would perhaps need a flexible realtime resampler class

**Comment by elanhickler** [comment]
yes, well below the fundamental. Ok, experimenting with this behavior, I'm using 2.0hz on the lowpass (yes TWO hertz). and 100,000 amplitude on the linear FM. Also, the quirky behavior only really happens using sawtooth. So that means the shape has to be assymetrical. Sine/Tri/Square doesn't work.

**Comment by RobinSchmidt** [comment]
very interesting. when the lowpass is at 2 Hz and amp is at 100,000, then 4 Hz is at 50k, 8Hz at 25k, 16 Hz at 12.5k, 32 at ...errr 2^k Hz is at an amplitude of 100,000 / (2^(k-1))...i think...what is the frequency of the LFO (or oscillator)

**Comment by elanhickler** [comment]
http://www.elanhickler.com/transfer/Spiral%20Generator%20quirky%20fm%20for%20robin.mp3

http://www.elanhickler.com/transfer/quirky%20fm%20for%20robin.xml

ooo just found a new trick, you can keep the moduator the same frequency and lower the target frequecy to get quirky behavior at lower "playing" frequencies

modulatorfollows the frequency of the target.

but it's good to offset the modulator's frequency from the target around +/-4hz

**Comment by elanhickler** [comment]
hmmmmmmm.... maybe it's a bit reduction kinda thing... because we're doing heavy filtering which lowers the amplitude of the signal significantly, then boosting the signal significantly... but... no... the effect goes away with more oversampling... :shrug:

**Comment by RobinSchmidt** [comment]
> maybe it's a bit reduction kinda thing... because we're doing heavy filtering which lowers the amplitude of the signal significantly, then boosting the signal significantly... but... no... the quirky effect is lessened with more oversampling

and with floating point numbers, there actually isn't such a thing as bit reduction at low amplitudes. it's only an issue with fixed point numbers
