### ISSUE TITLE
parameter smoothing is setting slider value

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#139]
I can't describe the problem exactly it because I didn't write the code, but this is just strange behavior. It seems like the smoothing manager is setting the slider value rather than the slider value setting the parameter manager's target value. Or maybe the problem is something else.

see gif: https://puu.sh/yIftr/9a55ecf48a.gif

**Comment by elanhickler** [comment]
It is becoming apparent that the slider glitch bug I thought was just a problem with PrettyScope, it's actually a problem with smoothing in general. I see sliders gitching/jumping around while I am adjusting said slider.

**Comment by RobinSchmidt** [comment]
uuuh...that's bad - so you see this in all plugins now? but i haven't seen in in chainer yet

**Comment by elanhickler** [comment]
use very high smoothing amount, try 1 second smoothing

**Comment by RobinSchmidt** [comment]
yes! you are right. with 1000ms, i see it in toolchain, too. damn!

**Comment by elanhickler** [comment]
Smoothing doesn't work for child modules when modulation is connected.

**Comment by RobinSchmidt** [comment]
isn't this point 6 in this list?
https://github.com/RobinSchmidt/RS-MET/issues/118
and was recently fixed? does it still (or again) not work?

**Comment by elanhickler** [comment]
yeah i guess it was never fixed. I forgot the problem was only when modulators are connected.

**Comment by elanhickler** [comment]
finally smoothing is bug free!!!!!!!!!!!!!!!!!!
