### ISSUE TITLE
Need an 11 note keyboard widget

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#141]
I need a little 11 note keyboard widget, I want to implement my algorithmic arpeggiator idea. Do you have a widget? If not, I think I could create my own out of a series of buttons or something. You simply enable what notes you want to be hit, then I'll have some sliders for timing, how many octaves, etc. Then to make one of my plugins do an arpeggio, you just modulate "currently selected note number"

Controls:
- Current Selected Note (Default is 1)
- Number of Octaves (Default is 1)
- Middle C (Default is C3)
- Tempo (How often to change the selected note)
- Synced Start Delay (like tempo offset / phase offset, how long to wait before starting the sequence)
- Swing Amount

so let's say you enable C and G. 

If # of octaves = 1, Note 1 = C3, Note 2 = G3. Note 3 = C3, Note 4 = G3, etc.

If # of octaves = 3, Note 1 = C3, Note 2 = G3, Note 3 = C4, Note 4 = G4, etc.

Assign a sine wave to modulate Current Selected Note, boom, you have an arpeggio. I will abs() the input value to allow negative modulation... or maybe it should wrap... maybe I'll have an option to wrap or abs.

Hmm, I could also have a slider for Current Octave so you could modulate octaves instead of saying how many octaves you want in the note sequence.

Tempo slider will control HOW OFTEN to allow note to change, so it can change on beats instead of whenever the modulator causes the slider to go to the next value. To get rhythmic variation, you can modulate the tempo slider, hmm... I might need a non-modulatable option for how often to allow tempo changes to keep things in beat.

**Comment by elanhickler** [comment]
To take things another step, there should be a way to switch chords, so you could quickly swap out the chosen notes for anotehr set of chosen notes.

Hmm, maybe I could have another slider for "current chosen note set". And the user can set up each set of notes (maybe I can have up to 10 selectable via slider or something), then you modulate the current chosen note set.

Chaotically modulating chosen note set could create some interesting melodies as you quickly switch chords. Well, chaotically modulating any of these parameters will offer interesting rhythms and melodies.

**Comment by elanhickler** [comment]
omg this would be so awesome animated, so it shows you what note is being played on the keyboard widget at any given time.

**Comment by RobinSchmidt** [comment]
the only thing i have that goes into that direction is the step-sequencer in AciDevil. maybe have a look. not exactly what you want but could possibly be used as starting point

**Comment by elanhickler** [comment]
k

**Comment by elanhickler** [comment]
thanks. going to close!
