### ISSUE TITLE
how do I make a plugin load xml preset under a different name?

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#144]
Right now Torus Generator, for example, only loads "Torus_Generator" presets. Can I also allow it to load "TorusGenerator" presets? As a matter of fact, I would do away with checking that xml/preset name.

**Comment by RobinSchmidt** [comment]
hmm...actually AudioModule::setStateFromXml does not even check the name of the xml-element. i think, the correct name is only relevant, when a module is a child-module of some other module. then, the parent-module has to use this name to identify which child-xml-element to use to restore the state of the child-module. what happens, when the tag-name is missing the underscore?

**Comment by elanhickler** [comment]
will have to get back to you on the exact details of the issue, but I had a project I think it was using the version of the plugin that was named TorusGenerator. I later changed the name to Torus_Generator and now the project loads default patches for all the instances. The patch is saved in the REAPER plugin states, which I may have to manually recover to get more details on the issue.

**Comment by elanhickler** [comment]
not sure what the issue was. I'll create a new thread if it comes up again and make sure I have my facts straight.
