### ISSUE TITLE
Standalone plugin crashes due to smoothing manager being nullptr

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#145]
And I suspect this could be the issue with my non-standalone-version plugins crashing for some customers.

Adding a "if not nullptr" check in a few places fixes this.

`jura_AudioModule.cpp` change needed (note you spelled Bypassed wrong, not sure why "by-assed" means, perhaps a german mistranslation of a curse?):
```cpp
  bool smoothingIsBypassed = true;
  if (smoothingManager != nullptr)
  {
    smoothingIsBypassed = smoothingManager->isSmoothingBypassed();
    smoothingManager->setBypassSmoothing(true);
  }
```

```cpp
  if (smoothingManager != nullptr)
    smoothingManager->setBypassSmoothing(smoothingIsBypassed); // restore old bypass state
```

aaaaand.... sh*** standalone plugin doesn't work at all due to a jassert, something about not calling reset for adding something to midi queue, but the call stack is all juce code!!!!!!! F********* I need this to work! I might have to rollback to an old RS-MET. This must be due to the new JUCE code.

![image](https://user-images.githubusercontent.com/9116575/34284951-fcea70fe-e692-11e7-8da9-304a3a4aa45a.png)

**Comment by elanhickler** [comment]
another weird thing about the new JUCE code is... this is how the previous audio settings looks:

![image](https://user-images.githubusercontent.com/9116575/34285038-c670af9c-e693-11e7-8917-0dae9f7b5773.png)

new version omits channel select!!! WTF:

![image](https://user-images.githubusercontent.com/9116575/34285053-e3c5afd4-e693-11e7-9883-9287e4a14ce5.png)

**Comment by elanhickler** [comment]
response seems to adress the standalone plugin issues.

**Comment by elanhickler** [comment]
I just confirmed the nullptr is causing crashes on mac

**Comment by RobinSchmidt** [comment]
ok, i fixed that nullptr in my library. thanks. i just ran into the problem itself when making straightliner load its default patch when pluugin it in. defual patch laoding has changed a little - just add, for example:

loadPreset("000-InitPatchSawtooth.xml");

at the end of your constructor. the path is assumed to be relative with respect to the module's default preset folder (which is given by whatever getSupportDirectory() returns + "/Presets/" + module-type-name)

**Comment by RobinSchmidt** [comment]
ok, done. just add the line `jura::FileManager::companyName = "Soundemote";` to your `AudioProcessor* JUCE_CALLTYPE createPluginFilter()` ...for example - or set it in other other convenient place

**Comment by elanhickler** [comment]
do you know how to customize the standalone plugin so we can actually make a usable one in JUCE 5?

**Comment by RobinSchmidt** [comment]
you mean because of the missing items in the audio setup? no - i did not try that yet

**Comment by elanhickler** [comment]
not asking if you tried it, asking if you know how! 😄

**Comment by RobinSchmidt** [comment]
well - if i didn't try, i don't even know what exactly the problem is. i need to (sort of) finish the release package for win/vst and mac/au first and update the website. if i then have some time left, i may look into supporting other formats - but getting *something* ready to publish has priority

**Comment by elanhickler** [comment]
So you won't be doing standalone? The problem and solution is all here, I just don't understand the solution given. It may be a very simple fix, did you read the reply?

> In the `AudioDeviceSelectorComponent` constructor, you can specify whether certain fields are visible or hidden as explained here: https://juce.com/doc/classAudioDeviceSelectorComponent#a859af6ef664a974dc7d2ce3d24d8f94c3
> 
> As for the assertion, you need to call `reset()` in the prepareToPlay() function of your `AudioProcessor` on your `MidiMessageCollector` like so:
> 
> `midiCollector.reset (sampleRate);`

I just want to know if you know what to even try.

**Comment by elanhickler** [comment]
I can't pull RS-MET changes until this is resolved btw, because it's a JUCE 5 issue.

**Comment by RobinSchmidt** [comment]
so you are now building against an old version of my library before i updated. ok, as said, when i'm done with the release package and website update, i'll look into this. maybe, i can can figure it out, i'll include standalone versions into the initial release, if not, only plugins (i don't really think standalone is very useful for an end-user, to be honest - i consider it more like a convenience for easy testing for us)

**Comment by elanhickler** [comment]
standalone is nice to have, especially for something like your liberty... and i especially need it for pretyscope.... just sayin'

**Comment by elanhickler** [comment]
Just got a message from a customer

> from Mark Loomis
> ```
> Working now, thanks!
> 
> BTW +1 for the standalone versions. Is it possible to create those for Nyquist and Mushroom as well? Much lower friction than launching a huge host app to create patches.
> ```

**Comment by RobinSchmidt** [comment]
yes, i agree - at some point, i'll do it. i just noticed that reaper recognizes toolchain as 64-channel plugin! wtf?! i guess, that's also since the juce update.

**Comment by elanhickler** [comment]
YES another JUCE 5 update. You have to set the number of channels somewhere. I saw it as I was browsing the code, forgot where.

**Comment by RobinSchmidt** [comment]
i thought, it's AudioProcessor::getBusCount. i override it and return 2. but that doesn't seem to be the solution.

**Comment by elanhickler** [comment]
no it's something like calling a function to set number of channels.

**Comment by elanhickler** [comment]
OH if you solve the standalone plugin issue, you will have also solved the number of channels issue.

**Comment by RobinSchmidt** [comment]
ok, it seems, i figured it out. damn, that was tricky! juce used to be a lot easier to use back then.

**Comment by elanhickler** [comment]
solved, created a new todo list for the little remaining issue.
