### ISSUE TITLE
what happened to getDefaultPresetLocation()

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#147]
getDefaultPresetLocation()

loadDefaultPreset()

Edit: Trying to get back onto RS-MET main development branch

**Comment by elanhickler** [comment]
hitting jassert when trying to assign audio output in standalone version

![image](https://user-images.githubusercontent.com/9116575/34324267-a3f795d8-e829-11e7-8e20-8f2b85546f04.png)

**Comment by RobinSchmidt** [comment]
i removed `getDefaultPresetLocation()`. it is sort of quirky to expect client code to override this and load the default preset in library (baseclass) code using that overriden function. instead. you now just call loadPreset at the end of your module constructor, as i mentioned here:
https://github.com/RobinSchmidt/RS-MET/issues/145#issuecomment-353712392

**Comment by elanhickler** [comment]
I invented my own file manager class! I want to continue to do that so I can eventually separate from your plugin framework as much as possible so we can be more independent and not having to worry about changes we each make or need.
