### ISSUE TITLE
Really need mod matrix, how is your library coming along?

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#15]
Really need a mod matrix system. Editing your library is not fun, I can't edit it without causing all sorts of errors, otherwise I would and implement an easy mod matrix for myself.

What are you planning, how will your mod matrix work?

**Comment by RobinSchmidt** [comment]
slowly but surely, i'm sorting everything out. i'm just done with the include centralizations and just started the renaming/prefixing. as for routable modulation...

**Comment by RobinSchmidt** [comment]
one possible design would involve to declare a baseclass Modulator:
```
class Modulator
{
public:
  virtual double* getOutputPointer() { return &output; }
  virtual void update();
protected:
  double output;
};
class Modulator
{
public:
  virtual double* getOutputPointer() { return &output; }
  virtual void update();
protected:
  double output;
};
```
...

**Comment by RobinSchmidt** [comment]
...where update would would be the per-sample update function that assigns the output to a new value and should be overriden by subclasses (like LFO, Envelope, etc.). Next, you would need a class ModulationCollector:

**Comment by RobinSchmidt** [comment]
```
ModulationCollector::collectAndCall()
{
  double sum = 0;
  for(int i = 0; i < size(inputs); i++)
    sum += inputs[i] * depths[i];
  targetCallback.call(sum);
}
```

**Comment by RobinSchmidt** [comment]
the "targetCallback" could be one of the usual setCutoff, setResonance etc. setter functions. there are some subtleties due to desired avoidance of redundant upadates (when a filter receives a setCutoff call - it typically re-computes coeffs, when it then receives a setResoCall (at the same instant, still before a sample is produced via getSample(), it re-computes coeffs again - which is a waste)....

**Comment by RobinSchmidt** [comment]
one could make a special filter class that doesn't re-compute coeffs on setCutoff etc but just sets a "dirty" flag which is checked inside getSample - if true, updateCoeffs is called. ...well...these are my first ideas

**Comment by RobinSchmidt** [comment]
somewhere inside the highest level getSample() function (i.e. of the whole synth), you would first update all modulators, then call collectAndCall for all modulation collectors and only then do the usual computations like filter.getSample(osc.getSample()), etc.

well...it's actually quite complicated and i don't know, if my design idea is viable. setting up a runtime-routable mod-system and make it work with what we already have is not so easy

**Comment by elanhickler** [comment]
wow i created this  issue almost half a year ago. finally fulfilled!
