### ISSUE TITLE
robin, you broke your breakpoint module

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#150]
time/level/shape sliders do nothing!!

😢

**Comment by RobinSchmidt** [comment]
fixed it. weird. in RSlider, i had no notify function anymore. or did i ever have one? but if not, how could it ever work? really weird indeed - i may have to check the history. anyway - it works now again

**Comment by elanhickler** [comment]
yay. :)

I'm making progress of FMD finally!
