### ISSUE TITLE
ideas for Macro controller

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#151]
![image](https://user-images.githubusercontent.com/9116575/34460568-5637c4d4-edcf-11e7-8a67-2fc0dc4342d0.png)

* the red line represents the position of the macro
* we don't necessarily need to have a knob next to the graph, it's just to give you an idea of how it works.
* there should be a right-click option on a parameter to add point to desired macro at its current position (the red line) at the parameter's current value
* there should be a way to engage multiple parameters to add a point for multiple parameters at macro position
* full multi-point implementation with curve options
* value of parameter should appear above the point as you drag as well as the position in the macro.
* mouse modifier to scale the parameter/multipoint in various ways, position or amplitude-wise

**Comment by RobinSchmidt** [comment]
i'm currently working on the node-editor:

![image](https://user-images.githubusercontent.com/1833099/34462206-bf4fe50e-ee3e-11e7-9c9d-daf628afd9a9.png)

..it still has some problems though. but when it's finished, i think, it may be useful in various contexts. currently, i'm developing it in the context of a waveshaper. and guess what: when i include nearest-neighbour interpolation, you can use it also as the flexible quantizer we were recently talking about

**Comment by RobinSchmidt** [comment]
it was a bit tricky to keep the array of (x,y)-values always sorted - which is necessary for it to work as a random-access breakpoint function. but i think, i'm almost there. i just have still problems when more than 2 points have the same x-value. then it gets messy, but i will sort that out

**Comment by RobinSchmidt** [comment]
> it was a bit tricky to keep the array of (x,y)-values always sorted

in my breakpoint editor, i sidestepped the issue by simply not allowing the breakpoint to be moved trough the x-coordinates of its neighbours. but i think, it's nicer, if that's possible

**Comment by RobinSchmidt** [comment]
>  i just have still problems when more than 2 points have the same x-value

which is of course a nonsensical setting - but should be handled reasonably anyway

**Comment by elanhickler** [comment]
two points with the same x value sounds like a square / edge, not nonsensical

I also want to use macro controller like this

midi keytracking -> curve -> some parameter

because so often patches don't sound right as you play the highest or lowest notes.

**Comment by RobinSchmidt** [comment]
> two points with the same x value sounds like a square / edge, not nonsensical

yes, but i said *more than* two. there's nothing you can do with 3 or more points at the same x that can't already do with 2. ...but meanwhile, i have it fixed anyway :-)

**Comment by RobinSchmidt** [comment]
> midi keytracking -> curve -> some parameter

absolutely essential. back in the day, i was wondering why so may big name commercial synths did not even provide keytracking for master volume (things may have changed since, idk)

**Comment by elanhickler** [comment]
btw, how are you achieving efficiency, are you going to store the curve in an array at with some number of data points?

**Comment by elanhickler** [comment]
btw random thought, I want to add your filters to FMD, you remember the ones you were trying to make for me a while back? I want to add them in as a "clean/generic" option, haha, sorry, that's what I think of them. "Generic analog"

**Comment by RobinSchmidt** [comment]
> btw, how are you achieving efficiency, are you going to store the curve in an array at with some number of data points?

my plan is to store only the original datapoints and perhaps for datapoint (i.e. for each curve segment) store precomputed coefficients. instead of
```cpp
  T getValueLinear(T x, size_t i)
  {
    T x1 = xValues[i];
    T y1 = yValues[i];
    T x2 = xValues[i+1];
    T y2 = yValues[i+1];
    T thresh = T(1.e-10); // todo: use epsilon of T
    if(fabs(x2-x1) < thresh)
      return T(0.5) * (y1+y2);
    return y1 + (y2-y1) * (x-x1) / (x2-x1);
  }
```
we'll have something like:
```cpp
  T getValueLinear(T x, size_t i)
  {
    // ...
    return a[i] + b[i] * (x-x[i]);
  }
```
such precomputed coeffs will make an even bigger difference when we use polynomial interpolation later. oh, and the search for right segment will be done by binary search and i'll use the previous result as initial guess for the search, so wee will mostly find the right segment immediately, assuming getting called with continous x-values one after another

**Comment by RobinSchmidt** [comment]
> I want to add your filters to FMD, you remember the ones you were trying to make for me a while back?

yes, i want to also drag them over to rapt and include the reso-replacer into toolchain. ...with loadable resonance waveform. ...any maybe more weird stuff

**Comment by elanhickler** [comment]
noooooooooo, not that one!

The one that you can't control the waveform.

You know, I can get any resonance waveform with FMD, just with experimentation. Just sayin'

**Comment by RobinSchmidt** [comment]
> The one that you can't control the waveform.

i think, that was some baseclass of the one that can anyway. the generic, basic ladder is actually already there. ...or which one are you talking about? we had several variants.

**Comment by elanhickler** [comment]
question: can you use this node thing at audio rate for vector oscillators?

question 2: can you make a 2D version? HEEHEE

**Comment by RobinSchmidt** [comment]
audio-rate: well - i'm currently implementing it as waveshaper, so yeah - i guess so. 

2D: hmmm....how would an interface for something like that look like?....maybe nodes that you drag around in the xy-plane and whose height (z-value) can be adjusted by the mousewheel....and then plot a height-map? or what?

**Comment by elanhickler** [comment]
something like a vector art program

https://puu.sh/yRzWA/9bef0a6435.gif

**Comment by RobinSchmidt** [comment]
ahhh - ok - now i understand. yes, i think, that's mostly a question of how you order the nodes

**Comment by RobinSchmidt** [comment]
oh - i just realized a problem. our automation/meta parameters are actually not really usable as macro-parameters because they require that we are able to do a backward mapping (from the actual parameter back to its meta). ...and such a backward mapping will be at least expensive in the case of arbitrary mapping curves and sometimes impossible (in case of a non-monotonic function) ...hmmm....what to do? introduce another level of indirection for the macro parameters? ...wait, no...maybe i can somehow keep track the x-value before it being mapped to avoid the requirement of an inverse mapping...i need to think about that...

**Comment by RobinSchmidt** [comment]
i think, it implies that the presence of a meta-attachment to some parameter would have to change the behavior of the slider. the slider thumb should always be in sync with the unmapped, normalized meta - but the numeric readout should reflect the actual value - after *both* mapping functions have been applied

**Comment by elanhickler** [comment]
tomorrow i might get started on using jim's solution for a macro parameter... but are you almost done with yours? maybe i could hold off a day or two.

**Comment by RobinSchmidt** [comment]
it really depends on how hard or easy the mapping problem is to solve. let's see where i am this evening with this. i think, i cannot call Parameter::setValue directly anymore from widgets (sliders, etc.)....i have to make sure that i always go through the Parameter::setProportionalValue when i set up a parameter from a widget (this is the normalized value in the 0..1 range)....maybe i even have to make Parameter::setValue protected...at least in subclasses.

but on the plus side - such a change may be also a big step into the solution of our smoothing problem where we noticed that we should better smooth the normalized value instead of the actual one

**Comment by RobinSchmidt** [comment]
btw. do you know, how jim handles this problem?

**Comment by elanhickler** [comment]
I'm using the modulation system to handle this.

dummy slider -> meta map to breakpoint position -> modulation to deisred parameter

**Comment by RobinSchmidt** [comment]
hmmm....i think, my new mapping stuff mayyyy work now. you can test it in toolchain with the debug-module. simply assign a meta to the "Left" parameter and open "Automation setup" to edit the mapping function. you actually re-map the slider behavior there. if you attach "Right" to the same meta, they get cross-coupled. the slider thumb always reflects the meta, the numeric readout reflects the actual value. you'll notice that the xy-pad does not yet reflect the meta but rather the actual value...it needs update.

"Left" and "Right" directly control the (DC) output signal of left and right channel, so with a scope, you can actually check that the mapping is correct

now i need to do some testing and sort out some details (like how to deal with default values in the context of the new, remapped behavior)

**Comment by RobinSchmidt** [comment]
ok, as a next step, i'll implement the state save/recall for the map. if this is done, i think, it may actually be used already in a preliminary way (there's a lot of refinement to do after that, though)

**Comment by RobinSchmidt** [comment]
ok. basic state recall of the mapper is implemented

**Comment by elanhickler** [comment]
I'm not paying for you creating the macro parameter feature, right? I think I can use what you made, but it seems like you are not doing what I wanted.

**Comment by elanhickler** [comment]
...or maybe you are, can't tell until i try to use it seriously

**Comment by RobinSchmidt** [comment]
> I'm not paying for you creating the macro parameter feature, right? 

right. i said, i would do this free of charge

**Comment by RobinSchmidt** [comment]
if does not do exactly what you want, i guess maybe it can be modified (subclassed) a bit for your purposes

**Comment by RobinSchmidt** [comment]
okay..it seems to basically work - now time for tests and detail work

**Comment by elanhickler** [comment]
yay

**Comment by RobinSchmidt** [comment]
you can assign two (or more) parameters to the same meta parameter to couple them - as before - and now for each parameter, you can open "Automation setup" to define the mapping curve. actually, this even worked before - but now the sliders below the plot also work and the values in the curve are given as normalized between 0..1. the parameter sliders will still move locked in sync but the actual values are determined by their individual curves (you see this in the numerical readout of the sliders). the widgets above the plot do not yet work. i think, the next step should probably be options for the transition curves for each node

**Comment by elanhickler** [comment]
This isn't working. Currently the assumption is that when you attach a parameter you want the full range of that parameter.

Sometimes when increasing one parameter fully on and off, I need another parameter to move very very slightly more or less. With the current setup it's impractical to create this behavior.

The way i want to work is this:

Adjust the "master" parameter (frequency in this case). Oh, it doesn't soudn good at this frequency. Ok, let's increase the problematic parameter value. Ok sounds good again. MARK. Increase the frequency. Ok it sounds bad again. Increase the problematic parameter value again. MARK. Now I am starting to paint a picture of how the parameters need to adjust as frequency increases.

![image](https://user-images.githubusercontent.com/9116575/42736122-24ebb88c-8815-11e8-9f82-74e81f4befca.png)

We have two data points inbetween min and max.

![image](https://user-images.githubusercontent.com/9116575/42736132-7c6971d0-8815-11e8-8bc9-bf4adff5baf3.png)

Now I know the final slope:

![image](https://user-images.githubusercontent.com/9116575/42736138-ad2f3a98-8815-11e8-92f1-df5dc8999e0e.png)

**Comment by elanhickler** [comment]
ISSUES:
 * When moving an automation data point, the parameter does not update. This means I can't hear the results as i adjust a data point
 * When the final point is selected, the X/Y controls do not appear, thereby making it impractical for fine tuning that point.
![image](https://puu.sh/AWQp9/8d70fffa54.gif)

**Comment by elanhickler** [comment]
IDEAS:
 * Add a cursor to represent where we are along the range.
![image](https://user-images.githubusercontent.com/9116575/42736211-10c78bb8-8817-11e8-9341-315b38c4675c.png)

**Comment by elanhickler** [comment]
If you solve the ISSUES and add my IDEA feature, I thiiiiink I might be able to get by for the first version of FMD, I think I'll be good for a while.

**Comment by RobinSchmidt** [comment]
ok, i added the vertical line and the node-changes now become immediately audible. i can't reproduce the bug with the non-appearing xy/sliders here - need more precise instructions (can you try this in toolchain, maybe with the ladder filter? ). i tried to keep the editor window on top via setAlwaysOnTop - but for some reason that doesn't work (maybe the plugin window itself is also always on top?)...hmm...maybe i should just add "a slider to move the cursor". the editor window does not actually disappear - technically, it just goes into the background (but the effect is the same, unless your slider happens to be at the bottom of the window in which case it only gets partially obscured)

> When you assign two parameters, the second parameter loses its original value. I thought that was the main issue you were solving.

most changes are in jura_NodeEditor.h/cpp and jura_AutomatableWidget.h/cpp. this is the last point in your issue list, right? ...to be solved by using a flat line as initial mapping function?

**Comment by elanhickler** [comment]
I'm not sure what the most common use case will be, but for me I would prefer to start off with a flat line (slider has no effect). That would be confusing for new users though.

Usually i will assign Frequency control, and then assign another parameter along with Frequency control, but this control usually will only move very slightly within value in the 0 to 1 normalized range. But yes, it's really important not to lose the initial value, as it is difficult to find that perfect value again, especially because you are displaying 0 ... 1... oh I guess I could try to re-find the value by adjusting the curve until the slider reads the desired value... buut uuhhh... yeah pretty inconvenient.

**Comment by RobinSchmidt** [comment]
the menu now doesn't go into the background anymore. setAlwaysOnTop works (i just stupidly called it from the wrong class)

>I could try to re-find the value by adjusting the curve until the slider reads the desired value... buut uuhhh... yeah pretty inconvenient.

so...should i add a convenience option like "Meta attach with flat map"? ...btw...it's understood that this "free of charge" applied only to my previous work on that, right? (which is actually the lions share anyway)

**Comment by elanhickler** [comment]
You've gotten me most of the way already. If you need to charge me for something, do it! Just get it done! FMD will be my legacy and I have waited too long!

**Comment by RobinSchmidt** [comment]
ok - so i fixed 2 of the 4 issues, one (non-appearing x/y sliders when selecting last point, i can't reproduce), do you want the flat-line next? ..and implemented 1 of the 3 ideas (vertical line). i think, the slider for the meta value would now - as the window stays on top - be redundant. you can just as well use the original slider now, right?  do you still want the non-crucial "add point at cursor" button?

**Comment by elanhickler** [comment]
yes i can use the original slider now.

let me see how I get by without the button... I dunno...

**Comment by elanhickler** [comment]
btw the goal of the flat line is so that the parameter keeps its original value when being connected to metaparameter

**Comment by RobinSchmidt** [comment]
ok - flat map added

**Comment by RobinSchmidt** [comment]
> The flat points need to be established based on the current value of the parameter, not based on the normalized value of the metaparameter.

ah - yes - of course. actually they are, but i'm taking over the value too late (after the parameter already had taken over the value form the meta). i tried to do a quick fix but stumbled over a bug. it may (or may not) have something to do with the non-appearing xy-sliders - i will try to fix it tomorrow

> I would like to achieve frequency-scaled resonance, or another layer of metaparameter attachment, or some other idea. I can't think of a solution at the moment.

you mean like: now that you have the resonance coupled to the cutoff, you still want to modify the resonance? ...yeahh...i was already thinking about that, too. i think, in its full generality, the problem can't really be solved by a bunch of 1D functions - it's intrinsically multidimensional. you have a bunch of N user parameters and another bunch of M algorithm parameters and each of the M algorithm parameters is some function of each of the N user parameters - so you end up with M functions, each having N inputs

**Comment by elanhickler** [comment]
One way I could achieve frequency-based resonance is to double my parameters/sliders. So, basically, just attach frequency to something else in Chaosfly that affects the resonance. I'll go with this idea for now.

Also, looking forward to exp/log curves in the automation map... not crucial though. I can manage without it.

**Comment by RobinSchmidt** [comment]
ok - try again. the flat line value should now be the one currently dialed in. ...multidimensional meta parameters...hmmm...i currently don't really know, how one would best approach such a thing. i could probably write some classes for you that do multidimensional interpolation of datapoints that you may record - maybe some kind of N-inputs-M-outputs function based on datapoints and interpolating in between. would perhaps be suitable for hardcoding such arbitrary user-parameter-to-algo-parameter mappings. ...making a reasonable gui for such a beast would be a whole other story, though

if the curve options are not crucial, i think, i will now look into the multicomp gui for jim and we may add them later. i was actually more thinking about smooth spline interpolation between datapoints - but exp/log should be possible, too

**Comment by elanhickler** [comment]
I usually will only need the start and end points, so exp/log/lin may be all I need, and the interpolation feature wouldn't be activated in that case.

**Comment by elanhickler** [comment]
OH I just got an idea for doing frequency-dependent resonance via the modulation system. All I need to do is have frequency attach to a dummy slider. That dummy slider controls a mod source amount. Mod source amount then adjusts whatever I want. I could have it control resonance amount to adding -3 to +3 modulation range to a parameter that controls resonance! Yes! This could work.

**Comment by elanhickler** [comment]
ISSUE
 * moving X/Y sliders in the automation map does not update parameter (changes are not heard)

**Comment by RobinSchmidt** [comment]
i have added curve shape options (exponential and rational) - this was more tricky than expected. will look into the issue tomorrow

**Comment by RobinSchmidt** [comment]
ok - try again. it should work now

**Comment by elanhickler** [comment]
I'm starting to see the big picture. I think you made the wrong choice by creating a metaparameter system. All this stuff going on with the metaparameter system should have been for the modulation system. I can explain more in the future. In the future I would be interested in paying you to retrofit the modulation system. This would make the metaparameter system obsolete AND allow for multidimensional pairings of controls. But for now, let's continue getting the metaparameter system to work. I can make progress on FMD for now if you can keep solving issues.

ISSUE

* Need cursor in automation to be visible at all times.

![image](https://puu.sh/B4kH9/17620a0664.gif)

**Comment by RobinSchmidt** [comment]
ok - the cursor is now always visible. will look into the patch saving bug probably tomorrow (again, i don't see this issue in toolchain - but who knows - might be my bug anyway - our under-the-hood wiring system stuff has grown pretty complex ...)

**Comment by elanhickler** [comment]
move to discussion / ideas
