### ISSUE TITLE
error with ProcessorCycleCount.h

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#153]
```cpp
    INT64 ReadTSC()  // Returns time stamp counter
    {
#ifdef _MSC_VER
      int   dummy[4];      // For unused returns
      INT64 clock;         // Time 
      __cpuid(dummy, 0);   // Serialize
      clock = __rdtsc();   // Read time
      __cpuid(dummy, 0);   // Serialize again
      return clock;
#else
			return 0;
#endif
    }
```

**Comment by elanhickler** [comment]
just deleted the function, got it to build

(I'm working with another programmer, I don't get this error)

**Comment by RobinSchmidt** [comment]
hmm...ok - it's not really relevant anymore, at least not to have it in the rosic library. i still use it in the test-suite though, but there i actually have a copy of it

**Comment by elanhickler** [comment]
oh the error specifically i think is cpuid is not found or not identified

**Comment by RobinSchmidt** [comment]
can he try to add

#include <intrin.h>

to rosic .h (somewhere there where i include all the other standard headers) to see if this fixes it?

**Comment by RobinSchmidt** [comment]
which compiler/version is he using?

**Comment by elanhickler** [comment]
VS 2017

**Comment by RobinSchmidt** [comment]
hmm.. i still use 2015. ...maybe there are some differences in which headers get automatically included by default or something. but you use 2017 too, right? ..and don't get this error - that would be weird. dunno.

**Comment by elanhickler** [comment]
I am building successfully with VS2019. Issue resolved.
