### ISSUE TITLE
how do you set size of 

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#154]
When dragging, the user should not be able to set the size of the window to an incorrect ratio. How do you set the size of the window? audio plugin version, I don't care about the standalone, that may need custom standalone code that I don't want to deal with now. Getting it solved for the plugin version is good for now.

I tried setSize and setBounds in resized function, didn't help set the size of the window.

![image](https://user-images.githubusercontent.com/9116575/34586493-6d9fb434-f161-11e7-84b5-a0cfe4441265.png)

**Comment by RobinSchmidt** [comment]
my AudioPluginEditor class is a subclass of this:
https://juce.com/doc/classAudioProcessorEditor
and i'm calling the setResizable, setResizeLimits, etc. functions from there. hmmm...i guess to support a fixed aspect ratio, we could use this:
https://juce.com/doc/classAudioProcessorEditor#a3a620a4659312f2456692c44c4ec999b

**Comment by elanhickler** [comment]
how?

**Comment by RobinSchmidt** [comment]
yeaahhh...i think, this is something, i'll have to do on the framework level - perhaps by letting my AudioPlugin class have a member of class:
https://juce.com/doc/classComponentBoundsConstrainer
and provide accessor functions which you could call from your createPluginFilter function or something

**Comment by RobinSchmidt** [comment]
done. now, the setEditorSizeLimits function has been replaced by setEditorBoundsConstrainer. you will need to create a new constrainer (in your createPluginFilter() function), set it up (setMinimumWidth, setFixedaspecRatio, etc.) and then pass it to the plugin object (plugIn->setEditorBoundsContsrainer(constrainer). that's the idea, at least. i didn't test it yet. create the constrainer with "new" and forget about it. the plugin object will delete it in its destructor

**Comment by elanhickler** [comment]
currently testing in FMD project, it doesn't work.

![image](https://user-images.githubusercontent.com/9116575/34643180-10e22812-f2dd-11e7-9e11-a22d047b861e.png)

Soundemote\AudioPlugins\FMD\FMD.jucer

**Comment by RobinSchmidt** [comment]
hmm...this is really weird - here they say something about the constrainer being bypassed in some situations:

https://juce.com/doc/classAudioProcessorEditor#a3d36f7385146270fc752ce17418f115a

...but then i really don't understand what this constrainer is supposed to do at all. maybe that's a question for the juce forum then. i don't understand their intentions in this case

**Comment by RobinSchmidt** [comment]
btw. in:
constrainer->setFixedAspectRatio(1000/695);
the quotient evaluates to 1 because it's an integer division. you need 1000.0/695.0 or something. ...but that's irrelevant, when it doesn't work at all

**Comment by RobinSchmidt** [comment]
in the destructor, i'm hitting this:
```cpp
XmlElement::XmlAttributeNode::XmlAttributeNode (const Identifier& n, const String& v) noexcept
    : name (n), value (v)
{
    jassert (isValidXmlName (name));
}
```
name is: "_1st knob", so i guess an underscore is not allowed as first letter

**Comment by elanhickler** [comment]
you can continue past that, also that should have been fixed. maybe re-pull soundemote

**Comment by RobinSchmidt** [comment]
ok - no problem for me. i just wanted to mention it

**Comment by elanhickler** [comment]
How can we disable resizing of plugin?

**Comment by RobinSchmidt** [comment]
hmm...there is the function: `jura::AudioPlugin::setEditorBoundsConstrainer` which was apparently made for this purpose - but i do not yet use that anywhere, so did not yet try, whether it really works as expected. maybe just try it if it works, fine, if not, i may have to add some code to the framework

**Comment by elanhickler** [comment]
it doesn't work

**Comment by elanhickler** [comment]
I need to be able to set the size of the editor to do show/hide sections of the plugin.

**Comment by RobinSchmidt** [comment]
ok - i got rid of that ComponentBoundsConstrainer stuff and reverted my code to the older version - which is less powerful, but at least it works. you can now call setEditorSizeLimits on the plugin object in your createPlugIn...function. if min and max re the same for with and height, the editor will be non-resizable

**Comment by elanhickler** [comment]
What about setting size during run time?

**Comment by RobinSchmidt** [comment]
it should be possible to just call setSize in your editor - and this should work regardless of any size limits (these apply only to the resizer widget). check out what happens in ToolChain when you replace a module

**Comment by elanhickler** [comment]
set size doesn't do what is expected, we shouldn't have "unused window size" when setting size of parent editor.

![image](https://user-images.githubusercontent.com/9116575/47307974-377d8480-d5e5-11e8-97df-ecba6eae7fe1.png)


![image](https://user-images.githubusercontent.com/9116575/47307955-27fe3b80-d5e5-11e8-88c8-7c908572cde9.png)

**Comment by elanhickler** [comment]
another issue, if the size of the windows was changed by the user, setting the editor unresizable like you mentioned does not mean we will have the desired window size. This is not an issue if the plugin was never resizable, but.............. still...........

![image](https://user-images.githubusercontent.com/9116575/47308495-a1e2f480-d5e6-11e8-938c-1b2c5d37a2ff.png)

**Comment by elanhickler** [comment]
![image](https://user-images.githubusercontent.com/9116575/47484544-cdd1c600-d7f0-11e8-8601-df83189dbe70.png)

I didn't know there was a repaint over children function! dam.

**Comment by RobinSchmidt** [comment]
yes - these are the sorts of things, one only learns over a long time using an api (this is juce stuff, not mine). are your resizing problems solved, too?

**Comment by elanhickler** [comment]
No. No idea how to access your parent editor code.

**Comment by RobinSchmidt** [comment]
to get a pointer to the parent editor, you could use this:
https://docs.juce.com/master/classComponent.html#ac4d430194f6637607b1af8631d7166e7
and then cast the returned pointer to AudioModuleEditor

**Comment by RobinSchmidt** [comment]
maybe you should have a look at this:
```cpp
void ToolChainEditor::resized()
{
  // ...blah blah blah...

  Component *parent =	getParentComponent();
  if(dynamic_cast<AudioPluginEditor*>(parent))
    parent->setSize(getWidth(), getHeight());
}
```

**Comment by elanhickler** [comment]
I'm slowly depending less and less on your library code. You've made it quite difficult though, by having things depend on each other a little too much. I would be interested in building a GUI library that easily connects with your library, the modulation stuff, the modulation animation, the stuff that takes a while to develop. And of course your DSP library is easy to throw in any library, that's not the concern.

Robin, you have no idea. Creating an interface with custom graphics requires a TOTALLY different and more complex way of programming. I need to develop a robust system to make this easy. If I do that, I could offer it as a GUI library that works with some of your stuff. And at the same time, you should edit your code where needed to make the connection easier and cleaner.

**Comment by RobinSchmidt** [comment]
what's wrong with setPainter()?

**Comment by elanhickler** [comment]
Like I said, you have no idea! Here's one example: You need custom hitboxes too, because half the time the clickable area != the drawing area.
