### ISSUE TITLE
cannot remove modulation connection without crash

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#157]
![image](https://user-images.githubusercontent.com/9116575/34644625-375874d2-f2f7-11e7-8bc2-cd80e0294b31.png)

tested on PrettyScope and Mushroom Generator

**Comment by RobinSchmidt** [comment]
i just fixed a bug where i was hitting this when closing the mod-menu after removing a mod-connection (the mod-depth parameter had a dangling pointer to the depth-slider). was that this one?

**Comment by elanhickler** [comment]
solved
