### ISSUE TITLE
Need Modwheel CC and Pitch wheel

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#16]
I found jura_AudioModule.h has

`virtual void setMidiController(int controllerNumber, float controllerValue);`
`virtual void setPitchBend(int pitchBendValue);`

I don't see a get. How do I get pitch bend and midi cc 1?

**Comment by RobinSchmidt** [comment]
what you have to do is to override these these methods in your particular subclass of AudioModule. they will then get called by some code in lower levels of the framework. you don't call getPitchBend to retrieve the pitch-bend but it goes the other way around - the pitch-wheel calls you (i.e. your overriden setPitchBend method). there, you take appropriate action to handle the pitch-wheel change.

**Comment by RobinSchmidt** [comment]
for mod-wheel...i think, that just sends a midi controller (whatever controller is assigned to the wheel), right? so it would be a matter of overriding setMidiController

**Comment by RobinSchmidt** [comment]
hollywood-principle = "don't call us - we will call you"
https://en.wikipedia.org/wiki/Inversion_of_control

**Comment by RobinSchmidt** [comment]
hmm...thinking about it - maybe i should rename these functions into pitchWheelChanged, etc. or something to make it more obvious that these are callbacks supposed to be overriden

**Comment by elanhickler** [comment]
yes do that.
