### ISSUE TITLE
TestPluginJUCE linker errors

### ISSUE THREAD

**Issue by martinfinke** [RobinSchmidt/RS-MET#161]
I get linker errors when trying to compile the TestPluginJUCE on Mac:

<img width="371" alt="bildschirmfoto 2018-01-09 um 10 20 46" src="https://user-images.githubusercontent.com/2064018/34713543-e5da047c-f526-11e7-9038-93e6b8bf0eb0.png">

Do I have to modify anything, or maybe add a template instantiation somewhere?

**Comment by RobinSchmidt** [comment]
ok, yes - the explicit instantiation was missing. i just added it. i wonder how that could ever work...

**Comment by RobinSchmidt** [comment]
i guess, i can close this then

**Comment by martinfinke** [comment]
Yes, thanks! 🙂
