### ISSUE TITLE
Need scroller section to change size based on page

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#165]
How should I change the size of the scroller based on page?

I set the scroller size in the PrettyScopeEditor resized()

![image](https://user-images.githubusercontent.com/9116575/34803508-ee894154-f630-11e7-9607-74c03dcb6060.png)

Ideally I'd set the size in the rButtonClicked for that widget section, but the widget section cannot notify the higher up PretyScopeEditor to resize... or something

![image](https://user-images.githubusercontent.com/9116575/34803571-35bf7c3c-f631-11e7-9c9d-72dddbc92241.png)

**Comment by elanhickler** [comment]
not the best solution, but I got a resized for prettyscope editor like this......

![image](https://user-images.githubusercontent.com/9116575/34803822-a3dba2c6-f632-11e7-8e14-fc4ac222d88d.png)

**Comment by RobinSchmidt** [comment]
i think, you need `ComponentScrollContainer::setScrolleeSize`

**Comment by elanhickler** [comment]
solved
