### ISSUE TITLE
crash when removing two sources

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#169]
Happens pretty consistently, any two modulation sources removed causes a crash. Tested with PrettyScope. Use any modulation target. If you don't get a crash at first, try the steps a few more times. Add two, remove two.

![](https://puu.sh/yZmfn/c1a9714f57.gif)

**Comment by RobinSchmidt** [comment]
is this new? i'm currently changing *a lot* of things in the parameter handling infrastructure to accomodate for the new mapping stuff. it's perhaps best to stick to an older version of the library.

...i guess, i should learn about git branches and not do such things on the master branch in the future

**Comment by elanhickler** [comment]
It probably came about with the crash of removing one modulator.

**Comment by elanhickler** [comment]
no longer relevant
