### ISSUE TITLE
how do you use ParameterObserver to repaint on widget change?

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#170]
Is ParameterObserver used on the Editor or Module?

Is there an example of usage I can look at how do register and de-register?

**Comment by elanhickler** [comment]
I need to make the breakpoint module update its display when I change "cursor position" for my macro parameter setup.

So, what needs to inherit ParameterObserver? Editor or Module?

**Comment by elanhickler** [comment]
do you call registerParameterObserver(this) on the widget(Editor) or the parameter(Module)?

**Comment by elanhickler** [comment]
oh but it has to be widget, because you're using "this"

well... does AutomatableSlider have a registerParameterObserver function? can't find it.

**Comment by RobinSchmidt** [comment]
no, the registerParameterObserver is a member function of Parameter. and you have have to pass to it a pointer to an object that is a subclass of ParameterObserver (as the widgets are, for example)

**Comment by RobinSchmidt** [comment]
huh? what is cursorPosition? seems to be a juce::Component, not a jura::Parameter

**Comment by RobinSchmidt** [comment]
wait...you want to use my BreakpointModulator for macro parameters? or are you working with the new rsNodeBasedFunction stuff?

**Comment by RobinSchmidt** [comment]
bcs the former won't work

**Comment by elanhickler** [comment]
I am not working with the rsNodeBasedFunction, first problem is that it's lacking curves... or maybe you just didn't add it to the interface.

**Comment by elanhickler** [comment]
I would like to create my own breakpoint modulator from scratch maybe using rsNodeBasedFunction, hopefully I can customize the look, or provide my own paint code somehow.

**Comment by RobinSchmidt** [comment]
no, it's right - it's still lacking curve options. however, it's the only breakpoint function that allows random access. the breakpoint-modulator creates its curves essentially by using filters, so the implementation is inherently time-based - you set it into some state and then retrieve one *time-sample* after another. it's actually a signal generator, not a random-access function

**Comment by elanhickler** [comment]
jim turned it into random access by simply running through the function and creating an array of 1024 values. then use simple linear interpolation

**Comment by RobinSchmidt** [comment]
are you in my ModulatorCurveEditor class? then, if i remember correctly, updatePlotCurveData - if your parameter changes causes the curve to change (like moving a breakpoint)

**Comment by elanhickler** [comment]
im in BreakpointModulatorGlobalEditor

**Comment by RobinSchmidt** [comment]
oh - that's a member of BreakpointModulatorEditor. then maybe walk up to the parent and call something like updatePlotAndGridWidgets or updateWidgetsAccordingToState, but i can't say for sure from the top of my head. i assume, you are re-implementing it? then maybe you need to provide your own update function - i guess, you somehow need to trigger jim's code that recomputes the curve for random access (again, assuming the curve actually changes in response to your parameter change)

**Comment by elanhickler** [comment]
9?

**Comment by RobinSchmidt** [comment]
the shift key just slipped ;-)

**Comment by RobinSchmidt** [comment]
btw. i think you can avoid that "walking up to the parent" step by just making BreakpointModulatorEditor itself your observer of the parameter in question

**Comment by elanhickler** [comment]
I need the curve plot editor

![image](https://user-images.githubusercontent.com/9116575/34888972-8f5754a0-f789-11e7-9700-850786aa63c5.png)

**Comment by RobinSchmidt** [comment]
it's the breakpointEditor member

**Comment by elanhickler** [comment]
it's giving me error invalid target for dynamic cast

![image](https://user-images.githubusercontent.com/9116575/34890460-3c4a3272-f78f-11e7-85dd-cbf6a763b87d.png)

**Comment by elanhickler** [comment]
ok i am not using the global editor, using just the editor now. got it working.. omg........

![](https://puu.sh/z00vX/35ddb4356c.gif)

**Comment by elanhickler** [comment]
I get a crash....................................... wtf???? It wasn't happening just a minute ago as proven by the gif.

![image](https://user-images.githubusercontent.com/9116575/34895197-d29b2d5a-f7a1-11e7-9c1e-d9e8380fbef2.png)

![image](https://user-images.githubusercontent.com/9116575/34895203-d8577064-f7a1-11e7-9dba-1940e82d265b.png)

**Comment by RobinSchmidt** [comment]
looks like a repaint was triggered from a thread other than the message thread. somewhere, something calls repaint in a function that is being called from - probably - the audio-thread. perhaps due to parameter automation or response to midi? i think, any call to repaint there should be replaced by repaintOnMessageThread. can you try to narrow it down to the offensive "repaint" call and replace that by repaintOnMessageThread? then tell me where, an i'll do the replacement in my library

**Comment by elanhickler** [comment]
I hardly know what you are saying.

What repaints are there? What calls repaints? Etc. I need some hints here.

**Comment by elanhickler** [comment]
And what do I replace with repaintOnMesageThread? I can do a straight 1 to 1 replacement anywhere I see "repaint()" ? So I have to replace the repaint overrides with repaintOnMessageThread overrides?

**Comment by RobinSchmidt** [comment]
i think, this updatePlotAndGridWidgets call will somewhere call repaint - maybe somewhere further down the library. i guess, can do it myself but not right now because i'm just preparing to leave. yes repaintOnMessageThread is a 1-to-1 replacement for repaint that can be called from other threads as well. ...i actually think, it would be the responsibility of juce itself to care about such things...however, apparently , it doesn't - perhaps for performance reasons or i don't know.

no - you don't replace overrides. you replace the function call

**Comment by RobinSchmidt** [comment]
so a call to repaint() gets replaced by a call to repaintOnMessageThread()

i'm not sure - maybe i should replace it every fucking where, but i have no idea if that will have a performance penalty in cases where it's not necessary

**Comment by RobinSchmidt** [comment]
it's sort of my personal workaround for a juce quirk. maybe i should raise that topic in the juce forum. or maybe someone else already has?

**Comment by elanhickler** [comment]
repaint is an override, right? so what do you mean you don't replace the override? you replace the function call?

**Comment by RobinSchmidt** [comment]
are you confusing it with paint()? *paint* is a function that you typically *override*, *repaint* is a function that you *call* whenever you deem a repaint necessary

**Comment by RobinSchmidt** [comment]
the call to repaint, will eventually invoke your overriden paint

**Comment by elanhickler** [comment]
ok i am confusing the two then.

**Comment by RobinSchmidt** [comment]
repaint is not even virtual, so you can't override it (at least not when you use pointers):
https://juce.com/doc/classComponent#af3ab3eabec93dd60faf983370f3a1206

**Comment by elanhickler** [comment]
ok i think i fixed it. I replaced a repaint with repaintOnMessageThread by seeing what repaint leads to the crash with the call stack.

**Comment by RobinSchmidt** [comment]
ok - great - maybe noodle around with it some more and if everything works fine, tell me where i have to do the replacement in my library - or just do a pull request with the change

**Comment by elanhickler** [comment]
pull request is sometimes not worth the effort, not for one line of code anyway

**Comment by elanhickler** [comment]
line 1335 of jura_CoordinateSystemOld.cpp

**Comment by RobinSchmidt** [comment]
ok, done. omg - i hate that class. my whole coordinate system drawing and function plotting system is a mess. don't look to closely at it

**Comment by elanhickler** [comment]
close for now.
