### ISSUE TITLE
Many sliders now have issues and are unusable

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#171]
Seems like bipolar sliders don't show their range, ranger they show a -1 to +1 range... or in general the range is messed up. Patches don't work, basically Chaosfly is unusable. Can't make progress now with FMD.

Also, many sliders even, non-bipolar sliders cause this:

![image](https://user-images.githubusercontent.com/9116575/34899054-d3ecbbd0-f7b3-11e7-9c3e-c20efff0f4b1.png)

You should make a branch when you are working on your library, I can't go back to an older commit now because all the code for my macro parameter is on the later commits of your library. I was going to do a PrettyScope update but now there's a bunch of new bugs with sliders that make it unusable. My business is not doing well at the moment. 

If you don't know how to use branches correctly you could lose your work, so make sure it's working before you do a bunch of work with other branches.

**Comment by RobinSchmidt** [comment]
yes, i should have used a branch. i need to read up on that how to do that with git. i could lose my work, if i make a mistake? woah - that really sucks! making this new mapping feature play nicely with all our existing features turned out to be a bit.....complicated. i'm currently doing a sort of open heart surgery on the library. not a good idea to do that while the patient is running

**Comment by elanhickler** [comment]
It's easy to do with sourcetree once you get the hang of it.

**Comment by elanhickler** [comment]
also could you add the "repaint for modulation" while you're at it? Since you're having to redo some code now it seems. I'll add my own painting methods to show modulation. I think I'll do a pink like that moves across the slider.

**Comment by RobinSchmidt** [comment]
i think, i should implement some automated unit-tests for the whole parameter-handling infrastructure, maybe something based on juce::UnitTest. i think, i will create a new project in my "Tests" folder with test for my jura framework and put the whole infrastructure into all possible scenarios an check if actual behavior matches desired behavior

repaint-for-modulation? what do you mean? widget animation? i actually think, it's really not a good time now to throw in yet another complication when trying to get something else to work. first things first

**Comment by elanhickler** [comment]
yes widget animation

**Comment by elanhickler** [comment]
ok but... why haven't you allowed for preset change to call a repaint? Widgets that cause sliders to appear or hide (based on combo boxes) don't update when you change the preset. Seems like that's a glaring omission in your framework.

**Comment by elanhickler** [comment]
or can you tell me how to do it?

**Comment by RobinSchmidt** [comment]
the "state" of the AudioModule is part of the AudioModule class (it's a subclass of StateManager - this baseclass is also responsible for the star to appear next to the preset name when you change something....but that currently does not work right)...anyway - there is no automatic notification system for the gui in case of state-changes - because always keep in mind: the user may not even open the gui. no editor object even exists in this case. an in many of my old simpler plugins, the set of widgets is just static - and the widgets themselves *do* update in a state change (induced by preset load) by means of  the parameterChanged callbacks

**Comment by RobinSchmidt** [comment]
also: repaint won't cut it. you will need to call setVisible(true/false) on the widgets. repainting the editor will only repaint the background.  a simple way would be to make you AudioModule a subclass of juce::ChangeBroadcaster, your editor a subclass of juce::ChangeListener, register your editor as listener at the audimodule and override setStateFromXml to call sendChangeMessage at the end. pick up the message in the editor and call some kind of "updateWidgetVisibility" function where you call all the relevant setVisible calls with true/false values that depend on the state of the AudioModule

**Comment by RobinSchmidt** [comment]
...wait...AudioModuleEditor already *is* a ChangeListener, and the changeListenerCallback implementation is:
```cpp
void AudioModuleEditor::changeListenerCallback(juce::ChangeBroadcaster *objectThatHasChanged)
{
  if( objectThatHasChanged == stateWidgetSet )
    updateWidgetsAccordingToState();
}
```
..soooo, it seems you only need to override updateWidgetsAccordingToState in your editor. (it's a while ago that i visited that code)

**Comment by RobinSchmidt** [comment]
the stateWidgetSet (this is the preset section) already sends out a message that the editor picks up

**Comment by RobinSchmidt** [comment]
so - there *is* an automatic notification system for the gui but only in the case, when you change the state from the gui (the host can also change the state without any gui existing - this is what happens in total recall, which happens typically straight after construction of the plugin - but there's nothing that prescribes that). it's not the AudioModule that sends out the state-change notification but the stateWidgetSet (when you load a new preset)

**Comment by elanhickler** [comment]
changeListenerCallback breakpoint is not getting hit when changing preset

![image](https://user-images.githubusercontent.com/9116575/34967286-c60a4f38-fa1e-11e7-8824-60cf949ae65c.png)

**Comment by elanhickler** [comment]
oh wait i think there's a few more steps you mentioned earlier.

**Comment by RobinSchmidt** [comment]
are you perhaps overriding it in you editor subclass? in this case, you overriden function will be called instead and you may have to add another branch to your handling code

**Comment by elanhickler** [comment]
the base class Editor is a subclass of ChangeListener
![image](https://user-images.githubusercontent.com/9116575/34967634-88170d4e-fa21-11e7-9c6a-537cc6dc3957.png)

the base class Module is a subclass of ChangeBroadcaster
![image](https://user-images.githubusercontent.com/9116575/34967645-939e8552-fa21-11e7-81a2-c71c2e138d4b.png)

the super class editor registers itself as a listener to the module
![image](https://user-images.githubusercontent.com/9116575/34967660-aa2127bc-fa21-11e7-9253-583c057108d0.png)

the super class module overrides setStateFromXml
![image](https://user-images.githubusercontent.com/9116575/34967853-d1120a52-fa22-11e7-84f2-2fd2e46c7507.png)


super class editor updates widgets according to state
![image](https://user-images.githubusercontent.com/9116575/34967740-2bcc582c-fa22-11e7-81ea-381eefa7be4c.png)

but now I just get a crash when loading a preset
![image](https://user-images.githubusercontent.com/9116575/34967868-eb51ab52-fa22-11e7-864c-1ac381dd28c3.png)

The class stack is all juce code.........

**Comment by RobinSchmidt** [comment]
> the super class editor registers itself as a listener to the super class module

do you also de-register in the destructor? if not, you'll have a dangling pointer in the broadcaster

**Comment by elanhickler** [comment]
like this? still crashes.

![image](https://user-images.githubusercontent.com/9116575/34968674-dddbdc2c-fa27-11e7-9ddb-b3a9a35a83ce.png)

**Comment by RobinSchmidt** [comment]
yes, this is what i meant. if it still crashes, then i don't know. does the crash go away when you comment out the sendChangeMessage? if so, it really smells like a dangling pointer to a deleted listener in the broadcaster. i may have to try it myself after fixing the parameter stuff

**Comment by elanhickler** [comment]
got it working after you asked if the sendChangeMessage was causing the crash. It wasn't. haha.

**Comment by RobinSchmidt** [comment]
ok, i'm having now a bunch of systematic unit tests in place for Parameter and its subclasses. with these, i discovered and fixed a few bugs and now the parameters pass all my current tests and it seems to also work as expected in my DebugAudioModule in ToolChain. so, parameters might finally work again. my tests do not yet cover everything, though - but i now have the structure in place to easily extend the test suite

**Comment by elanhickler** [comment]
i think we can close this

**Comment by RobinSchmidt** [comment]
so, can you confirm that the new issues with parameters are fixed now? as said - my testsuite is far from being complete yet

**Comment by elanhickler** [comment]
wait, typing in a number doesn't work.

**Comment by elanhickler** [comment]
after you press enter, nothing happens

**Comment by RobinSchmidt** [comment]
oh! right! i see. it's because due to the new arbitrary (possibly nonmonotonic) mapping function between normalized and actual value, i can't straightforwardly map back anymore from value to slider-position. i may actually have to employ some kind of root-finding algorithm to find the desired slider position that corresponds to the desired value (or one of them, if several are possible). damn! this mapping stuff really complicates things

**Comment by elanhickler** [comment]
.......wellllllllllll my original idea for mapping was pretty un-complicated, you've done it to yourself!

**Comment by RobinSchmidt** [comment]
what was it? it was using the mod-system somehow, right?

**Comment by elanhickler** [comment]
yes, mod system and macro parameter system

dummy slider assigned using meta parameter -> breakpoint modulator current position A, B, C, D, etc. assigned to same meta parameter -> breakpoint modulation out to various destination sliders

**Comment by RobinSchmidt** [comment]
wait - your dummy slider would determine the position inside the breakpoint curve, then the breakpoint curve would produce and output value (the value of the curve at that x- or "time" value)...and then you want to send that value as (constant) modulation signal to various parameters?

**Comment by elanhickler** [comment]
![image](https://user-images.githubusercontent.com/9116575/35060633-4890ce88-fb7c-11e7-8336-2288c09bf68e.png)

**Comment by RobinSchmidt** [comment]
woaahh...ok...i see... yes, using the mod-system sidesteps the "mapping-back" problem because the slider position just determines the *unmodulated* value - and the modulation signal just adds something to it. however, your slider numeric readout value will then be wrong because it doesn't take into account the "modulation", i.e. offset, in this case.

**Comment by RobinSchmidt** [comment]
if you would want to include the offset in the readout, you are back to square one - having to solve the same back-mapping problem that i have now

**Comment by RobinSchmidt** [comment]
hmm...maybe..ok, so what you do is to send a constant (slider-adjustable) value through an arbitrary function and modulate the final value by that function's output value. yeaah..ok...makes sense

**Comment by RobinSchmidt** [comment]
entering a value now works again - but correctly only when you don't have a map defined (i.e. use the identity map). next step is to make it work with an arbitrary map

**Comment by RobinSchmidt** [comment]
yes - it's not too complicated actually and it may be more generally useful in my library (in class rsNodeBasedFunction). the idea is that you have an arbitrary function that you can quite easily evaluate in one direction, like y = f(x) - but finding x given y is not as easy - because the function may be nonmonotonic, piecewise defined, etc.

**Comment by RobinSchmidt** [comment]
a classic example: y = x^2. easy to evaluate - but the other way around...well x = sqrt(y). if you have a sqrt function in your standard library - great - but if you have none, you'd have to implement it yourself. this is where root-finding comes into play. one standard algorithm for the square root is the babylonian algorithm, which is basically newton-iteration applied to the square-root function

**Comment by elanhickler** [comment]
what if a given value appears more than once, like a curve that goes up and down?

**Comment by elanhickler** [comment]
New problem: Setting smoothing time causes parameters to jump to the target value rather than simply changing smoothing time.

**Comment by RobinSchmidt** [comment]
> what if a given value appears more than once, like a curve that goes up and down

depends on the application - my plan in this case is to choose the leftmost x-value at which the given y-value occurs

> Setting smoothing time causes parameters to jump to the target value rather than simply changing smoothing time

ok, i'll look into this

**Comment by RobinSchmidt** [comment]
i don't see this behavior in ToolChain, in the Debug module - but there, i'm just calling setSmoothingTime on the smoothable parameter, which takes effect only in the next smoothing process (i don't bother there to update the currently running smoothers). what are you calling to set up the smoothing time? is any of that calling `rsSmoothingManager::flushTargetValues();` ?

**Comment by elanhickler** [comment]
Another problem: changing mod depth for modulation amount like this:

![image](https://user-images.githubusercontent.com/9116575/35115453-76ae5a0a-fc45-11e7-8d1a-8ce94837695e.png)

does not update the widget until you move the mod amount slider.

**Comment by RobinSchmidt** [comment]
how do you change the mod-depth, if not via the slider? via a meta?

**Comment by elanhickler** [comment]
here's the problem:

![](https://puu.sh/z4sxt/e7f6e7c8a6.gif)

**Comment by elanhickler** [comment]
can you also solve this bug, may be an old bug:

![](https://puu.sh/z4FV8/98c6d53625.gif)

**Comment by RobinSchmidt** [comment]
oh - damn! yes! good find!

**Comment by RobinSchmidt** [comment]
slider update on range-change and limiting the bandwidth is done
