### ISSUE TITLE
how the F is the state widget still showing up?

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#173]
![image](https://user-images.githubusercontent.com/9116575/35006114-f31a4840-fab2-11e7-996a-2563bb37e114.png)
![image](https://user-images.githubusercontent.com/9116575/35006115-f6bd910a-fab2-11e7-96a2-1a55c07331e8.png)

the only thing that seems to work is settinb state widget bounds to 0 0 0 0

howwWWWW!!!!!!!!!!! 😡 💢

**Comment by elanhickler** [comment]
I'm not calling resized from AudioModuleEditor, i've overridden it.

**Comment by elanhickler** [comment]
wow this doesn't even work
![image](https://user-images.githubusercontent.com/9116575/35006418-d767d3f0-fab3-11e7-96f1-7706e3d3af79.png)

**Comment by elanhickler** [comment]
must be something with EqualizerModuleEditor.

**Comment by elanhickler** [comment]
oh I think I found it:

![image](https://user-images.githubusercontent.com/9116575/35006664-62ba494c-fab4-11e7-9d4c-c6a4de3b4b3f.png)


whyyy robin............

**Comment by elanhickler** [comment]
oh but I can't because everything's private. Ok, this will work, then: 
![image](https://user-images.githubusercontent.com/9116575/35006995-66090fe2-fab5-11e7-9ca4-dfd4b8e3e260.png)

close.

**Comment by elanhickler** [comment]
ok now this is annoying...

if you right click on a band point, it crashes.

![image](https://user-images.githubusercontent.com/9116575/35007439-fd2a907a-fab6-11e7-9f4a-a8575a2e8ec1.png)

I see removeBand in the call stack

![image](https://user-images.githubusercontent.com/9116575/35007455-0a45e62e-fab7-11e7-9d7c-62083a9fe35e.png)

**Comment by elanhickler** [comment]
ok it doesn't crash for M-Ref Dev so I must have done something wrong.

**Comment by elanhickler** [comment]
OH, but that could be because I'm on your latest commit.........................ill try going back.

**Comment by RobinSchmidt** [comment]
> ok, ill override that. oh but I can't because everything's private

what is private? i don't see anything private there (in fact, i very rarely use private variables at all). it's only protected, so it's overridable

**Comment by elanhickler** [comment]
i meant protected.

**Comment by RobinSchmidt** [comment]
but protected functions *can* be called and overriden by subclasses, if i'm not totally mistaken

**Comment by elanhickler** [comment]
but the protected members cannot be interacted with.

**Comment by elanhickler** [comment]
but that doesn't matter at this point.

**Comment by RobinSchmidt** [comment]
protected member variables can not be accessed from outside code - also protected member functions cannot be called from outside code, like object->callProtectedFunction will not work. but they can be accessed and overriden by subclasses - as opposed to private members/methods which can't even be accessed by subclasses. so, when you make a subclass, you can override a protected member function. but anyway....
