### ISSUE TITLE
Can't get jura::PhaseScopeEditor / Display to work

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#174]
![image](https://user-images.githubusercontent.com/9116575/35033518-33c4f910-fb28-11e7-9444-5850ad5bdcd7.png)

What am I missing?

**Comment by elanhickler** [comment]
declare a phase scope editor in my main editor
![image](https://user-images.githubusercontent.com/9116575/35033576-6f1b6e40-fb28-11e7-9df1-6cb7ee284026.png)

instantiate it in my editor's createWidgets callback (during construction)
![image](https://user-images.githubusercontent.com/9116575/35033617-9166a2a8-fb28-11e7-9110-1e559acf94f2.png)

set bounds in resized callback
![image](https://user-images.githubusercontent.com/9116575/35033781-22b1a834-fb29-11e7-8724-b8bcdd309633.png)

**Comment by elanhickler** [comment]
here's the module side of things

![image](https://user-images.githubusercontent.com/9116575/35033840-5db9aac6-fb29-11e7-8cb9-c9ea71c660f8.png)

![image](https://user-images.githubusercontent.com/9116575/35033858-6bd2ffea-fb29-11e7-8e68-9fa2905d9ef0.png)

![image](https://user-images.githubusercontent.com/9116575/35033880-7e1e288c-fb29-11e7-9623-4ca2aff20a7c.png)

**Comment by elanhickler** [comment]
got it working

**Comment by RobinSchmidt** [comment]
semms like an implementation (override) for PhaseScope::processStereoFrame was missing. i just added it. was that the problem. although, i'm a bit confused why the display would be all-white. i'd expect all-black instead (unless you selected a white-to-black colormap)
