### ISSUE TITLE
EQ and Delay effects are "exploding", no idea how to debug

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#176]
Hey Robin, the EQ and Delay effects I added explode when in use. Using an EQ curve other than flat or a delay feedback other than 0 quickly has the effect going to infinite amplitude. Is there something I could have done wrong? Unfortunately I've made a handful of changes to my fork of RS-MET so you can't debug with your base RS-MET. If you learned to use branches you could temporarily use my branch.................................................... but maybe you can tell me how to debug or what I did wrong.

**Comment by RobinSchmidt** [comment]
did you make changes to the dsp code? especially in the coefficient computations? for debugging i would set a breakpoint in  rosic::Equalizer::getSample. the class has a std::vector "bands" of TwoPoleFilter units. i would open the bands vector and investigate the variables - filter coefficients and such and look for anything strange...maybe also something like a cutoff frequency above half the sample-rate. do the plots still plot correctly or are they messed up, too?

**Comment by elanhickler** [comment]
nooo no no no, this is your DSP code, I don't want to debug that!

All I'm doing is adding your effects to my plugin like a normal person would do.

Any code I'm changing is cosmetic, mostly widget colors and sometimes I need access to a setting on some protected member, but none of this has anything to do with EQ or Delay.

**Comment by elanhickler** [comment]
All I do is override paint and resized for my own Equalizer Editor.
![image](https://user-images.githubusercontent.com/9116575/35106880-b3c3ae36-fc2c-11e7-8698-35f3eb847f25.png)

classes in the Module
![image](https://user-images.githubusercontent.com/9116575/35106982-fa596192-fc2c-11e7-98a2-71e3396c3518.png)

instantion in Module
![image](https://user-images.githubusercontent.com/9116575/35107502-5a91c242-fc2e-11e7-9866-fdefb7a10709.png)

simple process block function for Module
![image](https://user-images.githubusercontent.com/9116575/35107463-3ada809c-fc2e-11e7-9121-734aeb36a8d7.png)

**Comment by elanhickler** [comment]
M-Ref dev which has an EQ still works, so I must have some kind of feedback loop.............. HOWW

**Comment by elanhickler** [comment]
specially the EQ is self-resonanting, but it's kinda ugly sounding, it's distorted, buzzy, not typical normal self-oscillation.

**Comment by RobinSchmidt** [comment]
ok, so what would i have to do to reproduce this over here?

**Comment by RobinSchmidt** [comment]
oh - wait - i'm getting a crash when removing a band, too...

**Comment by elanhickler** [comment]
I would have to make my library compatible with RS-MET again or you'd have to get on my fork temporarily.

**Comment by RobinSchmidt** [comment]
wait - i'll look into the crash i'm getting in toolchain first.. who knows, maybe it automagically fixes the other stuff too

**Comment by RobinSchmidt** [comment]
oh fuck! this was a big bug! i recently rename ParameterObserver::parameterIsGoingToBeDeleted to the shorter parameterWillBeDeleted - but apparently i did not replace all overrides. i actually did a text replacement in the whole solution but apparently something went wrong. so we had a lot of dangling pointers when parameters were deleted. i fixed that now. it fixes the crash when removing the selected band in the eq. ...maybe it fixes the blow-up, too?

**Comment by elanhickler** [comment]
no more crash deleting points, plugin still explodes

also, could you remove "reset" for delay or make it optional when changing time?

If you have smoothing on delay time, the plugin freezes as the smoother set the delay time over and over, causing a reset on the buffer over and over, freezing the software.

**Comment by elanhickler** [comment]
oops forgot to say which delay: Quadrifex Ping Pong delay

**Comment by RobinSchmidt** [comment]
ok, yes - i removed the reset. does not really seem to make sense anyway. as for the blow-up - yes, i guess i need to try that myself. so how shall we do this? do you want to make yourself compatible with my version or should temporarily i switch to your fork (if so, how would i do this?)

**Comment by elanhickler** [comment]
I'm ALWAYS always asLFIsndfkljsdf always available for you online if you want to hop on and I can direct you in doing this. It would be easy for me to kinda give you a tutorial on branches and the possible pitfalls.

👍

**Comment by RobinSchmidt** [comment]
is it that complicated? i actually prefer to read stuff, tbh. maybe i should work my way through one of the many git tutorials online. can you recommend one?

**Comment by elanhickler** [comment]
i prefer not to read so I can't recommend one.

But don't you use a git GUI like SourceTree? If so, maybe there's a tutorial on sourcetree. Or maybe you'd rather learn how git actually work, but I like to learn the opposite way. Using SourceTree GUI gives me a good idea of how it works.

**Comment by elanhickler** [comment]
main difference between our branches is some hack code I added to change button colors:
![image](https://user-images.githubusercontent.com/9116575/35120835-a63c59f0-fc56-11e7-9486-1df8d2b09c97.png)

**Comment by RobinSchmidt** [comment]
how about i just add that button-painter delegation as i did for sliders (did you actually try to use that already)?  then you don't need a "hack" anymore but can "officially" change the painting

**Comment by elanhickler** [comment]
that should work.

So I can add it only to specific buttons?

**Comment by RobinSchmidt** [comment]
yes - you would just call myButton->setPainter(myButtonPainter) - assuming you have a myButtonPainter object lying around somewhere. it will only affect those buttons to which you pass the painter, different buttons can use totally different painters, too, etc.

**Comment by elanhickler** [comment]
sounds good!

**Comment by RobinSchmidt** [comment]
ha! it was actually already there. but the naming conventions were slightly different from the corresponding slider stuff, so i just made that consistent. you need to subclass RButtonPainter, implement the paint method there, somewhere have an object of that subclass and pass it to the buttons that should use it via setPainter()

**Comment by RobinSchmidt** [comment]
let's hope, it works as expected...

**Comment by elanhickler** [comment]
RButtonPainter is quite a wimpy class

![image](https://user-images.githubusercontent.com/9116575/35129174-a38535f8-fc77-11e7-95d4-7f9c0f433d39.png)

Isn't this kind of thing the perfect use case for passing in a function like std::function?

**Comment by elanhickler** [comment]
ughh!!!!!!!!!!!
![image](https://user-images.githubusercontent.com/9116575/35129521-41fff4e2-fc79-11e7-9756-e6f90523a5c4.png)

**Comment by elanhickler** [comment]
alright, you're going to have to make some things unprotected....... ill do it and make a pull request.

**Comment by elanhickler** [comment]
actually no, you'll probably want to make a function for something like this.

**Comment by RobinSchmidt** [comment]
ah, ok - yeah - what do you need? getFont()?

**Comment by RobinSchmidt** [comment]
> oh wait, the point of a class is you could make the painter more complex with constructor options.

yeah - or something like: setButtonUpImage, setButtonDownImage, etc.

**Comment by RobinSchmidt** [comment]
and `drawBitmapFontText` is a global function, not a member function of RButton, so the `b->` must be deleted

**Comment by elanhickler** [comment]
i need function:

`AudioModule::getModuleNameAppendix() { return moduleNameAppendix; }`

and then we are compatible.

**Comment by RobinSchmidt** [comment]
done

**Comment by RobinSchmidt** [comment]
> Isn't this kind of thing the perfect use case for passing in a function like std::function

the perfect use case for this is actually my new rsRootFinder class, for example: 

```cpp
template<class T>
T rsRootFinder<T>::bisection(std::function<T(T)>& f, T xL, T xR, T y)
{
  static const int maxNumIterations = 60; // should be enough for double-precision
  T tol = std::numeric_limits<T>::epsilon();
  T fL  = f(xL) - y;
  T xM, fM;
  for(int i = 1; i <= maxNumIterations; i++) {
    xM = T(0.5)*(xL+xR);
    fM = f(xM) - y;
    if(fM == 0 || xR-xL <= fabs(xM*tol)) 
      return xM; // done
    if(fL*fM > 0) { xL = xM; fL = fM; }
    else          { xR = xM;          }
  }
  //rsError("rsRootFinder::bisection failed to converge");
  return xM;
}
```
i'm using it with a lambda-function in my unit-test suite. nice. i guess a function object (functor) will work just as well. ...and regular function pointers will work anyway, i think. i can assign all these things (lambda-functiosn, functors, function-pointers) to a std::function object with a matching signature, right?

**Comment by RobinSchmidt** [comment]
...yup - just tested it. works like clockwork. really nice. already have some idea how to use that for ultra-precise zero-crossing locations in audio-signals...

**Comment by RobinSchmidt** [comment]
namely - define a functor class that sinc-interpolates the audio signal and use the root-finder to find the zero-crossing of that sinc-interpolant. elegant!

**Comment by elanhickler** [comment]
does this mean you will make a better frequency locking tuner? we still need that for OTS

**Comment by RobinSchmidt** [comment]
*iff* the problem is the precision of the zero-crossing locations, then probably yes

**Comment by RobinSchmidt** [comment]
currently, i fit a polynomial interpolant and determine the zero crossing of that - which should not really be soo bad, i think. however, the sinc-interpolant is actually the proper interpolant, so it may improve things (of course, it will probably be costly in terms of cpu - but as it's a non-realtime algo anyway, that may be acceptable)

**Comment by RobinSchmidt** [comment]
btw. - there are some audio-dsp textbooks and papers that state things like that you can locate zero-crossings only to sample-accuracy. ha ha!

**Comment by elanhickler** [comment]
good. now you are superior than them!

**Comment by RobinSchmidt** [comment]
do recent samplers actually allow to set loop points with subsample accuracy? it's a long time ago i used a sampler but back then you could set loop points only to integer sample values

**Comment by elanhickler** [comment]
I don't think there's a point in subsample accurate loop points unless an algorithm is detecting a good loop point.

**Comment by RobinSchmidt** [comment]
think of looping a single cycle. or maybe two or 3 cycles. if the loop points are accurate only up to sample instants, the frequency will audibly diverge from where it should be

**Comment by elanhickler** [comment]
ok

**Comment by RobinSchmidt** [comment]
this comes to my mind because there was a time when i created sampler patches with a short sample from the beginning of the recording. think of an acoustic guitar - let it go through its transient and after a few tenths of a second, enter a loop of a single cycle. you would the need only a very short sample (say, half a second) to capture the transient and the steady state part would be created by looping a cycle. but here, you need to be subsample accurate. ...and a subsample-accurate zero-crossing finder could give you your loop points - but the sampler must then  support subsample loop points

**Comment by RobinSchmidt** [comment]
a bit similar to this "LA" synthesis by roland - just that we take the steady part also from the sample instead of synthesizing it by other means

**Comment by elanhickler** [comment]
don't be anti-crossfade

**Comment by RobinSchmidt** [comment]
i think, crossfade is nice for longer loops - but for very short loops containing just one or a few cycles - you should not need a crossfade to "cover up" a signal discontinuity

**Comment by elanhickler** [comment]
uhh, but there is a discontinuity no matter what, unless the waveform is perfectly synthesized. Might as well average the two cycles with a 100% crossfade to make it perfect.

**Comment by RobinSchmidt** [comment]
> there is a discontinuity no matter what

why - because the next cycle is slightly different from the current? ok, but i think this effect is very much (orders of magnitude maybe?) below the (worst case) artifacts that can be expected from having slightly wrong loop points

**Comment by RobinSchmidt** [comment]
i actually consider the idea of using samples for the transient and some kind of synthesis (under which i would subsume the single-cycle loop) as a very powerful concept for acoustic instrument synthesis. it was introduced back then by roland due to the memory limitations of samplers and romplers at that time:

https://en.wikipedia.org/wiki/Linear_Arithmetic_synthesis

but i think, the idea should not be discarded just because we have much more memory now

**Comment by elanhickler** [comment]
OrangeTreeSamples would love to make a synth-assisted sample library, but the sound would have to be nearly as good as samples and offer advantages. I'd need to hear an example.

**Comment by RobinSchmidt** [comment]
"Roland added a suite of sampled attack transients to subtractive synthesis. As well as the attack transients, Roland added a suite of single-cycle sampled waveforms that could be continuously looped"

instead of having the transient and sinngle-cycle samples separate, i would just just jump into a single cycle loop somewhere inside the instrument sample, when it has reached a steady state. otherwise, the technique would be very similar

**Comment by RobinSchmidt** [comment]
would one ore more of your sample-library producers be interested in algorithms to separate harmonic/inharmonic/noisy/transient content in one-shot instrument samples? i have some old matlab prototype code for that which was actually quite promising (for single note, more-or-less tonal content). maybe, if i port that to c++, you could create some reaper-functions from that with which you could quickly generate some money by using this for your sample-library-producer clients

**Comment by elanhickler** [comment]
yes, I need that for phaselocking and noise reduction. I'll get back to you on that.

**Comment by RobinSchmidt** [comment]
damn - i currently can't find the code, but the high level algorithm for separating the harmonic content goes like this:
-split signal into (approximate) cycles
-on each cycle, do a FFT (arbitrary size FFT)
-from this FFT data, obtain frequency and amplitude envelopes for an oscillator bank
-(bidirectionally) lowpass these envelopes at something like 20 Hz
-resynthesize the signal with an oscillator bank with the lowpassed freq- and amp data
->this is the harmonic content, subtracting it from original will give inharmonic/noise/transient

**Comment by elanhickler** [comment]
Radar is ready for release, just need the exploding EQ and Delay thing solved.

**Comment by elanhickler** [comment]
There is some strange things happening with EQ and Delay. I figured the feedback problem might have to do with the modulation system. Removing the mod and meta pointers from EQ and Delay means there's no more feedback, but now when those effects are not bypassed, the GUI freezes. And also there's no sound.

**Comment by elanhickler** [comment]
Also, if you modulate the EQ frequency, the plugin becomes somewhat unusable. Try it :) 👍

**Comment by RobinSchmidt** [comment]
yes, the eq was the first module in which i dared to *try* to use the modulation system on dynamically created parameters. it's somewhat new ground and probably not yet ready for production

**Comment by RobinSchmidt** [comment]
there are also issues with modulation when you need to plot a frequency response. so far, it was not problem to use the same equalizer object to do the actual dsp for the audio-part and to evaluate the frequency response for the gui. when the eq is modulated, that doesn't work anymore. i'll probably need a 2nd eq object just for evaluating the frequency response...

**Comment by elanhickler** [comment]
it's not the end of the world if EQ is not modulatable for release.

**Comment by elanhickler** [comment]
...so if you could just make the EQ and delay work... with or without modulation (although it would be disappointing to remove modulation for the delay), that would be very appreciated!

**Comment by RobinSchmidt** [comment]
i'll look into that tomorrow

**Comment by RobinSchmidt** [comment]
i have made the pingpongecho available in toolchain and it seems to work there with modulation (i tested only modulating delaytime, though) and removed the modulation and automation features from the eq per-band parameters. it seems to work fine in toolchain as well. if you still get crashes, i may have to try to debug in your codebase

**Comment by elanhickler** [comment]
there's no more crashes since your fix a few days ago, just explosions

**Comment by RobinSchmidt** [comment]
yes , ok - i mean explosions. i don't get these in toolchain either

**Comment by RobinSchmidt** [comment]
soo...is your codebase ready for me to debug with?

**Comment by elanhickler** [comment]
wait....... fixing build errors.

**Comment by elanhickler** [comment]
yeah, omg the delay is so weird. It's as if......... feedback control doesn't work or something.

**Comment by RobinSchmidt** [comment]
`JerobeamRadarModule::processBlock`:

```cpp
double left = 0, right = 0;
for (int n = 0; n < numSamples; n++)
{
   if (!isSilent)
     jbRadarCore.processSampleFrame(&left, &right);
}	
```
should be:
```cpp
for (int n = 0; n < numSamples; n++)
{
   double left = 0, right = 0;
   if (!isSilent)
     jbRadarCore.processSampleFrame(&left, &right);
}	
```
otherwise, when the radar goes silent within the loop, you call the eq with the same values again and again (whatever values it produced last)....although these values should presumably be zero, right? hmm..however - that seems to fix the eq problem

**Comment by RobinSchmidt** [comment]
the blowup was probably due to feeding DC into the eq...soo it probably didi not really blow up exponentially but maybe accumulated incoming DC or something?

**Comment by RobinSchmidt** [comment]
it also seems to solve the delay's sizzle which it previously produced. i didn't actually see it blow up, though. no idea why the feedback slider has no effect. where's the code where your connect the parameter with the callback and/or the slider with the parameter?

**Comment by elanhickler** [comment]
omg everything works!!!!!! TIME TO RELEASE RADAR!!! well.. start the process of releasing.

**Comment by RobinSchmidt** [comment]
the delay output seems strongly attenuated

**Comment by elanhickler** [comment]
wat u mean? seems good to me.

**Comment by RobinSchmidt** [comment]
oh - yes - it was the filter. ...changing the delaytime makes a funny noise, though

**Comment by elanhickler** [comment]
yeah, because it needs smoothing. Need to connect it to my global smoothing time.

wouldn't it be frikkin awesome to make toolchain a module that you can insert... for example, in the delay? o you could put EQ / filter / whatever you want in the delay instead of having the given built in lowpass highpass... while that would be awesome, actually draggable components is more needed to reorganize effects.

**Comment by RobinSchmidt** [comment]
you mean, to plug a who toolchain into the feedback path of a a delayline. i guess, such things are so close to an actual modular system (like reaktor) that it would make more sense to do such things liberty. i echolab, however, you have a full equalizer in the feedback path (as well as the input path). not sure what other modules i would want to put there, maybe waveshapers? ...hmm...or maybe something like chorus could be interesting as well - would probably more and more diffuse the echoes maybe going a bit into the direction of reverb?

**Comment by elanhickler** [comment]
f**k it, ill just make the FX section a liberty instance 😀 😆

**Comment by elanhickler** [comment]
or even a ... button to "turn to the back" and the back of the synth is a liberty instance.

**Comment by RobinSchmidt** [comment]
sounds more like liberty itself needs "turn-to-front" button (i.e. let the user create a gui, as in reaktor)

**Comment by elanhickler** [comment]
nooooooooooooooo

robin PLEASE! Do not follow any program that exists right now, they all suck, they all do it wrong IMO, and you are on the verge of doing it right.

**Comment by RobinSchmidt** [comment]
i was not actually being serious. i'm quite happy with the current gui concept.

**Comment by elanhickler** [comment]
... 😒

**Comment by elanhickler** [comment]
resolved!
