### ISSUE TITLE
SuperOscillator::getSample() not returning

### ISSUE THREAD

**Issue by martinfinke** [RobinSchmidt/RS-MET#181]
I just ran into an issue where SuperOscillator::getSample() didn't return. Breaking in the debugger showed that it doesn't go out of this loop:

https://github.com/RobinSchmidt/RS-MET/blob/1fcaf9d8b902c88f31540cb9e92dc452c33c3cd8/Libraries/JUCE/modules/rosic/generators/rosic_SuperOscillator.h#L409

Here, `i` is `2` and `phaseIndices[2]` is `+Inf` because both `increments1[2]` and `increments2[2]` are `+Inf`.

Is there anything I have to keep in mind when calling `setFreq`, `setDetuneRatio` or `setPulseWidth`? Any help is appreciated 😊

**Comment by RobinSchmidt** [comment]
what is value for pulseWidth? it's really long ago that i wrote this code and i'm not even sure, if i ever used it anywhere. but looking at the code, it seems like pulseWidth should be between 0 and 1 - ends *ex*cluded (there's a div-by-zero otherwise...i think)

**Comment by martinfinke** [comment]
Ah, yes. The problem occurred when changing the pulse width, and I was using [0…1] as the range, not (0…1). I'll constrain the range, and get back if the problem still occurs. Thank you!
