### ISSUE TITLE
plz build mac and fix errors

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#182]
do this

**Comment by elanhickler** [comment]
what are all these _mm functions, they don't build on mac.

once again, this would be a GREAT time for a branch

**Comment by RobinSchmidt** [comment]
just comment out the line 

#include "Simd/FloatSimdVectors.h"

in Data.h in the rapt library. i'm currently working on a wrapper class for SIMD vectors

**Comment by elanhickler** [comment]
im not trying to stay on your latest commit, but it becomes a problem when I need other people to get your latest build...... I'll have to go back to using a personal branch.

**Comment by RobinSchmidt** [comment]
or maybe try including #include <xmmintrin.h> and/or #include <pmmintrin.h> in rapt.h - maybe it will work then on mac

> im not trying to stay on your latest commit, but it becomes a problem when I need other people to get your latest build

yes, but actually i consider this repo as more or less personal even though it's public. it's not really practical to check for every little addition during transitional or development stages, that it works everywhere

**Comment by elanhickler** [comment]
if you can remember to do this, really fast, add a send level to pingPongDelay, "setSendLevel" function which basically multiplies the input signal from 0 to 1. 

Otherwise, you have to remove all the dry/wet stuff from pingPongDelay, so I can do send level and dry/wet outside of pingPongDelay.

**Comment by RobinSchmidt** [comment]
i think, what you want is already there: PingPongEcho::setWetLevel. it multiplies the (wet, i.e. delayed) output signal but for linear effects (as this is) this makes no difference

**Comment by RobinSchmidt** [comment]
...or do you mean i need to add a Parameter object for that in the audio-module and a slider in the editor?

**Comment by elanhickler** [comment]
I'm not trying to control the volume of the output of the delay, im trying to control the volume of the input. Send Level, how much signal to send.

Don't add a slider, I am creating my own gui. I simply need to be able to set send level.

line 201 rosic_PingPingEcho.h
```cpp
inM = ONE_OVER_SQRT2 * (*inOutL + *inOutR) * sendLevel;
```

line 227

```cpp
tmp1 = (gLL*(*inOutL) + gRL*(*inOutR)) * sendLevel;
tmp2 = (gLR*(*inOutL) + gRR*(*inOutR)) * sendLevel;
```

**Comment by RobinSchmidt** [comment]
> I'm not trying to control the volume of the output of the delay, im trying to control the volume of the input. Send Level, how much signal to send.

as said: this is the same thing, for linear effects. it doesn't matter if you multiply the input or the output of a linear effect with a factor. the result is the same. `effect(gain*input) == gain*effect(input)`. this is one of the two defining properties of a linear system (the other is: `effect(in1 + in2) == effect(in1) + effect(in2)` - you can express both conditions in a single equation, though)

**Comment by RobinSchmidt** [comment]
and a delay *is* a linear system

**Comment by elanhickler** [comment]
you've lost me!

Are you saying to control amplitude of input signal from OUTSIDE the pingPongDelay? because that's not going to work, that will also remove the dry signal.

**Comment by elanhickler** [comment]
hence my suggestion to remove dry/wet from pingPongDelay, so I can handle all that outside.

**Comment by elanhickler** [comment]
i guess i could, just override pingPongDelay with a subclass...

**Comment by RobinSchmidt** [comment]
no, i'm saying, multiplying the *output* signal of the delay with a factor (which is what setWetLevel does) has the *same effect* as multiplying the *input* signal of the delay with that factor. for linear effects, it doesn't make a difference if you apply a gain at the input or output side

**Comment by RobinSchmidt** [comment]
...or maybe i'm not really understanding what you want to achieve..

**Comment by elanhickler** [comment]
you are right that multiplying the output has the same effect as multiplying the input.

But there's two inputs here.

Dry/Original and what I call "Send"

Send goes into the delay buffer. Dry is just passed through.

**Comment by elanhickler** [comment]
it only makes sense when you modulate send level

**Comment by RobinSchmidt** [comment]
oh...when you modulate something, actually what i said before doesn't really apply anymore. i was sloppy - the condition (that input gain has the same effect as output gain) actually holds for linear, time-invariant (LTI) systems. as soon as modulation comes into play, it's not time-invariant anymore. hmmm...i need to think about that

**Comment by elanhickler** [comment]
huh? don't think about it! Anyway, I better just make a subclass of pingPongDelay. This is a really simple addition, but I can't just do a pull request because I know you'll want to do it your own way.

**Comment by elanhickler** [comment]
btw there's other build errors besides the simd stuff.

**Comment by RobinSchmidt** [comment]
i always need to think about everything that i add to my library - if it makes sense, how to do it best, etc. for example, your code above:
```
tmp1 = (gLL*(*inOutL) + gRL*(*inOutR)) * sendLevel;
tmp2 = (gLR*(*inOutL) + gRR*(*inOutR)) * sendLevel;
```
contains two potentially superfluous multiplications - if the sendLevel could be absorbed into the gLL, ...factors. anyway, if you want to do t with a subclass, there you go

**Comment by elanhickler** [comment]
I know that it contains superfluous multiplication... but sometimes I just need a quick fix!

**Comment by RobinSchmidt** [comment]
fair enough. but i mostly like to think a little bit more how to do it the best way possible rather than doing the first quick-and-dirty thing that comes to mind

**Comment by elanhickler** [comment]
you should do more quick and dirty things 😌

**Comment by RobinSchmidt** [comment]
> Dry/Wet controls volume of output vs original signal

`PingPongEcho::setWetLevel` does not control the dry/wet ratio. this would be `setDryWetRatio` setWetLevel is an additional factor for the wet signal

**Comment by RobinSchmidt** [comment]
> you should do more quick and dirty things 😌

in my experience, you will then often move to the next task and never clean it up...and then the dirt piles up, gets layered. new dirt will rely on old dirt and at the end you have a mess that can never be fixed :-P

**Comment by elanhickler** [comment]
That's not the kind of dirty things I'm talking about! 😞

**Comment by RobinSchmidt** [comment]
what exactly is wrong with setWetLevel? did you even try it? you seem to have assumed that i was talking about setDryWetRatio which i wasn't

**Comment by elanhickler** [comment]
setWetLevel changes the *output* amplitude of the delay, right? I need to change the input... without changing the dry level.

**Comment by RobinSchmidt** [comment]
yes, but then i explained that it doesn't make a difference if you change the input or output amplitude - at least as long as you don't modulate it. ok, you said then, it makes sense only *with* modulation. because otherwise the modulation signal would be applied in a delayed fashion which is inacceptable in your scenario? i just try to understand the issue at hand to make sure that we don't add redundant stuff because of misunderstandings

**Comment by RobinSchmidt** [comment]
> setWetLevel changes the output amplitude of the delay, right?

it changes the aplitude of the *wet* signal. the dry signal is unaffected

**Comment by RobinSchmidt** [comment]
so basically, it has its own dry/wet control and in addition an additional factor for the wet signal

**Comment by RobinSchmidt** [comment]
...the latter is applied at the output side but the effect is the same as if it would have been applied at the input side.

**Comment by elanhickler** [comment]
> it changes the amplitude of the wet signal. the dry signal is unaffected

yes, the *output* of the wet signal

> ...the latter is applied at the output side but the effect is the same as if it would have been applied at the input side.

unless you're modulating it.

**Comment by RobinSchmidt** [comment]
ok, so the issue is that the modulation is applied to the delayed signal and you want to apply the modulation before it enters the delayline. soo, like for example, feeding a signal with applied tremolo into the delayline rather than delaying signal and then applying the tremolo to that (which basically would result in a time-shift of the tremolo signal)?

**Comment by elanhickler** [comment]
yes, in addition to / on top of the dry signal (assuming dry/wet is not 100% wet)

**Comment by RobinSchmidt** [comment]
hmmm....ok..but now i wonder if that should be a dB value or a raw multiplier. i have the output gain as dB value - which is more convenient. but raw amplitude would be more flexible due to allowing negative values. ...but then i should probably change the other one (output gain) to raw, too - for consistency. what do you think is better?

**Comment by RobinSchmidt** [comment]
ok, i added setDelayInputLevel. i takes values in dB

**Comment by elanhickler** [comment]
ok but I would prefer raw ampitude 😉

**Comment by elanhickler** [comment]
raw amplitude is better because the goal is to modulate it, and going from 0 to 1 will generally be the use case... for me at least... I want to do "stutter delay" type effects, where you stutter the amplitude of the input to create an interesting stuttered sound at the output (on top of the original signal).

**Comment by RobinSchmidt** [comment]
ok, done. and such stutter delay effects are more interesting when the delay's input is being stuttered rather that the output? when you request features, you should perhaps tell me what your desired end goals are so i can get a better grasp why current facilities are inadequate

**Comment by RobinSchmidt** [comment]
ok - i fixed the mac build errors. i had to include emmintrin.h and rewrite my wrapper in terms of using a member of the __m128d datatype instead of making my wrapper a subclass of it. apparently, the MS compiler allows primitive datatypes to be viewed as classes while gcc doesn't. took me quite a while to figure this out!

**Comment by RobinSchmidt** [comment]
nice - my sse wrapper works. i think, i can soon use it to provide some stereo filters at the computational cost of mono filters. (it will really work easily only with processors that only need basic arithmetic operations, though).

**Comment by elanhickler** [comment]
nieeeece

**Comment by RobinSchmidt** [comment]
the best thing is: when i write my filter class as templates (which i already did in many cases) and instantiate the template not with double or float but with my simd wrapper class: bäm! two parallel filters for the price of one without writing additional code. *that*s why writing the dsp code as templates makes sense (among other things). it's more hassle but it pays off. and when i write a similar wrapper for four floats (instead of two doubles), we can have even four (single precision) channels for the price of one. probably not very useful for audio - but 4 floats are good for RGBA values in image processing. maybe i can optimize the pixel-decay in my scope with that - we'll see

**Comment by elanhickler** [comment]
yes do it.

**Comment by RobinSchmidt** [comment]
> raw amplitude is better because the goal is to modulate it, and going from 0 to 1 will generally be the use case

aah - so this is precisely the situation that i had in mind when implementing the "Multiplicative" modulation mode. i guess, you are using that here?

**Comment by elanhickler** [comment]
i tend to use relative or exponential. btw exponential is a little difficult to use because the depth of modulation has little to do with the actual amount. 20 depth is like a range of... 20,000?

**Comment by RobinSchmidt** [comment]
in exponential mode, the depth is in octaves. so if you have a cutoff frequency of 1000 Hz and an LFO between -1 and +1 and a mod depth of 1, the modulation goes one octave down and one octave up - so the cutoff oscillates between 500 Hz and 2000 Hz.

**Comment by RobinSchmidt** [comment]
20 would be 20 octaves! :-O seems like a large amount!

**Comment by RobinSchmidt** [comment]
it's most useful for exponentially scaled parameters such as a frequency

**Comment by elanhickler** [comment]
would be nice to show some number representing even a guestimate of the range... I guess I could add that in when I design my own modulation GUI out of calling your various get/set functions for modulation and attaching to UI components.

**Comment by elanhickler** [comment]
oh, so we can repaint when we assign modulation, do you have facilities to repaint as modulation depth is changed? I could draw an additional thing on the slider to show range... like you said you wanted to do.

**Comment by RobinSchmidt** [comment]
> would be nice to show some number representing even a guestimate of the range.

i think, we would would have to add virtual functions getMin/getMax to ModulationSource - this function should be overriden by subclasses to return the extremal points of the modulation curve - like the lowest and highest breakpoint ind breakpoint-env. then, each modulation connection could compute min/max values of the target parameter due to *this* connection. adding up all these min/max values could give the overall (potential) modulation range (*potential* because the range will be fully spanned only, if all minima and maxima of all modulators occur at the same instant)

**Comment by RobinSchmidt** [comment]
> we can repaint when we assign modulation, do you have facilities to repaint as modulation depth is changed?

no, there's no call back for that yet. currently, we have only ModulationTargetObserver::modulationsChanged which is called when connections are added or removed. i think, we could add another callback modulationDepthChanged (and maybe rename the first into modulationConnectionsChanged).  ...or maybe the ModulationTargetObserver could also be  ParameterObserver and register to the mod-depth parameter to receive parameterChanged callbacks whenever the mod-depth (Parameter) changes

**Comment by elanhickler** [comment]
ok, let me know if you get around to that.

**Comment by RobinSchmidt** [comment]
> two parallel filters for the price of one without writing additional code

EngineersFilter is now based on instantiating a template with the simd-wrapper. should roughly reduce computations by factor two (i didn't measure yet). there's also a new version of the ladder filter in rosic based on that. has probably no implications for your code yet, but as next step, i can base the EllipticSubBandFilter on that. then you can get rid of antiAliasFilterL, antiAliasFilterR in your oversamples modules and replace them by just one which handles both channels for the cost of one. coming sooon...

**Comment by RobinSchmidt** [comment]
YAY! i measured it! EngineersFilter does indeed take only half of the cpu now compared to before! mission SIMD accomplished! now, it only remains to make use of it in all modules where it makes sense.  ..but that can be done step by step. it doesn't have to be done all at once. the required facilities are in place and working.

**Comment by elanhickler** [comment]
WOAH YES! Wait, that means oversampling cost will be cut in half? That means...... 4x sampling is as expensive as 2x sampling?

**Comment by RobinSchmidt** [comment]
well - the anti-alias filter will cost one half (if i use the simd class there too - not yet done). the computational cost of your over-sampled process itself is obviously not affected

**Comment by RobinSchmidt** [comment]
well - these are the kinds of processes that can be vectorized just by instantiating the dsp class with the simd class, without writing any special code. that doesn't rule out that with some more special code, you may find ways to optimize other algorithms as well. but that's then not just a throw in but actual thinking

**Comment by elanhickler** [comment]
o right.
