### ISSUE TITLE
remove message box on close

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#185]
The alert box for PaywareAudioPlugin shows up and hangs around even when PrettyScope is not in the REAPER project. It shows up whenever you start REAPER. This has been a problem from the beginning with all my plugins that use PaywardAudioPlugin. Is there a way to ensure that it closes?

se_PaywareAudioPlugIn.cpp
![image](https://user-images.githubusercontent.com/9116575/35491154-eebbb37a-0461-11e8-9939-7806f0712867.png)

The destructor is not called when REAPER starts up.

The problem seems to be that when REAPER does a preliminary loading of PrettyScope (or any plugin), it then closes PrettyScope in way that never runs the PaywardAudioPlugin destructor.

Yet, it works when removing the plugin from REAPER.

**Comment by elanhickler** [comment]
When loading a plugin in REAPER, i hit PrettyScopeEditor's constructor, then destructor, then constructor again. I bet the MessageBox not going away has to do with getting remvoed the first time around and... well it doesn't even show up.

So the only time PrettyScope shows the alert box is on REAPER starting and not when actually using the plugin.

**Comment by elanhickler** [comment]
I'm starting the process of putting PaywareAudioPlugin functionality inside the ModuleEditor so I can fix all this.

**Comment by elanhickler** [comment]
Ok, basically finished with that.

Need one more thing.

How do you notify parent editor that a child editor's button was clicked?

I want to run a function when closing the alertBox.

**Comment by elanhickler** [comment]
![image](https://user-images.githubusercontent.com/9116575/35505945-f48bde18-04a4-11e8-9b7a-87f0b03fbde5.png)

**Comment by RobinSchmidt** [comment]
so, you have "solved" it yourself? i use quotes because this behavior of the message box popping up when you load a project was intentional. i think, it would be weird, if a user loads a project and it sounds differently than when he saved it (because total recall doesn't work) without notifying the user why this is the case.

i have no idea why some hosts construct the plugin twice. the juce host does this also. i find this rather strange.

> How do you notify parent editor that a child editor's button was clicked? Should i do changed listener/broadcaster?

either you can do that or you can register the parent editor as button-listener with the button itself (make it a public member in the child or use friend declarations). it's a bit hacky but usually no problem if you know what you are doing and being careful

**Comment by RobinSchmidt** [comment]
> The alert box for PaywareAudioPlugin shows up and hangs around even when PrettyScope is not in the REAPER project. It shows up whenever you start REAPER. 

wait - what? the plugin is not plugged in? or do you just mean that the gui isn't open (which makes more sense)

**Comment by elanhickler** [comment]
I mean exactly what I wrote! The whole system is broken! It pops up whether or not you have PrettyScope in a project. Oh, if you have PrettyScope in a project, it pops up twice, once for the time REAPER did an initial load, then again for loading the project. So you have multiple windows stacked. Oh and if you have multiple product demos, multiple versions of plugins (x86, x64, torus generator, spiral generator, prettyscope) you're going to have a hell of a lot of popups to deal with every time you start REAPER.

So yes, I solved it by integrating the PaywareAudioPlugin directly into the editor. The registration helper window pops up if no license is found, and you can access the popup with the Register button:

![image](https://user-images.githubusercontent.com/9116575/35544081-ce85c270-0525-11e8-8967-fe0b24e0510b.png)

**Comment by RobinSchmidt** [comment]
so, that means, reaper instantiates the plugin, even if it not plugged in? like - you can load an empty project, and it instantiates all plugins? WTF? why does it do that?

**Comment by RobinSchmidt** [comment]
my mental model was like: a host instantiates a plugin when a user plugs it in (or loads a project with the plugin plugged in) ...which sort of makes sense to me. a host that instantiating plugins that are not used is a big WTF to me

**Comment by elanhickler** [comment]
it's obvious why it does this, it validate that the plugin runs before allowing you to load it in a project... to protect your project from crashes or becoming broken or whatever.

**Comment by RobinSchmidt** [comment]
that doesn't really sit right with me. validating that the plugin runs is what the scanning process is for. ...or i assumed so. why would a host validate *all* plugins again and again every time a user loads a project?

**Comment by RobinSchmidt** [comment]
moreover, if a project would crash on load due to a broken plugin, it doesn't make a difference for the user, if it crashes on first or second instantiation. ...you really find this obvious? i find it totally baffling!

**Comment by elanhickler** [comment]
if it crashes once, the host will skip trying to load that plugin next time around.

...but it is weird that the plugin is run every time REAPER starts, that doesn't make sense... I don't see how REAPER could start up so quickly if it has to re-verify every possible plugin... unless it has some kind of "quick start" which causes my plugins to not destruct correctly.

**Comment by RobinSchmidt** [comment]
> if it crashes once, the host will skip trying to load that plugin next time around.

i still i don't see why this would require a sort of "test-run" of all instantiations. it could just try to load the project, if it doesn't crash, keep the instances and be ready to go and only in the case one (or more) plugins crash, try a reload with the offending plugins removed. hmmmm...well.. but it still does not make sense to instantiate plugins that are not used in the project ...really weird stuff

**Comment by RobinSchmidt** [comment]
and what makes even less sense that the host is trying to invoke a state recall in a plugin that is not part of the project (it's the state-recall by the host that triggers the opening of the message box)

**Comment by elanhickler** [comment]
resolved.
