### ISSUE TITLE
defaults not working

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#187]
Are defaults working for your plugins? They are not working for my plugins (Radar and PrettyScope are both buildable right now).

For example, Radar has a Density readout of 3.0 

BUT the slider looks to be set at 0. 

BUT the actually value is indeed 3.

BUT if you move the slider, the value then audibly jumps to 0 and then follows the slider as normal.

I do call `callParameterCallbacks(true);`

**Comment by RobinSchmidt** [comment]
default values seem to work fine for my plugins. but i'm not yet using custom mapper objects anywhere. is this a problem for all parameters or only those with custom mappers?

**Comment by elanhickler** [comment]
Running the debugger, the mapper is set before `updateWidgetFromAssignedParameter()` is called.

I need a quick fix for now.

**Comment by elanhickler** [comment]
please make a default constructor for mappers without parameters.

**Comment by elanhickler** [comment]
or maybe ill just copy paste your mappers for myself

**Comment by RobinSchmidt** [comment]
the rsParameterMapper actually has a default constructor. are you talking about some of the subclass constructors, like rsParameterMapperSinh(double minValue, double maxValue, double shape)? 

maybe we should use default values min=-1, max=+1, and shape, such that a=1 in these curves?:

https://www.desmos.com/calculator/jhnlcxgmsx

**Comment by elanhickler** [comment]
I thought loading a default preset would fix the defaults problem. I am releasing Radar tomorrow, I need a quick fix! I am not on your development branch of RS-MET, I don't want to do risk something being wrong right before release.

**Comment by elanhickler** [comment]
you delete mappers?

![image](https://user-images.githubusercontent.com/9116575/35930331-db719246-0bee-11e8-9651-eb3fae37d4a7.png)

I stopped using new because of memory leak.........now what?

**Comment by RobinSchmidt** [comment]
yes, i delete the mapper. the parameter objects takes over ownership as said in the doc of Parameter::setMapper. 

> I stopped using new because of memory leak.........now what?

use new. simply do something like 
`myParameter->setMapper(new rsParameterMapperSinh(-1, +1, 5));`
...i.e. don't even declare a variable for the mapper, create it and pass it to the parameter in one go. it *will* be deleted when the parameter is deleted, so that actually shouldn't create a memleak

**Comment by RobinSchmidt** [comment]
> I could be on your development branch if there's not any breaking changes.

my refactoring of the drawing code is not yet finished. no good idea to switch. there are still bugs

**Comment by elanhickler** [comment]
how is smoothing manager assigned? i forget. Does it come from the metaparameter manager?

**Comment by RobinSchmidt** [comment]
the smoothing manager is a member of AudioPlugin and a pointer is passed to the AudioModule via setSmoothingManager. normally, you should not have to care about this (i think)...because in AudioPlugin::setAudioModuleToWrap, this will be called....and this should recursively be passed to all child-modules as well.

**Comment by elanhickler** [comment]
How then do I set smoothing speed of parameters for the Equalizer child module on Radar?

**Comment by elanhickler** [comment]
oh i see, the parameters need to be modulatable. EQ parameters are not modulatable.

**Comment by RobinSchmidt** [comment]
you mean this?:
```cpp
void EqualizerAudioModule::addBand(int channel, int mode, double frequency, double gain, double bandwidth,   bool selectNewBand, bool suppressNotification)
{

  typedef Parameter Param;
  //typedef ModulatableParameter Param; // experimental, does not yet work right
  Param* p;
```
maybe one could try rsSmoothableParameter which is in between in the inheritance hierarchy. but i don'T know, if that will work correctly. didn't try it yet

**Comment by elanhickler** [comment]
going to close this until the problem arises again. It's possible that not setting mapper with the function was my issue. (i set it with the = operator before)
