### ISSUE TITLE
loading default preset

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#189]
why is this commented out? how do I load default preset?

![image](https://user-images.githubusercontent.com/9116575/35929639-2b77a3cc-0bed-11e8-8ee4-7bb3b60907e7.png)

**Comment by elanhickler** [comment]
defaults are now loading correctly i used "loadFile" function somewhere in my audioModule, not sure if it's the preset working or defaults working.

**Comment by elanhickler** [comment]
wtf, ok, i just tested it, default preset is not being loaded, so defaults are working now?

loading a default preset makes the default values work, but the default preset is not actually loaded, not sure how to load a default preset now that these functions are commented out. But I guess my temporary fix is loading a default preset (that isn't actually loaded).

**Comment by RobinSchmidt** [comment]
i guess trying to load a preset triggers a call to updateWidgetsAccordingToState...even if nothing was loaded...or something (just guessing)

> not sure how to load a default preset now that these functions are commented out

just call loadPreset(DefaultPresetFileName.xml) in the constructor of your AudioModule. that's much simpler than before. the old methods are deprecated and i will probably delete them completely at some point (i sometimes just comment out obsolete code, just in case i need an easy rollback)

**Comment by elanhickler** [comment]
please add a jassert for when file does not exist

**Comment by elanhickler** [comment]
loading default file in constructor isn't working, ill try to load it a few other places.

**Comment by RobinSchmidt** [comment]
jassert added? why does it not work? what happens. it works for straightliner

**Comment by elanhickler** [comment]
it seems like there's no indiciation of the file not loading

........uhhh ok everything is working now, no idea why it wasn't working before. defaults don't work by themselves, but loading default preset forces the defaults to work AND the default preset is now loading.

going to close.
