### ISSUE TITLE
Envelope generator parameters only change when retriggered

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#19]
Why is the breakpoint envelope generator not responding to changes in parameters? It only changes after being retriggered. For example, doing a long decay time and changing decay time does not change the decay time until retriggering the envelope.

Maybe you need to design a modulatable breakpoint envelope system.

**Comment by RobinSchmidt** [comment]
yeah - that's a limitation of the implementation. the envelope generator is based on recursive generation of certain functions (exponential decay, growth, sinusoids (using a 2-pole filter, aka trigonometric recursion). tanh and sinh ("sigmoid" and "spikey") shapes are certain combinations of exponential decay and growth (look up the defining formulas for sinh and tanh). whenever a breakpoint "arrives", the parameters for the recursion formulas are recomputed - and then used until the next breakpoint arrives. it's a bit like a digital filter - and then doing some stuff

**Comment by RobinSchmidt** [comment]
that's also the reason why the envelope doesn't allow "random-access" of the shape given a time instant. you have to "go-through" it...because at its core it's based on digital filters

**Comment by RobinSchmidt** [comment]
a modulatable (and also random access) system would either require to evaluate the math-formulas for the exp/sin/etc shapes at each point (which would be expensive) - or use different (easier to evaluate) shapes - like polynomial splines - which we will need anyway for the (meta)parameter mapping system. such a tables-based mapping function could also be re-purposed for modulatable/random-access envelopes. but as said - the transition shapes would be different and perhaps less "natural"
