### ISSUE TITLE
setHeadlineText() is acting very strange

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#190]
![image](https://user-images.githubusercontent.com/9116575/35954421-bc0c32f0-0c46-11e8-895e-59ca9ad2fdd3.png)

First the title is set to "PrettyScope 1.3.0 - Demo running"
Later the title i set to "PrettyScope 1.3.0 - Demo timed out"

you can see the "ut" at the very end.

This issue fixes itself if you hide/show the UI.

**Comment by RobinSchmidt** [comment]
can you try to add an repaint() or repaintOnMessageThread in the implementation of the function (the latter version is necessarry, if you call it from another thread)?  if that fixes it, i'll put it into the library

**Comment by elanhickler** [comment]
what component do I repaint? headline text is not a component.

**Comment by elanhickler** [comment]
undefined
![image](https://user-images.githubusercontent.com/9116575/36050398-a34342be-0da3-11e8-93a7-cd00393f5eed.png)

**Comment by elanhickler** [comment]
repaint(); is undefined apparently.. or no it's just intellisense... ok

**Comment by elanhickler** [comment]
ok this fixed it.
closing.

**Comment by RobinSchmidt** [comment]
yeah - when working in the framework code, intellisense does not work properly. it actually barely works at all. it's quite a pain in the ass to work on library code, which is almost all i'm doing :'-(. apparently, vs is not prepared to handle this module based build system of juce.

**Comment by RobinSchmidt** [comment]
wait - no - i added it too and it doesn't compile. how can it compile for you?

**Comment by RobinSchmidt** [comment]
oh - or are you using repaint()? i thought we were talking about repaintOnMessageThread

**Comment by RobinSchmidt** [comment]
ok, i added repaint too - but maybe that will cause crashes when you call it from the audio thread. do you call it from the audio thread?

**Comment by elanhickler** [comment]
I don't call it from the audio thread.

**Comment by RobinSchmidt** [comment]
so, are you calling it from the message thread? ...well, i guess so, because if not, i think, you would have hit the same assert crash as with setVisible
