### ISSUE TITLE
WTF? my repository access just stopped working

### ISSUE THREAD

**Issue by RobinSchmidt** [RobinSchmidt/RS-MET#191]
all of a sudden, i couldn't push to my repo anymore. i'm getting this error:

fatal: unable to access 'https://github.com/RobinSchmidt/RS-MET.git/': error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version

happens also, when i try to clone (i.e. download) the repo. elan, can you try, if you can still clone my repo? seems like github has messed with its server or something? :-O this sucks!

**Comment by RobinSchmidt** [comment]
...works again. wtf was this?

**Comment by elanhickler** [comment]
i never saw this... uhhh... I don't get notified of you cerating issues it looks like.

**Comment by RobinSchmidt** [comment]
the error re-appeared yesterday. this time it didn't go away after an hour but still persists today. doing a quick search, i found this:

https://stackoverflow.com/questions/48938019/git-pull-push-unable-to-access-https-ssl-routines-seem-to-be-down

hmm...seems i need to update git...can you pull my repo? if not you may need to update, too?

**Comment by RobinSchmidt** [comment]
ok, yes - the re-installation fixed the issue. the login dialog looks different now, too
