### ISSUE TITLE
Exponential mod mode doesn't like 0

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#192]
![image](https://user-images.githubusercontent.com/9116575/36055527-5355acee-0dba-11e8-8530-a478f66b2cc4.png)

If the tune slider is set above 0, i get an infinity for frequency which causes NaN which leads to dead plugin.

edit: the issue is more complex than that, trying to figure it out.

**Comment by elanhickler** [comment]
well... do I really need exponential mode for a parameter that is already exponential in nature?

**Comment by elanhickler** [comment]
ok this is the culprit

pitchToFreq
![image](https://user-images.githubusercontent.com/9116575/36055907-25ec8798-0dbd-11e8-8bd8-8b996992326c.png)

I think we are hitting DBL_MAX... mmmhmm, yep, this must be it.

**Comment by RobinSchmidt** [comment]
> do I really need exponential mode for a parameter that is already exponential in nature?

it depends what you mean by "is exponential in nature". if it is a frequency in Hz with a parameter that uses an exponential scaling then yes. if it is a pitch or dB value, then linear modulation may be more appropriate

hmmm...can you tame it with the min/max settings? if not, i may have to introduce limiting within....or wait...one moment: this is a tune slider in semitones so it is already internally scaled exponentially. the exponential modulation mode is actually appropriate only for parameters that don't go through zero...just like the exponential parameter scaling doesn't support going down to zero....hmmm...i need to think what to do about that...maybe making the exponential option unavailable for parameters whose lower limit is <= 0...or somehow handling special conditions in the modulation code (could make realtime dsp code more expensive)

**Comment by elanhickler** [comment]
i don't think it has anything to do with the parameter actually being 0, I discovered that my semitone parameter is being modulated to 12,000+ with the help of exponential modulation. That would create a frequency beyond DBL_MAX

**Comment by elanhickler** [comment]
closing this issue, solution is to limit your values where needed.

**Comment by RobinSchmidt** [comment]
you mean, limiting on the gui? i don't have to change the code?

it's a bit risky to leave such sanity checks to the user....users tend to throw insane data at your programs ;-) 
 ...but ok, if it's ok for now

**Comment by elanhickler** [comment]
i dont see much point in exposing limits to the user btw, i would remove it from the UI.

**Comment by RobinSchmidt** [comment]
the point of having the limits on the gui is not mainly to expose them but rather to make them adjustable. the user may want to limit cutoff modulation, so it doesn't go above 20 kHz or maybe half the sample rate - because some filter design formulas don't work anymore when the cutoff goes above fs/2 (or below zero ...or even to zero itself).

hmm...maybe i should impose such limits in the respective filter class...but i think, it can be still useful to adjust modulation limits
