### ISSUE TITLE
does your latest RS-MET library build on Mac?

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#195]
please test something like building toolchain on mac to see if you have any errors.

im getting errors. not sure if it's due to using later JUCE library. going to try going back to older library.

**Comment by elanhickler** [comment]
```
Undefined symbols for architecture i386:

  "RAPT::rsMultiBandSplitter<rsFloat64x2, double>::~rsMultiBandSplitter()", referenced from:
      jura::MultiBandEffect::MultiBandEffect(juce::CriticalSection*, jura::MetaParameterManager*, jura::ModulationManager*) in libM-Ref Dev.a(include_jura_processors.o)
      jura::MultiBandEffect::~MultiBandEffect() in libM-Ref Dev.a(include_jura_processors.o)

ld: symbol(s) not found for architecture i386

clang: error: linker command failed with exit code 1 (use -v to see invocation)

(null): "RAPT::rsMultiBandSplitter<rsFloat64x2, double>::~rsMultiBandSplitter()", referenced from:

(null): Jura::MultiBandEffect::MultiBandEffect(juce::CriticalSection*, jura::MetaParameterManager*, jura::ModulationManager*) in libM-Ref Dev.a(include_jura_processors.o)

Jura::MultiBandEffect::~MultiBandEffect() in libM-Ref Dev.a(include_jura_processors.o)

Symbol(s) not found for architecture i386

Linker command failed with exit code 1 (use -v to see invocation)
```

do you know about this error?

**Comment by RobinSchmidt** [comment]
oh! where do you get this? which project and what configuration? i'm not getting this here when building ToolChain (i build the standalone version in debug mode and run it and it builds and opens just fine (i'm hitting a jassert in the debugger due to not finding preset files, but when hitting "continue", the gui opens)

**Comment by RobinSchmidt** [comment]
...ok...i'm getting these now, too when building in release mode....damn!

**Comment by RobinSchmidt** [comment]
ok - try again. it seems to work now (i just built it successfully in the profile built "scheme" which uses release-mode). i had to add some more explicit template instantiations for the classes in question (RAPT::rsMultiBandEffect and actually two more rsBiquadCascade and rsRotationXY).

**Comment by elanhickler** [comment]
windows 32 bit does not compile, lots of errors, here's just a handful to give you an idea:
```
Severity	Code	Description	Project	Line	File	Suppression State
Error	C2719	'z': formal parameter with requested alignment of 16 won't be aligned (compiling source file ..\..\JuceLibraryCode\include_rosic.cpp)	M-Ref Dev_SharedCode	59	d:\_programming\rs-met\libraries\juce\modules\rosic\basics\ComplexFloat64x2.h	
Error	C2719	'c3': formal parameter with requested alignment of 16 won't be aligned (compiling source file ..\..\JuceLibraryCode\include_rosic.cpp)	M-Ref Dev_SharedCode	81	d:\_programming\rs-met\libraries\juce\modules\rapt\filters\Musical\LadderFilter.h	
Error	C2719	'a': formal parameter with requested alignment of 16 won't be aligned (compiling source file ..\..\JuceLibraryCode\include_romos.cpp)	M-Ref Dev_SharedCode	129	d:\_programming\rs-met\libraries\juce\modules\rapt\filters\Musical\LadderFilter.h	
Error	C2719	'newCutoff': formal parameter with requested alignment of 16 won't be aligned (compiling source file ..\..\JuceLibraryCode\include_se_framework.cpp)	M-Ref Dev_SharedCode	65	d:\_programming\rs-met\libraries\juce\modules\rapt\filters\Musical\LadderFilter.h	
Error	C2719	'c4': formal parameter with requested alignment of 16 won't be aligned (compiling source file ..\..\JuceLibraryCode\include_jura_processors.cpp)	M-Ref Dev_SharedCode	81	d:\_programming\rs-met\libraries\juce\modules\rapt\filters\Musical\LadderFilter.h	
Error	C2719	'c1': formal parameter with requested alignment of 16 won't be aligned (compiling source file ..\..\BuildPlugin.cpp)	M-Ref Dev_SharedCode	81	d:\_programming\rs-met\libraries\juce\modules\rapt\filters\Musical\LadderFilter.h	
Error	C2719	'decay': formal parameter with requested alignment of 16 won't be aligned (compiling source file ..\..\..\Source\MRefCore.cpp)	M-Ref Dev_SharedCode	134	d:\_programming\rs-met\libraries\juce\modules\rapt\filters\Musical\LadderFilter.h	
Error	C2719	'x': formal parameter with requested alignment of 16 won't be aligned (compiling source file ..\..\..\Source\MRefCore.cpp)	M-Ref Dev_SharedCode	14	d:\_programming\rs-met\libraries\juce\modules\rosic\unfinished\rosic_QuadSource.h	
Error	LNK2001	unresolved external symbol "public: bool __thiscall juce::AudioProcessor::setBusesLayout(struct juce::AudioProcessor::BusesLayout const &)" (?setBusesLayout@AudioProcessor@juce@@QAE_NABUBusesLayout@12@@Z)	M-Ref Dev_VST	1	D:\_PROGRAMMING\Soundemote\M-Ref\Mref Dev\Builds\VisualStudio2015\include_juce_audio_plugin_client_VST2.obj	
Error	LNK1120	29 unresolved externals	M-Ref Dev_VST	1	D:\_PROGRAMMING\Soundemote\M-Ref\Mref Dev\Builds\VisualStudio2015\Win32\Release\VST\M-Ref Dev (x86).dll	
```

**Comment by RobinSchmidt** [comment]
hmm...looks like it refuses to respect my memory alignment requests (which once added looong ago (but not very consistently) for optimization purposes - not sure, if it's still relevant).  i don't normally compile for 32 bit anymore, that's why i don't see these. hmm...ok - tomorrow, i'm not at home - i'll look into it thursday. maybe, i'll #ifdef it or throw it out entirely - not sure yet. i guess, i should do some performance measurements with and without

**Comment by RobinSchmidt** [comment]
when do you need this to be fixed? is this urgent?

**Comment by elanhickler** [comment]
hmmmmmmm, not urgent but I will need to build 32 bit plugins for Soundemote synths and Jim Welch pretty sure. For my plugins I may just revert to an old commit.

**Comment by RobinSchmidt** [comment]
ok - ToolChain now compiles in Win32 mode (although, with lots of warnings, for the time being)

**Comment by elanhickler** [comment]
I get an error trying to build mushroom generator. Could you check to see if your toolchain still builds? If so, I'll need you to take a look at mushroom generator, error has to do with 32 bit, something about rsImage:

Undefined symbols for architecture i386:
  "RAPT::rsImage<float>::~rsImage()", referenced from:
      OscilloscopeModule::OscilloscopeModule(juce::CriticalSection*, jura::MetaParameterManager*, jura::ModulationManager*) in libMushroom Generator.a(include_se_framework.o)
      OscilloscopeModule::~OscilloscopeModule() in libMushroom Generator.a(include_se_framework.o)
      RAPT::rsPhaseScopeBuffer<double, float, double>::~rsPhaseScopeBuffer() in libMushroom Generator.a(include_se_framework.o)
      RAPT::rsPhaseScopeBuffer<double, float, double>::~rsPhaseScopeBuffer() in libMushroom Generator.a(include_se_framework.o)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by RobinSchmidt** [comment]
yep - builds here. you can actually easily try this yourself. if you still get errors, maybe try to add an explicit instantiation of RAPT::rsImage<float>. sometimes, this helps. (rosic.cpp is a good place for that - that's where i have all my explicit instantiations anyway)

**Comment by elanhickler** [comment]
I'm not sure what to do, my C++ knowledge in this stuff is not good.

**Comment by RobinSchmidt** [comment]
ok - i added it as comment in rosic.cpp, line 98 - just try to uncomment that and see if it helps. but it's just a shot in a dark.
