### ISSUE TITLE
Frequency Locking progress

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#196]
I'm adding modules to reaper_OTSplugin repository/project https://github.com/gregjazz/reaper_OTSplugin and I get these errors. You can start by fixing this and charge OTS your hourly rate.

```
Error	C3246	'jura::ColourizableBitmap': cannot inherit from 'juce::Image' as it has been declared as 'final' (compiling source file ..\..\Source\action_code\Action.cpp)	reaper_OTSplugin_DynamicLibrary	11	d:\_programming\rs-met\libraries\juce\modules\jura_framework\gui\graphics\jura_ColourizableBitmap.h	

Error	C3246	'jura::ColourizableBitmap': cannot inherit from 'juce::Image' as it has been declared as 'final' (compiling source file ..\..\Source\main.cpp)	reaper_OTSplugin_DynamicLibrary	11	d:\_programming\rs-met\libraries\juce\modules\jura_framework\gui\graphics\jura_ColourizableBitmap.h	

Error	C2504	'ButtonListener': base class undefined (compiling source file ..\..\Source\action_code\Action.cpp)	reaper_OTSplugin_DynamicLibrary	7	d:\_programming\rs-met\libraries\juce\modules\jura_framework\gui\dialogs\jura_ImageSavingDialog.h	

Error	C2504	'ComboBoxListener': base class undefined (compiling source file ..\..\Source\action_code\Action.cpp)	reaper_OTSplugin_DynamicLibrary	7	d:\_programming\rs-met\libraries\juce\modules\jura_framework\gui\dialogs\jura_ImageSavingDialog.h	

Error	C2504	'LabelListener': base class undefined (compiling source file ..\..\Source\action_code\Action.cpp)	reaper_OTSplugin_DynamicLibrary	9	d:\_programming\rs-met\libraries\juce\modules\jura_framework\gui\dialogs\jura_ImageSavingDialog.h	

Error	C2504	'ButtonListener': base class undefined (compiling source file ..\..\Source\main.cpp)	reaper_OTSplugin_DynamicLibrary	7	d:\_programming\rs-met\libraries\juce\modules\jura_framework\gui\dialogs\jura_ImageSavingDialog.h	

Error	C2504	'ComboBoxListener': base class undefined (compiling source file ..\..\Source\main.cpp)	reaper_OTSplugin_DynamicLibrary	7	d:\_programming\rs-met\libraries\juce\modules\jura_framework\gui\dialogs\jura_ImageSavingDialog.h	

Error	C2504	'LabelListener': base class undefined (compiling source file ..\..\Source\main.cpp)	reaper_OTSplugin_DynamicLibrary	9	d:\_programming\rs-met\libraries\juce\modules\jura_framework\gui\dialogs\jura_ImageSavingDialog.h	

Error	C3246	'jura::ColourizableBitmap': cannot inherit from 'juce::Image' as it has been declared as 'final' (compiling source file ..\..\JuceLibraryCode\include_jura_framework.cpp)	reaper_OTSplugin_DynamicLibrary	11	d:\_programming\rs-met\libraries\juce\modules\jura_framework\gui\graphics\jura_ColourizableBitmap.h	

Error	C2504	'ButtonListener': base class undefined (compiling source file ..\..\JuceLibraryCode\include_jura_framework.cpp)	reaper_OTSplugin_DynamicLibrary	7	d:\_programming\rs-met\libraries\juce\modules\jura_framework\gui\dialogs\jura_ImageSavingDialog.h	

Error	C2504	'ComboBoxListener': base class undefined (compiling source file ..\..\JuceLibraryCode\include_jura_framework.cpp)	reaper_OTSplugin_DynamicLibrary	7	d:\_programming\rs-met\libraries\juce\modules\jura_framework\gui\dialogs\jura_ImageSavingDialog.h	

Error	C2504	'LabelListener': base class undefined (compiling source file ..\..\JuceLibraryCode\include_jura_framework.cpp)	reaper_OTSplugin_DynamicLibrary	9	d:\_programming\rs-met\libraries\juce\modules\jura_framework\gui\dialogs\jura_ImageSavingDialog.h	

Error	C3246	'jura::ColourizableBitmap': cannot inherit from 'juce::Image' as it has been declared as 'final' (compiling source file ..\..\JuceLibraryCode\include_jura_processors.cpp)	reaper_OTSplugin_DynamicLibrary	11	d:\_programming\rs-met\libraries\juce\modules\jura_framework\gui\graphics\jura_ColourizableBitmap.h	

Error	C2504	'ButtonListener': base class undefined (compiling source file ..\..\JuceLibraryCode\include_jura_processors.cpp)	reaper_OTSplugin_DynamicLibrary	7	d:\_programming\rs-met\libraries\juce\modules\jura_framework\gui\dialogs\jura_ImageSavingDialog.h	

Error	C2504	'ComboBoxListener': base class undefined (compiling source file ..\..\JuceLibraryCode\include_jura_processors.cpp)	reaper_OTSplugin_DynamicLibrary	7	d:\_programming\rs-met\libraries\juce\modules\jura_framework\gui\dialogs\jura_ImageSavingDialog.h	

Error	C2504	'LabelListener': base class undefined (compiling source file ..\..\JuceLibraryCode\include_jura_processors.cpp)	reaper_OTSplugin_DynamicLibrary	9	d:\_programming\rs-met\libraries\juce\modules\jura_framework\gui\dialogs\jura_ImageSavingDialog.h	

Error	C2664	'void juce::Button::addListener(juce::Button::Listener *)': cannot convert argument 1 from 'jura::ImageSavingDialog *const ' to 'juce::Button::Listener *' (compiling source file ..\..\JuceLibraryCode\include_jura_framework.cpp)	reaper_OTSplugin_DynamicLibrary	25	d:\_programming\rs-met\libraries\juce\modules\jura_framework\gui\dialogs\jura_ImageSavingDialog.cpp	

Error	C2664	'void juce::Label::addListener(juce::Label::Listener *)': cannot convert argument 1 from 'jura::ImageSavingDialog *const ' to 'juce::Label::Listener *' (compiling source file ..\..\JuceLibraryCode\include_jura_framework.cpp)	reaper_OTSplugin_DynamicLibrary	51	d:\_programming\rs-met\libraries\juce\modules\jura_framework\gui\dialogs\jura_ImageSavingDialog.cpp	

Error	C2664	'void juce::Label::addListener(juce::Label::Listener *)': cannot convert argument 1 from 'jura::ImageSavingDialog *const ' to 'juce::Label::Listener *' (compiling source file ..\..\JuceLibraryCode\include_jura_framework.cpp)	reaper_OTSplugin_DynamicLibrary	66	d:\_programming\rs-met\libraries\juce\modules\jura_framework\gui\dialogs\jura_ImageSavingDialog.cpp	

Error	C2664	'void juce::Button::addListener(juce::Button::Listener *)': cannot convert argument 1 from 'jura::ImageSavingDialog *const ' to 'juce::Button::Listener *' (compiling source file ..\..\JuceLibraryCode\include_jura_framework.cpp)	reaper_OTSplugin_DynamicLibrary	91	d:\_programming\rs-met\libraries\juce\modules\jura_framework\gui\dialogs\jura_ImageSavingDialog.cpp	

Error	C3246	'jura::ColourizableBitmap': cannot inherit from 'juce::Image' as it has been declared as 'final' (compiling source file ..\..\JuceLibraryCode\include_seObjectiveReaper.cpp)	reaper_OTSplugin_DynamicLibrary	11	d:\_programming\rs-met\libraries\juce\modules\jura_framework\gui\graphics\jura_ColourizableBitmap.h	

Error	C2504	'ButtonListener': base class undefined (compiling source file ..\..\JuceLibraryCode\include_seObjectiveReaper.cpp)	reaper_OTSplugin_DynamicLibrary	7	d:\_programming\rs-met\libraries\juce\modules\jura_framework\gui\dialogs\jura_ImageSavingDialog.h	

Error	C2504	'ComboBoxListener': base class undefined (compiling source file ..\..\JuceLibraryCode\include_seObjectiveReaper.cpp)	reaper_OTSplugin_DynamicLibrary	7	d:\_programming\rs-met\libraries\juce\modules\jura_framework\gui\dialogs\jura_ImageSavingDialog.h	

Error	C2504	'LabelListener': base class undefined (compiling source file ..\..\JuceLibraryCode\include_seObjectiveReaper.cpp)	reaper_OTSplugin_DynamicLibrary	9	d:\_programming\rs-met\libraries\juce\modules\jura_framework\gui\dialogs\jura_ImageSavingDialog.h	
```

**Comment by RobinSchmidt** [comment]
ok, i cloned the repository. why is it a juce-based project anyway? what is juce used for in this context? doesn't reaper have its own API? how is it supposed to work? i thought, we would start from your existing reaper plugin project and first just swap RSLib for RAPT? my juce dsp modules (rapt,rosic) - btw. - although conforming to juce module format, are not dependent on any other juce modules - not even juce_core.

**Comment by elanhickler** [comment]
it's always been with juce, it provides a GUI.

Just get it to compile and we'll move on to the next step.

**Comment by elanhickler** [comment]
once you have it compiled on Windows you put the dll into REAPER\UserPlugins or REAPER\Plugins

![image](https://user-images.githubusercontent.com/9116575/41054424-29ef6240-6973-11e8-830f-87a9c9ec7909.png)

find the action and run it on an audio item:

![image](https://user-images.githubusercontent.com/9116575/41054441-39d5bbd2-6973-11e8-8db2-130d0f116bca.png)

**Comment by RobinSchmidt** [comment]
> it's always been with juce (for the freuquency locking testing), it provides a GUI.

hmm...ok - but your other reaper plugins before that used the generic gui provided by reaper itself, right? what's the point of dragging in a (huge) framework library like juce just to provide another type of generic gui? are you planning to do more sophisticated guis for your reaper plugins in the future?

> Just get it to compile and we'll move on to the next step.

the repo is missing a juce module called "seObjectiveReaper". well, it's actually missing all the required juce modules, but the other ones, i have myself in my own repo so i can point it to there

**Comment by elanhickler** [comment]
https://github.com/elanhickler/seObjectiveReaper

**Comment by elanhickler** [comment]
let me know if you get stuck

**Comment by RobinSchmidt** [comment]
ok - this:
http://www.rs-met.com/temp/reaper_OTSplugin.7z
when placed right next to the RS-MET directory compiles. i don't know, if i have write access to the repo and i would assume that i don't. why should i? is this your repo? but it would not seem to make much sense to check it in into the repo as is, i think

**Comment by RobinSchmidt** [comment]
i also don't know, how you want to organize the code - if you want to have separate repositories for the dependencies or want to copy them into the repo, etc.

**Comment by elanhickler** [comment]
You have write access to OTS reaper plugin, you need to make sure everything is working, and if it isn't then you can fix the issue and push the changes.

We are in the process of removing RSLib so that we can use the frequency locking code from RS-MET which is the same code (since I don't think you made any changes to this stuff).

**Comment by elanhickler** [comment]
it still doesn't compile for me due to errors listed above, need your help to get moving on this.

**Comment by elanhickler** [comment]
omgaaad, get online so we can solve this. There's too much potential for confusion.

**Comment by RobinSchmidt** [comment]
ok - i'll move the seObjectiveReaper folder on the same level as RS-MET and reaper_OTSplugin, change the jucer file appropritely, then get rid of RSLib and then commit

**Comment by RobinSchmidt** [comment]
ok, now reaper_OTSplugin, RS-MET, seObjectiveReaper and RSLib folders must be next to each other. compiles here (with lots of warnings - i guess we should reduce the warning level). ...anyway, i'll take care of getting rid of RSLib next

**Comment by RobinSchmidt** [comment]
ok - done. it was actually much simpler than assumed because  the code just used one class rsCycleMarkFinder. i thought, that this codebase would contain all your other reaper plugins (or actions or whatever they call it), too. the RSLib folder next to the others can now be deleted. it takes the cyclemark finder now from rosic. i also removed the unused juce modules from the project and reduced the warning level for cleaner compilation.

**Comment by elanhickler** [comment]
here is a reaper project and test audio:
http://www.elanhickler.com/transfer/Soundemote/FundamentalEstimatorTestAudio.rar

Currently getting a crash using algo 1 (CYCLE_CORRELATION) due to some vector sizing issue.

**Comment by RobinSchmidt** [comment]
> once you have it compiled on Windows you put the dll into REAPER\UserPlugins or REAPER\Plugins

do you know the post-build event syntax to do that automatically? i tried a couple of things but always get an error

**Comment by elanhickler** [comment]
xcopy /y "$(OutDir)$(TargetFileName)" "PathToREAPER\REAPER\UserPlugins\"

for debugging:

PathToREAPER\REAPER\reaper.exe
"PathToREAPER\REAPER\reaper_test.rpp"

**Comment by RobinSchmidt** [comment]
i think, this is what i tried before. it gives me this:

```
1>------ Build started: Project: reaper_OTSplugin_DynamicLibrary, Configuration: Debug x64 ------
1>  reaper_OTSplugin_DynamicLibrary.vcxproj -> E:\Programming\C++\reaper_OTSplugin\Builds\VisualStudio2015\x64\Debug\Dynamic Library\reaper_OTSplugin_x64.dll
1>  Does C:\Program Files\REAPER (x64)\UserPlugins specify a file name
1>  or directory name on the target
1>  (F = file, D = directory)?
1>  Does C:\Program Files\REAPER (x64)\UserPlugins specify a file name
1>  or directory name on the target
1>  (F = file, D = directory)?
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: The command "xcopy /y "E:\Programming\C++\reaper_OTSplugin\Builds\VisualStudio2015\x64\Debug\Dynamic Library\reaper_OTSplugin_x64.dll" "C:\Program Files\REAPER (x64)\UserPlugins"
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: :VCEnd" exited with code 2.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by RobinSchmidt** [comment]
ah - ok - adding a backslash to  "PathToREAPER\REAPER\UserPlugins" turning it into  "PathToREAPER\REAPER\UserPlugins\"  seems to solve this. but now i'm getting an "access denied".

**Comment by RobinSchmidt** [comment]
ok, i seem to have solved it using:
robocopy "$(OutDir) " "C:\Program Files\REAPER (x64)\UserPlugins\ " reaper_OTSplugin_x64.dll
creating the UserPlugins folder manually and setting the access permissions for it (right-click -> properties ->security -> ..."
it still produces an error message but the copying actually works - the file is there. ...strange

**Comment by RobinSchmidt** [comment]
reaper doesn't seem to find the plugin when i put it in UserPlugins. Plugins works though, so i'm using that. finally, the setup is up and running and i can see the crash. it's because the refined marks at some point overrun the unrefined ones, leading to a negative distance in the next step. that may be a hint of what's generally wrong with the algorithm, even when it doesn't crash. i'll try to come up with an experiment that exposes this behavior in my TestSuite

**Comment by RobinSchmidt** [comment]
i have totally re-implemented the CYCLE_CORRELATION algorithms - well - it's a totally different algorithm actually. the old version is still available as CYCLE_CORRELATION_OLD but maybe it's too flawed to keep it around. the new algorithm starts in the middle of the signal (and sets its first cycle mark there), then looks at a distance P (given by a preliminary estimate of the period) from there for a location where the correlation between a chunk around the current sample index n and n+P (or n-P) has its maximum. then it uses that distance as a new estimate of P and finds the next position with max-correlation and so on. maybe it's worthwhile to experiment with `setRelativeCorrelationLength` which gives the length of the segments to be correlated in terms of the signal period.

...now testing is needed

**Comment by RobinSchmidt** [comment]
i created a pretty nasty inharmonic test signal with 2 frequencies at 1000 Hz and (around) 3236 Hz (*). the old algorithm tries to pick up at the 1kHz tone, the new sets cycle marks spaced such that always 4 marks of the old algo fall between 2 marks of the new:
![image](https://user-images.githubusercontent.com/1833099/41683218-49aa6284-74da-11e8-8fc4-3ace0f655093.png)
..the new marks "look" actually quite resonable. more tests are needed...

(*) this strange value is 1000 * (1+sqrt(5)) where the factor 1+sqrt(5) is two times the golden ratio. it's somewhere near the harmonic ratio of 3, but very inharmonic (in some sense that can be made precise, the golden ratio is the "most irrational" number that exists)

**Comment by elanhickler** [comment]
Is it time for us to test on cello and synth samples?

**Comment by RobinSchmidt** [comment]
that's what i want to try next...i'm not sure - it seemed to be inferior to the zero-crossing algo for a simple 1kHz sine wave

**Comment by RobinSchmidt** [comment]
i mean, i have also thrown the new algo at a simple sine wave. there, the zero-crossing based algo gave me better results than the new one. 

but maybe the new one can still be tweaked, refined and fiddled with to improve the results. we'll see. it's just the first shot. i can imagine to try different window-functions, etc. also, there are two obvious places for a performance optimization - so i'm not yet finished. but i have some prototype to experiment with

**Comment by RobinSchmidt** [comment]
> i mean, i have also thrown the new algo at a simple sine wave (it's the first thing to try, obviously). there, the zero-crossing based algo gave me better results than the new one.

ok, i made a mistake in handling rounded vs non-rounded values - fixed it and getting now similar performance from the new algo as from the zero-crossings. i think, i will next come up with a more systematic way of quality assessment of the cycle marks - like defining various error measures (like the mean- and maximum deviation from a known, true target value of the period) and write a test that compares these measures for the different algorithms...

**Comment by elanhickler** [comment]
nice, sounds like you're almost ready to do real world tests

**Comment by RobinSchmidt** [comment]
here are the errors (in percent) for the estimated period length graphed as function of the true period length (for period lengths from 48 to 52) for both algorithms (black: zero-crossings, blue: correlation):

![image](https://user-images.githubusercontent.com/1833099/41927209-d8c041aa-7971-11e8-91e6-85a3a740fab0.png)

so, for a sine input, the estimation error is somehow an erratic function of the true period between -0.01%...+0.01%. i tried the new algo on the cello - and figured that i need to include some robustification measures. it (unsurprisingly) goes wild at the end, when the signal fades into the noise floor. the old algo doesn't have this problem due to the aggressive bandpass filtering which imprints a periodicity (close to the one of the signal) even into the noise floor - or even into total silence due to ring-out effects

**Comment by elanhickler** [comment]
You are about to over engineer this. I want you to get the frequency flattening perfected. If you start dealing with noisy signals, you are going to be doing more than I asked for and possibly creating a insufficient solution to the problem. Highly non-ideal signals is a completely separate problem. We need to have a discussion on solving this problem that is completely separate from the frequency estimation. That's my somewhat educated opinionanyway.

**Comment by RobinSchmidt** [comment]
i think, it's a quite common situation that a real world sample fades into the background at the end, so i think, i have to deal with it somehow. i'm not trying to make any kind of good "measurement" there, just trying to make sure that the algorithm somehow notices the situation and skips over that region

**Comment by elanhickler** [comment]
yes, but still, I need you to focus on the frequency estimate. Helmholtz algorithm already has a solution for that. If anything, I could use Helmholtz to detect noisy areas, and the problem will be solved. You're potentially wasting time on this noise detection right now.

**Comment by elanhickler** [comment]
I plan on hiring you for FFT based soluations, including noise reduction, noise detection, etc. When you work on that, then you will have a much better noise detection solution.

**Comment by RobinSchmidt** [comment]
ok, well - then try it with the cello. i just did and the results look reasonable in the middle section with some garbage marks at the start/end sections. i just added a quick crude check just to prevent the algorithm from crashing in these silent/noisy fade-in/out sections.

**Comment by RobinSchmidt** [comment]
hmmm...i actually think, the algorithm can quite easily be extended to provide some sort of reliability measure for each cycle mark. currently, i just compute the *position* of the maximum of the cross-corelation. the *value* itself could be used as reliability measure

**Comment by elanhickler** [comment]
Definitely going to need human intervention no matter how good the algorithm is. Just a matter of how much. Willing to use plenty of human intervention for now until we invest in a robust noise detection.

**Comment by elanhickler** [comment]
Ok, I just tested. It is much improved but there is still a tiny drift.

near beginning marker:
![image](https://user-images.githubusercontent.com/9116575/41995716-8edd6540-7a07-11e8-9c27-521a05c715d2.png)

near ending marker:
![image](https://user-images.githubusercontent.com/9116575/41995681-7602ace2-7a07-11e8-97c1-6c210792452b.png)

**Comment by elanhickler** [comment]
maybe the drift is because you are always correlating with the previous waveform which makes a continuous rounding error. Hmm.......

**Comment by RobinSchmidt** [comment]
hmm - can you try incorporating a parameter that calls `setRelativeCorrelationLength` and pass some value less than 1 and see if the improves the situation? it dertermines the size of the neighbourhood that is taken into account in terms of cycle lengths. 1 is the default value.  maybe try 0.5 or something.

but maybe i have a bug somewhere. if the drift is due to a consistent over- or underestimation, this may be. i need to about, how i could figure that out...

**Comment by RobinSchmidt** [comment]
is this one of the samples in the test project, so i can try myself? what kind of code is it? what exactly does it do?

**Comment by elanhickler** [comment]
get this repository, compile: https://github.com/gregjazz/SeSALT

look at D:\_PROGRAMMING\SeSALT\libs

the FFT functions rely on D:\_PROGRAMMING\SeSALT\libs\libs\kiss_fft130

![image](https://user-images.githubusercontent.com/9116575/42005304-7ec08680-7a28-11e8-946e-66982a036094.png)

Your goal here is to help me repurpose the harmonic extractor for my old phaselocking stuff... well, replace your harmonic extraction filter that I use for phaselocking.

Hmm, an online meeting may be a better way to convey all the information so we can get on the same page.

**Comment by RobinSchmidt** [comment]
the link is dead. however, before looking into that, i'd like to try a few things with the current algorithm

**Comment by RobinSchmidt** [comment]
i can expose the drift now in my testsuite project. it's strange. it seems almost like cycle-length estimate is systematically too small by some fraction of a sample. i will double check all my formulas to see if there is anything that could introduce such a bias. i could also try to fit a quartic instead of a quadratic parabola to get a more precise estimate of the subsample-precision maximum.

but i actually think, maybe a hybrid approach would be even better: use the maximum of the correlation as preliminary value and find a zero-crossing in the vicinity of that and use that as mark (this time, a zero-crossing of the original signal, not the bandpass filtered version)

**Comment by elanhickler** [comment]
Ok, just be aware that we have to move to FFT anyway no matter how good the frequency locking is. I'm not even sure at this point there's much of a use for it. But it may come in handy in the future for something.

**Comment by RobinSchmidt** [comment]
yes, works now

**Comment by RobinSchmidt** [comment]
i'm getting a compilation error:

`fatal error C1083: Cannot open include file: '../dockable-windows/Source/JDockableWindows.h': No such file or directory (compiling source file ..\..\Source\Main.cpp)`

the folder `dockable-windows` is there but its empty

> let's meet online and discuss having you create a harmonic extractor (or repurpose the code for us).

ok, just let me implement the hybrid cycle-mark algo. i've now also added a second autocorrelation based algorithm which is a bit different in its details (CYCLE_CORRELATION_2)...but it may produce drift as well. i really think, i need to take absolute signal features such as zero crossings explicitly into account to avoid drift. however, i think it could make sense to expose the other parameters of the algorithms set by
```
setRelativeCorrelationHighpassFreq
setRelativeCorrelationLength
setRelativeBandpassWidth
```
to the user, i.e. have widgets for them on the gui. can you add these to the reaper_OTSplugin repo so i can pull in an update?

**Comment by elanhickler** [comment]
done, pull update from seObjectiveReaper

**Comment by elanhickler** [comment]
Are you nearing conclusion of this endeavor? We need to move on, getting frequency flattened perfectly seems to be not useful.

**Comment by RobinSchmidt** [comment]
i think so. i have just finished the implementation of the hybrid algo. i just wanted to test in reaper - but with your new additions i'm getting these compiler errors:

error C2039: 'getPosition': is not a member of 'ITEM'
error C2660: 'ShowGenericUserInputs': function does not take 4 arguments

so i tested with the old version. it's a bit weird - it seems like in your reaper project, the found cycle marks are always one sample behind a zero crossing. i don't see this in my test project. when this is debugged, i think, we should be done with it. it's now a 3 step procedure:

1: make a rough prediction, where the new mark should be, based on two previous marks
2: refine the new mark by correlation
3: refine further by looking for the closest zero crossing

the algo is called CORRELATED_ZEROS, number 4 in the list (starting at 0). i think, this is pretty close to what a human would do (where step 2 is a sort of subconscious pattern matching)

**Comment by elanhickler** [comment]
you need to pull seObjectiveReaper repository

**Comment by RobinSchmidt** [comment]
ah - ok - i see - my bad

**Comment by RobinSchmidt** [comment]
hmm...well - aside from that one-sample offset, i seem to get good results. could this offset be introduced by the surrounding framework code? maybe somehow in the conversion from sample-index within the sample to reaper's absolute time or something? can you see this offset, too?

**Comment by elanhickler** [comment]
is it one sampe offset DRIFT? or one sample offset everywhere?

**Comment by RobinSchmidt** [comment]
everywhere - as far as i can see

**Comment by elanhickler** [comment]
what settings?

**Comment by RobinSchmidt** [comment]
algorithm 4, precision doesn't seem matter (but maybe use 0 - this uses a linear interpolant for the zero-crossing, so it *should* coincide with the graph's zero crossing)

**Comment by elanhickler** [comment]
drift is gone, but a new problem is that the markers jump around a little bit (only at the beginning) for the two samples I tested

**Comment by RobinSchmidt** [comment]
jump around? like in jitter? can you show me the samples/graphs?

**Comment by elanhickler** [comment]
not jitter, just a little jumping around. after this section, it's perfect.

https://puu.sh/APRzk/243c976afe.gif

**Comment by RobinSchmidt** [comment]
is this one of these SynthSustain... samples that i have in my test project, too? it looks like, there's a sort of DC transient that makes the whole wave go up a little bit and then down again in the beginning - and this may raise one of the faster overtones fully over the zero line and then later duck under the zero line or something or into some range where it actually crosses the zero line. maybe a highpass pre-processing (i.e dc removal) could help in this case. maybe try some nonzero setting for relative correlation HP (maybe 0.5 or something)

**Comment by elanhickler** [comment]
tried 0 , 0.5, and 1, no difference

**Comment by RobinSchmidt** [comment]
hmm...weird...i still think, it probably has something to do with this dc transient. i need to think about this and try this myself and maybe write another test that exposes this behavior

**Comment by elanhickler** [comment]
If you're charging hourly for this we better move on.

**Comment by elanhickler** [comment]
cello: https://puu.sh/APZ0u/9bf54318ea.gif

**Comment by RobinSchmidt** [comment]
damn! but this cello example exposes pretty well what is going on: at first the small wiggle is completely below the zero line, then moves through it and at the end is completely above it. so, of course, the algorithm - being based on zero crossings, must place the mark after the wiggle in the first section and before the wiggle in the last section (and maybe inside the wiggle in the middle which is probably to short to see in the animation).

i tried to experiment with a decaying dc, similar to what the synth sample shows - highpassing *does* help in my artificial test case - but here, something else is going on. i think, the small wiggle walking its way through the big cycle means that we are dealing with a slightly mistuned overtone. it's probably not exactly an integer multiple but slightly off...hmmm

ok, we may put this on hold for the time being. maybe then meeting tomorrow for harmonic extraction talks? i've updated the sheet with my work-hours on my server (url as always, if you lost it, i can send you the link again as email). i've discounted some of the less than productive stuff (meetings, setting up build systems)

**Comment by RobinSchmidt** [comment]
i have created a test-case for the "walking-wiggle" problem. two sines, the second at a frequency 9.9 times the "fundamental":
![image](https://user-images.githubusercontent.com/1833099/42241643-8f7bdec4-7f0b-11e8-95fa-c601be1b15db.png)
the wiggle approaches the zero line from below and walks through it. i may try to think about a solution without any more charge. ..but i'm not sure if there is any. cycle-mark finding is a somewhat ill defined problem when the signal is not strictly "cyclic"

**Comment by RobinSchmidt** [comment]
we could also try to *lowpass* in order to get rid of the wiggles....or lowpass and highpass to get rid of walking-wiggles *and* subharmonics/dc - but then we would approach the bandpass-at-fundamental (and find zeros) algorithm again

**Comment by elanhickler** [comment]
> we could also try to lowpass in order to get rid of the wiggles

No, that is chasing your tail. I'm starting to think waveform processing is more or less a waste of time.

**Comment by RobinSchmidt** [comment]
> Any time you do something to fix it in one case, it will break in another case.

yes, indeed. so, you said, the correlation-only based algorithm that doesn't use zero crossings at all, did not show *this* problem (but another one, namely the drift)?

as said above (in the edit) - i think, following the walking wiggles would actually imply drift, right? it's a question of the desired behavior. maybe we need to be more explicit about that

**Comment by RobinSchmidt** [comment]
this is really frustrating. i think i'll have to create a test-signal that clearly exposes the drift and experiment with that. i have 3 more ideas, how i could tweak the previous algorithm - but i need to make a good test-case. i won't charge for that

**Comment by RobinSchmidt** [comment]
can you tell me exactly what sample to look at and what settings to use to expose the drift?

**Comment by elanhickler** [comment]
SynthSustain`n=A2`rr=1

algorithm 1 or 2.

also why does your zero crossing algorithm not extract the fundamental? zero crossing is useless without getting as pure a sine as possible. FFT seems to work well for this. FFT is the way to go for extracting harmonics.

**Comment by RobinSchmidt** [comment]
> also why does your zero crossing algorithm not extract the fundamental?

the pure zero-crossing algo (0) does extract the fundamental. the hybrid algo (4) looks for a zero crossing near the correlation maximum in the original signal. otherwise, it wouldn't make sense to look for a correlation maximum at all. oh - wait - do you mean 3? 

btw. - i can see the issue with n=A2 rr=1 - and i don't think it's drift. one moment...

**Comment by RobinSchmidt** [comment]
between marker 18 and 20, it seems to jump from the 3rd-of-3 spikes to the 2nd-of-3 (algo 2):

![image](https://user-images.githubusercontent.com/1833099/42249193-45dabdde-7f2a-11e8-811b-71a4b4b4c775.png)

a similar jump occurs between markers 34-38, where it "jumps" from 2-of-3 to 1-of-3:

![image](https://user-images.githubusercontent.com/1833099/42249264-b76ee81c-7f2a-11e8-9cea-16004585ae78.png)

after that, it remains on 1-of-3 until the end. it doesn't "drift". if you look closely at the signal at marker 19 or at 35...37, you'll notice that the marker actually does not jump over to another spike but one spike disappears on the left while a new one comes up to the right. hmmm...

**Comment by RobinSchmidt** [comment]
hmmm....thinking about it - it is actually quite surprising that such a local feature like the dis/appearing of a little spike would bother the algorithm that much because the algorithm looks at a whole cycle and averages over that. but somehow it seems unlikely to be just a coincidence

**Comment by elanhickler** [comment]
no longer relevant
