### ISSUE TITLE
Allow for me the programmer to decide what mouse modifiers do what.

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#2]
Allow for me the programmer to decide what mouse modifiers do what.

We have the following actions:
* Set slider value (drag)
* Fine-tune (ctrl + mousewheel)
* Reset slider (ctrl+click
* Access slider menu (right click)
* Type in value (double click)

Missing:
* Change slider value according to mouse drag rather than jump to mouse
  * When you click on a slider the value moves to your mouse instead of waiting for you to drag. This can be annoying sometimes.

Use Case:
* To fix the above issue it would be better to have Set slider be assigned to shift, as a coarse tune and have unmodified mouse drag before for changing the slider with dragging.

**Comment by RobinSchmidt** [comment]
yeaahhh...ok...i see. "jump-to-new-mouse-position" seems undesirable. someone else also told me that recently. ok, i'll think i'll change that. but as for client code deciding such things...is subclassing an option? then you could override the mouse callbacks in your subclass

**Comment by elanhickler** [comment]
is subclassing an option? I don't know these things!  I was thinking more along the lines of:

object.MouseModifierForFineTune = hotkey
