### ISSUE TITLE
why does MonoSynth have no noteOff function?

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#20]
why does MonoSynth have no noteOff function?

it's very confusing to combine noteOn to and noteOff into one function called noteOn

**Comment by RobinSchmidt** [comment]
that's an artifact of the MIDI specification. in the spec, note-off events are (or can be) passed as note-on with velocity 0. of course, you could add a note off function - like when noteOn sees a velocity 0, call noteOff ...or something

**Comment by RobinSchmidt** [comment]
https://www.kvraudio.com/forum/viewtopic.php?p=4167096

**Comment by elanhickler** [comment]
what about midi note off velocity?

**Comment by RobinSchmidt** [comment]
oh - hmm... i think, there are two types of note-off messages. actual note-offs (which support note-off velocity) and these pseudo note-offs (note ons with zero vel, mainly introduced to save interface bandwidth back then in the 80s). i never used note-off velocity so far and considered it somehow an arcane feature. if you need it, i may have to change something down in my midi-event handling code in my framework (specifically in AudioModule::handleMidiEvent, iirc)

**Comment by elanhickler** [comment]
Can I help you design a synth prototype that can be reused?

Polyphony, legato modes, pitch glide styles, note on/ note off callbacks, other midi callbacks.

**Comment by RobinSchmidt** [comment]
maybe. i mean, i already have the rosic::PolyphonicInstrument class as baseclass for polyphonic instruments (which abstracts things like voice allocation, etc.). straightliner is a subclass of that. lot's of re-usable functionality is factored out into this class. but maybe it can be improved. to be honest. i'm actually not really happy at all with the way, polyphony is currently handled in my library. for every module that needs to be polyphonic (like an osc, filter, env, etc.) i'm currently keeping some kind of array of "slaves" - there's a "master" which has all the shared parameters and an array of "slaves" which have the state-variables of the voices. but it clutters up the library design...

**Comment by RobinSchmidt** [comment]
i need to find a way how to design dsp modules that are - by themselves - monophonic but can easily be made polyphonic, if one so wishes

**Comment by RobinSchmidt** [comment]
...because we don't want every little dsp class (like a 1-pole filter) be cluttered with polyphony handling code.

**Comment by RobinSchmidt** [comment]
the problem is, that you typically compose higher level dsp modules from lower level ones. like a chorus has delaylines, lfos, maybe filters, etc. ...at which level should you introduce the polyphony handling?

**Comment by elanhickler** [comment]
What if you designed a polyphony object that could be inserted at any level? And you insert it where needed when building an instrument. It is not predefined anywhere except the very top level.

**Comment by elanhickler** [comment]
hmmm... I would save leave polyphony only for the very top level. Maybe a solution is not obvious yet or will not be obvious or will just not be needed and we should be designing polyphony handling ourselves at lower level where needed.

**Comment by RobinSchmidt** [comment]
if i would make all the core dsp classes monophonic (oscs, filters, modulators, etc) and then build a whole monophonic synth from these ....and then, in order to make it polyphonic, just use an array of the monophonic synth class, i would duplicate a lot of data. that would perhaps be inefficient. think of a sample-based sound generator. a polyphonic one would just need to keep frequency and some state variables for each voice - all the sample data could be shared. i don't really know yet how to make a general design that avoids data redundancies and is easy to use in various contexts. currently, i just introduced the polyphony handling code in classes where it was needed - implying that it's not generally available and introduces overhead where it's not needed...hmmm...again a software engineering problem

**Comment by RobinSchmidt** [comment]
i think, at some point, i'll announce my library at kvr and then discuss such things with the folks there. maybe the "rosic" library can be a prototype, and step-by-step, i'll migrate classes over to the new template based "rapt" library - where we then have type independence and perhaps some new general design approaches

**Comment by RobinSchmidt** [comment]
i really want to get rid of that master/slave stuff currently present in BreakpointModulator (and some other classes)

**Comment by elanhickler** [comment]
how would you keep track of shared data? is that what a shared pointer is?

**Comment by RobinSchmidt** [comment]
yeah. you would somehow allocate the data (like a buffer of samples), and all users (i.e. the sample based oscs, for example) would keep a reference to the data. that's how the wavetable oscillators in straightliner work.  however, the idea of shared-pointers as in the STL also includes some automatic lifetime management of the data (i.e. automatic destruction when a reference counter goes to zero). i currently do that memory management manually. ...perhaps a bit old-school. maybe that can be improved/modernized as well.

**Comment by RobinSchmidt** [comment]
i'm not very familiar with more recent additions to the stl...as said - i need a c++11 book sometime soon

**Comment by elanhickler** [comment]
ask Christoph (HISE), he probably had to solve a lot of these things.

**Comment by RobinSchmidt** [comment]
ahh - yeah - it's even open-source: http://hise.audio/ ...nice. i'll probably get some inspiration with regard to general framework design. is he actually on kvr?

**Comment by elanhickler** [comment]
he makes dozens of posts to my questions and others on his own forum: http://forum.hise.audio/

I'm creating a HISE instrument for a client now.

**Comment by RobinSchmidt** [comment]
that hise project really looks interesting. maybe we can have some synergies in the future
