### ISSUE TITLE
Does your library have a transient detector?

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#201]
Does your library have a transient detector? We need it for OTS plugin.

**Comment by RobinSchmidt** [comment]
i have rosic::OnsetDetector. i made this some time long ago for a beat detector for a dj software for another client, so it's perhaps not optimal for the purpose here (what is the exact purpose, actually?)

**Comment by elanhickler** [comment]
To detect the start of a guitar pluck

**Comment by RobinSchmidt** [comment]
in what kind of sample? i assume, it can't be a one-shot guitar sample because then the transient is supposed to be at the beginning of the file anyway. so is it a sort of short phrase played on the guitar?

**Comment by RobinSchmidt** [comment]
the algorithm is based on this:

https://www.eecs.qmul.ac.uk/~simond/pub/2006/dafx.pdf

and in particular the "spectral-flux" measure (section 2.1). i also have some tweaks that weight low-frequencies stronger than high frequencies (seemed to suitable for full mixdowns - bassdrums are more important) - for guitar plucks, a stronger weighting toward high frequencies might be better.

i guess, i could also experiment with the other measures mentioned in the paper, so maybe it's more like a starting point

**Comment by elanhickler** [comment]
Hold off on continuing this discussion until further notice.

**Comment by elanhickler** [comment]
fail!
![image](https://user-images.githubusercontent.com/9116575/44828027-dc25ac00-abca-11e8-8f6d-fa849a84fc3c.png)

**Comment by elanhickler** [comment]
Is it helpful for this kind of algorithm to see multiple samples? does it not work as well for single samples?

**Comment by RobinSchmidt** [comment]
well, the algorithm was originally written to handle full mixdowns to mark the beats in a dj application (for syncing tracks, etc.) - so it expects a looong input file, chops it into blocks (size 1024 by default) with a "hop-size" of 128 (distance between (overlapping) block-starts). so this 128 hop-size defines the maximum time precision by which the transients can be detected ( about 3 ms at 44.1). that's perhaps not precise enough for this case. also, one-shot samples are typically already cut at the beginning so maybe we should prepend so silence. also, it seems, the algorithm is faaar too sensitive for your signals (so many false positives). i think, there is a threshold somewhere in the algorithm which we should adjust.

**Comment by RobinSchmidt** [comment]
> something based on the instantaneous envelope

i'm talking about things like explained here:

https://www.gaussianwaves.com/2017/04/extracting-instantaneous-amplitude-phase-frequency-hilbert-transform/

the article linked at the bottom, i just mark for later reading:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4003734/pdf/kja-18-1.pdf

**Comment by elanhickler** [comment]
the false positives are ok for now. they are low in strength and I can discard false positives that are not within "x window of time of the beginning of the sample"

I can feed it multiple samples at once but on the back end I know roughly where each sample starts and ends.

**Comment by elanhickler** [comment]
The first thing to do here would be to up the precision.

**Comment by elanhickler** [comment]
solved
