### ISSUE TITLE
problem saving patches with Chaosfly

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#203]
https://www.youtube.com/watch?v=QLTBs-IMtdA

![image](https://user-images.githubusercontent.com/9116575/43032431-736538bc-8c6b-11e8-8285-913a00d18511.png)

button settings are not getting saved right, oversampling works with the patch below:

```xml
<?xml version="1.0" encoding="UTF-8"?>

<Chaosfly PatchFormat="1" FMD_Freq="0.709635" FMD_Out="0.550781" FMD_Res="0.260417"
          Channel_Mode="Osc2" Gain="6" OutputClipLevel="1.47917" Feedback_Gain="-0.768229"
          Output_Osc1_Pre_Filter="0" Modulate_With_Osc1_Pre_Filter="1"
          Tune="30.1875" Octave="-2" Ratio="1.01199" ModDepth="10" Mod11="9.58333"
          Mod22="5.45833" Mod12="-20" Mod21="-1.41927" ModEnvDepth="1.0125"
          Filter1CutoffScale="0.544929" Filter1Mode="Lowpass 24 dB/oct"
          Filter2CutoffScale="200" Filter2Mode="Flat" InputToFeedback="0.109379"
          OscInDetune="-10" OscInAmplitude="0.726563" OscInWave="SawUp"
          Osc1FreqScale="0" Osc1ClipLevel="0.009375" Osc2FreqScale="0.0333333"
          Noise_HPF="6054.33">
  <MetaMapping>
    <FMD_Freq MetaIndex="0"/>
    <FMD_Res MetaIndex="1"/>
    <Tune MetaIndex="0"/>
    <Mod11 MetaIndex="1"/>
  </MetaMapping>
  <MetaParameterValues M0="0.70963537693023681641" M1="0.2604166865348815918"/>
  <RatioParameterMap>
    <Node X="0" Y="0"/>
    <Node X="1" Y="0.0041349533705683470808"/>
  </RatioParameterMap>
  <Mod11ParameterMap>
    <Node X="0" Y="1"/>
    <Node X="1" Y="0"/>
  </Mod11ParameterMap>
  <RatioParameterMap>
    <Node X="0" Y="0"/>
    <Node X="1" Y="0.0041349533705683470808"/>
  </RatioParameterMap>
  <RatioParameterMap>
    <Node X="0" Y="0"/>
    <Node X="1" Y="0.0041349533705683470808"/>
  </RatioParameterMap>
  <Mod11ParameterMap>
    <Node X="0" Y="1"/>
    <Node X="1" Y="0"/>
  </Mod11ParameterMap>
  <RatioParameterMap>
    <Node X="0" Y="0"/>
    <Node X="1" Y="0.0041349533705683470808"/>
  </RatioParameterMap>
  <ModEnv PatchFormat="1" GridX="1" GridY="1" ScaleFactor="1" Offset="0"
          TimeScale="1" TimeScaleByKey="0" TimeScaleByVel="0" Depth="1"
          DepthByKey="0" DepthByVel="0" SyncMode="0" LoopStartIndex="2"
          LoopEndIndex="3" LoopMode="Forward">
    <Breakpoint Time="0" Level="0" Shape="Analog" ShapeAmount="1"/>
    <Breakpoint Time="0.090983606557376972557" Level="0.50000000000000011102"
                Shape="Analog" ShapeAmount="1"/>
    <Breakpoint Time="1" Level="0.5" Shape="Analog" ShapeAmount="1"/>
    <Breakpoint Time="2" Level="0.5" Shape="Analog" ShapeAmount="1"/>
    <Breakpoint Time="3" Level="0" Shape="Analog" ShapeAmount="1"/>
  </ModEnv>
  <AmpEnv PatchFormat="1" GridX="1" GridY="1" ScaleFactor="1" Offset="0"
          TimeScale="1" TimeScaleByKey="0" TimeScaleByVel="0" Depth="1"
          DepthByKey="0" DepthByVel="0" SyncMode="0" LoopStartIndex="2"
          LoopEndIndex="3" LoopMode="Forward">
    <Breakpoint Time="0" Level="0" Shape="Analog" ShapeAmount="1"/>
    <Breakpoint Time="0" Level="1.007692307692307887" Shape="Analog" ShapeAmount="1"/>
    <Breakpoint Time="1" Level="1" Shape="Analog" ShapeAmount="1"/>
    <Breakpoint Time="2" Level="1" Shape="Analog" ShapeAmount="1"/>
    <Breakpoint Time="3" Level="0" Shape="Analog" ShapeAmount="1"/>
  </AmpEnv>
  <Curve1 PatchFormat="1" GridX="1" GridY="1" ScaleFactor="1" Offset="0"
          TimeScale="1" TimeScaleByKey="0" TimeScaleByVel="0" Depth="1"
          DepthByKey="0" DepthByVel="0" SyncMode="0" LoopStartIndex="0"
          LoopEndIndex="1" LoopMode="Off">
    <Breakpoint Time="0" Level="1" Shape="Analog" ShapeAmount="1"/>
    <Breakpoint Time="1" Level="1" Shape="Analog" ShapeAmount="1"/>
  </Curve1>
  <Curve2 PatchFormat="1" GridX="1" GridY="1" ScaleFactor="1" Offset="0"
          TimeScale="1" TimeScaleByKey="0" TimeScaleByVel="0" Depth="1"
          DepthByKey="0" DepthByVel="0" SyncMode="0" LoopStartIndex="0"
          LoopEndIndex="1" LoopMode="Off">
    <Breakpoint Time="0" Level="1" Shape="Analog" ShapeAmount="1"/>
    <Breakpoint Time="1" Level="1" Shape="Analog" ShapeAmount="1"/>
  </Curve2>
  <Curve3 PatchFormat="1" GridX="1" GridY="1" ScaleFactor="1" Offset="0"
          TimeScale="1" TimeScaleByKey="0" TimeScaleByVel="0" Depth="1"
          DepthByKey="0" DepthByVel="0" SyncMode="0" LoopStartIndex="0"
          LoopEndIndex="1" LoopMode="Off">
    <Breakpoint Time="0" Level="1" Shape="Analog" ShapeAmount="1"/>
    <Breakpoint Time="1" Level="1" Shape="Analog" ShapeAmount="1"/>
  </Curve3>
  <Curve4 PatchFormat="1" GridX="1" GridY="1" ScaleFactor="1" Offset="0"
          TimeScale="1" TimeScaleByKey="0" TimeScaleByVel="0" Depth="1"
          DepthByKey="0" DepthByVel="0" SyncMode="0" LoopStartIndex="0"
          LoopEndIndex="1" LoopMode="Off">
    <Breakpoint Time="0" Level="1" Shape="Analog" ShapeAmount="1"/>
    <Breakpoint Time="1" Level="1" Shape="Analog" ShapeAmount="1"/>
  </Curve4>
  <Curve5 PatchFormat="1" GridX="1" GridY="1" ScaleFactor="1" Offset="0"
          TimeScale="1" TimeScaleByKey="0" TimeScaleByVel="0" Depth="1"
          DepthByKey="0" DepthByVel="0" SyncMode="0" LoopStartIndex="0"
          LoopEndIndex="1" LoopMode="Off">
    <Breakpoint Time="0" Level="1" Shape="Analog" ShapeAmount="1"/>
    <Breakpoint Time="1" Level="1" Shape="Analog" ShapeAmount="1"/>
  </Curve5>
  <Curve6 PatchFormat="1" GridX="1" GridY="1" ScaleFactor="1" Offset="0"
          TimeScale="1" TimeScaleByKey="0" TimeScaleByVel="0" Depth="1"
          DepthByKey="0" DepthByVel="0" SyncMode="0" LoopStartIndex="0"
          LoopEndIndex="1" LoopMode="Off">
    <Breakpoint Time="0" Level="1" Shape="Analog" ShapeAmount="1"/>
    <Breakpoint Time="1" Level="1" Shape="Analog" ShapeAmount="1"/>
  </Curve6>
  <Curve7 PatchFormat="1" GridX="1" GridY="1" ScaleFactor="1" Offset="0"
          TimeScale="1" TimeScaleByKey="0" TimeScaleByVel="0" Depth="1"
          DepthByKey="0" DepthByVel="0" SyncMode="0" LoopStartIndex="0"
          LoopEndIndex="1" LoopMode="Off">
    <Breakpoint Time="0" Level="1" Shape="Analog" ShapeAmount="1"/>
    <Breakpoint Time="1" Level="1" Shape="Analog" ShapeAmount="1"/>
  </Curve7>
  <Curve8 PatchFormat="1" GridX="1" GridY="1" ScaleFactor="1" Offset="0"
          TimeScale="1" TimeScaleByKey="0" TimeScaleByVel="0" Depth="1"
          DepthByKey="0" DepthByVel="0" SyncMode="0" LoopStartIndex="0"
          LoopEndIndex="1" LoopMode="Off">
    <Breakpoint Time="0" Level="1" Shape="Analog" ShapeAmount="1"/>
    <Breakpoint Time="1" Level="1" Shape="Analog" ShapeAmount="1"/>
  </Curve8>
  <Curve9 PatchFormat="1" GridX="1" GridY="1" ScaleFactor="1" Offset="0"
          TimeScale="1" TimeScaleByKey="0" TimeScaleByVel="0" Depth="1"
          DepthByKey="0" DepthByVel="0" SyncMode="0" LoopStartIndex="0"
          LoopEndIndex="1" LoopMode="Off">
    <Breakpoint Time="0" Level="1" Shape="Analog" ShapeAmount="1"/>
    <Breakpoint Time="1" Level="1" Shape="Analog" ShapeAmount="1"/>
  </Curve9>
  <Curve10 PatchFormat="1" GridX="1" GridY="1" ScaleFactor="1" Offset="0"
           TimeScale="1" TimeScaleByKey="0" TimeScaleByVel="0" Depth="1"
           DepthByKey="0" DepthByVel="0" SyncMode="0" LoopStartIndex="0"
           LoopEndIndex="1" LoopMode="Off">
    <Breakpoint Time="0" Level="1" Shape="Analog" ShapeAmount="1"/>
    <Breakpoint Time="1" Level="1" Shape="Analog" ShapeAmount="1"/>
  </Curve10>
</Chaosfly>
```

**Comment by RobinSchmidt** [comment]
>  The logic should be: If saving default value, be sure to remove the current value in the state.

i don't understand that. "remove value from the state"? there is no value to remove. the state xml is built from scratch every time and if some parameter is at its default value, it simply doesn't get added.

> I might want to just activate "save all values all the time even if the value is default."
> What are the disadvantages of saving all values?

ok - i think, i'll make that optional. i just didn't want to blow up my xml files with all these "do-nothing" parameters which could potentially be many

**Comment by RobinSchmidt** [comment]
actually, i think, my reasoning was: if some value is missing in the xml, the parameter should take its default value which i assume to be some sort of neutral setting - which makes sense if you later extend the parameter set and want to load old patches that don't have a value for the new parameters (think of a phase-offset in an osc or something). and if that behavior can be assumed, there is no need to store default values. ...makes patches also easier to read by humans - less distractions

**Comment by elanhickler** [comment]
so back to the original problem: why can I not save an oversampling value of 1 (default)? did you watch the video? I show that saving a patch with oversampling 1 then loading it again... well... when saving the patch, it doesn't write oversampling of 4 as if the xml is **not** created from scratch

**Comment by RobinSchmidt** [comment]
whoa - that is weird indeed. so it writes a value of 4 into to the file even though the actual setting is 1? can i pull your repo and build chaosfly to check that myself? or does it also happen in toolchain somewhere?

**Comment by elanhickler** [comment]
you'd have to test with chaosfly using the provided patch in the 2nd post.

**Comment by elanhickler** [comment]
I want to work on my FMD prototype tomorrow. Can you have a solution for me tomorrow? Just need to be able to save/recall patches! Can't get anywhere without that function. 👍

**Comment by RobinSchmidt** [comment]
i tried to load your patch - it correctly set the oversampling to 4 here (i hit a jassert related to drawing at invalid pixel coordinates, when i load it though). tried to set oversampling manually back to 1 and load the patch again - it gets set correctly back to 4 ...hmmm...i also made two test patches myself. using default settings and 1 and 4 for oversampling and tried to load them...works as expected here (i built the 64-bit debug version with the default toolset, btw.)

**Comment by RobinSchmidt** [comment]
...wait...when i load the patch with 4, set it back to 1 and the save again, it becomes 4...what?

**Comment by RobinSchmidt** [comment]
ok - this is really mysterious and i couldn't really figure it out right now. are you sure, this is my bug? anyway - instead, i have made it possible to save parameter values to xml, even when they are at their default values. ...and using that option seems to solve the problem. all you have to do is to somewhere in your code call `jura::Parameter::setStoreDefaultValuesToXml(true);` - this switches saving of default values globally on, for all parameter objects (it's controlled via a static flag in class Parameter)

**Comment by elanhickler** [comment]
yes, that's the problem.

**Comment by RobinSchmidt** [comment]
> I'm running into a patch saving bug with Chaosfly again! This time I can't save the automation graph.
> image
> 
> PATCH: noisy FMD filter.txt (rename as xml)

i think, this belongs here.  inspecting the xml-file, i see that there are several elements with the same tag-name, like this:
```xml
  <RatioParameterMap>
    <Node X="0" Y="0"/>
    <Node X="1" Y="0.0041349533705683470808"/>
  </RatioParameterMap>
```
appears several times when there should be only one. when i look at the code in ChaosflyModule::createParameters, i see this:
```cpp
 Ratio.initSlider("Ratio", 1/64.0, 64, 1);
 //...
 parCompRatio.initSlider("Ratio", 1, 40, 1);
```
so could it be that you create several parameters with the same name (inside the same AudioModule)? if so, this will not work because parameters are identified by their names in the xml, so the patch saving code will overwrite the xml attribute with the last parameter value that has a given name. parameter names (within a given AudioModule) must be unique. you can have parameters of the same name inside a submodule, though - i.e. if the compressor is a submodule it may have a parameter named "Ratio"

**Comment by RobinSchmidt** [comment]
btw - did `jura::Parameter::setStoreDefaultValuesToXml(true);` help with the other problem?

**Comment by elanhickler** [comment]
Yes! And I will recheck all components to make sure I'm not giving things the same name. Maybe I'll put in a debug error checking for that.

**Comment by RobinSchmidt** [comment]
yes that's a good idea. i may even put that into the framework...something like
jassert(areParameterNamesDistinct()) at the beginning of getStateasXml or something...but the check might be expensive (should scale with N^2 where N is the number of parameters)

**Comment by elanhickler** [comment]
Here, I threw together a duplicate checker, works! For your duplicate checker I'd wait until going through all parameters before throwing an exception so that we can see all the duplicates at once instead of through an exception after just the first duplicate... or maybe that's overkill.

![image](https://user-images.githubusercontent.com/9116575/43481371-a6685044-94ba-11e8-93e8-08f7d1d65f86.png)

**Comment by RobinSchmidt** [comment]
>  still can't save Ratio's automation graph when it uses the default 0 to 1 points. It does save the automation graph if a point is not default.

yes, that's intentional. when it only has the default points, nothing is saved. and if - on recall - nothing is found in the xml, the curve gets initialized with the default points. does the init-to-defaults not work?

**Comment by RobinSchmidt** [comment]
the idea is: as long as the graph uses default settings, there's no need to store the map. otherwise, the xml would be swamped wit all these identity maps.

i dragged in your update....hmm...when saving the xml, i still get two RatioParameterMaps...hmm..

**Comment by RobinSchmidt** [comment]
i added a debug check in my framework - whenever you add a new parameter, it checks, if a parameter with the same name already exists and triggers a jassert, if it does. ....aaaand it looks like it gets triggered *a lot* in chaosfly. looks almost like you are creating/adding every parameter (at least) twice or something? :-O

**Comment by elanhickler** [comment]
I know defaults are not saved. But the old value continues to be there.

**Comment by elanhickler** [comment]
Does the new debug check NOT get triggered with your other plugins? You should make sure.

**Comment by RobinSchmidt** [comment]
yes - i tried with toolchain. didn't get triggered

**Comment by RobinSchmidt** [comment]
why do have all these duplicate parameters? this seems very wrong to me and goes totally against how the framework is supposed to work

**Comment by elanhickler** [comment]
yep i was instantiating every parameter twice. I had a relic of old code that I forgot to remove..... dam. FIXED.
