### ISSUE TITLE
missing functions

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#204]
where did these go?

![image](https://user-images.githubusercontent.com/9116575/43050241-3a0ebf66-8dba-11e8-8928-1fb2c08965b6.png)

**Comment by elanhickler** [comment]
![image](https://user-images.githubusercontent.com/9116575/43050315-9d011852-8dbb-11e8-900f-785ac6b63584.png)

**Comment by elanhickler** [comment]
![image](https://user-images.githubusercontent.com/9116575/43050329-bffa2614-8dbb-11e8-99b5-5529608f4891.png)

**Comment by elanhickler** [comment]
rsInstantaneousFundamentalEstimator::measureInstantaneousFundamental
rsRecreateSine
rsZeroCrossingFinder
rsSinePhaseAt
rsSineShiftAmount

**Comment by RobinSchmidt** [comment]
these are all functions that i wrote back then in the context of RSLib but i actually think that i dragged them all over already. many are in Resampler.h and AudioFunctions.h. are you perhaps missing the RAPT namespace?

**Comment by elanhickler** [comment]
rslib include was not found.
