### ISSUE TITLE
Modulation system for multidimensional macro parameters

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#205]
Here's an explanation.

![image](https://user-images.githubusercontent.com/9116575/43353515-60a65dd0-91ef-11e8-880a-91b2f47aeef2.png)

For FMD, for frequency-scaled resonance the connection would look like this:

FMD Frequency (DC offset mod source) -> Mod Range of -72 to +72 -> Chaosfly Tune (filter frequency)

FMD Frequency (DC offset mod source) -> Inverted Mod Range of +3 to -3 -> Chaosfly Mod Amt (filter resonance)

FMD Resonance (DC offset mod source) -> Mod Range of -5 to +5 -> Chaosfly Mod Amt (filter resonance)

When I turn up FMD Frequency, it decreases Mod Amt (resonance). When I turn up FMD Resonance it increases Mod Amt. Naturally, the values are accumulated for a final Mod Amt value.

Now I want to have a "frequency-scaled resonance amount control."

FMD Frequency (DC offset mod source) -> Inverted Mod Range of +3 to -3 -> DC offset mod source with an amplitude control

Frequeny-Scaled-Resonance (DC offset mod source) -> DC Offset amplitude control

 DC offset mod source with an amplitude control -> Chaosfly Tune (filter frequency)

ooh that's confusing... hmm... maybe it would be better to invest in a fully modular (with visible wiring) system or perhaps find a program that already does this... or possibly do some hard coded connections. Ok, need to think about this more. This is really just for prototyping.

**Comment by RobinSchmidt** [comment]
yes! i see. i think, we need to slap in the same (or similar) mapper that we now use for meta-mapping on each modulation connection as well. i guess, most of the code we are using for meta-mapping can be (more or less) directly re-used for this (maybe some refactoring is needed)

**Comment by elanhickler** [comment]
solved
