### ISSUE TITLE
Bouncillator

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#206]
Here's the previous issue with formulas and such: https://github.com/RobinSchmidt/RS-MET/issues/80

I created a plugin for this, see: `Soundemote\AudioPlugins\Envelope Submodule` , compile for your testing.

![image](https://user-images.githubusercontent.com/9116575/43370841-525b355a-933b-11e8-8ca3-44578ab3e00a.png)

Could you work on this when you have some spare minutes? I'll pay for this as well. Start with these, these should be easy:

1. Need a "setSampleRate" function so that when I increase oversampling, the frequency remains relatively the same. It might not remain perfectly the same, that's ok.

1. Can you make it so that when increment/decrement speed is changed, the update happens right away? Currently, updates only happen after a reflection.

1. When Floor/Ceiling are equal, we get infinite hang.

OR do you have a new idea for a bouncillator and want to start over? Let me restate the goals just in case:

 * An envelope generator with modulatable shape and timing
 * Does not suffer from frequency quantization at high frequencies due to sample rate limit.
 * Lin/Log/Exp/Exp*2/S-curve shapes
 * Currently Bouncillator suffers from control issues, increasing timing decreases exponential shape.

**Comment by RobinSchmidt** [comment]
should it be some sort of mix between oscillator and envelope generator, like something that procudes a periodic succession of attack and decay curves attack-decay-attack-decay-....

**Comment by RobinSchmidt** [comment]
i mean, the basic bouncillator actually produces a sort of asymmetric triangle/sawtooth waveform - basically, the "TriSaw" waveform for which we already have code. various shape could be introduced by just passing the TriSaw wavefrom through suitable waveshaper ...but maybe not just a simple waveshaper but one that applies a different shaping function to the upward and downward parts - it should be easy too keep track of where we are and just switch between two functions for attack and decay

**Comment by RobinSchmidt** [comment]
my idea is to just start with TriSaw waveform:
![image](https://user-images.githubusercontent.com/1833099/43691951-75afec10-9923-11e8-8987-ddae2b74f20d.png)
(you can imagine this to oscillate between 0..1, too). and then apply separate waveshaping curvers to up and down sections, maybe functions of such a kind:
![image](https://user-images.githubusercontent.com/1833099/43691957-7fa23c6e-9923-11e8-91ca-b3b9e124b087.png)
for the sigmoid shape and just one half of them for the (pseudo) exp/anti-exp shape

**Comment by elanhickler** [comment]
You cannot use an oscillator because of the floor/ceiling paradigm. Envelope generator is a time-based/trigger based function with "speed" instead of "frequency". You can't use an oscillator paradigm because: what if the user modulates ceiling down as the envelope is rising up. You need to know when the signal hits the ceiling to then bounce off or go to decay phase. How would you simulate that with an oscillator?

**Comment by RobinSchmidt** [comment]
to modulate floor and ceiling, i would just take the osc-output, scale it with a factor and add a DC offset. of course, the response to such a modulation would be different than here, but i would actually think, in a way that's preferable since the timing of hitting floor and ceil would be naturally decoupled from the values of floor and ceil

**Comment by elanhickler** [comment]
I want the timing to be coupled. I'd want attack time or speed vs decay time or speed like an envelope, not an attack/decay ratio.

**Comment by RobinSchmidt** [comment]
i just edited my former reply. i think, you could re-couple them by scaling oscillator increments by the difference ceil-floor

**Comment by RobinSchmidt** [comment]
so, it's mostly about different parametrizations, i.e. what is coupled vs what is decoupled. but i think, all such couplings/decouplings can also be achieved in the oscillator with a little bit of trickery

**Comment by elanhickler** [comment]
It needs to be non-loopable as well like a normal ADSR. I need to modulate shape for example, go from expo to Lin on decay. The difference between oscillator and envelope is that with oscillator you know where you are based on phase. With envelope you don't know, like, you modulate parameters and you would not know when you will hit the floor or ceiling until you cross the threshold

**Comment by elanhickler** [comment]
Maybe it's ok to use a shapable oscillator. I am just concerned that modulation will not produce the desired effect.

**Comment by elanhickler** [comment]
Oops. Didn't mean to close. Another example of the problem, oh this may be THE problem with an oscillator. What if you change attack time while in decay stage? Wouldn't the decay stage be affected because you are recalculating the entire signal / shape?

**Comment by RobinSchmidt** [comment]
hmmm...well...yeah - it's certainly a different parametrization, but as said, with some little tweaks and formulas, i would think, that we can translate one parameterization into another. i just don't know what exactly the desired effects are. ...i mean, for example, should the distance between floor and ceiling affect the timing or not. normally, in bouncillator, tha farther they are apart, the longer it takes to go from one to another with a given speed/increment. ...may be a desirable effect - or not. depending on the application. but it should be straightforward to implement it one or the other way or both

> What if you change attack time while in decay stage? Wouldn't the decay stage be affected because you are recalculating the entire signal / shape?

i think so, yes. hmm...but maybe i can find a tweak for that, too. how do you actually achieve non-looped envelopes in bouncillator? i mean, it repeats itself over and over again as well.

the thing is, this whole "predict-when-to-hit-the-wall" leads to a horribly messy (and expensive) formula in the case of a curved transition. and the curve isn't even very flexible yet

**Comment by elanhickler** [comment]
An oscillator might work........

**Comment by elanhickler** [comment]
Ok let's try an oscillator. As long as you can seamlessly switch between loopable and non loopable with it.

**Comment by elanhickler** [comment]
OH WAIT. Can you modulate frequency to 0 to induce sustain? Yes it should work. So sustain would be a matter of "how fast to go to 0hz" instead of exact sustain level. When you increase decay time, the curve down to 0hz needs to scale with decay time.

**Comment by elanhickler** [comment]
Hmm the problem with going to 0hz for sustain is that if the attack phase is near instant and you wanted a sustain level of 100% the signal would be in decay phase a bit before 0hz could be reached. The faster the attack phase the more unpredictable the sustain level.

**Comment by elanhickler** [comment]
wait wait wait. first of all, why does attack/decay time on bouncillator only update after bounce?

**Comment by elanhickler** [comment]
Definitely fix the increment/decrement not updating, I think we are not done exploring this.

TriSaw parameters:
- attack time
- decay time
- full envelope time scaler
- attack shape (either seamless exp/lin/log or a switch + curvature)
- decay shape

**Comment by RobinSchmidt** [comment]
yes - i've already started with this, just need to fill in a few things. i'm currently exploring some functions that could be useful for the shapes. i used your one-parametric rational mapping function as starting point but i want to introduce a second parameter that somehow controls the s-shape. ...it's a bit of exploration and trial-and-error...but i have a good candidate already....need to walk through some math to get a nice and convenient parametrization. i want to make it seamless

**Comment by RobinSchmidt** [comment]
...maybe something like this:
https://www.desmos.com/calculator/lhk7brjm9h
with b=0, it *is* the well-known bilinear rational mapping with "a" being the curvature parameter. ...i'm not yet happy with the behavior of "b"....needs more experimentation

**Comment by RobinSchmidt** [comment]
this seems nice:
https://www.desmos.com/calculator/hfjkrggqye

**Comment by RobinSchmidt** [comment]
ok, there's a new TriSawOscillator module available in ToolChain (under Sources) that can be used to experiment with the various parameters. it's currently working with the parametrization suitable for an osc (frequency and asymmetry) (set the frequency by hitting a midi note). that's good for experimenting. i think, i'll do the re-parametrization via attack/decay times in a subclass, so we can use the baseclass as regular osc. it can even do pulsewave without any further ado like introducing clippers - by setting bot bending parameters to full scale (1 or -1) and asymmetry for pulse-width. ...but maybe with an additional clipper, we can do even more useful shapes...dunno....but such a thing could be useful for hold/sustain stuff...

**Comment by elanhickler** [comment]
Ok, we need attack/decay time parameters for TriSaw and fix the Bouncillator update problem and you are done with Envelope-related stuff for now. I need to experiment now.

What I am beginning to think about is to create envelope SPECIFICALLY for a use case rather than, with bouncillator or TriSaw, trying to fulfill everything in one. Example: I may want your help creating a "pluck/guitar" envelope where the attack is expo, decay is expo then transitions to linear, where parameters would be:

PLUCK ENVELOPE
- pluckyness (some kind of attack/decay shape)
- sustain (how fast decay goes from expo to linear)
- release (the release is actually a log shape)
- overall full envelope speed to make it easy to go from "heavy string muting" type envelopes to "open string" type envelopes.
- loop on/off

REED ENVELOPE
- S shape attack with parameter for how long it takes to go into its log portion
- Sustain level (this is where I want a smooth transition to sustain somehow)
- S or log shape release

Then we can really hone in, finely craft the parameters and equations, come up with new ways to create really nice envelopes that are smooth, organic, and responsive.

![image](https://user-images.githubusercontent.com/9116575/43791111-781284f2-9a29-11e8-9614-4c9b42757bb6.png)

**Comment by elanhickler** [comment]
By modulating decay speed by hand I was able to achieve this desired shape, which I want for my Pluck envelope:

![image](https://user-images.githubusercontent.com/9116575/43852274-a9efca66-9af1-11e8-9b70-c4c644691d7f.png)

The next step for Bouncillator is the get expo attack expo decay. Right now it's expo attack log decay or vice versa.

OH LOOK!

![image](https://user-images.githubusercontent.com/9116575/43853259-7b4430c8-9af4-11e8-8d5f-ca53ff6c8c93.png)

I just registered a feedback modulation to the modulation manager and by messing with limits of the feedback modulation I am getting a number of useful curves on the decay. I also used negative feedback on the attack to create the exponential attack.

**Comment by RobinSchmidt** [comment]
> Definitely fix the increment/decrement not updating, I think we are not done exploring this.

fixed already yesterday. should work now.

> TriSaw parameters:
> 
> attack time
> decay time
> full envelope time scaler

there's now a class rsTriSawModulator in rosic that is set up in terms of these parameters. i also has adjustable floor/ceil

**Comment by elanhickler** [comment]
Can you enable those things in Toolchain so I can test quickly?

**Comment by RobinSchmidt** [comment]
do you mean, i should add the TriSawModulator as modulation source in toolchain?...because for the TriSawOscillator it wouldn't make sense to replace frequency and asymmetry with attack/decay. you also wouldn't be able to do feedback modulation in this case

**Comment by RobinSchmidt** [comment]
ok, i'll do it

**Comment by RobinSchmidt** [comment]
done. it's under Modulators. there seems to be bug with the TimeScale parameter...

**Comment by elanhickler** [comment]
uhhhhhh I need the output, I'm not using it as a modulator yet.

**Comment by elanhickler** [comment]
ok im getting output by modulation DebugAudioModule. All good! Yes except for time scale.

**Comment by RobinSchmidt** [comment]
TimeScale is fixed and i'm having some fun already! :-)
```xml
<?xml version="1.0" encoding="UTF-8"?>

<ToolChain PatchFormat="1" ActiveSlot="1">
  <Slot Type="TriSawOscillator">
    <Slot1-TriSawOscillator PatchFormat="1" AttackSigmoid="0.5" DecaySigmoid="0.585227"/>
  </Slot>
  <Slot Type="Limiter">
    <Slot2-Limiter PatchFormat="1" OutLevel="-7"/>
  </Slot>
  <Slot Type="TriSawModulator">
    <Slot3-TriSawModulator PatchFormat="1" Attack="53.367" Decay="519.887" TimeScale="2.43424"/>
  </Slot>
  <Slot Type="None">
    <Slot4-None PatchFormat="1"/>
  </Slot>
  <Modulations>
    <Connection Source="Slot3-TriSawModulator" Target="Slot1-TriSawOscillator.Asymmetry"
                Depth="0.66964285714285787243" DepthMin="-1" DepthMax="1" Mode="Absolute"/>
    <Connection Source="Slot3-TriSawModulator" Target="Slot3-TriSawModulator.Floor"
                Depth="0.2946428571428572063" DepthMin="-1" DepthMax="1" Mode="Absolute"/>
    <Connection Source="Slot3-TriSawModulator" Target="Slot3-TriSawModulator.Ceiling"
                Depth="0.40178571428571463464" DepthMin="-1" DepthMax="1" Mode="Absolute"/>
    <Connection Source="Slot3-TriSawModulator" Target="Slot3-TriSawModulator.TimeScale"
                Depth="-0.72321428571428603149" DepthMin="-1" DepthMax="1" Mode="Absolute"/>
  </Modulations>
</ToolChain>
```

...will add missing shape parameters now

**Comment by RobinSchmidt** [comment]
shape parameters added (took so long to upload because i was distracted by playing with the new toys)

**Comment by elanhickler** [comment]
good. what are you playing with? that same patch above?

**Comment by elanhickler** [comment]
no longer relevant and will revisit topic elsewhere.
