### ISSUE TITLE
Modular Framework idea

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#207]
see image:

![image](https://user-images.githubusercontent.com/9116575/43371162-27805e4a-9341-11e8-8c45-880948e016c9.png)

**Comment by RobinSchmidt** [comment]
hmmm...would the user be supposed to arrange the modules in the editor two times - once for the collapsed and once for the full view?

**Comment by RobinSchmidt** [comment]
but i like how it combines sliders and modulation inputs - use the sliders when you only need fixed values and use the inputs only when you actually want modulations

**Comment by elanhickler** [comment]
Yeah maybe... I can think about it more.
