### ISSUE TITLE
How do you get midi aftertouch?

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#21]
Is there a function you have to get midi aftertouch value?

**Comment by RobinSchmidt** [comment]
i currently don't handle aftertouch in my library. i think, it would involve to change 

`void AudioModuleWithMidiIn::handleMidiMessage(MidiMessage message)`

look at the method definition. it's the general callback function to handle any kind of midi message. it then dispatches to more specialized callback functions like noteOn, setMidiController, etc.. you could introduce another callback setAfterTouch (or handleAfterTouch or whatever), augment the dispatcher method (handleMidiEvent) and then override your new aftertouch handler method in the particular instrument subclass

**Comment by RobinSchmidt** [comment]
by the way, you can also override handleMidiMessage itself in your synth subclass. then you would get ALL midi messages and could do all the dispatching/handling yourself in your overriden function
