### ISSUE TITLE
Debug module for ToolChain only appears in debug mode

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#214]
![image](https://user-images.githubusercontent.com/9116575/44623408-74e1c200-a881-11e8-8540-e8788b8157e5.png)

could you have this module appear in release mode as well? it's the only way to hear modulator output, by modulating the left/right DC sliders.

**Comment by RobinSchmidt** [comment]
> Debug module [..] only appears in debug mode

yeah - that's kinda the point ;-)

**Comment by elanhickler** [comment]
I need a way to hear modulator output.

**Comment by elanhickler** [comment]
i guess i can just run debug mode, I don't use toolchain for anything serious so I don't actually need to be in release mode... well... I will want to use Liberty seriously at some point for analog-style filter design.

**Comment by elanhickler** [comment]
well if I'm using Liberty then maybe I can just make you add my needed modules there, it's easy to send the output of anything to the liberty final output sooooooooooo whatever.

**Comment by RobinSchmidt** [comment]
i think, i must somehow make the liberty parameter modules modulatable via our modulation system. that would be cool
