### ISSUE TITLE
OrangeTreeSamples needs function "get spectral energy peak"

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#215]
![image](https://user-images.githubusercontent.com/9116575/44624248-9a7cc480-a89d-11e8-9510-ac8751fb58d8.png)

OrangeTreeSamples wants an automated way to find that spectral peak as accurately as possible. It might be the same as transient detection, but it should not depend on the waveform as any waveform peaks will not reveal the actual peak due to resonances / imperfect phase of harmonics messing with where the peak lands,

![image](https://user-images.githubusercontent.com/9116575/44624322-c7ca7200-a89f-11e8-9c22-5e566454c9f7.png)

**Comment by RobinSchmidt** [comment]
spectral peak? with that i usually mean the strongest/loudest frequency in an fft plot. but you seem to be talking about transients and spectrograms. maybe my onset detector can be used as starting point. what is the use case?

**Comment by elanhickler** [comment]
the use case is to get the same spectral peak across guitar pluck samples to automate sample cutting.

the spectral peak would be the exact location of the highest energy which is the point of plucking the string.

ok, what is the onset detector class and where is it in the library?

**Comment by elanhickler** [comment]
looks liike I made a similar thread here: https://github.com/RobinSchmidt/RS-MET/issues/201

**Comment by RobinSchmidt** [comment]
yes - so you want to detect the onsets of the individual guitar plucks? your usage of the term "spectral peak" was really confusing me. to me, this is a spectral peak:
![image](https://user-images.githubusercontent.com/1833099/44723757-2f1b3880-aad1-11e8-940a-0b3ee615c6a3.png)
you seem to be talking about time instants, where the total spectral energy has a maximum?

**Comment by elanhickler** [comment]
ok, yes, I mean peak of spectral energy, when energy is at the maximum. im going to close this thread so we can discuss in the other one
