### ISSUE TITLE
Need a total reset for patch changes

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#217]
Working on FMD and I'm noticing patches sometimes don't sound right until I do a total plugin reset (unload/reload).

Right now I'm resetting Chaosfly filter1, filter2, fbfilter (bandpass filter), osc1, osc2, inputOsc, I don't know what else to reset.

Can you think of a way to induce a full plugin reload or something?

**Comment by RobinSchmidt** [comment]
this sounds like a bug. maybe the reset is somehow incomplete? did you check the state-variables of all dsp-objects in the debugger (filter states, osc-phases, etc.)? or some parameters are for whatever reason not set to their correct values. i guess, i may introduce some function that calls all resets and also sets back all the parameters to their default values. but that sounds more like a workaround than a fix

**Comment by elanhickler** [comment]
yes it may be a workaround, ill have to do a more thorough check of variables. The nature of FMD is that the state of things can screw up the feedback mechanisms that create the desired filter. Sensitive to initial conditions or something.

**Comment by elanhickler** [comment]
I found the bug. It has to do with the metaparameter system. The automation graphs are not updated... or the current value based on the graph of the new patch is not loaded.

**Comment by RobinSchmidt** [comment]
can you give me an example patch so i can give it a spin in the debugger myself? 

> 1) load the patch. 2) re-load the plugin. 3) load the patch again.

this is really weird. whatever you do before reloading the plugin should not have any impact. i assume that reloading means that the old plugin object is deleted and a fresh one is created (but may that's not the case? ..but that would be weird)

**Comment by elanhickler** [comment]
ok let's fix these bugs one at a time, fixing this could solve everything or just be a good first step:

![image](https://user-images.githubusercontent.com/9116575/44737882-0468ba00-aaa8-11e8-82f8-97137547aea2.png)

1. use exponential automation graph on some parameter
2. do not attach to metaparameter
3. save
4. load
5. move said parameter and notice the slider is no concurrent with the value.

```xml
<?xml version="1.0" encoding="UTF-8"?>

<ToolChain PatchFormat="1" ActiveSlot="1">
  <MetaParameterValues M0="0.082631833851337432861"/>
  <Slot Type="TriSawOscillator">
    <Slot1-TriSawOscillator PatchFormat="1" Asymmetry="-0.0356921">
      <AsymmetryParameterMap>
        <Node X="0" Y="1" Shape="Exponential" ShapeParameter="-0.15338028169014061852"/>
        <Node X="1" Y="0" Shape="Exponential" ShapeParameter="0.97605633802816904598"/>
      </AsymmetryParameterMap>
    </Slot1-TriSawOscillator>
  </Slot>
  <Slot Type="None">
    <Slot2-None PatchFormat="1"/>
  </Slot>
</ToolChain>
```

**Comment by elanhickler** [comment]
see the value jump:

![image](https://puu.sh/BlPvM/1d19532cac.gif)

**Comment by RobinSchmidt** [comment]
i will look into this tomorrow. i was just very busy with trying to continue with my old attempts of getting a higher order (> 6dB/oct) perfect reconstruction IIR splitter to work (and had to add some tools to my toolkit for this research). i think, i made some mistake back then and think i'm on a good track now

**Comment by RobinSchmidt** [comment]
damn! yes i can reproduce this. i will try to figure it out...

**Comment by RobinSchmidt** [comment]
oh fuck! i think, we have a fundamental flaw in how parameters are saved and restored. Parameter::saveToXml, Parameter::recallFromXml just store the current value via getValue/setValue. this was good enough at the time when there was only the internal (invertible) mapping. but since we have the free, user-adjustable, custom (and possibly non-invertible) mapping, i can't just store and retrieve the value from the xml. do you remember, when i said, i need to keep track of the parameter's normalized value at all times (and can't just rely on inverse mapping)? of course, that applies to save/recall, too. i somehow need to store the normalized value in the xml, when there's a user-defined mapping. duh!

**Comment by RobinSchmidt** [comment]
>  ....i try to take into account what a user who manually edits the xml would expect to produce as little surprises as possible in such a case

maybe i actually should store the redundant values. when the user deletes the meta-mapping from the xml, the redundantly stored value in the map would still be there to recall the value. and if the user deletes the map, the redundantly stored parameter attribute "Asymmetry="-0.0356921"  would still hold the value. but: when the user edits it, to say "Asymmetry="0.5", then, in the recalled patch, it would be inconsistent with the stored normalized values and they would then override this setting. hmmmm....

**Comment by RobinSchmidt** [comment]
i tend to think that inconsistencies are worse than loosing values. when the user deletes the map and there is no attribute for the parameter stored. they should not be too surprised, when the respective parameter reverts to default, when loading the patch

**Comment by RobinSchmidt** [comment]
ooookayy. i made the change to MetaControlledParameter::saveToXml/recallFromXml as i said (avoid redundant storage of anything). it seems to work now. at least when you freshly save the patch. the way i do it now may break the loading of old patches that rely on the (final, mapped) value of the parameter stored as attribute (because i don't look for that attribute anymore, when there's a map). do you have any patches that rely on this...but actually, as i think about, those are precisely the sort of patches that would not have worked anyway due to the bug...however - i guess it's a good idea to do some more tests now

**Comment by elanhickler** [comment]
![image](https://user-images.githubusercontent.com/9116575/44944671-c1e8fb00-ad8f-11e8-91c1-c73f0f86dcbb.png)

1. create a patch like this
2. double click asymmetry to open the keyboard input dialog and simply press enter. do this multiple times. Each time you press enter, the value changes.

**Comment by RobinSchmidt** [comment]
ah - ok - i see. it's because of this:
```cpp
template<class T>
T rsNodeBasedFunction<T>::applyInverseFunction(T y)
{
  return y; // preliminary
}
```
...the implementation is still missing. i will try to add it...

**Comment by RobinSchmidt** [comment]
done. isn't that neat?:
```cpp
template<class T>
T rsNodeBasedFunction<T>::applyInverseFunction(T y)
{
  return rsRootFinder<T>::falsePosition(std::function<T(T)>(*this), getMinX(), getMaxX(), y);
}
```
i love it when the different parts of the codebase work together like clockwork

**Comment by elanhickler** [comment]
I think we can close this thread, patch loading for FMD seems to be working.
