### ISSUE TITLE
How do you call resized()?

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#22]
I have if statements to set controls visible in the resize callback to show or hide things. When I set a modulation target I want to call a resized.

**Comment by RobinSchmidt** [comment]
i call it like this: 

`resized();`

;-) ..well, i guess i don't understand the question. you just call it. or are you outside the editor class, when the setting of the mod-target happens? but why do you put that if-statement into the resized function at all. i think, the cleaner way would be to make a dedicated "updateWidgetVisibility" function, or something like that

**Comment by elanhickler** [comment]
I cannot find anywhere to call resized based on a gui event. It seems impossible.

**Comment by elanhickler** [comment]
Are you checking your e-mails? I could really use your help to clear the last few issues. I want to get an update out on June 1st.

**Comment by RobinSchmidt** [comment]
how do you set the modulation target? is this a combobox? if so, the proper place to do the update would be in the combo-box callback. but there you should probably to the update based on a state-variable/parameter that is part of the underlying "AudioModule" - so it works also on preset-load etc (when you don't get combobox callbacks).

i'm a bit busy right now with straightening out issues with my library. i thought, we are "on hold" at the moment?

**Comment by elanhickler** [comment]
We are on hold in terms me paying you monthly for tons of work, but you're too busy just to help me for 30 minutes online to get through the last few issues I'm having with your framework?

**Comment by elanhickler** [comment]
also I said I will pay for your time. $30 an hour for an online meeting or whatever you are charging it a lot less than $1000 per month of work.
