### ISSUE TITLE
Can you make a knob mouse drag for me? (knob discussion)

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#220]
Here is your slider drag code. I need two differences. 

1. needs to be based on Y-plane instead of horizontal X-plane.
2. needs to not be based on knob size, i.e. each pixel needs to be a fixed amount of value increase.

Edit: I edited this code already, seems to work:
```cpp
void RSlider::mouseDrag(const MouseEvent& e)
{
  if( e.originalComponent != this )
    return; // ignore drag on the label, when it's not 'inside' the actual slider

  //double scale = 0.01; // 1% change per pixel
  double scale = .005;
  if(ModifierKeys::getCurrentModifiers().isShiftDown()) // fine tuning via shift
    scale *= 0.0625;

  if( isEnabled() )
  {
    if( !e.mods.isRightButtonDown() && !e.mods.isCommandDown() )
    {

      // new, handles press/release of shift during drag correctly:
      int newDragDistance = e.getDistanceFromDragStartY();
      int dragDelta       = newDragDistance - oldDragDistance;
      oldDragDistance     = newDragDistance;  // update - from now on we only need dragDelta
      dragValue += scale*dragDelta;
      double y = normalizedValueOnMouseDown;  // in 0..1
      y -= dragValue;
      y = clip(y, 0, 1);

      setNormalizedValue(y);
    }
  }
}
```

**Comment by elanhickler** [comment]
this is no longer going to work:

![image](https://user-images.githubusercontent.com/9116575/44987533-5c863d00-af3c-11e8-8129-2df32a970a8e.png)

we need to limit the size or set the size specifically

**Comment by elanhickler** [comment]
![image](https://puu.sh/BoZpl/285d5c9be6.gif)

see how values show up in a separate part of the GUI in this synth (Cypher)? I need a way to redraw some text on the interface based on the last moved knob and display its value there.

**Comment by RobinSchmidt** [comment]
ok, i will make the slider switchable to a vertical response mode tomorrow.

> we need to set the size of the input box specifically to a single size for all knobs. height need only be as tall as the text.

why that? shouldn't the knob be grabbable everywhere?

> I need a way to redraw some text on the interface based on the last moved knob and display its value there.

you need to derive your gui element from ParameterObserver and register it with the parameter in question (via registerParameterObserver) and then override parameterChanged to update it in response to the parameter change. be sure to also de-register in the destructor to avoid a dangling pointer

**Comment by elanhickler** [comment]
> why that? shouldn't the knob be grabbable everywhere?

I'm only talking about the value input text box

> ok, i will make the slider switchable to a vertical response mode tomorrow.

I've already overridden the method. I can use your switch instead, but you need to allow the ability to set the per-pixel drag scale.

**Comment by elanhickler** [comment]
![image](https://imgur.com/zHpn8GX.gif)

This is working, but I need a place in the parameter to set and get the parameter alias / display string.

![image](https://user-images.githubusercontent.com/9116575/45003298-e44c6580-af95-11e8-8d0a-a678cfd93417.png)

As you can see, getName is all I have. I need "getDisplayString" or something.

hmm, it's in your todo list:

![image](https://user-images.githubusercontent.com/9116575/45003325-28d80100-af96-11e8-8f90-f833d1a11af9.png)

**Comment by RobinSchmidt** [comment]
hmm...okay...i added get/setDisplayName to Parameter. the thing above in the todo list is actually not intended for the name but for multiple-choice options in a combo-box parameter. at the moment, the names of the options must be unique. which makes sense for a linear list box. but i was thinking also about tree-views eher you can select something like "lowpass" and the "24dB" in the lower level below lowpass. and the same "24dB" string could also appear below a "highpass" subtree...but so far, i did not yet need that

**Comment by elanhickler** [comment]
OK! Next feature needed. Not just when I move the knob/widget do I want to see the value. When I simply click on it, I want to see the value. How can I connect "on mouse down" to "display parameter name & value"?

**Comment by RobinSchmidt** [comment]
i would probably register my editor (or maybe the display widget) as MouseListener with the sliders:

https://docs.juce.com/master/classComponent.html#ae45db6bb7d7826eb7e936c21fec105ce

then, you can receive the mouse events that occur in your sliders (additionally) in some other object

**Comment by elanhickler** [comment]
I've never heard of "originalComponent" what is that? So far I have this (not working, need to figure out how to get the parameter):

![image](https://user-images.githubusercontent.com/9116575/45110125-4623e100-b0f6-11e8-96ee-772ca2a11d8d.png)

**Comment by RobinSchmidt** [comment]
> I've never heard of "originalComponent" what is that?

i can also just quote the juce-doc (i'm not that familiar with that stuff either):
https://docs.juce.com/master/classMouseEvent.html#abe6b50fe43981f161200d99e6d235953

> need to figure out how to get the parameter

make a dynamic_cast to RWidget and then use getAssignedParameter

**Comment by elanhickler** [comment]
Robin you responded too soon lol I figured it out I'm smart!

NEXT FEATURE!!!!

I want to use the parameter's underlying string conversion function. Something like

parameter->getValueString(); // returns the string for the value as it would be displayed using its underlying string conversion functino

**Comment by elanhickler** [comment]
fail!

![image](https://user-images.githubusercontent.com/9116575/45111435-d0217900-b0f9-11e8-8873-263d5558ca20.png)

The string conversion function is not stored in parameter or widget, it's stored in a higher class like rslider. :(

**Comment by RobinSchmidt** [comment]
it is in RWidget - but protected. i just added getValueDisplayString to RWidget

**Comment by elanhickler** [comment]
ok did we really need parameter display string?

```
	String getDisplayTextForParameterFromMouseEvent(const MouseEvent& event)
	{
		auto widget =  dynamic_cast<jura::RWidget *>(event.eventComponent);
		auto parameter = widget->getAssignedParameter();
		String name = parameter->getDisplayName();
		return name + " : " + widget->getValueDisplayString();
	}
```

it could have been

```
	String getDisplayTextForParameterFromMouseEvent(const MouseEvent& event)
	{
		auto widget =  dynamic_cast<jura::RWidget *>(event.eventComponent);
		auto parameter = widget->getAssignedParameter();
		String name = widget->getName();
		return name + " : " + widget->getValueDisplayString();
	}
```

but then... what is a widget name for? Maybe it's not just for display.

**Comment by RobinSchmidt** [comment]
RWidget::getName? i don't see this function in my code. maybe it's inherited from juce::Component?

**Comment by elanhickler** [comment]
ah yes it is from juce:component

**Comment by elanhickler** [comment]
I'm going to close this thread, knob features are finished. You can let me know when you add mouse handling for knobs so I can reference your code instead of my own.
