### ISSUE TITLE
I need to add the patch name to the state and xml

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#221]
I need to add the name of the patch to the xml file and state when it is saved and then retrieve the patch name on load (when re-loading the plugin the state). I'll then use that to change the text of a text widget to display the patch name.

**Comment by elanhickler** [comment]
as you can see it just goes to "recalled by host"

![a4fdf0f0c1 1](https://user-images.githubusercontent.com/9116575/45456698-996ed400-b6a0-11e8-87d1-3f6494f0a819.gif)

**Comment by elanhickler** [comment]
robin, would this work: create a text widget that is connected to a string parameter so that the parameter causes the string to be stored, then loading the patch, that text widget / preset name display gets the name back.

the only other thing that we need the save dialog to automatically put in that patch name as a suggested /  default file name.

also,  I need access to the notification system for knowing when the patch is marked dirty. Maybe I can figure that out by looking at the code.

**Comment by RobinSchmidt** [comment]
the "string parameter" is actually badly named - it's intention is to be a multiple choice parameter and the choices are to be represented as strings. so storing a state name there would require to jump through all sorts of hoops (like using only one possible choice and changing that dynamically). perhaps a cleaner solution would be to just store a state-name in your AudioModule baseclass and override get/setState to store and retrieve that name there. you would then also have to use your own state-load/save widget set. when i was designing this state management system, i was thinking of the state-name to *be* the file-name of the state file (if any - and empty if none) and i actually still think that this makes a lot of sense

yeah...a dirtfification-notification system is already there...but i think, it's a bit buggy

**Comment by elanhickler** [comment]
Ok, I'm not even going to use the native file browser. I'll create my own, you will never leave the plugin UI. Here's what I'm doing at the moment, so no need to delete:

![image](https://user-images.githubusercontent.com/9116575/46549189-0af80780-c886-11e8-916d-df44d2463fb7.png)

**Comment by RobinSchmidt** [comment]
>  I'm not even going to use the native file browser. I'll create my own, you will never leave the plugin UI. 

ah! nice! i was once thinking about making the preset widget a sort of dropdown menu showing a tree view of the directory structure when you click on the state-name (another good reason why it makes sense to identify the file-name with the state-name)  ...maybe some day.... many other things to do first

**Comment by elanhickler** [comment]
Also, you can get rid of your modal value edit and replace with a global value edit that:

1. show text widget on double click
2. store the widget that was double clicked
2. position text widget to double clicked widget
2. listen for enter key or escape on widget
3. on enter event, update parameter value of stored widget
4. on any mouse events that are not on text widget, hide widget (because user clicked away)
# Declare
```cpp
TextEditor entryFieldForValueInput;
```
# Setup
```cpp
addChildComponent(entryFieldForValueInput);
entryFieldForValueInput.setInputRestrictions(20, "1234567890.-+");
entryFieldForValueInput.addListener(this);
entryFieldForValueInput.setAlwaysOnTop(true);
entryFieldForValueInput.setVisible(false);
```
# Events
```cpp
void textEditorEscapeKeyPressed(TextEditor&) override
{
    entryFieldForValueInput.setVisible(false);
}

void textEditorReturnKeyPressed(TextEditor&) override

{
    entryFieldForValueInput.setVisible(false);
    currentlyEditingWithInputBox->setValue(entryFieldForValueInput.getText().getDoubleValue(), false, false);
}

void mouseDown(const MouseEvent& event) override
{
    if (event.eventComponent != &entryFieldForValueInput)
        entryFieldForValueInput.setVisible(false);
}

void mouseDoubleClick(const MouseEvent& event) override
{
    currentlyEditingWithInputBox = dynamic_cast<ElanModulatableSlider *>(event.eventComponent);

    if (currentlyEditingWithInputBox == nullptr)
        return;

    juce::Rectangle<int> bounds(90, 20);
    auto area = getLocalArea(currentlyEditingWithInputBox, currentlyEditingWithInputBox->getLocalBounds());

    entryFieldForValueInput.setBounds(area.withSizeKeepingCentre(90, 16));
    entryFieldForValueInput.setText(String(currentlyEditingWithInputBox->getValue()));
    entryFieldForValueInput.selectAll();
    entryFieldForValueInput.setVisible(true);
    entryFieldForValueInput.grabKeyboardFocus();
}
```

**Comment by elanhickler** [comment]
your current modal entry system means if you have a knob and you want a value display to be bigger than the knob, it can't be, because it will get clipped, because you make the text field inside itself. Unusable for anything other than sliders!

and this:

![image](https://user-images.githubusercontent.com/9116575/46553674-f79f6900-c892-11e8-8dcd-4caa6bcd7f6c.png)

**Comment by elanhickler** [comment]
yes its already working code. It's not a static member, it's just a member. It's not clipped because I make the widget on the top level parent editor.
