### ISSUE TITLE
CRASH: Finally got Liberty debug info in Release mode with exe version

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#226]
I had to follow this guide: https://msdn.microsoft.com/en-us/library/fsk896zz.aspx?f=255&MSPPError=-2147217396

![image](https://user-images.githubusercontent.com/9116575/45595108-80de1280-b95b-11e8-8273-e618fe6970ea.png)
![image](https://user-images.githubusercontent.com/9116575/45595299-3742f700-b95e-11e8-9e8c-95344fdfc752.png)

Steps to produce:

1. Run Toolchain exe
2. add Liberty module

**Comment by RobinSchmidt** [comment]
ok - look like i have fixed it. had something to do with var_arg lists in the initialization. but i really wonder why it worked in debug mode then. anyway - i just removed the var_arg stuff entirely. was already deprecated anyway

**Comment by elanhickler** [comment]
confirmed
