### ISSUE TITLE
CRASH: involving automation node editor

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#228]
![image](https://user-images.githubusercontent.com/9116575/45597072-5439f300-b97b-11e8-9e2f-7ec3cb0775be.png)

Steps to reproduce:

1. load Toolchain exe
2. Add any module
3. Open automation editor for any parameter
4. Right click on any of the two default nodes
5. Left click on the same node.

Yes, just a simple, right click left click, one two punch, CRASH!

**Comment by elanhickler** [comment]
It's Crash Sunday! All the best crashes, all day! Enjoy!

**Comment by RobinSchmidt** [comment]
...so it's debug monday then. yay! great! :-P

**Comment by elanhickler** [comment]
confirmed
