### ISSUE TITLE
Let's work out a way to collaberate

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#23]
I'd like to offer code to your library free from obligation, you can take my code and do whatever you want with it and I will not ask for compensation. I just want to make your library better so it's better for me.

I'm still working on this one, but this gives you an idea of a class you can add onto as a subclass (or whatver the correct terminology is). I've attached this to my SimpleLFO class so now I can controls the frequency of the LFO easily in 3 modes: pitch/hz/tempo.

I'm still working on what to do to make it easy to create custom tempo options. Like I said I have a string to value convert for this style of tempo: "1/4T" "1/4." "1/8" etc. but I didn't implement it here just yet.

So, what do you think? You should take my code and "Robinize" it as needed. Then I will rewrite my own stuff to connect with the class that you came up with.

```CPP
class FrequencyModeHelper
{
public:
	enum class Mode { hz, tempo, pitch };

	vector<juce::String> TempoOptionsStr ={ "1/4","1/3","1/2","x1","x1.333","1.5x","x2","x2.666","x3","x4","x5.333",
		"x6", "x8","x10.666","x12","x16","x21.333","x24","x32","x42.666","x48","x64","x85.333","x96","x128", };

	vector<double> TempoMultipliers ={ 4.0, 3.0, 2.0, 1/1.0, 0.75/1.0, 1/1.5, 1/2.0, 0.75/2.0, 1/3.0, 1/4.0,
		0.75/4.0, 1/6.0, 1/8.0, 0.75/8.0, 1/12.0, 1/16.0, 0.75/16.0, 1/24.0, 1/32.0, 0.75/32.0, 1/48.0, 1/64.0, 0.75/64.0, 1/96.0, 1/128.0, };

	void setTempoOption(int idx)
	{
		tempo_selection = idx;
		updateTempoInHz();
	}

	void setBPM(double bpm)
	{
		bpm_factor = bpm/60.0;
		updateTempoInHz();
	}

	void setFrequency(double f)
	{
		hz = f;
	}

	void setPitch(double pitch)
	{
		pitch_in_hz = pitchToFreq(pitch);
	}

	void setFreqMode(Mode mode)
	{
		freqMode = mode;
	}

	double getFrequency()
	{
		switch (freqMode)
		{
		case Mode::hz:    return hz;
		case Mode::pitch: return pitch_in_hz;
		case Mode::tempo: return tempo_in_hz;
		}
	}


protected:
	Mode freqMode = Mode::hz;

	double hz = 1.0;
	double pitch_in_hz = 1.0;
	double tempo_in_hz = 1.0;
	
	double bpm_factor = 1.0;
	int tempo_selection = 3;

	void updateTempoInHz()
	{
		tempo_in_hz = bpm_factor * TempoMultipliers[tempo_selection];
	}
};

**Comment by elanhickler** [comment]
I purposely keep hz / pitch-hz / tempo-hz variables completely separate. This is because... well firstly it's more CPU cost to update all variables, secondly when I implement the GUI I want to save those values separately for the user for easy switch. I don't the user to control pitch just to realize "oh now my tempo setting was changed" when the user switches back to tempo mode. I could always make a function "synchronize all hz values" as an optional function you could call.

**Comment by RobinSchmidt** [comment]
haha! "Robinize". i like that. yeah...i use some different coding style conventions.. hmmm....well...i guess, i could add that class to my jura_processors module...i would need to add comments...hmmm.....but i'm not so sure, if that class will be useful for me or other clients. the options don't seem general enough. some of the choices seem arbitrary, like 10.666, 21.333. why are these values interesting? ok, it's 0.75 divided by some power of 2? perhaps, i would prefer to let the user select numerator and denominator separately....not sure

**Comment by elanhickler** [comment]
this class is still not 100% correct.

TempoOptionStr and TempoMultipliers should be pointers to arrays outside of the class and FrequencyModeHelper, and of course the developer should choose what to use there. They can use anything as long as the strings and the numbers match, or we can create a string to multiplier convenience function to build the array for you.

```
vector<juce::String> FrequencyModeHelper::TempoOptionsStr =
{
	"1/4","1/3","1/2","x1",
	"x1.333","1.5x","x2",
	"x2.666","x3","x4",
	"x5.333", "x6", "x8",
	"x10.666","x12","x16",
	"x21.333","x24","x32",
	"x42.666","x48","x64",
	"x85.333","x96","x128",
};

vector<double> FrequencyModeHelper::TempoMultipliers =
{ 
	0.25*1/4.0, 0.25*1/3.0, 0.25*1/2.0, 0.25*1.0,
	0.75/1.0, 0.25*1.5, 0.25*2.0,
	1.0/(4.0*0.75/2.0), 0.25*3.0, 0.25*4.0,
	1.0/(4.0*0.75/4.0), 0.25*6.0, 0.25*8.0,
	1.0/(4.0*0.75/8.0), 0.25*12.0, 0.25*16.0,
	1.0/(4.0*0.75/16.0), 0.25*24.0, 0.25*32.0,
	1.0/(4.0*0.75/32.0), 0.25*48.0, 0.25*64.0,
	1.0/(4.0*0.75/64.0), 0.25*96.0, 0.25*128.0,
};
```

this array represets this series: 
```
4/1 3/1 2/1 1/1 
1/2. 1/1 T 1/2 
1/4. 1/2T 1/4 
1/8. 1/4T 1/8 
1/16. 1/8T 1/16 
1/32. 1/16T 1/32
1/64. 1/32T 1/64 
1/128. 1/64T 1/128
```

I'm just doing strings and math that make sense to me. I like to represent speed/tempo with x###

**Comment by elanhickler** [comment]
Here's what the class turned into. I now have octave/semitione offset/current note variables. I found that I needed it. But I don't think it will always be used.
```
class FrequencyModeHelper
{
public:
	static vector<juce::String> TempoOptionsStr;

	static vector<double> TempoMultipliers;

	enum class Mode { hz, pitch, tempo};

	static juce::String getTempoStr(int idx);

	void setTempoOption(int idx)
	{
		tempo_selection = idx;
		updateTempoInHz();
	}

	void setBPM(double bpm)
	{
		bpm_factor = bpm/60.0;
		updateTempoInHz();
	}

	void setFrequency(double f)
	{
		hz = f;
	}

	void setOctave(int x)
	{
		octave_offset = x;
		updatePitchInHz();
	}

	void setCurrentNote(double x)
	{
		current_note = x;
		updatePitchInHz();
	}
	void setSemitoneOffset(double x)
	{
		semitone_offset = x;
		updatePitchInHz();
	}

	void setFreqMode(Mode mode)
	{
		freqMode = mode;
	}

	double getFrequency()
	{
		switch (freqMode)
		{
		case Mode::hz:    return hz;
		case Mode::pitch: return pitch_in_hz;
		case Mode::tempo: return tempo_in_hz;
		}
	}

protected:
	Mode freqMode = Mode::hz;

	double hz = 1.0;
	double pitch_in_hz = 1.0;	
	double current_note = 0.0;
	double octave_offset = 0;
	double semitone_offset = 0.0;

	double tempo_in_hz = 1.0;
	double bpm_factor = 1.0;
	int tempo_selection = 3;

	void updatePitchInHz()
	{
		pitch_in_hz = pitchToFreq(current_note + semitone_offset + octave_offset*12);
	}
	void updateTempoInHz()
	{
		tempo_in_hz = bpm_factor * TempoMultipliers[tempo_selection];
	}
};
```

**Comment by elanhickler** [comment]
Oh but if currentNote changes, that needs to be taken into account... unless I calculate pitch every sample... ugh... ok I dunno how to be a programmer sometimes. This is just an example of what I'm going for. It won't be obvious what this class should and should not do until I make more progress.
