### ISSUE TITLE
How do you loop through widgets to create generic editor?

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#230]
Howwww

![image](https://user-images.githubusercontent.com/9116575/45602768-9f362380-b9d8-11e8-91a5-0ed22feb315f.png)

the widgets vector in editor class is protected and its split up into two vector, widget sets and widgets.

**Comment by elanhickler** [comment]
Also could you make buttons have some button text if not se based on the name of the underling parameter or the name of the juce component?

**Comment by elanhickler** [comment]
Also is there a convenient way to get the number of widgets to know the height of an editor?

**Comment by RobinSchmidt** [comment]
perhaps best to subclass from GenericAudioModuleEditor. i just fixed the button text (basing it on the parameter name was the intention anyway - the cod was just not there yet) and i added a function getRequiredHeight (which you may override, if your generic editor looks different). there's an array parameterWidgets with all the widgets for the parameter (i.e. excluding the patch-management widgets)

**Comment by RobinSchmidt** [comment]
edit: you don't have to make your generic editor a subclass of mine - you can as well write your own by just subclassing from AudioModuleEditor (if you don't want/need my parameterWidgets array because you want to use your own custom widgets, for example)

**Comment by elanhickler** [comment]
the generic editor is for creating the plugin without the UI assets.

**Comment by elanhickler** [comment]
ok!
