### ISSUE TITLE
How do you create a step sequencer widget?

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#232]
I can handle the DSP, but how do you make the UI?

What classes should I look at? How should I group widgets programmatically? 

Is each step an `Editor` class? And then each sequencer has like 16 of said `Editor`? That would be weird... It would have to be something like:

vector<sequencerStepModule> sequencerStepsModules{ 16 };
vector<sequencerStepEditor> sequencerStepsEditors{ 16 }

but I'd rather spawn them programmatically by the user selecting number of steps.

Another thing is I need maybe 6 different sequencers, maybe total of up to 64 steps:

vector<sequencerAStepModule> sequencerAStepsModules{ 64 };
vector<sequencerAStepEditor> sequencerAStepsEditors{ 64 };

vector<sequencerBStepModule> sequencerBStepsModules{ 64 };
vector<sequencerBStepEditor> sequencerBStepsEditors{ 64 };

vector<sequencerCStepModule> sequencerCStepsModules{ 64 };
vector<sequencerCStepEditor> sequencerCStepsEditors{ 64 };

vector<sequencerDStepModule> sequencerDStepsModules{ 64 };
vector<sequencerDStepEditor> sequencerDStepsEditors{ 64 };

vector<sequencerEStepModule> sequencerEStepsModules{ 64 };
vector<sequencerEStepEditor> sequencerEStepsEditors{ 64 };

vector<sequencerFStepModule> sequencerFStepsModules{ 64 };
vector<sequencerFStepEditor> sequencerFStepsEditors{ 64 };

I need to learn to add/remove modules & editors based on user UI interaction.

Edit: Oh! I could do an intermiediary editor to hold the 64 steps!

**Comment by elanhickler** [comment]
but I also need to update the editor based on the current step to show what step is being played.

**Comment by elanhickler** [comment]
oh f*** and we also need things like "dragging your mouse across the widget means multiple widgets get activated"

![ezgif-4-18c38051c2 1](https://user-images.githubusercontent.com/9116575/45762480-4c7c8780-bbe3-11e8-9a49-488a7dc56a6f.gif)

**Comment by RobinSchmidt** [comment]
> Is each step an Editor class? And then each sequencer has like 16 of said Editor? That would be weird.

noo! the only thing i made, that goes into that direction is the step-sequence in AciDevil. but what you show in the pic below looks like you are looking for something different. for the gui, i would probably just subclass from RWidget and implement the mouse response (updating step-heights) directly in the mouse callback. do you want to associate a (modulatable/automatable) parameter withe each step?

**Comment by elanhickler** [comment]
modulation probably not needed, I think a modulation of a pattern selector would be the most appropriate and useful.

Yeah I'll try subclassing RWidget.

**Comment by elanhickler** [comment]
Hey Robin, before you said I shouldn't make each step its own module/editor, but I have a case where I do infact want everything to be modulatable.

I guess I could do a rWidgetSet, right? and declare ModulatableButton and ModulatableSlider.

![image](https://user-images.githubusercontent.com/9116575/46056908-da86cf80-c107-11e8-94b6-2b7631ba66a5.png)

**Comment by elanhickler** [comment]
### Widget
```cpp
class PulseVisualizer : public RWidget
{
public:
	PulseVisualizer() = default;
	~PulseVisualizer() = default;

	void paint(Graphics & g) override
	{

		g.setColour({ 0,0,0 });
		g.drawEllipse(0,0,getWidth(), getHeight(), 1);

		g.setColour({ 255, 255, 255 });
		for (double value : values)
		{
			const int margin = 2;
			int drawAreaHorizontal = getWidth() - margin;
			int drawAreaVertical = getWidth() - margin;

			int lineLocationX = margin + drawAreaHorizontal * value;
			int lineLocationY = margin + drawAreaVertical * value;

			g.drawLine(lineLocationX, margin, lineLocationX, getHeight() - margin, 1);
		}
	}

	void updateClickLocation(int index, double normalizedValue)
	{
		if (index < 0 || index >= values.size())
			return;

		values[index] = normalizedValue;
		repaint();
	}

	vector<double> values{ 2 };

protected:
};
```
### WidgetSet
```cpp
class RaPG_ClockDividerWidgetSet : public WidgetSet, public jura::RSliderListener
{
public:
	RaPG_ClockDividerWidgetSet(RaPG_RhythmModule * newModuletoEdit)
	{

		addWidget(pulseDisplay = new PulseVisualizer());
		pulseDisplay->setDescription("description");
		pulseDisplay->setDescriptionField(infoField);
	}

	~RaPG_ClockDividerWidgetSet() = default;

	void rSliderValueChanged(RSlider * rSlider) override
	{
		if (rSlider == pulse1time_slider)
			pulseDisplay->updateClickLocation(rSlider->getNormalizedValue(), 0);
		else if (rSlider == pulse2time_slider)
			pulseDisplay->updateClickLocation(rSlider->getNormalizedValue(), 1);
	}

protected:
	PulseVisualizer * pulseDisplay;
};
```

**Comment by RobinSchmidt** [comment]
> But is there really much of a difference between WidgetSet and Editor if you remove the headline and state widget set? And the fact that the editor drawing is limited to a box.

...and that it can have child editors, close buttons and a couple of other features. but yeah - basically, you are right. in this case, i'd say, you can choose what feels more appropriate. i tend to use the rule of thumb: each AudioModule gets its own Editor, so the child/editor tree reflects the module tree. but that's not required (if i'm not mistaken) - just a thumb rule

**Comment by elanhickler** [comment]
thanks, that's by Soundemote's new official UI artist!
