### ISSUE TITLE
0 is a valid filter cutoff, can i convince you to remove your check for 0?

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#233]
![image](https://user-images.githubusercontent.com/9116575/45779094-076e4a80-bc0f-11e8-9525-25b9b0851056.png)

please remove this code... or else!!! I will have to create my own filter class.

code should simply be:
```cpp
void OnePoleFilter::setCutoff(double newCutoff)
{
 cutoff = newCutoff;
 calcCoeffs();
 return;
}
```
A hilarious problem occurs with this code as well, if you are in highpass mode, 0 means silence.

**Comment by RobinSchmidt** [comment]
hmm...hmm..hmmm...if i remember correctly, i introduced these limitations because the coefficient computation formulas may run into problems (like div-by-zero or producing unstable filters) when the cutoff is <=0 or >= sampleRate. i actually totally agree that it is desirable to run smoothly into limiting cases. maybe try to remove the code and see if the filter explodes - it may also depend on the mode. ...this should be thoroughly tested (and/or i should have a close look at the coefficient equations and their behavior in limit cases)

**Comment by RobinSchmidt** [comment]
but generally - yes - i would happily lift this limitation, if possible without catastrophic consequences. i'll take a closer look

**Comment by elanhickler** [comment]
I've been using it fine so far. Made the edit for myself for now.

**Comment by RobinSchmidt** [comment]
ok, i'm refactoring the filter a little. i'll factor out a baseclass without restrictions which keeps only the x1, y1, b0, b1, a1 members (state and coeffs) but no user parameters (makes it leaner to user when some outlying class keeps the sampleRate around anyway) and provides the bare coeff-computation formulas as static functions ..and the we'll see what to do with it...

**Comment by RobinSchmidt** [comment]
i did some refactoring and removed the check. i hope this doesn't break any of my code :-O but if it does, i think, i should do such safety checks at other places. i think, the IIT based designs can handle 0 and sr/2 settings just fine - nothing special happens. but the BLT based designs get a problem with sr/2 - then i compute the tangent of pi/2 - which is inf - and further computations with that will turn it into NaN...but i may investigate the limit behavior, catch the situation as special case and assign appropriate values in that case (greets from l'Hospital)

**Comment by elanhickler** [comment]
wat? greets form i hospital?

**Comment by RobinSchmidt** [comment]
https://en.wikipedia.org/wiki/L%27H%C3%B4pital%27s_rule

**Comment by elanhickler** [comment]
zero divided by anything is definitely still 0, not NaN or inf, otherwise you're creating energy from nothing. I wish I could divide zero dollars and get infinite dollars.

**Comment by RobinSchmidt** [comment]
> zero divided by anything is definitely still 0, not NaN or inf

nope. not if that anything is also zero

**Comment by RobinSchmidt** [comment]
i just stumbled over this:
https://www.1dividedby0.com/
very nice read!

**Comment by elanhickler** [comment]
solved
