### ISSUE TITLE
How do you limit TriSaw slope to be at least two samples in length?

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#235]
We need to limit TriSaw slope (asymmetry parameter) to two samples in length for antialiasing purposes.

Can you give me the formula? Then i can do:

asymmetry = clip(value, -asymmetryInSamples(2), +asymmetryInSamples(2));

**Comment by RobinSchmidt** [comment]
i just added asymForTransitionSamples to rsTriSawOscillator which should work the way you suggested with the clip function. i did only a very quick test though. make sure to call it *after* you have set up the increment/frequency of the osc because the value will obviously depend on that setting

**Comment by elanhickler** [comment]
closing for now!

**Comment by RobinSchmidt** [comment]
...but how? what to do, if it is dead center? should it go "up" in the negative or positive direction? ...we would somehow have to take into account the sign of the current setting and just increase the absolute value depending on frequency. perhaps a natural convention would be to increase it towards +1 for settings >= 0 and towards -1 for settings < 0

**Comment by RobinSchmidt** [comment]
...wait - no - nonsense....forget what i said....negative values are spikey

**Comment by elanhickler** [comment]
o right.

**Comment by RobinSchmidt** [comment]
yes, i deleted my post - because it was nonsense.

of course, this is not "proper" anti-aliasing. neither is limiting the symmetry. but the sigmodity parameter makes the waveform more sinusoidal, hence less overtones and therefore less aliasing, no? or am i missing something here?

> you did say you can use the upsampler of the phase scope for 1d signals to smooth out arbitrary signals

no - i was not talking about smoothing but upsampling/oversampling

.

**Comment by elanhickler** [comment]
To go from spikey to linear to sigmoid makes much less sense than ensuring a slope is at least 2 samples in length. You would have to go from spikey to sigmoid OR linear to sigmoid, you can't pass through a linear slope to do faux antialiasing. On the other hand, the faux antialiasing of simply limiting the slope makes more sense, it's the main cause of aliasing in TriSaw.

**Comment by elanhickler** [comment]
OH! I wonder if your asymForTransitionSamples works for all my Oscilloscope Music algorithms which have a very similar asymmetrical control as TriSaw. Yesss, I've been wanting to add that to OMS for a long time.

**Comment by RobinSchmidt** [comment]
hmm...well....that may depend on the particular osc algorithm - but if the parameter has a similar effect, limit it should probably also have a similar effect. you can just grab the formula form the code and convert it into a free function taking the "inc" variable (phase-increment per sample) as parameter

**Comment by elanhickler** [comment]
ok, going from spikey to linear to sigmoid could actually work for antialiasing. Yeah... not sure it's worth going into that much detail with TriSaw. I guess you could choose an some curve over frequency and be done with it.

**Comment by elanhickler** [comment]
btw, I can't use your TriSaw oscillator until you add negative frequency and phase offset options. I've copied code from Liberty's TriSaw and using my phasor class to run the algorithm.

You should use a phasor so you don't have to repeat this code for every oscillator, and a phasor would allow for negative frequencies.

![image](https://user-images.githubusercontent.com/9116575/45919284-c614af80-be47-11e8-8d59-78b0974036ad.png)

**Comment by elanhickler** [comment]
here's how I wrap phase:

![image](https://user-images.githubusercontent.com/9116575/45919298-fe1bf280-be47-11e8-9bb3-dc07206699b1.png)

**Comment by elanhickler** [comment]
YES IT WORKS! I'm using transition samples 2. Perfect. yayyyyyyyyyyyy

**Comment by RobinSchmidt** [comment]
yes, looks good. i added support for negative frequencies to the trisaw. yes - factoring out a phasor class would make sense. ...the floor function for wrap-around....i would guess, my while-loop is more efficient but i should probably set up some performance tests for that. i think, supporting phase-modulation would imply to apply the wrap-around code in the update *and* in the read-out

**Comment by elanhickler** [comment]
http://www.elanhickler.com/transfer/_/chaosarp/trisaw_limited_asym_0_1_2_limit.wav

here's the difference, 3 examples. no limit, 1 sample limit, 2 sample limit

I might use 1 sample limit actually. OH! How about this. I could use 2 sample limit if user has no oversampling enabled, and 1 sample limit if there is oversampling.

**Comment by RobinSchmidt** [comment]
whoa - the first sucks sooo bad. the 2nd is already a lot better. it's soo cheap and simple and surprisingly effective

**Comment by RobinSchmidt** [comment]
i'm leaving home now. i think, i will tomorrow experiment a bit with automatic increase sigmoidity - let's see, if we can beat down the aliasing some more...

**Comment by RobinSchmidt** [comment]
i consider aliasing as my arch nemesis. always nice to expand the arsenal of weapons against it

**Comment by RobinSchmidt** [comment]
yes - the bend parameter/s is/are another one which which should be limited depending on frequency. but i was actually talking about the sigmoidity - which turns the triangle into an (almost) sine. a true sine wave at some given frequency would show no aliasing at all, so it seems to make sense to force the waveform to be more sinusoidal at higher frequencies

**Comment by RobinSchmidt** [comment]
yes - limiting sigmoidity also makes a difference:
www.rs-met.com/temp/audio/TriSawSweep-AntiSigmoidNoAA.wav
www.rs-met.com/temp/audio/TriSawSweep-AntiSigmoidLimited20.wav

**Comment by elanhickler** [comment]
Limiting the increment means limiting the frequency? That doesn't make sense. You must be thinking of something else.

**Comment by RobinSchmidt** [comment]
i didn't say "limit the incremet" but make the (asymmetry) limit a function of the increment

**Comment by elanhickler** [comment]
btw I find this scheme of controlling TriSaw to be nice for oscillator.

```cpp
void setWaveAsymmetrical(double v) { triSawOsc.setAsymmetrical(v); }

void setWaveBendAktDec(double v)
{
	bend = v;
	recalculateBend();
}
void setWaveBendOffset(double v)
{
	bendOffset = v;
	recalculateBend();
}

void setWaveSigmoidAtkDec(double v)
{
	sigmoid = v;
	recalculateSigmoid();
}
void setWaveSigmoidOffset(double v)
{
	sigmoidOffset = v;
	recalculateSigmoid();
}

void recalculateBend()
{
	double absoluteValue = bendOffset;
	double target = 1;

	if (bendOffset < 0)
	{
		absoluteValue = -bendOffset;
		target = -target;
	}

	triSawOsc.setAttackBend(juce::jmap(absoluteValue, bend, target));
	triSawOsc.setDecayBend(juce::jmap(absoluteValue, -bend, target));
}
void recalculateSigmoid()
{
	double absoluteValue = sigmoidOffset;
	double target = 1;

	if (sigmoidOffset < 0)
	{
		absoluteValue = -sigmoidOffset;
		target = -target;
	}

	triSawOsc.setAttackSigmoid(juce::jmap(absoluteValue, sigmoid, target));
	triSawOsc.setDecaySigmoid(juce::jmap(absoluteValue, sigmoid, -target));
}
```
![ezgif-4-6ed2d3953a 1](https://user-images.githubusercontent.com/9116575/45973521-930f1f00-bff3-11e8-8697-f8b377335194.gif)

**Comment by RobinSchmidt** [comment]
i was also already experimenting with some user-parameter to algo-parameter mappings. specifically, i'd like to be able to control both bend params at the same time - having and out-vs-in parameter (bending outward towards square-wave vs bending inward toward narrow pulses)....but everything i tried so far made some settings unreachable. does your mapping reach all possible settings?

**Comment by RobinSchmidt** [comment]
that's great! i have to try it...did you also extend the negative range for sigmo already? i think, we can go down to -2....so the meaningful range would be -2...+1

**Comment by elanhickler** [comment]
yes. I just multiply the final value by *2 if less than 0.

it would be nice if you could go to go +2, sine should move toward square like ellipseoscillator :)

**Comment by elanhickler** [comment]
It's funny that this was obvious to me and not to you! I guess there's a first for everything. I came up with it just by first coupling attack/decay bending and attack/decay sigmoid. So now two controls change all 4 parameters. Then I needed a way to gradually decouple or diverge or converge the 2 pairs of attack/decay parameters. So I used jmap to create linear diverging/converging of the attack/decay values. I dunno if my explanation helps, this was probably what you were trying to do already.

I just imagined one slider controlling two other sliders (attack/decay) to make them move together. Then another slider makes the two sliders have some offset, to diverge or converge or swap values gradually.

**Comment by RobinSchmidt** [comment]
seems like i just didn't have the right idea / think into the right direction. here i'm plotting both functions (i.e. both algo params) as functions of the two user-params. 
![image](https://user-images.githubusercontent.com/1833099/46042835-abc42580-c116-11e8-827c-3c183b633fb4.png)
on the base-plane are contour lines (lines of equal height) for both surfaces. when each line of one set crosses each line from the other set, all combinations of target params are reachable (i think).

**Comment by elanhickler** [comment]
I've stared at this for a while, it's a pretty graphic.

**Comment by RobinSchmidt** [comment]
haha - if you install GNUPlot, you can recreate it yourself and rotate it with the mouse :-) it's actually a pretty clever formula. in a generic abstract sense, it provides a mapping from some sort of "Amount" and "Spread" user-parameter to two "Amount1/Amount2" algo-parameters. i think, i'll include is as such into the library. maybe something like:
```cpp
void distributeAmounts(double amount, double spread, double* amount1, double *amount2)
{
  double absAmt = amount;
  double target = 1;
  if(amount < 0) {
    absAmt = -amount;
    target = -target;
  }
  *amount1 = RAPT::rsLinToLin(absAmt, 0.0, 1.0,  spread, target);
  *amount2 = RAPT::rsLinToLin(absAmt, 0.0, 1.0, -spread, target);
}
```
you could then call it from recalculateBend/recalculateSigmoid to get rid of the code duplication

**Comment by elanhickler** [comment]
this is essentially solved. Closing.
