### ISSUE TITLE
Ok sirrisly robin I need to learn how to add/swap/remove modules/editors

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#236]
I want to do something like a [+] tab system for modulator for example, where you can click add, select from a menu "lorenz, trisaw, envelope, etc." and the user can add whatever module they want. Then I can finally easily experiment with different oscillators, chaos generators, etc.

Also, I need this for my oscilloscope music series the user can select whatever algorithm they want.

What should I look at to get started learning how to do it?

Is the preset system going to be complex, do I need to a custom state read/write function to load/save a list of modules?

**Comment by RobinSchmidt** [comment]
also important: `jura::AudioModuleFactory`

**Comment by elanhickler** [comment]
most of that is just you defining various modules tho, right?

**Comment by RobinSchmidt** [comment]
you mean the code in populateModuleFactory? yes, that is for telling the factor object, which modules should be in the list and how to create them (by passing a creator function, which just wraps the constructor of the respective class into a lambda function)
