### ISSUE TITLE
Waveform drawer widget needed

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#239]
I need a widget that updates when I change the TriSaw shape so I can show the user the shape. I need to render one cycle for the user.

Also it would be nice to have one for my breakpoint envelope (that just uses knobs to control breakpoints instead of displaying the breakpoint editor).

Would be easy to explain how I could do it?

**Comment by elanhickler** [comment]
I got this so far:
![image](https://user-images.githubusercontent.com/9116575/46251177-b9242d00-c400-11e8-9faa-a6860c43d8e3.png)

```cpp
class JUCE_API RaPG_WaveformVisualizer : public jura::RWidget
{
public:
    Phasor phasor;

    RaPG_WaveformVisualizer()
    {
        waveformVisualizer.setSampleRate(44100);
        phasor.setSampleRate(44100);
        phasor.setFrequency(100);
    }

    jura::rsWaveformPlot waveformVisualizer;

protected:
    void paint(Graphics & g) override
    {
        waveformVisualizer.paint(g);
    }

    void fillBuffer()
    {
        for (double phase = 0; phase < 1; phase = phasor.getSample())
        {
            double x;
            if (phase < h)
                x = RAPT::rsTriSawOscillator<double>::shape(a0 + a1 * phase, atkbend, -0.5 * atksig); // upward section
            else
                x = RAPT::rsTriSawOscillator<double>::shape(b0 + b1 * phase, -decbend, -0.5 * decsig);  // downward section
            points.push_back(x);
        }        
    }

    void parameterChanged(Parameter* parameterThatHasChanged) override
    {
        updateCoefficients();
        fillBuffer();
        waveformVisualizer.setWaveform((double**)points.data(), (int)points.size(), 1);
        waveformVisualizer.updateWaveformCurve();
        repaint();
    }

    void updateCoefficients()
    {
        h = 0.5 * (asym + 1);
        a0 = -1;
        a1 = 2 / h;
        b0 = (1 + h) / (1 - h);
        b1 = -1 - b0;
    }

    vector<double> points;

    double h, a0, a1, b0, b1;

    double phaseOffset = 0;
    double asym = 0;
    double atkbend = 0;
    double atksig = 0;
    double decbend = 0;
    double decsig = 0;
};
```

**Comment by elanhickler** [comment]
### progress on envelope display, not drawing anything ???

![image](https://user-images.githubusercontent.com/9116575/46251571-af072c00-c40a-11e8-80e9-1a4d0eb4d371.png)

### class
```cpp
class JUCE_API RaPG_EnvelopeVisualizer : public jura::ModulatorCurveEditor
{
public:
    RaPG_EnvelopeVisualizer() = default;
    ~RaPG_EnvelopeVisualizer() = default;
protected:
    void mouseDown(const MouseEvent &e) override {}
    void mouseDrag(const MouseEvent &e) override {}
    void mouseMove(const MouseEvent &e) override {}
    void mouseUp(const MouseEvent &e) override {}
};
```

### constructor
```cpp
    envelope_display = new RaPG_EnvelopeVisualizer();
    envelope_display->setModulatorToEdit(&moduleToEdit->envelope.env);
    addChildComponent(envelope_display);
```

**Comment by elanhickler** [comment]
Robin, please build and test my Rhythm and Pitch Generator, you will find that it's very fun to use and it may inspire you to help me frikkin finish this thing! I just can't release this without an envelope visualizer.

I can skip the waveform visualizer and the modulation system!

I'll make a video demonstration of the plugin soon so if you don't test it now maybe you'll like to test after you see it in action.

**Comment by elanhickler** [comment]
edit: I should probably give you some code references and make sure you know what code to look at.

hold off!

**Comment by elanhickler** [comment]
OK! I got it working!

I just need help on getting the parameter (slider/knob) movements to update the disaply with whatever the change message system that is in place here.

**Comment by elanhickler** [comment]
WORKS!

**Comment by RobinSchmidt** [comment]
so - nothing to do for me here anymore?

**Comment by elanhickler** [comment]
hmm maybe it's ok

![image](https://user-images.githubusercontent.com/9116575/46424852-195feb00-c6ef-11e8-8519-e48d258f4501.png)

would like to make the background maybe half a .5 alfo at least

**Comment by elanhickler** [comment]
closing, will create my own waveform drawer.
