### ISSUE TITLE
GUI Widgets/parameters need a "value has changed" check before calling function

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#24]
If you have a parameter assigned to DAW host automation, the DAW will continuously send updates to that parameter even if the value has not changed. This is bad, will eat up a lot of unecessary CPU for some functions otherwise I have to put a "value change" check for every function. Please allow for parameters to be set to not call the function if value has not changed. I think this should be default. Then you can turn off this feature where needed in the parameter/widget constructor/setup.

**Comment by RobinSchmidt** [comment]
i just added the code:
```
void MetaParameter::setMetaValue(double newValue)
{ 
  if(newValue == metaValue)
    return; // avoid superfluous updates (some DAWs continuously send constant values)

  // ...update code
}
```
since all the automation is mediated through MetaParameters, this should be the right place, i think. i hope, it' won't break anything (but actually, it shouldn't). silly DAW :-P

**Comment by RobinSchmidt** [comment]
...nah - i moved the check "up" in the class hierarchy into AudioPluginParameter (glue between jura::MetaParameter and juce::AudioProcessorParameter:
```
void AudioPluginParameter::setValue(float newValue)
{
  if(newValue != metaValue)                           // avoid superfluous updates (some DAWs 
    MetaParameter::setMetaValue((double)newValue);    // continuously send constant values)
}
```

**Comment by RobinSchmidt** [comment]
or is that "down"...anyway. that should fix it. i didn't try, though

**Comment by elanhickler** [comment]
works.
