### ISSUE TITLE
Can't get modulation to work

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#243]
### InternalModSrc class
```cpp
class InternalModSrc : public jura::ModulationSource
{
public:
	InternalModSrc(String name, String displayName)
		: valuePtr(valuePtr)
	{
		setModulationSourceName(name);
		setModulationSourceDisplayName(displayName);
		valuePtr = &dummy;
	}

	void setValuePtr(double * ptr)
	{
		valuePtr = ptr;
	}

protected:

	virtual double getModulatorOutputSample() override
	{
		return * valuePtr;
	}

	double * valuePtr;

	double dummy = 0;
};
```
### create a modulation manager
BasicModule inherits for AudioModuleWithMidiIn
```cpp
class JUCE_API RhythmAndPitchGeneratorModule : public BasicModule, public MidiSlave
{
public:
  RhythmAndPitchGeneratorModule(CriticalSection *lockToUse, jura::MetaParameterManager * metaManagerToUse);
  virtual ~RhythmAndPitchGeneratorModule() = default;

  RaPG_EnvelopeModule * envelopeModule;
  RaPG_OscillatorModule * oscillatorModule;
  RaPG_PitchModule * pitchModule;
  RaPG_RhythmModule * rhythmModule;

  jura::ModulationManager modulationManager;

protected:

  InternalModSrc oscSource{ "osc_mod", "oscillator source" };
  InternalModSrc oscFiltered{ "osc_flt_mod", "oscillator filtered" };
  InternalModSrc oscFltAmp{ "osc_fltamp_mod", "oscillator flt amp" };
  InternalModSrc oscFinalOut{ "osc_final_mod", "oscillator final out" };
  InternalModSrc envSource{ "env_mod", "envelope source" };
  InternalModSrc pitchNoiseSource{ "pitch_noise_mod", "pitch noise source" };
  InternalModSrc rhythmNoiseSource{ "rhythm_noise_mod", "rhythm noise source" };
  InternalModSrc rhythmClickSource{ "rhythm_pulse_amp", "rythm pulse amplitude" };

  JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR(RhythmAndPitchGeneratorModule)
};
```
### constructor
```cpp
RhythmAndPitchGeneratorModule::RhythmAndPitchGeneratorModule(CriticalSection *lockToUse, jura::MetaParameterManager * metaManagerToUse)
  : BasicModule(lockToUse, metaManagerToUse), modulationManager(lockToUse)
{
  ScopedLock scopedLock(*lock);

  setSmoothingManager(&smootyMan);

  setModulationManager(&modulationManager);  
  modulationManager.setMetaParameterManager(metaParamManager);
}
```
### assign modulation manager to sub modules
```cpp
  envelopeModule = new RaPG_EnvelopeModule(lock, metaParamManager);
  envelopeModule->setModulationManager(&modulationManager);
  envelopeModule->setModuleName("Envelope");
  addChildAudioModule(envelopeModule);

  oscillatorModule = new RaPG_OscillatorModule(lock, metaParamManager);
  oscillatorModule->setModulationManager(&modulationManager);
  oscillatorModule->setModuleName("Oscillator");
  addChildAudioModule(oscillatorModule);

  pitchModule = new RaPG_PitchModule(lock, metaParamManager);
  pitchModule->setModulationManager(&modulationManager);
  pitchModule->setModuleName("Pitch");
  addChildAudioModule(pitchModule);

  rhythmModule = new RaPG_RhythmModule(lock, metaParamManager);
  rhythmModule->setModulationManager(&modulationManager);
  rhythmModule->setModuleName("Rhythm");
  addChildAudioModule(rhythmModule);
```
### register modulation sources
Line 282 RhythmAndPitchGeneratorModule.cpp
```cpp
registerModulationSource(&oscSource);
registerModulationSource(&oscFiltered);
registerModulationSource(&oscFltAmp);
registerModulationSource(&oscFinalOut);
registerModulationSource(&envSource);
registerModulationSource(&pitchNoiseSource);
registerModulationSource(&rhythmClickSource);
```
### process block & sample
```cpp
void RhythmAndPitchGeneratorModule::processBlock(double **inOutBuffer, int numChannels, int numSamples)
{
  ScopedLock scopedLock(*lock);

  const bool doApplyModulations = modulationManager.getNumConnections() != 0;

  const bool doApplySmoothing = smoothingManager->needsSmoothing(); 

  double x, y;

  for (int n = 0; n < numSamples; n++)
  {
    if (doApplySmoothing)
      smoothingManager->updateSmoothedValues();

    // retrieve input point:
    x = inOutBuffer[0] ? inOutBuffer[0][n] : 0.0;
    y = inOutBuffer[1] ? inOutBuffer[1][n] : 0.0;

    if (MIDIMASTER.areNotesHeld() || !envelopeModule->envelope.isSilent())
    {
      for (int i = 0; i < oversampling; i++)
      {
        if (doApplyModulations)
          modulationManager.applyModulations();

        processSampleFrame(&x, &y);

        if (oversampling > 1)
        {
          x = y = antiAliasFilterL.getSampleDirect1(x);
          //y = antiAliasFilterR.getSampleDirect1(y);
        }
      }
    }

    x = y = dcFilter.getSample(x);

    if (inOutBuffer[0]) { inOutBuffer[0][n] = x; }
    if (inOutBuffer[1]) { inOutBuffer[1][n] = y; }    
  }
}

```

**Comment by elanhickler** [comment]
### confirm that things are happening
![image](https://user-images.githubusercontent.com/9116575/46252215-9272f000-c41a-11e8-8b60-1a943ec65612.png)

**Comment by elanhickler** [comment]
Would be nice to get modulation working for RaPG release. Any thoughts on why it might not be working? Let me enable modulation sources in the latest build in case you take a look.

**Comment by elanhickler** [comment]
Overkill is ok for now.

### RhythmAndPitchGeneratorModule.cpp
![image](https://user-images.githubusercontent.com/9116575/46553982-beb3c400-c893-11e8-89ca-1fb370aa0596.png)

I had to comment out for release. Enable if you get to debugging this.

**Comment by elanhickler** [comment]
We released Rhythm and Pitch Generator!: https://www.soundemote.com/labs#rapg

Still need to do video demos, will do them tomorrow (today actually, Saturday) so I can explain how to use the plugin and why it's actually a cool little toy.

Would love to do an update with modulation!!!!!!!!!!!! wink wink!!!!!! 🙃

**Comment by elanhickler** [comment]
im now caught up so you can debug my code with your latest RS-MET

**Comment by RobinSchmidt** [comment]
cool! i like the "Tweaking the envelope" demo. very trancy. that's to my taste. i like the sound of the osc. crisp highs, full lows. did you post-process it by eq or something? i mean, obviously there's reverb, but that's not what i mean...or maybe it plays a role, too? could be. anyway, i posted it on my facebook company page. let me know, when you have videos. then i'll post them, too. i also like the sciency theme of the website (being a great admirer of science myself :-))

ok, i'll attempt a build maybe tomorrow or monday (leaving home soon for saturday night activities)

**Comment by elanhickler** [comment]
crisp highs is because of oversampling and some of your work on antialiasing the trisaw osc. I'm not yet using your latest implementation. There's no EQ.

**Comment by RobinSchmidt** [comment]
it's really surprising how effective this simple asymmetry limiting works for anti-aliasing. with the trisaw osc, we have a nice little piece of dsp code in our toolbag. i'm really happy with it :-)

**Comment by RobinSchmidt** [comment]
> Would love to do an update with modulation!!!!!!!!!!!! wink wink!!!!!! 

i think it may be because you are using ModulatableParameter instead of ModulatableParameter2? i made that subclass ModulatableParameter2 specifically for you so you can use the std::function based callback instead of my homebrewn mechanism

by the way...i got a clean build out of the box. nice. you seem have put a copy of my library into your codebase instead of pointing to it. ..yes....that's a very advisable thing to do - i did it myself with juce

**Comment by elanhickler** [comment]
i don't use that copy for anything except for the old Spiral Generator

**Comment by RobinSchmidt** [comment]
btw. i stumbled yesterday over this video:
https://www.youtube.com/watch?v=VK7XR-wlpAk&t=16m39s
and was immediately thinking of your torus generator. is this what it does?

**Comment by elanhickler** [comment]
modulation works!
