### ISSUE TITLE
Sending a change message crashes plugin

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#244]
I'm trying to update a text display to show the host beats per minute so I call sendChangeMessage on the module in the  `void setBeatsPerMinute()` callback. It crashes half the time when the i call `sendChangeMessage()`, even if I'm not doing anything in the `changeListenereCallback()` function. 

I'm going to try this via jura::Parameter route.

**Comment by elanhickler** [comment]
ModulatableSlider in the editor and ModulatableParameter in the module does the trick.

Really annoying that I don't know how to simply update a text display though.

**Comment by elanhickler** [comment]
off topic note: I'm now using painters. I see the huge value in setting painters now, because I created a subclass of ModulatableSlider for a text widget, but then I wanted that same text widget for an RSlider (non-modulatable slider)... so i would have had to create a whole new copy of the class for Rslider.

Painter is a good idea.

**Comment by elanhickler** [comment]
Scoped pointers solved my leaking object problem.

![image](https://user-images.githubusercontent.com/9116575/46338690-b33b7100-c5e5-11e8-9c3e-2f487b83c59f.png)

**Comment by elanhickler** [comment]
and omg using std::function for text is so nice. I could quickly add "X" to my oversampling text display.

![image](https://user-images.githubusercontent.com/9116575/46339350-68225d80-c5e7-11e8-8e63-491603322a23.png)

**Comment by RobinSchmidt** [comment]
did you check the de-registering code?

**Comment by elanhickler** [comment]
ok, crashes solved. I was needlessly registering parameter observers. and they werent deregistering. I deleted that code.

Ok that still leaves the problem of sendChangeMessage causing crashes.

Why would failing to deregister cause a crash? Deregistering should only take place ... I dunno... when the plugin UI is closed or the plugin is removed? would it cause a crash just by sending a notification?

**Comment by elanhickler** [comment]
alright f*** let me try it.

**Comment by RobinSchmidt** [comment]
> Why would failing to deregister cause a crash

because then the broadcaster keeps a pointer to an object that doesn't exist anymore, i.e. a dangling pointer and my try to send messages to that non-existent object. ...and some hosts seem also to show weird behavior such as creating an editor twice and weird stuff like that, so you can't just assume that the editor is just created once and that's it

**Comment by elanhickler** [comment]
IT WORKS! Thank you. Been at this for hours so confused, making progress but the crashes really dampened my progress.

Man UI programming is f***ing insane.

Robin, one thing you could do that would help me is adding an option for vertical-drag on sliders and being able to set the set the pixel-value increment. I'm currently using .005 per pixel, .0625 per pixel for shift on my SVG knobs.

**Comment by elanhickler** [comment]
Quick question: When should I NOT use a pointer? I could make all my StaticText and TextDisplay painters as variables (non-pointers).

![image](https://user-images.githubusercontent.com/9116575/46347006-e807f200-c5fe-11e8-8160-873e492da245.png)

**Comment by RobinSchmidt** [comment]
> Been at this for hours so confused, making progress but the crashes really dampened my progress.
welcome to the joys of debugging! :-P

> When should I NOT use a pointer? I could make all my StaticText and TextDisplay painters as variables (non-pointers).
yes, in this case, i think, direct members are more appropriate. as a rule of thumb, i would say, use pointers only when the ownership should be transferred to another object or deletion should be managed by a baseclass

**Comment by RobinSchmidt** [comment]
> Robin, one thing you could do that would help me is adding an option for vertical-drag on sliders and being able to set the set the pixel-value increment. 

how can i help with this? do you mean, i should include members for this to RSlider? ...or can you do this in your subclass? ...because every member i add to a basic framework baseclass (especially one that is used en masse like widgets) blows up the memory footprint of all plugins

**Comment by elanhickler** [comment]
Ok, I can do this in my subclass, I have to figure out how not to duplicate the mouse handling code.

**Comment by RobinSchmidt** [comment]
>  I have to figure out how not to duplicate the mouse handling code for my various subclasses.

just make your own baselass and override the mouse-handler there and your various subclasses are subclasses or *your*  slider baseclass (which itself is a subclass of my slider class)

**Comment by elanhickler** [comment]
> just make your own baselass and override the mouse-handler there and your various subclasses are subclasses or your slider baseclass (which itself is a subclass of my slider class)

ModulatableSlider -> VerticalSlider -> SVGKnob
ModulatableSlider -> VerticalSlider -> TextDisplay

the problem is what if I want the base class to be RSlider sometimes? Will have to duplicate .

RSlider -> VerticalSlider -> TextDisplay

**Comment by elanhickler** [comment]
f*** it I'm duplicating my mouse handling code.

**Comment by RobinSchmidt** [comment]
ok - yes - in this case, what i have suggested wouldn't work. quite similar design problem as with the parameters (when adding features, like modulatability, smoothing, and meta-control). hmm...yeah...maybe using mouse handling objects could be a solution. that would be the "Strategy" design pattern, if you want to look it up

**Comment by elanhickler** [comment]
g*d da**it, I'm using RSliderPainter which doesn't handle mouse handling, so I'll have to NOT use painters in order to subclass the ModulatableSlider properly.

Hmm... it would almost make sense if RSliderPainter also contained mouse handling..... 🙂 ey? ey?

**Comment by elanhickler** [comment]
or I could say  **** it and everything is going to be a modulatable slider, and use a text display painter on SVG knobs.

**Comment by RobinSchmidt** [comment]
> I'll have to NOT use painters in order to subclass the ModulatableSlider properly.

what? why that? ModulatableSlider is a subclass of RSlider and as such, it supports painters, too

>  it would almost make sense if RSliderPainter also contained mouse handling

i think, that would be bad design. painting and mouse handling are unrelated. if anything, there should be separate handlers - one for each

> or I could say **** it and everything is going to be a modulatable slider

if you don't mind the extra data that ModulatableSlider stores which you don't need, you can do this, too. maybe that's not exactly very elegant, but it should work

**Comment by elanhickler** [comment]
I just don't want people to modulate oversampling.

>>I'll have to NOT use painters in order to subclass the ModulatableSlider properly.

>what? why that? ModulatableSlider is a subclass of RSlider and as such, it supports painters, too

I'm just saying that painter's can't change the mouse handling, so I'll need to subclass RSlider or ModulatableSlider instead of using a painter.

**Comment by RobinSchmidt** [comment]
>  I'll need to subclass RSlider or ModulatableSlider instead of using a painter.

why "instead of"? in addition to

> I just don't want people to modulate oversampling.

maybe just try to use a non-modulatable parameter. if i'm not mistaken, the popup menu should then not show the "Modulation setup" option

**Comment by elanhickler** [comment]
> why "instead of"? in addition to
either or.

I find myself having to create a new UI class for every unique element on the interface. This is the learning process, I need to know what is practical to include in a larger customizable class versus smaller classes with repeated code, and maybe attempt to reduce repeated code with lots of base classes, but then too many base classes would be too confusing.

AGGGHH!

**Comment by RobinSchmidt** [comment]
as a general rule: repeated code is always bad, unless it's really short and trivial

**Comment by elanhickler** [comment]
ok this thread can be closed!
