### ISSUE TITLE
rsRoundToInt mac error still not fixed

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#246]
please fix. Build RhythmAndPitchGenerator and you'll see the error is coming from jura::rsNodeBasedFunctionEditor::setupNodeParameterCallbacks

symbol not found

edit: i only got the error doing a release build

edit: i replaced rsRoundToInt with (int)round(), build successful.

**Comment by RobinSchmidt** [comment]
i now do it internally in rsRoundToInt like that too and inlined the function. ..should probably work now
