### ISSUE TITLE
How do I update my own text widget for preset name change?

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#248]
Need to do this for my preset text. I did override updateWidgetsAccordingToState but the problem is that it doesn't update text for saving a preset, because that's not a state change.

In terms of load/save/prev/next buttons I'm just laying the stateWidgetSet with very low opacity on top of my dummy graphic.

![image](https://user-images.githubusercontent.com/9116575/46408757-0ab20d80-c6c8-11e8-8a6c-b3de22405b0b.png)

**Comment by RobinSchmidt** [comment]
i would try to override `saveStateToXmlFile `(inherited from `StateFileManager`). call the baseclass method in your override and then repaint on your text widget (or whatever else you need to update it)

**Comment by elanhickler** [comment]
WORKS
