### ISSUE TITLE
trying to modulate one pole filter, but response is extremely non-linear

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#25]
How do I correct for the extremely non-linear modulation of the one pole filter? Like for example, if I modulate rosic::OnePoleFilter by calling setCutoff, it doesn't sound like it really starts filtering until a very tiny portion of the modulation.

What math should I use to convert the modulation to be more compatible with it?

**Comment by RobinSchmidt** [comment]
non-linear modulation? what do you mean by that?

**Comment by elanhickler** [comment]
i guess it's the problem of modulating a the cutoff with a linear slider. imagine going from 0 to 1 with a slider to modulate cutoff and the effective range is between 0 and .01

**Comment by RobinSchmidt** [comment]
can you show me some code? do you have an lof and do things like: 
`setCutoff(centerCutoff + depth * lfo.getSample())`? 
in this case, you would linearly modulate the cutoff frequency around some center value. however, frequencies are perceived logarithmically, so you may want an exponential modulation. for example, you could do:
`setCutoff(centerCutoff * pitchOffsetToFreqFactor(depth * lfo.getSample()))`
assuming that your lfo output is between -1...+1, then "depth" would be in semitones (in the former case, it would be in Hz)

**Comment by RobinSchmidt** [comment]
so, if depth=12 and centerCutoff=1000, you would one octave up and one octave down, i.e. modulate between 500 and 2000 Hz

**Comment by RobinSchmidt** [comment]
with envelopes, i typically also just multiply the basic cutoff value with the envelope output (although that's, as far as i know, not what analog synths do - they add the envelope output). however, i prefer multiplication, so you have a kind of wysiwyg behavior if you would plot a spectrogram with a linear frequency axis

**Comment by elanhickler** [comment]
hmm, pitchOffsetToFreqFactor seems to go in the wrong direction for envelope modulation. It makes the problem worse. I need the inverse of that... weird.

**Comment by RobinSchmidt** [comment]
the inverse? i have also a function freqFactorToPitchOffset - but somehow i can't see, how that would be useful in this case. for envelopes, i typically just multiply my basic cutoff value with the raw output value of the envelope
