### ISSUE TITLE
Need more advanced metaparameter setup

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#250]
First, I need access to `autoUpdateMetaNames` in RS-MET\Libraries\JUCE\modules\jura_framework\control\jura_MetaParameter.h

Not sure how this all works, but essentially we need two behaviors

1. Default connected parameters setup during runtime.
2. Additional connected parameters setup by user.

Default connected parameters of course should not have the `updateMetaName` thing, which currently makes it impossible to properly name my default-connected metaparameters. Also, these parameters should not be able to be disconnected.

Ultimately we need a better user interface for metaparameters to properly separate default and user connected metaparameters. For now, I just need to be able to set the name of the default connected parameters.

Use case is this: My plugins will have the main parameters automatically connected. Then the user may add or remove envelopes/lfos/modulators. The user may want to control some additional plugin components' parameters via host. The better interface (which I will be responsible to create) will allow the user to add/remove/organize the metaparameter connections.

**Comment by RobinSchmidt** [comment]
ok - so this means, the problem is solved?

**Comment by elanhickler** [comment]
for now
