### ISSUE TITLE
Emergency: Mac build issues, sale starts in 3 hours!

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#258]
Try building Radar Generator, I get a bunch of errors from your library. Please solve! My sale starts in 3 hours!

**Comment by RobinSchmidt** [comment]
i was already asleep when you posted this. however, Radar Generator builds fine over here

**Comment by elanhickler** [comment]
Yes, looks like debug version succeeds building. You are not building release version by doing "build for run" you have to switch to "Relese".

Product --> Scheme --> Edit Scheme --> Run --> Build Confirguation --> Release

**Comment by elanhickler** [comment]
yayyy
