### ISSUE TITLE
How did we solve the "slider not showing current value" problem?

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#259]
For example, if Radar Generator does not load the init preset at startup, the Density will read "1", the slider position is "0", the internal value is "1", so you hear "1", when you move the slider with mouse you hear the value jump to "0".

**Comment by RobinSchmidt** [comment]
hmm - i just wanted to try this but i don't see you RadarGenerator directory in your AudioPlugins directory. so, the slider drawing is not in sync with the value of the underlying parameter?

**Comment by RobinSchmidt** [comment]
i can imagine that the "normalizedValue" of the underlying Parameter is not in sync with the "value":
![image](https://user-images.githubusercontent.com/1833099/47945727-3d883500-df04-11e8-936d-8c53535ad671.png)

where do you create and initialize the parameter?

**Comment by RobinSchmidt** [comment]
ok - this should be fixed

**Comment by elanhickler** [comment]
nieece. I don't use myparams anymore, moving forward i will be using vanilla ModulatableParameter2

**Comment by RobinSchmidt** [comment]
good. i always found this confusing
