### ISSUE TITLE
Is this a thread crash? Trying to get preset name/category/author/description to work.

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#262]
I just solved this by making `Module` the owner of `PresetInformation` instead of `Module` accessing a pointer to `PresetInformation` through a Listener class which holds `PresetInformation` pointer. Crash is caused by `PresetInformation` trying to access its own struct.

I have no idea how to debug this kind of stuff. Maybe it's because I was using the fancy Juce::ListenerList when I shouldn't be. You should probably think about adding real String parameters. I have no idea how thread safety and threads work. I tried using `CriticalLock` and `ScopedLock` like you do inside your xml functions, but that didn't work.

![image](https://user-images.githubusercontent.com/9116575/48419728-eb21f200-e715-11e8-959c-5b2dc727c2a5.png)

**Comment by RobinSchmidt** [comment]
Module? PresetInformation? are these classes from your framework? i would need more background information

**Comment by elanhickler** [comment]
Yes, those are my classes. No point in trying to debug this. A more productive solution would be to add string based parameters or I need to learn some basics on JUCE threads.

**Comment by RobinSchmidt** [comment]
what do you mean by string based parameters? apparently it must be something different from what my Parameter class already has.

**Comment by elanhickler** [comment]
see: https://github.com/RobinSchmidt/RS-MET/issues/221#issuecomment-427380434

**Comment by elanhickler** [comment]
Well looks like I'm doing what you suggested, storing the string parameters in my audio module.

**Comment by RobinSchmidt** [comment]
that seems to me the most straightforward solution, if you want to store some (meta) information in presets. a "string-parameter" would actually be nothing more than a key/value pair where both, key and value are of class string. maybe you could make a class StringPair for that, if you want...or maybe even a general KeyValuePair<KeyType, ValueType> template class (i actually had such a class in RSLib). juce also has the class StringPairArray which seems to be made for this purpose

**Comment by RobinSchmidt** [comment]
but ok - if you need a sort of change-notification system (like a valueChanged callback that can be picked up by a widget), then  maybe a dedicated class would be appropriate

**Comment by RobinSchmidt** [comment]
maybe, if desired, i could integrate that KeyValuePair class into rosic (if i didn't do that already...not sure, actually) and add a notification system (but maybe in a subclass)

**Comment by elanhickler** [comment]
Ok, still working out my preset system, not sure how I will update widgets yet, but I'll probably figure it out.

**Comment by elanhickler** [comment]
Can't figure it out, I just get a crash, trying to use scopedLock, but didn't work.

![image](https://user-images.githubusercontent.com/9116575/48581153-40a8fb00-e8de-11e8-995f-7a16995d2783.png)
