### ISSUE TITLE
For antialiasing, what if we switch to additive at high frequency?

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#268]
What if we switched to additive to generate the waveform, such as a sawtooth, when it becomes efficient (when the number of sines required is low?) At 1000hz, we need 20 sines, at 2000hz we need 10 sines, 5000hz we only need 4.

I'm probably not the first to think about doing this.

**Comment by RobinSchmidt** [comment]
well, i already do *switch* the wavetable dependent on frequency - why would i want to switch the complete algorithm? efficiency? i think, table-readout isn't too expensive and the code for switching between the different versions of the tables can be made efficient with some bit-trickery
