### ISSUE TITLE
jim had strong suggestions for the spiral generator GUI, what is easy to change?

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#27]
#1 change color of sliders, that could help draw attention to important ones. Is that easy, how do I do it? 

#2 change size of sliders, that's easy I can do that.

#3 add lines/dividers

#4 add header text

**Comment by RobinSchmidt** [comment]
changing colors should be easy: use setColourScheme (member function of RWidget, the baseclass for all widgets). you need to pass in an object of type WidgetColourScheme which defines colors for various aspect of widgets.

for adding lines, dividers and arbitrary text, you can override the editor's paint method and there call drawLine, etc. for dividing the a into various areas, i like to use this gradient-background rectangle. look at my FuncShaperModuleEditor to see, how this can be done.

**Comment by elanhickler** [comment]
Robiiin plzzz spell it out for me, I tried that. Could you give me example code for changing a slider handle to red? I think for now I will just change some slider handles

**Comment by elanhickler** [comment]
so far I got this:
![](https://puu.sh/w862m/f8d68c187a.png)

**Comment by RobinSchmidt** [comment]
yes - that needs some organization. maybe you could make sections: Performance (gain, tune, glide,... - i think also oversampling and smoothing belongs there), Shape (the big sliders), View (rotate, depth, offset), LFOs, Envelopes

**Comment by elanhickler** [comment]
noooo please just tell me how to change the slider color (example code), that's all I want to do and I'm done with this project for now.

**Comment by RobinSchmidt** [comment]
ahhh...right...that's not as easy as i thought at first. i need to look into this.

**Comment by elanhickler** [comment]
i get 282 errors when using your new library. Is there a module that needs to be added?

**Comment by RobinSchmidt** [comment]
i added some example code to SpiralGeneratorEditor::createWidgets. there's now a 
```
 jura::WidgetColourScheme colorScheme;
  colorScheme.setAppearance(WidgetColourScheme::BRIGHT_ON_DARK);
  colorScheme.setSaturationMultiplier(0.5);
  colorScheme.setCentralHue(0.75);
  colorScheme.setBrightnessGamma(0.5);
```
to set up a color scheme, and later, you must pass that to the widgets in question, for example, i added to the gainSlider construction code: `s->setColourScheme(colorScheme);`.

**Comment by RobinSchmidt** [comment]
within my framework, i don't define colors directly but indirectly by letting the user choose a general bright-on-dark or dark-on-bright appearance, then hue, saturation, etc.
