### ISSUE TITLE
all of a sudden a ton of build errors

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#277]
I was messing with trying to use the new envelope follower `EnvelopeFollower2` and then all of a sudden none of my projects build. I didn't update the repository when this happened.

Edit: If you want to build one of my projects use FlowerChildFilter or OMS

Most errors come from expression evaluator. It can't find an include file.

**Comment by RobinSchmidt** [comment]
i can't generate the project files from the jucer file. it seems like it's missing the "ElanJuceHelpers" module ("cannot find the module at the specified path"). what do you mean by "I didn't update the repository when this happened."?

**Comment by elanhickler** [comment]
added a link to all dependencies to Soundemote readme so you shouldn't be confused next time: https://gitlab.com/Hickler/Soundemote/edit/master/README.md

ElanJuceHelpers is here: https://gitlab.com/Hickler/elanjucehelpers

**Comment by RobinSchmidt** [comment]
i can build FlowerChildFilter alright (standalone Win32 and x64). i added an accessor function StateWatcher::getWatchedStateManager, so you don't need to unprotect the watchedStateManager member anymore and fixed a couple of other issues specific to Win32 builds. but none of the errors you posted above appeared over here.  

it seems like your code does not reference your copy of RS-MET residing in your codebase but my version sitting right next to the "Soundemote" main folder. is that intentional?

**Comment by elanhickler** [comment]
ok i fixed all the errors, it built after commenting out a lot of code and adding jura:: to things to fix ambiguous symbol. What if it's my build system? I am using VS2019 v141 toolset?

**Comment by RobinSchmidt** [comment]
> it built after commenting out a lot of code and adding jura:: to things to fix ambiguous symbol 

oh - it looks like i have a class called "AudioModule" also in the legacy folder of rosic. but actually, the relevant .h file is not included from rosic.h (nothing from the legacy folder is - that's its purpose), so that legacy code should actually be invisible to the compiler - unless you have included these files from somewhere else. ...what did you comment out? ...i guess, i should also switch to vs2109

**Comment by RobinSchmidt** [comment]
yes - all your errors seem to have something to do with code form this legacy folder - that code is supposed to be dead. i just still keep it around, just in case, i want to look up how i did some things back then. the question is why your compiler sees this code

**Comment by RobinSchmidt** [comment]
> i guess, i should also switch to vs2109

i just installed it. i can build flowerChildFilter with it, too. but it seems like i have to use the vs2015 exporter of the projucer regardless, because the vs2019 exporter doesn't correctly add the custom module path. 


VS2015 exporter - correct path setting:
![image](https://user-images.githubusercontent.com/1833099/58278613-b49bf280-7d9c-11e9-8914-a133dd64b7ca.png)


VS2019 exporter - projucer apparently want's me to use c:/modules for my custom juce modules. no way!
![image](https://user-images.githubusercontent.com/1833099/58278731-f5940700-7d9c-11e9-941b-92c3cc367a83.png)

**Comment by elanhickler** [comment]
Are you sure about that? Check your modules paths. I think you're just getting the default path.

![image](https://user-images.githubusercontent.com/9116575/58280576-c60ddc00-7d55-11e9-8565-50bc541605f5.png)

**Comment by RobinSchmidt** [comment]
you are right! i didn't know, that i have to set the module path there. now the 2019 exporter works! yay! i'm up to date again with my dev setup.

**Comment by elanhickler** [comment]
Still getting same errors trying to build Flower Child Filter after pulling the latest RS-MET

**Comment by elanhickler** [comment]
```
Error	C1083	Cannot open include file: 'ExprEval\expreval.h': No such file or directory (compiling source file ..\..\Source\FlowerChildFilterModule.cpp)	Flower Child Filter_SharedCode	D:\_PROGRAMMING\RS-MET\Libraries\RobsJuceModules\rosic\legacy\ExpressionEvaluator.h	4	
Error	C1083	Cannot open include file: 'ExprEval\expreval.h': No such file or directory (compiling source file ..\..\Source\FlowerChildFilterEditor.cpp)	Flower Child Filter_SharedCode	D:\_PROGRAMMING\RS-MET\Libraries\RobsJuceModules\rosic\legacy\ExpressionEvaluator.h	4	
Error	C1083	Cannot open include file: 'ExprEval\expreval.h': No such file or directory (compiling source file ..\..\Source\FlowerChildFilterCore.cpp)	Flower Child Filter_SharedCode	D:\_PROGRAMMING\RS-MET\Libraries\RobsJuceModules\rosic\legacy\ExpressionEvaluator.h	4	
Error	C1083	Cannot open include file: 'ExprEval\expreval.h': No such file or directory (compiling source file ..\..\JuceLibraryCode\include_se_framework.cpp)	Flower Child Filter_SharedCode	D:\_PROGRAMMING\RS-MET\Libraries\RobsJuceModules\rosic\legacy\ExpressionEvaluator.h	4	
Error	C1083	Cannot open include file: 'ExprEval\expreval.h': No such file or directory (compiling source file ..\..\FlowerChildFilter.cpp)	Flower Child Filter_SharedCode	D:\_PROGRAMMING\RS-MET\Libraries\RobsJuceModules\rosic\legacy\ExpressionEvaluator.h	4	
Error	C2872	'AudioModule': ambiguous symbol (compiling source file ..\..\Source\FlowerChildFilterModule.cpp)	Flower Child Filter_SharedCode	D:\_PROGRAMMING\RS-MET\Libraries\RobsJuceModules\rosic\legacy\AudioModule.h	78	
Error	C2872	'AudioModule': ambiguous symbol (compiling source file ..\..\Source\FlowerChildFilterModule.cpp)	Flower Child Filter_SharedCode	D:\_PROGRAMMING\RS-MET\Libraries\RobsJuceModules\rosic\legacy\AudioModule.h	82	
Error	C2872	'AudioModule': ambiguous symbol (compiling source file ..\..\Source\FlowerChildFilterModule.cpp)	Flower Child Filter_SharedCode	D:\_PROGRAMMING\RS-MET\Libraries\RobsJuceModules\rosic\legacy\AudioModule.h	93	
Error	C2872	'AudioModule': ambiguous symbol (compiling source file ..\..\Source\FlowerChildFilterModule.cpp)	Flower Child Filter_SharedCode	D:\_PROGRAMMING\RS-MET\Libraries\RobsJuceModules\rosic\legacy\AudioModule.h	104	
Error	C2872	'AudioModule': ambiguous symbol (compiling source file ..\..\Source\FlowerChildFilterModule.cpp)	Flower Child Filter_SharedCode	D:\_PROGRAMMING\RS-MET\Libraries\RobsJuceModules\rosic\legacy\AudioModule.h	115	
Error	C2872	'AudioModule': ambiguous symbol (compiling source file ..\..\Source\FlowerChildFilterModule.cpp)	Flower Child Filter_SharedCode	D:\_PROGRAMMING\RS-MET\Libraries\RobsJuceModules\rosic\legacy\TwoPoleBandpass.h	16	
Error	C2872	'AudioModule': ambiguous symbol (compiling source file ..\..\Source\FlowerChildFilterModule.cpp)	Flower Child Filter_SharedCode	D:\_PROGRAMMING\RS-MET\Libraries\RobsJuceModules\rosic\legacy\Upsampler.h	17	
Error	C2872	'AudioModule': ambiguous symbol (compiling source file ..\..\Source\FlowerChildFilterEditor.cpp)	Flower Child Filter_SharedCode	D:\_PROGRAMMING\RS-MET\Libraries\RobsJuceModules\rosic\legacy\AudioModule.h	78	
Error	C2872	'AudioModule': ambiguous symbol (compiling source file ..\..\Source\FlowerChildFilterEditor.cpp)	Flower Child Filter_SharedCode	D:\_PROGRAMMING\RS-MET\Libraries\RobsJuceModules\rosic\legacy\AudioModule.h	82	
Error	C2872	'AudioModule': ambiguous symbol (compiling source file ..\..\Source\FlowerChildFilterEditor.cpp)	Flower Child Filter_SharedCode	D:\_PROGRAMMING\RS-MET\Libraries\RobsJuceModules\rosic\legacy\AudioModule.h	93	
Error	C2872	'AudioModule': ambiguous symbol (compiling source file ..\..\Source\FlowerChildFilterEditor.cpp)	Flower Child Filter_SharedCode	D:\_PROGRAMMING\RS-MET\Libraries\RobsJuceModules\rosic\legacy\AudioModule.h	104	
Error	C2872	'AudioModule': ambiguous symbol (compiling source file ..\..\Source\FlowerChildFilterEditor.cpp)	Flower Child Filter_SharedCode	D:\_PROGRAMMING\RS-MET\Libraries\RobsJuceModules\rosic\legacy\AudioModule.h	115	
Error	C2872	'AudioModule': ambiguous symbol (compiling source file ..\..\Source\FlowerChildFilterEditor.cpp)	Flower Child Filter_SharedCode	D:\_PROGRAMMING\RS-MET\Libraries\RobsJuceModules\rosic\legacy\TwoPoleBandpass.h	16	
Error	C2872	'AudioModule': ambiguous symbol (compiling source file ..\..\Source\FlowerChildFilterEditor.cpp)	Flower Child Filter_SharedCode	D:\_PROGRAMMING\RS-MET\Libraries\RobsJuceModules\rosic\legacy\Upsampler.h	17	
Error	C2872	'AudioModule': ambiguous symbol (compiling source file ..\..\Source\FlowerChildFilterCore.cpp)	Flower Child Filter_SharedCode	D:\_PROGRAMMING\RS-MET\Libraries\RobsJuceModules\rosic\legacy\AudioModule.h	78	
Error	C2872	'AudioModule': ambiguous symbol (compiling source file ..\..\Source\FlowerChildFilterCore.cpp)	Flower Child Filter_SharedCode	D:\_PROGRAMMING\RS-MET\Libraries\RobsJuceModules\rosic\legacy\AudioModule.h	82	
Error	C2872	'AudioModule': ambiguous symbol (compiling source file ..\..\Source\FlowerChildFilterCore.cpp)	Flower Child Filter_SharedCode	D:\_PROGRAMMING\RS-MET\Libraries\RobsJuceModules\rosic\legacy\AudioModule.h	93	
Error	C2872	'AudioModule': ambiguous symbol (compiling source file ..\..\Source\FlowerChildFilterCore.cpp)	Flower Child Filter_SharedCode	D:\_PROGRAMMING\RS-MET\Libraries\RobsJuceModules\rosic\legacy\AudioModule.h	104	
Error	C2872	'AudioModule': ambiguous symbol (compiling source file ..\..\Source\FlowerChildFilterCore.cpp)	Flower Child Filter_SharedCode	D:\_PROGRAMMING\RS-MET\Libraries\RobsJuceModules\rosic\legacy\AudioModule.h	115	
Error	C2872	'AudioModule': ambiguous symbol (compiling source file ..\..\Source\FlowerChildFilterCore.cpp)	Flower Child Filter_SharedCode	D:\_PROGRAMMING\RS-MET\Libraries\RobsJuceModules\rosic\legacy\TwoPoleBandpass.h	16	
Error	C2872	'AudioModule': ambiguous symbol (compiling source file ..\..\Source\FlowerChildFilterCore.cpp)	Flower Child Filter_SharedCode	D:\_PROGRAMMING\RS-MET\Libraries\RobsJuceModules\rosic\legacy\Upsampler.h	17	
Error	C2872	'AudioModule': ambiguous symbol (compiling source file ..\..\JuceLibraryCode\include_se_framework.cpp)	Flower Child Filter_SharedCode	D:\_PROGRAMMING\RS-MET\Libraries\RobsJuceModules\rosic\legacy\AudioModule.h	78	
Error	C2872	'AudioModule': ambiguous symbol (compiling source file ..\..\JuceLibraryCode\include_se_framework.cpp)	Flower Child Filter_SharedCode	D:\_PROGRAMMING\RS-MET\Libraries\RobsJuceModules\rosic\legacy\AudioModule.h	82	
Error	C2872	'AudioModule': ambiguous symbol (compiling source file ..\..\JuceLibraryCode\include_se_framework.cpp)	Flower Child Filter_SharedCode	D:\_PROGRAMMING\RS-MET\Libraries\RobsJuceModules\rosic\legacy\AudioModule.h	93	
Error	C2872	'AudioModule': ambiguous symbol (compiling source file ..\..\JuceLibraryCode\include_se_framework.cpp)	Flower Child Filter_SharedCode	D:\_PROGRAMMING\RS-MET\Libraries\RobsJuceModules\rosic\legacy\AudioModule.h	104	
Error	C2872	'AudioModule': ambiguous symbol (compiling source file ..\..\JuceLibraryCode\include_se_framework.cpp)	Flower Child Filter_SharedCode	D:\_PROGRAMMING\RS-MET\Libraries\RobsJuceModules\rosic\legacy\AudioModule.h	115	
Error	C2872	'AudioModule': ambiguous symbol (compiling source file ..\..\JuceLibraryCode\include_se_framework.cpp)	Flower Child Filter_SharedCode	D:\_PROGRAMMING\RS-MET\Libraries\RobsJuceModules\rosic\legacy\TwoPoleBandpass.h	16	
Error	C2872	'AudioModule': ambiguous symbol (compiling source file ..\..\JuceLibraryCode\include_se_framework.cpp)	Flower Child Filter_SharedCode	D:\_PROGRAMMING\RS-MET\Libraries\RobsJuceModules\rosic\legacy\Upsampler.h	17	
Error	C2872	'AudioModule': ambiguous symbol (compiling source file ..\..\FlowerChildFilter.cpp)	Flower Child Filter_SharedCode	D:\_PROGRAMMING\RS-MET\Libraries\RobsJuceModules\rosic\legacy\AudioModule.h	78	
Error	C2872	'AudioModule': ambiguous symbol (compiling source file ..\..\FlowerChildFilter.cpp)	Flower Child Filter_SharedCode	D:\_PROGRAMMING\RS-MET\Libraries\RobsJuceModules\rosic\legacy\AudioModule.h	82	
Error	C2872	'AudioModule': ambiguous symbol (compiling source file ..\..\FlowerChildFilter.cpp)	Flower Child Filter_SharedCode	D:\_PROGRAMMING\RS-MET\Libraries\RobsJuceModules\rosic\legacy\AudioModule.h	93	
Error	C2872	'AudioModule': ambiguous symbol (compiling source file ..\..\FlowerChildFilter.cpp)	Flower Child Filter_SharedCode	D:\_PROGRAMMING\RS-MET\Libraries\RobsJuceModules\rosic\legacy\AudioModule.h	104	
Error	C2872	'AudioModule': ambiguous symbol (compiling source file ..\..\FlowerChildFilter.cpp)	Flower Child Filter_SharedCode	D:\_PROGRAMMING\RS-MET\Libraries\RobsJuceModules\rosic\legacy\AudioModule.h	115	
Error	C2872	'AudioModule': ambiguous symbol (compiling source file ..\..\FlowerChildFilter.cpp)	Flower Child Filter_SharedCode	D:\_PROGRAMMING\RS-MET\Libraries\RobsJuceModules\rosic\legacy\TwoPoleBandpass.h	16	
Error	C2872	'AudioModule': ambiguous symbol (compiling source file ..\..\FlowerChildFilter.cpp)	Flower Child Filter_SharedCode	D:\_PROGRAMMING\RS-MET\Libraries\RobsJuceModules\rosic\legacy\Upsampler.h	17	
```

**Comment by RobinSchmidt** [comment]
wtf? can you figure out why your compiler sees h/cpp files from the legacy folder? some file in one of your compilation unit must be including these files. but why would this happen only on your machine? and which configuration are you building?

**Comment by RobinSchmidt** [comment]
that's, what happens over here:
![image](https://user-images.githubusercontent.com/1833099/58297706-f5b1f800-7dd8-11e9-9e8d-f6cedc0574ec.png)

**Comment by elanhickler** [comment]
how could our compile settings be different? What toolset are you using? That shouldn't matter, that's controlled by the jucer file. Our settings should be the same................

**Comment by elanhickler** [comment]
Alejandro, the other guy I work with, was able to compile it as well... the OMS plugin that is. WHAT'S WRONG WTIH MEEEEEEEEEEEE.

**Comment by RobinSchmidt** [comment]
maybe try the following: rename (or temporarily delete) that whole legacy folder from the rosic source tree. as said - code from there is not supposed to be used anywhere or even seen by the compiler. try to build and see, if some of your compilation units (like FlowerChildFilter.cpp or whatever) balks about missing include files. then you have found the place that erroneously these files. check out, why - get rid of the includes

**Comment by RobinSchmidt** [comment]
>  I am using VS2019 v141 toolset.

i'm using the vs2015 exporter (from your jucer file - in my version, there is no vs2019 exporter yet - have you just added one?) with toolset setting: "Default (v140)"

**Comment by elanhickler** [comment]
pfffffFFFTT!! HAHAHAHAHA WHAT IS THIS

![image](https://user-images.githubusercontent.com/9116575/58318402-87673880-7dcc-11e9-9983-91b1bf87575b.png)

WHYYY DID I DO THIS?

**Comment by RobinSchmidt** [comment]
where is this and why has it no effect on my machine?

**Comment by RobinSchmidt** [comment]
maybe you didn't commit/push this to the repo?
![image](https://user-images.githubusercontent.com/1833099/58318995-36316600-7e19-11e9-88f8-ab75f454ceed.png)

**Comment by elanhickler** [comment]
I definitely committed it.
![image](https://user-images.githubusercontent.com/9116575/58319894-59372800-7dcf-11e9-8d2a-18fe3e04106e.png)

And I know what happened. The VS2019 intellisense added that include for me, I must have pressed something and intellisense added the "necessary include" (not at all necessary). VS2019 can add includes for you now based on missing definitions.

**Comment by RobinSchmidt** [comment]
> VS2019 can add includes for you now based on missing definitions.

how "helpful". during installation, i've even seen some option for "AI-assisted development". i disabled that (i think...hope......the installation process was messy because i wanted to have an offline installer...which was...messy)

**Comment by RobinSchmidt** [comment]
but what's really good is that the code-completion feature finally works (more or less) smoothly with the unity build system. that feature totally failed in vs2015
