### ISSUE TITLE
Please compile Mac, need to release Flower Child filter update!

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#279]
Robin, please attempt to compile mac. I want to release a new product ASAP and I know that Mac always fails to compile. Please attempt to compile your ToolChain on Mac and let me know how it goes.

**Comment by RobinSchmidt** [comment]
it seems, i'm running into this issue:
https://forum.juce.com/t/building-projucer-5-3-2-with-xcode-7/28179/1
...tried to install a new version of xcode as recommended - which doesn't work because it says my osx is too old for the new version of xcode! did you try it yourself? which issues do you run into?

**Comment by RobinSchmidt** [comment]
>Mac always fails to compile

indeed! it's so annoying! :-(

**Comment by RobinSchmidt** [comment]
i just discovered this:
https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started/what-is-azure-pipelines?view=azure-devops
considering to try it. integrates with github, is free for public projects and even for private projects with a 30 hour/month limit, which should be more than enough for the occasional mac build

**Comment by elanhickler** [comment]
/Users/elan/Desktop/RS-MET/Libraries/RobsJuceModules/rapt/Basics/Plotting.h:53:3: Use of undeclared identifier 'RAPT'

/Users/elan/Desktop/RS-MET/Libraries/RobsJuceModules/rapt/Basics/Plotting.h:108:3: Use of undeclared identifier 'RAPT'

/Users/elan/Desktop/RS-MET/Libraries/RobsJuceModules/rapt/Basics/Plotting.h:121:3: Use of undeclared identifier 'RAPT'

/Users/elan/Desktop/RS-MET/Libraries/RobsJuceModules/rapt/Data/Buffers.h

/Users/elan/Desktop/RS-MET/Libraries/RobsJuceModules/rapt/Data/Buffers.h:38:35: Member initializer 'rsBuffer' does not name a non-static data member or base class

/Users/elan/Desktop/RS-MET/Libraries/RobsJuceModules/rapt/Data/Buffers.h:59:5: Use of undeclared identifier 'data'

/Users/elan/Desktop/RS-MET/Libraries/RobsJuceModules/rapt/Data/Buffers.h:60:13: Use of undeclared identifier 'data'; did you mean 'atan'?

/Users/elan/Desktop/RS-MET/Libraries/RobsJuceModules/rapt/Data/Buffers.h:72:12: Use of undeclared identifier 'data'; did you mean 'juce::MidiBuffer::data'?

/Users/elan/Desktop/RS-MET/Libraries/RobsJuceModules/rapt/Data/Buffers.h:74:11: Use of undeclared identifier 'wrap'

/Users/elan/Desktop/RS-MET/Libraries/RobsJuceModules/rapt/Data/Buffers.h:75:10: Use of undeclared identifier 'data'

/Users/elan/Desktop/RS-MET/Libraries/RobsJuceModules/rapt/Data/Buffers.h:76:14: Use of undeclared identifier 'data'; did you mean 'juce::MidiBuffer::data'?

/Users/elan/Desktop/RS-MET/Libraries/RobsJuceModules/rapt/Data/Buffers.h:135:5: Use of undeclared identifier 'data'

/Users/elan/Desktop/RS-MET/Libraries/RobsJuceModules/rapt/Data/Buffers.h:143:5: Use of undeclared identifier 'data'

Too many errors emitted, stopping now

**Comment by RobinSchmidt** [comment]
did you get past the juce build errors? did you update your mac os? for the undeclared identifier RPT error - can you try to change the include order in rapt.h from:
```cpp
#include "Basics/Plotting.h"
#include "Basics/Basics.h"  
#include "Data/Data.h"
```
to
```cpp
#include "Basics/Basics.h"  
#include "Basics/Plotting.h"
#include "Data/Data.h"
```
or, if that is not enough, to
```cpp
#include "Basics/Basics.h"  
#include "Data/Data.h"
#include "Basics/Plotting.h"
```

**Comment by RobinSchmidt** [comment]
for the "Use of undeclared identifier 'data'" - can you try to replace the references to `data` by `this->data`

**Comment by RobinSchmidt** [comment]
"can you try to change the include order" - or wait - no - i'll try something else....

**Comment by RobinSchmidt** [comment]
> "can you try to change the include order" - or wait - no - i'll try something else....

ok - i have un-inlined and moved those parts of the Plotting.g into Plotting.cpp that call functions from rapt. i hope that this should fix the first error. changing the include order is less desirable because then i could not inject plotting commands into my code anymore in those files that are included before including Plotting.h. ..and i think - especially for rsArray - it can be useful to be able to plot stuff there for debugging

**Comment by elanhickler** [comment]
I have not updated mac os. Maybe I need to abandon my virtual mac.

/Users/elan/Desktop/RS-MET/Libraries/RobsJuceModules/rapt/Data/Buffers.h

/Users/elan/Desktop/RS-MET/Libraries/RobsJuceModules/rapt/Data/Buffers.h:38:35: Member initializer 'rsBuffer' does not name a non-static data member or base class

/Users/elan/Desktop/RS-MET/Libraries/RobsJuceModules/rapt/Data/Buffers.h:59:5: Use of undeclared identifier 'data'

/Users/elan/Desktop/RS-MET/Libraries/RobsJuceModules/rapt/Data/Buffers.h:60:13: Use of undeclared identifier 'data'; did you mean 'atan'?
/Users/elan/Desktop/RS-MET/Libraries/RobsJuceModules/rapt/Data/Buffers.h:72:12: Use of undeclared identifier 'data'; did you mean 'juce::MidiBuffer::data'?
/Users/elan/Desktop/RS-MET/Libraries/RobsJuceModules/rapt/Data/Buffers.h:74:11: Use of undeclared identifier 'wrap'
/Users/elan/Desktop/RS-MET/Libraries/RobsJuceModules/rapt/Data/Buffers.h:75:10: Use of undeclared identifier 'data'
/Users/elan/Desktop/RS-MET/Libraries/RobsJuceModules/rapt/Data/Buffers.h:76:14: Use of undeclared identifier 'data'; did you mean 'juce::MidiBuffer::data'?

/Users/elan/Desktop/RS-MET/Libraries/RobsJuceModules/rapt/Data/Buffers.h:135:5: Use of undeclared identifier 'data'

/Users/elan/Desktop/RS-MET/Libraries/RobsJuceModules/rapt/Data/Buffers.h:143:5: Use of undeclared identifier 'data'

/Users/elan/Desktop/RS-MET/Libraries/RobsJuceModules/rapt/Data/Buffers.h:152:12: Use of undeclared identifier 'data'; did you mean 'tan'?

/Users/elan/Desktop/RS-MET/Libraries/RobsJuceModules/rapt/Data/Buffers.h:160:12: Use of undeclared identifier 'data'; did you mean 'tan'?

/Users/elan/Desktop/RS-MET/Libraries/RobsJuceModules/rapt/Data/Buffers.h:167:12: Use of undeclared identifier 'data'

**Comment by RobinSchmidt** [comment]
ok - it seems the first error is fixed. did you try to replace `data` by `this->data` already?

> I have not updated mac os

then i wonder why you don't get the same errors when compiling juce as i do. what version of osx and xcode do you use?

**Comment by elanhickler** [comment]
two new errors on windows machine since some of your latest commits:

Error	LNK2019	unresolved external symbol "public: static void __cdecl RAPT::rsArray::fillWithIndex<double>(double *,int)" (??$fillWithIndex@N@rsArray@RAPT@@SAXPEANH@Z) referenced in function "void __cdecl rsStemPlot<double>(class std::vector<double,class std::allocator<double> >)" (??$rsStemPlot@N@@YAXV?$vector@NV?$allocator@N@std@@@std@@@Z)	SeSALT_App	D:\_PROGRAMMING\SeSALT\Builds\VisualStudio2019\include_rapt.obj	1	

Error	LNK2019	unresolved external symbol "public: static void __cdecl RAPT::rsArray::fillWithZeros<double>(double *,int)" (??$fillWithZeros@N@rsArray@RAPT@@SAXPEANH@Z) referenced in function "void __cdecl rsPlotMarkers<double>(double *,int)" (??$rsPlotMarkers@N@@YAXPEANH@Z)	SeSALT_App	D:\_PROGRAMMING\SeSALT\Builds\VisualStudio2019\include_rapt.obj	1

**Comment by elanhickler** [comment]
adding template instantiations solved it

**Comment by elanhickler** [comment]
Mac Os Mojave 10.14.1
Xcode Version 10.1 (10B61)

Flower Child Filter - Shared Code Group
Semantic Issue Group
/RS-MET/Libraries/RobsJuceModules/rapt/Data/Buffers.h:38:35: Member initializer 'rsBuffer' does not name a non-static data member or base class
/Volumes/AH_samples/SOUNDEMOTE/Source Tree/Soundemote/AudioPlugins/FlowerChildFilter/JuceLibraryCode/include_rapt.cpp:9:10: In file included from /Volumes/AH_samples/SOUNDEMOTE/Source Tree/Soundemote/AudioPlugins/FlowerChildFilter/JuceLibraryCode/include_rapt.cpp:9:
/RS-MET/Libraries/RobsJuceModules/rapt/rapt.cpp:12:10: In file included from ../../../../../RS-MET/Libraries/RobsJuceModules/rapt/rapt.cpp:12:
/RS-MET/Libraries/RobsJuceModules/rapt/Basics/Plotting.cpp:2:10: In file included from ../../../../../RS-MET/Libraries/RobsJuceModules/rapt/Basics/Plotting.cpp:2:
/RS-MET/Libraries/RobsJuceModules/rapt/rapt.h:44:10: In file included from ../../../../../RS-MET/Libraries/RobsJuceModules/rapt/Basics/../rapt.h:44:
/RS-MET/Libraries/RobsJuceModules/rapt/Data/Data.h:10:10: In file included from ../../../../../RS-MET/Libraries/RobsJuceModules/rapt/Data/Data.h:10:
/RS-MET/Libraries/RobsJuceModules/rapt/Data/Buffers.h:59:5: Use of undeclared identifier 'data'
/Volumes/AH_samples/SOUNDEMOTE/Source Tree/Soundemote/AudioPlugins/FlowerChildFilter/JuceLibraryCode/include_rapt.cpp:9:10: In file included from /Volumes/AH_samples/SOUNDEMOTE/Source Tree/Soundemote/AudioPlugins/FlowerChildFilter/JuceLibraryCode/include_rapt.cpp:9:
/RS-MET/Libraries/RobsJuceModules/rapt/rapt.cpp:12:10: In file included from ../../../../../RS-MET/Libraries/RobsJuceModules/rapt/rapt.cpp:12:
/RS-MET/Libraries/RobsJuceModules/rapt/Basics/Plotting.cpp:2:10: In file included from ../../../../../RS-MET/Libraries/RobsJuceModules/rapt/Basics/Plotting.cpp:2:
/RS-MET/Libraries/RobsJuceModules/rapt/rapt.h:44:10: In file included from ../../../../../RS-MET/Libraries/RobsJuceModules/rapt/Basics/../rapt.h:44:
/RS-MET/Libraries/RobsJuceModules/rapt/Data/Data.h:10:10: In file included from ../../../../../RS-MET/Libraries/RobsJuceModules/rapt/Data/Data.h:10:
/RS-MET/Libraries/RobsJuceModules/rapt/Data/Buffers.h:60:13: Use of undeclared identifier 'data'; did you mean 'atan'?
/Volumes/AH_samples/SOUNDEMOTE/Source Tree/Soundemote/AudioPlugins/FlowerChildFilter/JuceLibraryCode/include_rapt.cpp:9:10: In file included from /Volumes/AH_samples/SOUNDEMOTE/Source Tree/Soundemote/AudioPlugins/FlowerChildFilter/JuceLibraryCode/include_rapt.cpp:9:
/RS-MET/Libraries/RobsJuceModules/rapt/rapt.cpp:12:10: In file included from ../../../../../RS-MET/Libraries/RobsJuceModules/rapt/rapt.cpp:12:
/RS-MET/Libraries/RobsJuceModules/rapt/Basics/Plotting.cpp:2:10: In file included from ../../../../../RS-MET/Libraries/RobsJuceModules/rapt/Basics/Plotting.cpp:2:
/RS-MET/Libraries/RobsJuceModules/rapt/rapt.h:44:10: In file included from ../../../../../RS-MET/Libraries/RobsJuceModules/rapt/Basics/../rapt.h:44:
/RS-MET/Libraries/RobsJuceModules/rapt/Data/Data.h:10:10: In file included from ../../../../../RS-MET/Libraries/RobsJuceModules/rapt/Data/Data.h:10:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/math.h:778:1: 'atan' declared here
/RS-MET/Libraries/RobsJuceModules/rapt/Data/Buffers.h:72:12: Use of undeclared identifier 'data'
/Volumes/AH_samples/SOUNDEMOTE/Source Tree/Soundemote/AudioPlugins/FlowerChildFilter/JuceLibraryCode/include_rapt.cpp:9:10: In file included from /Volumes/AH_samples/SOUNDEMOTE/Source Tree/Soundemote/AudioPlugins/FlowerChildFilter/JuceLibraryCode/include_rapt.cpp:9:
/RS-MET/Libraries/RobsJuceModules/rapt/rapt.cpp:12:10: In file included from ../../../../../RS-MET/Libraries/RobsJuceModules/rapt/rapt.cpp:12:
/RS-MET/Libraries/RobsJuceModules/rapt/Basics/Plotting.cpp:2:10: In file included from ../../../../../RS-MET/Libraries/RobsJuceModules/rapt/Basics/Plotting.cpp:2:
/RS-MET/Libraries/RobsJuceModules/rapt/rapt.h:44:10: In file included from ../../../../../RS-MET/Libraries/RobsJuceModules/rapt/Basics/../rapt.h:44:
/RS-MET/Libraries/RobsJuceModules/rapt/Data/Data.h:10:10: In file included from ../../../../../RS-MET/Libraries/RobsJuceModules/rapt/Data/Data.h:10:
/RS-MET/Libraries/RobsJuceModules/rapt/Data/Buffers.h:74:11: Use of undeclared identifier 'wrap'
/Volumes/AH_samples/SOUNDEMOTE/Source Tree/Soundemote/AudioPlugins/FlowerChildFilter/JuceLibraryCode/include_rapt.cpp:9:10: In file included from /Volumes/AH_samples/SOUNDEMOTE/Source Tree/Soundemote/AudioPlugins/FlowerChildFilter/JuceLibraryCode/include_rapt.cpp:9:
/RS-MET/Libraries/RobsJuceModules/rapt/rapt.cpp:12:10: In file included from ../../../../../RS-MET/Libraries/RobsJuceModules/rapt/rapt.cpp:12:
/RS-MET/Libraries/RobsJuceModules/rapt/Basics/Plotting.cpp:2:10: In file included from ../../../../../RS-MET/Libraries/RobsJuceModules/rapt/Basics/Plotting.cpp:2:
/RS-MET/Libraries/RobsJuceModules/rapt/rapt.h:44:10: In file included from ../../../../../RS-MET/Libraries/RobsJuceModules/rapt/Basics/../rapt.h:44:
/RS-MET/Libraries/RobsJuceModules/rapt/Data/Data.h:10:10: In file included from ../../../../../RS-MET/Libraries/RobsJuceModules/rapt/Data/Data.h:10:
/RS-MET/Libraries/RobsJuceModules/rapt/Data/Buffers.h:75:10: Use of undeclared identifier 'data'
/Volumes/AH_samples/SOUNDEMOTE/Source Tree/Soundemote/AudioPlugins/FlowerChildFilter/JuceLibraryCode/include_rapt.cpp:9:10: In file included from /Volumes/AH_samples/SOUNDEMOTE/Source Tree/Soundemote/AudioPlugins/FlowerChildFilter/JuceLibraryCode/include_rapt.cpp:9:
/RS-MET/Libraries/RobsJuceModules/rapt/rapt.cpp:12:10: In file included from ../../../../../RS-MET/Libraries/RobsJuceModules/rapt/rapt.cpp:12:
/RS-MET/Libraries/RobsJuceModules/rapt/Basics/Plotting.cpp:2:10: In file included from ../../../../../RS-MET/Libraries/RobsJuceModules/rapt/Basics/Plotting.cpp:2:
/RS-MET/Libraries/RobsJuceModules/rapt/rapt.h:44:10: In file included from ../../../../../RS-MET/Libraries/RobsJuceModules/rapt/Basics/../rapt.h:44:
/RS-MET/Libraries/RobsJuceModules/rapt/Data/Data.h:10:10: In file included from ../../../../../RS-MET/Libraries/RobsJuceModules/rapt/Data/Data.h:10:
/RS-MET/Libraries/RobsJuceModules/rapt/Data/Buffers.h:76:14: Use of undeclared identifier 'data'
/Volumes/AH_samples/SOUNDEMOTE/Source Tree/Soundemote/AudioPlugins/FlowerChildFilter/JuceLibraryCode/include_rapt.cpp:9:10: In file included from /Volumes/AH_samples/SOUNDEMOTE/Source Tree/Soundemote/AudioPlugins/FlowerChildFilter/JuceLibraryCode/include_rapt.cpp:9:
/RS-MET/Libraries/RobsJuceModules/rapt/rapt.cpp:12:10: In file included from ../../../../../RS-MET/Libraries/RobsJuceModules/rapt/rapt.cpp:12:
/RS-MET/Libraries/RobsJuceModules/rapt/Basics/Plotting.cpp:2:10: In file included from ../../../../../RS-MET/Libraries/RobsJuceModules/rapt/Basics/Plotting.cpp:2:
/RS-MET/Libraries/RobsJuceModules/rapt/rapt.h:44:10: In file included from ../../../../../RS-MET/Libraries/RobsJuceModules/rapt/Basics/../rapt.h:44:
/RS-MET/Libraries/RobsJuceModules/rapt/Data/Data.h:10:10: In file included from ../../../../../RS-MET/Libraries/RobsJuceModules/rapt/Data/Data.h:10:
/RS-MET/Libraries/RobsJuceModules/rapt/Data/Buffers.h:135:5: Use of undeclared identifier 'data'
/Volumes/AH_samples/SOUNDEMOTE/Source Tree/Soundemote/AudioPlugins/FlowerChildFilter/JuceLibraryCode/include_rapt.cpp:9:10: In file included from /Volumes/AH_samples/SOUNDEMOTE/Source Tree/Soundemote/AudioPlugins/FlowerChildFilter/JuceLibraryCode/include_rapt.cpp:9:
/RS-MET/Libraries/RobsJuceModules/rapt/rapt.cpp:12:10: In file included from ../../../../../RS-MET/Libraries/RobsJuceModules/rapt/rapt.cpp:12:
/RS-MET/Libraries/RobsJuceModules/rapt/Basics/Plotting.cpp:2:10: In file included from ../../../../../RS-MET/Libraries/RobsJuceModules/rapt/Basics/Plotting.cpp:2:
/RS-MET/Libraries/RobsJuceModules/rapt/rapt.h:44:10: In file included from ../../../../../RS-MET/Libraries/RobsJuceModules/rapt/Basics/../rapt.h:44:
/RS-MET/Libraries/RobsJuceModules/rapt/Data/Data.h:10:10: In file included from ../../../../../RS-MET/Libraries/RobsJuceModules/rapt/Data/Data.h:10:
/RS-MET/Libraries/RobsJuceModules/rapt/Data/Buffers.h:143:5: Use of undeclared identifier 'data'
/Volumes/AH_samples/SOUNDEMOTE/Source Tree/Soundemote/AudioPlugins/FlowerChildFilter/JuceLibraryCode/include_rapt.cpp:9:10: In file included from /Volumes/AH_samples/SOUNDEMOTE/Source Tree/Soundemote/AudioPlugins/FlowerChildFilter/JuceLibraryCode/include_rapt.cpp:9:
/RS-MET/Libraries/RobsJuceModules/rapt/rapt.cpp:12:10: In file included from ../../../../../RS-MET/Libraries/RobsJuceModules/rapt/rapt.cpp:12:
/RS-MET/Libraries/RobsJuceModules/rapt/Basics/Plotting.cpp:2:10: In file included from ../../../../../RS-MET/Libraries/RobsJuceModules/rapt/Basics/Plotting.cpp:2:
/RS-MET/Libraries/RobsJuceModules/rapt/rapt.h:44:10: In file included from ../../../../../RS-MET/Libraries/RobsJuceModules/rapt/Basics/../rapt.h:44:
/RS-MET/Libraries/RobsJuceModules/rapt/Data/Data.h:10:10: In file included from ../../../../../RS-MET/Libraries/RobsJuceModules/rapt/Data/Data.h:10:
/RS-MET/Libraries/RobsJuceModules/rapt/Data/Buffers.h:152:12: Use of undeclared identifier 'data'; did you mean 'atan'?
/Volumes/AH_samples/SOUNDEMOTE/Source Tree/Soundemote/AudioPlugins/FlowerChildFilter/JuceLibraryCode/include_rapt.cpp:9:10: In file included from /Volumes/AH_samples/SOUNDEMOTE/Source Tree/Soundemote/AudioPlugins/FlowerChildFilter/JuceLibraryCode/include_rapt.cpp:9:
/RS-MET/Libraries/RobsJuceModules/rapt/rapt.cpp:12:10: In file included from ../../../../../RS-MET/Libraries/RobsJuceModules/rapt/rapt.cpp:12:
/RS-MET/Libraries/RobsJuceModules/rapt/Basics/Plotting.cpp:2:10: In file included from ../../../../../RS-MET/Libraries/RobsJuceModules/rapt/Basics/Plotting.cpp:2:
/RS-MET/Libraries/RobsJuceModules/rapt/rapt.h:44:10: In file included from ../../../../../RS-MET/Libraries/RobsJuceModules/rapt/Basics/../rapt.h:44:
/RS-MET/Libraries/RobsJuceModules/rapt/Data/Data.h:10:10: In file included from ../../../../../RS-MET/Libraries/RobsJuceModules/rapt/Data/Data.h:10:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/math.h:778:1: 'atan' declared here
/RS-MET/Libraries/RobsJuceModules/rapt/Data/Buffers.h:160:12: Use of undeclared identifier 'data'; did you mean 'atan'?
/Volumes/AH_samples/SOUNDEMOTE/Source Tree/Soundemote/AudioPlugins/FlowerChildFilter/JuceLibraryCode/include_rapt.cpp:9:10: In file included from /Volumes/AH_samples/SOUNDEMOTE/Source Tree/Soundemote/AudioPlugins/FlowerChildFilter/JuceLibraryCode/include_rapt.cpp:9:
/RS-MET/Libraries/RobsJuceModules/rapt/rapt.cpp:12:10: In file included from ../../../../../RS-MET/Libraries/RobsJuceModules/rapt/rapt.cpp:12:
/RS-MET/Libraries/RobsJuceModules/rapt/Basics/Plotting.cpp:2:10: In file included from ../../../../../RS-MET/Libraries/RobsJuceModules/rapt/Basics/Plotting.cpp:2:
/RS-MET/Libraries/RobsJuceModules/rapt/rapt.h:44:10: In file included from ../../../../../RS-MET/Libraries/RobsJuceModules/rapt/Basics/../rapt.h:44:
/RS-MET/Libraries/RobsJuceModules/rapt/Data/Data.h:10:10: In file included from ../../../../../RS-MET/Libraries/RobsJuceModules/rapt/Data/Data.h:10:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/math.h:778:1: 'atan' declared here
/RS-MET/Libraries/RobsJuceModules/rapt/Data/Buffers.h:167:12: Use of undeclared identifier 'data'
/Volumes/AH_samples/SOUNDEMOTE/Source Tree/Soundemote/AudioPlugins/FlowerChildFilter/JuceLibraryCode/include_rapt.cpp:9:10: In file included from /Volumes/AH_samples/SOUNDEMOTE/Source Tree/Soundemote/AudioPlugins/FlowerChildFilter/JuceLibraryCode/include_rapt.cpp:9:
/RS-MET/Libraries/RobsJuceModules/rapt/rapt.cpp:12:10: In file included from ../../../../../RS-MET/Libraries/RobsJuceModules/rapt/rapt.cpp:12:
/RS-MET/Libraries/RobsJuceModules/rapt/Basics/Plotting.cpp:2:10: In file included from ../../../../../RS-MET/Libraries/RobsJuceModules/rapt/Basics/Plotting.cpp:2:
/RS-MET/Libraries/RobsJuceModules/rapt/rapt.h:44:10: In file included from ../../../../../RS-MET/Libraries/RobsJuceModules/rapt/Basics/../rapt.h:44:
/RS-MET/Libraries/RobsJuceModules/rapt/Data/Data.h:10:10: In file included from ../../../../../RS-MET/Libraries/RobsJuceModules/rapt/Data/Data.h:10:
/RS-MET/Libraries/RobsJuceModules/rapt/Data/Buffers.h:174:12: Use of undeclared identifier 'data'
/Volumes/AH_samples/SOUNDEMOTE/Source Tree/Soundemote/AudioPlugins/FlowerChildFilter/JuceLibraryCode/include_rapt.cpp:9:10: In file included from /Volumes/AH_samples/SOUNDEMOTE/Source Tree/Soundemote/AudioPlugins/FlowerChildFilter/JuceLibraryCode/include_rapt.cpp:9:
/RS-MET/Libraries/RobsJuceModules/rapt/rapt.cpp:12:10: In file included from ../../../../../RS-MET/Libraries/RobsJuceModules/rapt/rapt.cpp:12:
/RS-MET/Libraries/RobsJuceModules/rapt/Basics/Plotting.cpp:2:10: In file included from ../../../../../RS-MET/Libraries/RobsJuceModules/rapt/Basics/Plotting.cpp:2:
/RS-MET/Libraries/RobsJuceModules/rapt/rapt.h:44:10: In file included from ../../../../../RS-MET/Libraries/RobsJuceModules/rapt/Basics/../rapt.h:44:
/RS-MET/Libraries/RobsJuceModules/rapt/Data/Data.h:10:10: In file included from ../../../../../RS-MET/Libraries/RobsJuceModules/rapt/Data/Data.h:10:
/RS-MET/Libraries/RobsJuceModules/rapt/Data/Buffers.h:187:7: Use of undeclared identifier 'initBufferValues'
/Volumes/AH_samples/SOUNDEMOTE/Source Tree/Soundemote/AudioPlugins/FlowerChildFilter/JuceLibraryCode/include_rapt.cpp:9:10: In file included from /Volumes/AH_samples/SOUNDEMOTE/Source Tree/Soundemote/AudioPlugins/FlowerChildFilter/JuceLibraryCode/include_rapt.cpp:9:
/RS-MET/Libraries/RobsJuceModules/rapt/rapt.cpp:12:10: In file included from ../../../../../RS-MET/Libraries/RobsJuceModules/rapt/rapt.cpp:12:
/RS-MET/Libraries/RobsJuceModules/rapt/Basics/Plotting.cpp:2:10: In file included from ../../../../../RS-MET/Libraries/RobsJuceModules/rapt/Basics/Plotting.cpp:2:
/RS-MET/Libraries/RobsJuceModules/rapt/rapt.h:44:10: In file included from ../../../../../RS-MET/Libraries/RobsJuceModules/rapt/Basics/../rapt.h:44:
/RS-MET/Libraries/RobsJuceModules/rapt/Data/Data.h:10:10: In file included from ../../../../../RS-MET/Libraries/RobsJuceModules/rapt/Data/Data.h:10:
/RS-MET/Libraries/RobsJuceModules/rapt/Data/Buffers.h:199:47: Use of undeclared identifier 'data'
/Volumes/AH_samples/SOUNDEMOTE/Source Tree/Soundemote/AudioPlugins/FlowerChildFilter/JuceLibraryCode/include_rapt.cpp:9:10: In file included from /Volumes/AH_samples/SOUNDEMOTE/Source Tree/Soundemote/AudioPlugins/FlowerChildFilter/JuceLibraryCode/include_rapt.cpp:9:
/RS-MET/Libraries/RobsJuceModules/rapt/rapt.cpp:12:10: In file included from ../../../../../RS-MET/Libraries/RobsJuceModules/rapt/rapt.cpp:12:
/RS-MET/Libraries/RobsJuceModules/rapt/Basics/Plotting.cpp:2:10: In file included from ../../../../../RS-MET/Libraries/RobsJuceModules/rapt/Basics/Plotting.cpp:2:
/RS-MET/Libraries/RobsJuceModules/rapt/rapt.h:44:10: In file included from ../../../../../RS-MET/Libraries/RobsJuceModules/rapt/Basics/../rapt.h:44:
/RS-MET/Libraries/RobsJuceModules/rapt/Data/Data.h:10:10: In file included from ../../../../../RS-MET/Libraries/RobsJuceModules/rapt/Data/Data.h:10:
/RS-MET/Libraries/RobsJuceModules/rapt/Filters/Basic/MovingWindowFilters.h:132:44: Member initializer 'rsMovingMaximumFilter' does not name a non-static data member or base class
/Volumes/AH_samples/SOUNDEMOTE/Source Tree/Soundemote/AudioPlugins/FlowerChildFilter/JuceLibraryCode/include_rapt.cpp:9:10: In file included from /Volumes/AH_samples/SOUNDEMOTE/Source Tree/Soundemote/AudioPlugins/FlowerChildFilter/JuceLibraryCode/include_rapt.cpp:9:
/RS-MET/Libraries/RobsJuceModules/rapt/rapt.cpp:12:10: In file included from ../../../../../RS-MET/Libraries/RobsJuceModules/rapt/rapt.cpp:12:
/RS-MET/Libraries/RobsJuceModules/rapt/Basics/Plotting.cpp:2:10: In file included from ../../../../../RS-MET/Libraries/RobsJuceModules/rapt/Basics/Plotting.cpp:2:
/RS-MET/Libraries/RobsJuceModules/rapt/rapt.h:48:10: In file included from ../../../../../RS-MET/Libraries/RobsJuceModules/rapt/Basics/../rapt.h:48:
/RS-MET/Libraries/RobsJuceModules/rapt/Filters/Filters.h:9:10: In file included from ../../../../../RS-MET/Libraries/RobsJuceModules/rapt/Filters/Filters.h:9:
/RS-MET/Libraries/RobsJuceModules/rapt/Filters/Basic/MovingWindowFilters.h:139:34: Cannot refer to class template 'greater' without a template argument list
/Volumes/AH_samples/SOUNDEMOTE/Source Tree/Soundemote/AudioPlugins/FlowerChildFilter/JuceLibraryCode/include_rapt.cpp:9:10: In file included from /Volumes/AH_samples/SOUNDEMOTE/Source Tree/Soundemote/AudioPlugins/FlowerChildFilter/JuceLibraryCode/include_rapt.cpp:9:
/RS-MET/Libraries/RobsJuceModules/rapt/rapt.cpp:12:10: In file included from ../../../../../RS-MET/Libraries/RobsJuceModules/rapt/rapt.cpp:12:
/RS-MET/Libraries/RobsJuceModules/rapt/Basics/Plotting.cpp:2:10: In file included from ../../../../../RS-MET/Libraries/RobsJuceModules/rapt/Basics/Plotting.cpp:2:
/RS-MET/Libraries/RobsJuceModules/rapt/rapt.h:48:10: In file included from ../../../../../RS-MET/Libraries/RobsJuceModules/rapt/Basics/../rapt.h:48:
/RS-MET/Libraries/RobsJuceModules/rapt/Filters/Filters.h:9:10: In file included from ../../../../../RS-MET/Libraries/RobsJuceModules/rapt/Filters/Filters.h:9:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/functional:720:29: Template is declared here
/RS-MET/Libraries/RobsJuceModules/rapt/Filters/Basic/MovingWindowFilters.h:139:46: Use of undeclared identifier 'maxDeque'; did you mean 'minDeque'?
/Volumes/AH_samples/SOUNDEMOTE/Source Tree/Soundemote/AudioPlugins/FlowerChildFilter/JuceLibraryCode/include_rapt.cpp:9:10: In file included from /Volumes/AH_samples/SOUNDEMOTE/Source Tree/Soundemote/AudioPlugins/FlowerChildFilter/JuceLibraryCode/include_rapt.cpp:9:
/RS-MET/Libraries/RobsJuceModules/rapt/rapt.cpp:12:10: In file included from ../../../../../RS-MET/Libraries/RobsJuceModules/rapt/rapt.cpp:12:
/RS-MET/Libraries/RobsJuceModules/rapt/Basics/Plotting.cpp:2:10: In file included from ../../../../../RS-MET/Libraries/RobsJuceModules/rapt/Basics/Plotting.cpp:2:
/RS-MET/Libraries/RobsJuceModules/rapt/rapt.h:48:10: In file included from ../../../../../RS-MET/Libraries/RobsJuceModules/rapt/Basics/../rapt.h:48:
/RS-MET/Libraries/RobsJuceModules/rapt/Filters/Filters.h:9:10: In file included from ../../../../../RS-MET/Libraries/RobsJuceModules/rapt/Filters/Filters.h:9:

**Comment by RobinSchmidt** [comment]
ok, i'm now trying to compile with gcc on windows. this should probably expose many of these same errors (as issue is (mostly) gcc here, not mac) - replacing `data` with `this->data` (as suggested) seems to help already. many more to fix, but i must leave now. will look into the rest later

**Comment by elanhickler** [comment]
how do you compile with gcc on windows?

**Comment by RobinSchmidt** [comment]
i have CodeBlocks installed. if i remember correctly, it will also install some version of gcc, if necessary - or at least, you will find instructions, how to do it yourself manually (and then point the IDE to the installation). it's a while ago (so apparently, i'm using a somewhat old version - and at the moment, only 32-bit works - i guess, i should update some time soon)

**Comment by RobinSchmidt** [comment]
i have fixed most of the errors - just 1 remains (related to std::to_string - it doesn't find it - it seems to be a known bug in mingw, so it probably won't happen on mac)

**Comment by elanhickler** [comment]
could you try compiling flower child filter? since your changes, Alejandro tried compiling and he got the same errors, doesn't make sense there would be the exact same errors though. In any case, compile it, see if you can reduce some errors. Add your time to my tab.

**Comment by RobinSchmidt** [comment]
i have updated my codeblocks in the hope that the new version comes with a 64 bit compiler (because i get compilation errors when tying to compile juce - that seem to indicate that juce doesn't compile with the 32-bit version of gcc). but the compiler bundled with the new codeblocks still doesn't seem to support compiling in 64 bit mode. ...and i get a few more other inscrutable compilation errors new when compiling in 32 bit mode. hmm...

**Comment by elanhickler** [comment]
All of a sudden I'm getting new errors I've never seen before from Intrin.h.

Do you know anything about this?

**Comment by elanhickler** [comment]
I found the issue. In rosic.h you need to do an ifdef to only include if compiling on windows for intrin.h

**Comment by RobinSchmidt** [comment]
ok - what's the macro that i should use for the #ifdef? WIN32 ...or __WIN32? or both? or something else?

**Comment by elanhickler** [comment]
I'm not familiar with those kinds of macros. I guess try what you think will work and we'll see.

**Comment by RobinSchmidt** [comment]
ah - ok - i thought, you already had that figured out. i'm going by MSC_VER by now, which identifies the microsoft compiler.

**Comment by elanhickler** [comment]
no longer relevant
