### ISSUE TITLE
assertion error from latest commit

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#28]
4a8575279b660bbdd39e5d98941ad02c75b6d059

causes assertion errors for
```
		c->setDescription("");
		c->setDescriptionField(infoField);
```
in my code

**Comment by RobinSchmidt** [comment]
yes . that's the assertion i added (or modified) to alarm you when you attach a combobox to a non-string parameter

**Comment by RobinSchmidt** [comment]
err...or..wait...where do you trigger this assert?

**Comment by elanhickler** [comment]
well fuck

https://puu.sh/w9laZ/dd61fa4758.mp4

now what's wrong?

This is using your latest, I just re-downloaded your library to make sure.

**Comment by elanhickler** [comment]
here's the assertion error

https://puu.sh/w9lqc/45a2d99128.mp4

**Comment by RobinSchmidt** [comment]
looks like you are hitting the assertion that i have deliberately added to catch, when you try to attach a combobox to a parameter that doesn't use the "string" scaling (i should rename that to choice at some point). i fixed only one of your parameter-constructors in spiral-generator (line 103). probably, you have more of that sort. check the constructors of the underlying parameters and make sure, they use Parameter::STRING for the scaling

**Comment by RobinSchmidt** [comment]
to catch such errors was the point of adding that assertion :-)

**Comment by elanhickler** [comment]
jeez ok. good. fixed.

Your error message confused me. Please change it to:

// trying to assign non-string parameter *scaling* to a combo box
