### ISSUE TITLE
Please add "moduleVendor" member to AudioModule

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#29]
jura_AudioModule.h

below moduleName add moduleVendor

**Comment by RobinSchmidt** [comment]
what do you need this for? if anything, then it would perhaps make more sense to add it to jura_AudioPlugin

**Comment by elanhickler** [comment]
i get compiler error when you try to use macros in a string apparently, and that is needed to setup folder structure for active directory/presets/etc.

**Comment by RobinSchmidt** [comment]
hmm...well...some of those things seem to apply on the plugin-level (license, vendor, preferences). the "module"-level is one below. you can throw together a plugin from various modules. preset-directories, on the other hand, make sense on the module level - where it already is, although i currently have no distinction between user and factory presets

**Comment by RobinSchmidt** [comment]
i think, having distinct factory and user preset folders makes sense only when we have a custom preset browser. as long as we use the regular file loading dialog box, the current setActiveDirectory seems to be sufficient, no?

**Comment by elanhickler** [comment]
correct, will need to wait until we have a custom browser

**Comment by elanhickler** [comment]
other newer issues cover this
