### ISSUE TITLE
Need resampling algorithms.

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#296]
Hey Robin, do you have resampling algorithms for samplerate conversions? Up and down. Like going from 44100 to 96000 and vice versa. I expect to input an array and then get a new array as the output.

**Comment by RobinSchmidt** [comment]
hmmm. i have this class here which was actually the very first thing, i wrote for you, here: 
`rsResampler<TSig, TPos>::signalValueViaSincAt` which we used back then to remove vibrato. ...so that's a sinc interpolator function. that could probably be used for such as thing

**Comment by RobinSchmidt** [comment]
that' a pretty general sinc interpolation function. there are ways, it could be refined, for example by allowing client code to select between various window functions

**Comment by elanhickler** [comment]
How do I turn that into a function that takes and input array and gives an output array?

**Comment by elanhickler** [comment]
I was going to make another thread but I think this is relevant here.

Can you explain or give example of how I could use your various interpolation (linear, log, exp, possibly bezier or cubic) to add envelope amplitudes to audio arrays? Obviously bezier / cubic will require more than two points. OH, maybe I need to use your multipoint envelope somehow. Is there something more suitable than BreakpointModulator for offline functions?

```
static void applyEnvelope(MetaAudioFile& audio, DataEnvelope envelope, double defaultValue = 1)
{
	int numSamples = audio.getNumSamples();
	int sampleRate = audio.getSampleRate();

	for (auto& c : audio.channels)
	{
		auto ptr = c.audio.getWritePointer();

		int startSample = Envelope[0].time * sampleRate;
		if (startSample > 0) // start at sample 0 and apply flat envelopeto the first envelope point
			interpolateLinear(ptr, numSamples, sampleRate, 0, Envelope[i].value, startSample, Envelope[i].value);

		for (int i = 0; i < Envelope.numPoints - 1; ++i);
		{
			int startSample = Envelope[i].time * sampleRate;
			int endSample = Envelope[i+1].time * sampleRate; 
			double startVal = Envelope[i].value;
			double endVal = Envelope[i+1].value;

			interpolateLinear(ptr, numSamples, sampleRate, startSample, startVal, endSample, endVal);
		}

		int endSample = Envelope.back().time * sampleRate; 

		if (endSample+1 < numSamples) // start at last point and apply flat envelopeto the end of the array
			interpolateLinear(ptr, numSamples, sampleRate, endSample, Envelope.back().value, numSamples-1, Envelope.back().value);		
	}
}
```

**Comment by RobinSchmidt** [comment]
> How do I use that to create a function that takes and input array and gives an output array?

there is a resampler() function ResamplingExperiments.cpp that shows. how it can be used. i also just added a convenience function to work with std::vectors (takes one, returns one)

**Comment by elanhickler** [comment]
ok found the functions. 
```
96000/44100 = 2.17687074829931972789
44100/96000 = 0.459375
```
what should my resampling ratio be if I'm upsampling? Less than 1 or more than 1?

**Comment by RobinSchmidt** [comment]
less than 1. the function takes a transposition factor, so 2 would mean: one octave up

**Comment by elanhickler** [comment]
and the number of new samples needed is the inverse? numSamples * 1/resamplingRatio

**Comment by RobinSchmidt** [comment]
yes. i use `ceil` of the that value in convenience function for std::vector

**Comment by elanhickler** [comment]
okkkk what should I use for my offline envelope needs?

**Comment by elanhickler** [comment]
[p.s. merry christmas, thanks for all your help]

**Comment by RobinSchmidt** [comment]
thank you! same to you!

hmmm...interpolating amplitude envelopes....in my sinusoidal synthesizer, i also have to interpolate amplitude data (from datapoint-"rate" to sample-rate) and i use either linear or cubic interpolation there. i experimented with taking the log - interpolate  - than taking exp afterwards. this would amount to a sort exponential interpolation - or you may see it as linear interpolation on a db scale -  however, i discarded the idea again, because the attack-sections would be interpolated with a shape like this
![image](https://user-images.githubusercontent.com/1833099/71450938-e8445e00-276b-11ea-8de9-9e5ddec1dd9d.png)
...which is probably not what you want. if you don't care whether the envelope goes exactly through your datapoints, one could also try linear interpolation with smoothing afterwards

**Comment by RobinSchmidt** [comment]
the cubic interpolants may sometimes cause problems with overshooting, so i actually mostly use linear interpolation.

**Comment by elanhickler** [comment]
compile error, needed to add TSig() TPos()

![image](https://user-images.githubusercontent.com/9116575/71451622-65091500-2737-11ea-877d-270e83d39377.png)

**Comment by RobinSchmidt** [comment]
oh - in this case, i think, both arguments should be wrapped int TPos. i don't get this error - probably because i instantiate the template only for double and you use float?

**Comment by elanhickler** [comment]
yeah im using float... oh no Robin. I just tried the resampler and the downsampled audio drifts significantly from the original! Could it be because I'm using floats? But the beginning is fine, it seems the drift is unpredictable, not constant.
![image](https://user-images.githubusercontent.com/9116575/71451906-0b571980-273c-11ea-8a96-fa2c0f84ee67.png)

**Comment by RobinSchmidt** [comment]
i made small change which may fix the drift - can you try it?

**Comment by elanhickler** [comment]
looks like the drift is solved but im going to test another resampler to see how the results compare.
![image](https://user-images.githubusercontent.com/9116575/71452381-de0d6a00-2741-11ea-84bf-3d60b62e2f5b.png)

**Comment by elanhickler** [comment]
REAPER
![image](https://user-images.githubusercontent.com/9116575/71452419-2e84c780-2742-11ea-82b8-200bc18696d1.png)

yours
![image](https://user-images.githubusercontent.com/9116575/71452422-32184e80-2742-11ea-942d-fc0afcd4a0a6.png)

yeah it does look a little off.

**Comment by elanhickler** [comment]
Hmm, looks like the offset is exactly 1 sample.

**Comment by RobinSchmidt** [comment]
indeeeeed! my resampler produces a delay of one sample. :-O how could this bug go unnoticed for so long?

**Comment by RobinSchmidt** [comment]
> how could this bug go unnoticed for so long?

it didn't. it was actually my (improperly applied) drift-fix that introduced the delay. fixed.

**Comment by elanhickler** [comment]
ah great!

**Comment by elanhickler** [comment]
this issue is largely solved.
