### ISSUE TITLE
Spiral Generator fails at FM, what am I doing wrong?

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#30]
when modulating tune by an LFO (and the LFO is set to track the pitch of the oscillator) it doesn't sound right. Different keys sound too different timbrally.

I do something like take the main oscillator pitch and set the LFO to that same pitch plus a tuning offset. I then convert that to frequency with pitchToFrequency(). LFO and Oscillator should be tracking perfectly as they are set to the same pitches plus optional tuning offsets.

**Comment by elanhickler** [comment]
hmm oh maybe it's because I use + isntead of * for pitch offset. I need to setup a ratio system / multiplication system rather than use addition.

**Comment by RobinSchmidt** [comment]
hmmm - actually, adding in the (logarithmic) pitch domain sounds right to me. this is mathematically the same as multiplying in the raw frequency domain as logarithms take multiplication to addition: log(a*b) = log(a)+log(b). so when you add a constant in the pitch domain, and then convert to frequency after addeing, this should yield constant frequency ratios.

**Comment by RobinSchmidt** [comment]
maybe i need more details and/or look at your actual code

**Comment by elanhickler** [comment]
it's heavily influenced by amplitude of modulation as well.

**Comment by elanhickler** [comment]
hmm I think it's working correctly, just the results are not as I want them to be. Not sure what the solution is other than to have per-key settings to fine-tune each key... when I do that I might see a pattern that I could use to have more musical FM.

**Comment by RobinSchmidt** [comment]
maybe some amount of (negative) keytracking of the modulation depth? this would make higher notes more muffled

**Comment by elanhickler** [comment]
naa, that's not the issue. will close!

**Comment by elanhickler** [comment]
re-opening this issue. I'd like to fix this before releasing:

https://puu.sh/wbMeI/9bd9aa25b8.mp4

It's the pitch offset that is bothering me. If you have pitch offset set to -24 -12 0 12 24 etc it works as expected. If you do something like 12.5 or even 13 or ANYTHING that is not a perfect multiple of 12 you get a frequency that is more and more off depending on the note you play.

How would I get a consistent sound with a pitch offset?

**Comment by elanhickler** [comment]
ok here's a clue

.1 semitone offset playing C3 equates to playing C4 with 0.05 semitone offset. So every octave up needs to half the semitone offset.

**Comment by RobinSchmidt** [comment]
aaahh! i think, i see. maybe...how to explain....you are getting some kind of beating effect there which is perceived in the time domain - like an lfo. and you want the "lfo-frequency" to stay the same throughout the keyrange. but when you let the pitch-offset between the two oscillators stay the same throughout the keyrange, the the frequency ratio of the 2 oscs stays the same - and the beating frequency goes up as well. so when you play a not an octave higher, you have twice the beating frequency...oh my god...i think what i just said sounds very convoluted. but yeah - i think, for constant beating frequency, you need the frequency difference (not the frequency ratio) stay the same throughout the keyrange. ...which is what happens when you dived the pitch-offset by two for each octave you go up

**Comment by RobinSchmidt** [comment]
you could also just add something to the frequency of one osc (after conversion from pitch to frequency), i.e. introduce an additional absolute frequency offset

**Comment by elanhickler** [comment]
ok, yes, a simple frequency offset works.

**Comment by RobinSchmidt** [comment]
oh - yes - i think exponential FM creates inharmonic spectra even for simple carrier/modulator ratios (where linear FM produces harmonic spectra)

**Comment by RobinSchmidt** [comment]
or...does it? not sure

**Comment by RobinSchmidt** [comment]
ah: https://www.kvraudio.com/forum/viewtopic.php?t=310508

"The main problem with exponential FM is, as you increase the FM index, the perceived fundamental of the pitch shifts."

**Comment by RobinSchmidt** [comment]
here is a paper about exponential FM. it has equations that could probably be used to compensate for this detuning, making exponential FM playable in tune. ...could be interesting to explore....

**Comment by elanhickler** [comment]
I would be musical exponential fm, will return to this topic in the future.
