### ISSUE TITLE
Need help with rsTimeWarper, seems to be warping off-time

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#313]
Could you do some simple tests with rsTimeWarper and ensure that it is working correctly on your end? It seems like the warp map I give it is offset, so for example, if something goes up and down in pitch, the warp map will be going down instead of up, and then up instead of down, like, off phase.

[TriVibrato`n=A2.zip](https://github.com/RobinSchmidt/RS-MET/files/5915551/TriVibrato.n.A2.zip) [convert to mono if needed, it's stereo by mistake]

Here's a simple triangle wave that goes up and down in pitch and in volume (for visual purposes) centered around A2 which is 220hz

**Comment by RobinSchmidt** [comment]
check out the experiment pitchFlattening() in ResamplingExperiments.cpp. it applies pitch flattening to a very similar input signal and works well. i just added a convenience function rsFlattenPitch to the library which is used there

**Comment by elanhickler** [comment]
I got the test working thanks to your description.

```cpp
  // Compute desired readout speed for each sample which is given by the ratio of the desired 
  // instantaneous frequency and the actual instantaneous frequency of the input signal:
  for(n = 0; n < xN; n++)
    r[n] = fy / f[n];
```

Could you add a version of the test where you replace that with one of your pitch detectors?

**Comment by elanhickler** [comment]
sorry im stupid, i think you have that already

```cpp
  // Compute output using the new convenience function rsFlattenPitch, which doesn't need the array 
  // with the true instantaneous frequencies (i.e. the f array) but instead measures the 
  // instantaneous frequency internally:
  std::vector<double> y4 = rsFlattenPitch(x, xN, fs, fy);
  writeToMonoWaveFile("PitchFlatteningOutputMeasuredF0.wav",  
    &y4[0], (int)y4.size(), (int) fs, 16);
```
