### ISSUE TITLE
cannot build on OS X, missing definitions

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#36]
see thread: https://forum.juce.com/t/abs-rand-randmax-etc-functions-on-os-x-not-found/22856

**Comment by elanhickler** [comment]
please add me to the contributor list for RS-MET so we can finally fix the OS X issues.

**Comment by elanhickler** [comment]
alloca in rosic_WaveletTransforms.h also not found.

**Comment by elanhickler** [comment]
alloca in rosic_Matrix.h

**Comment by RobinSchmidt** [comment]
i have now included stdlib.h in rosic.h - this should contain the missing definitions and it seems to be automatically included anywhere but on osx. i really really really need to review any change to my library before i drag them into the repository. it's not safe to assume that you can make a change here or there without breaking anything else (even if it seems so at first). so, can you work on your fork and pass me the desired changes? maybe, you can upload your fork to your gitlab and give me the link?  however, i think, i'll set myself up with a mac build-system next week. after all, i want a mac version of my chainer, too

...i need to make my new mini-pc my main workstation. then i can also work directly on prettyscope on a proper desk (it sucks to work on the big screen without desk...i.e. sitting in an armchair with a plank for keyboard and mouse)

**Comment by elanhickler** [comment]
in jura_AudioPlugin.cpp

bool AudioPlugin::setPreferredBusArrangement(bool isInput, int bus, const AudioChannelSet& preferredSet)

no definition for this function in AudioPlugin, comment it out

**Comment by elanhickler** [comment]
imageDrawer.cpp

swap should be std::swap

**Comment by elanhickler** [comment]
ImagePainter.cpp

move your template functions to ImagePainter.h

y u do dis robin!!!

**Comment by RobinSchmidt** [comment]
ok - i'll add these changes tomorrow...keep posting. ... i know, much of this stuff seems innocuous enough...but only i know the quirks of my code

**Comment by elanhickler** [comment]
romos_AudioConnection.h

AudioConnection::AudioConnection(Module *sourceModule = NULL, int outputIndex = 0, Module *targetModule = NULL, int inputIndex = 0);

change to

AudioConnection(Module *sourceModule = NULL, int outputIndex = 0, Module *targetModule = NULL, int inputIndex = 0);

(just remove AudioConnection:: i believe)

**Comment by elanhickler** [comment]
romos_ModuleTypeRegistry.h `ModuleTypeRegistry::ModuleTypeRegistry();` -> remove ModuleTypeRegistry::

romos_ProcessingStatus.h `VoiceAllocator::VoiceAllocator();` -> remove ProcessingStatus::

romos_VoiceAllocator.h `VoiceAllocator::VoiceAllocator();` -> remove VoiceAllocator::

romos_InfrastructuralModules.h `virtual void ParameterModule::setValueFromController(double controllerValue);` -> remove ParameterModule::

**Comment by elanhickler** [comment]
```
template <class T>
Sparse_Matrix_CompRow<T>::Sparse_Matrix_CompRow(int M, int N, int nz,
	const T *val, const int *r, const int *c) : val_(nz,val), 
		rowptr_(M, r), colind_(nz, c), dim1_(M), dim2_(N) {}
```

rowptr_(M, r), colind_(nz, c)
should be 
rowptr_(M, *r), colind_(nz, *c)

**Comment by elanhickler** [comment]
kiss_fft.h
had to comment out `#include <malloc.h>`
get malloc from <stdlib.h>

rosin.h
had to comment out `#include <malloc.h>`
get malloc from <stdlib.h>

**Comment by elanhickler** [comment]
jura_Editor.h

juce::Array<Rectangle<int> > guiLayoutRectangles;

Rectangle needs namespace, add juce::

**Comment by RobinSchmidt** [comment]
ok - i applied a batch of changes (some a little different from what you suggested):

imageDrawer.cpp
swap should be std::swap

->replaced by rsSwap


romos_AudioConnection.h
AudioConnection::AudioConnection(Module *sourceModule = NULL, int outputIndex = 0, Module *targetModule = NULL, int inputIndex = 0);
change to
AudioConnection(Module *sourceModule = NULL, int outputIndex = 0, Module *targetModule = NULL, int inputIndex = 0);
(just remove AudioConnection:: i believe)

->done


romos_ModuleTypeRegistry.h
ModuleTypeRegistry::ModuleTypeRegistry();
-> remove ModuleTypeRegistry::
romos_ProcessingStatus.h
VoiceAllocator::VoiceAllocator();
-> remove ProcessingStatus::
romos_VoiceAllocator.h
VoiceAllocator::VoiceAllocator();
-> remove VoiceAllocator::
romos_InfrastructuralModules.h
virtual void ParameterModule::setValueFromController(double controllerValue);
-> remove ParameterModule::

->done


tnt_sparse_matrix_csr.h
template <class T>
Sparse_Matrix_CompRow<T>::Sparse_Matrix_CompRow(int M, int N, int nz,
	const T *val, const int *r, const int *c) : val_(nz,val), 
		rowptr_(M, r), colind_(nz, c), dim1_(M), dim2_(N) {}
rowptr_(M, r), colind_(nz, c)
should be
rowptr_(M, *r), colind_(nz, *c)

->removed TNT dependency (singular value decomposition commented out)


jura_Editor.h
juce::Array<Rectangle > guiLayoutRectangles;
Rectangle needs namespace, add juce::

->done


kiss_fft.h
had to comment out #include <malloc.h>
get malloc from <stdlib.h>

->done

**Comment by RobinSchmidt** [comment]
some other changes need further consideration:

rosic.h
had to comment out #include <malloc.h>
get malloc from <stdlib.h>

->breaks windows codeblocks project due to alloca

     
in jura_AudioPlugin.cpp
bool AudioPlugin::setPreferredBusArrangement(bool isInput, int bus, const AudioChannelSet& preferredSet)
no definition for this function in AudioPlugin, comment it out, or i think it's override that is causing the problem, there's no function to override

-> commenting out triggers assertion with msvc


ImagePainter.cpp
move your template functions to ImagePainter.h
y u do dis robin!!!

-> no good idea: (non-inlined) template functions in headers easily lead to "multiple definition" linker errors

**Comment by RobinSchmidt** [comment]
what error messages do these produce? there must be different ways to solve these issues without introducing other issues...or maybe just wait until i have my own mac build system and sort these out myself...

**Comment by elanhickler** [comment]
> ImagePainter.cpp
> move your template functions to ImagePainter.h
> y u do dis robin!!!
> 
> -> no good idea: (non-inlined) template functions in headers easily lead to "multiple definition" linker errors

why did you define your own abs

**Comment by RobinSchmidt** [comment]
where did i? probably because i needed a template-based version. not sure. where is it?

**Comment by elanhickler** [comment]
oh, nevermind abs.

template<class T> inline int   roundToInt(T x) { return ipart(x + 0.5f); }
template<class T> inline void swap(T& x, T& y) { T t = x; x = y; y = t;  }

definitely those are redifinitions

**Comment by elanhickler** [comment]
use std::swap

**Comment by RobinSchmidt** [comment]
ahh...these come from copying over the wu algorithm from wikipedia at the point where this source file didn't have access to the other definitions. can probably be removed now. but shouldn't be an issue

**Comment by elanhickler** [comment]
> some other changes need further consideration:
> 
> rosic.h
> had to comment out #include <malloc.h>
> get malloc from <stdlib.h>
> 
> ->breaks windows codeblocks project due to alloca (probably linux too - need to try)

then do ifdefs

**Comment by RobinSchmidt** [comment]
using rsSwap now

**Comment by RobinSchmidt** [comment]
ok, i have rosic.h:wrapped #include <malloc> into #ifndef __APPLE__ in rosic.h

**Comment by RobinSchmidt** [comment]
..äähh...the software here apparently automatically converts double underscores to boldface

**Comment by RobinSchmidt** [comment]
...and messes up other things in other ways

**Comment by elanhickler** [comment]
last few issues

Libraries/JUCE/modules/rapt/Visualization/Graphics/ImageDrawer.cpp
roundToInt undefined in 3 places

Libraries/JUCE/modules/jura_framework/audio/jura_AudioPlugin.h
const AudioChannelSet& preferredSet) override;
get rid of override, there's no function to override.

Libraries/JUCE/modules/jura_framework/audio/jura_AudioPlugin.cpp
line 218 remove AudioProcessor::
you shouldn't put a class namespace within its own scope!

**Comment by elanhickler** [comment]
oh i see, once it's not overridden then that becomes a problem.

**Comment by RobinSchmidt** [comment]
this is weird - there is a setPreferredBusArrangement baseclass function: juce_AudioProcessor.h, line 338

**Comment by RobinSchmidt** [comment]
> Libraries/JUCE/modules/jura_framework/audio/jura_AudioPlugin.cpp
line 218 remove AudioProcessor::
you shouldn't put a class namespace within its own scope!

this is actually a call to the baseclass method

**Comment by RobinSchmidt** [comment]
without it, i'd have an infinite recursion ;-)

**Comment by elanhickler** [comment]
what does that function do anyway? do I need it right now?

**Comment by RobinSchmidt** [comment]
i trigger an assertion error if i don't override it - look at the comment in the cpp file. build a plugin with msvc, plug it in: BÄM: jassert(blah) gets triggered. ...at least in my chainer. does it not happen in your plugins?

**Comment by RobinSchmidt** [comment]
> alloca should never be used

hmm...well - this was a optimization for some performance critical code. stack memory is (much) faster to allocate than heap memory. i may try to get rid of this

**Comment by elanhickler** [comment]
ok then keep alloca, it's not an issue anymore

**Comment by RobinSchmidt** [comment]
i think, a better way to deal with the situation when a performance critical (i.e. supposed to be used inside realtime code) function needs some temporary auxilliary memory would be to pass a "workArea" pointer. this could be even more efficient....but also more inconvenient on the client code side (which must maintain the workArea memory).....i want to use this idiom for low-level dsp functions in rapt

**Comment by RobinSchmidt** [comment]
> Libraries/JUCE/modules/rapt/Visualization/Graphics/ImageDrawer.cpp
roundToInt undefined in 3 places

using rsRoundToInt now

**Comment by RobinSchmidt** [comment]
...soo the last one is setPreferredBusArrangement now?

**Comment by elanhickler** [comment]
yes, except rsRoundToInt is not found in mac osx... but no idea why. Can't give any suggetions.

**Comment by elanhickler** [comment]
I think your includes are somehow structured wrong. When I go to definition in MSVC or in XCode it goes to Breakpoint Modulator

D:\_PROGRAMMING\RS-MET\Libraries\JUCE\modules\rapt\Modulators\Envelopes\BreakpointModulator.cpp

that's where it thinks it's defined.

**Comment by elanhickler** [comment]
when i hover my mouse over it in MSVC it says RAPT::roundToInt

wtfffffffff

**Comment by elanhickler** [comment]
I would get rid of RoindToInt in the breakpointmodulator and go from there

**Comment by RobinSchmidt** [comment]
oh! i get warnings (but not errors) related to that in windows/codeblocks, too

**Comment by RobinSchmidt** [comment]
yeah...i'll try to get rid of these "preliminary" implementations there

**Comment by RobinSchmidt** [comment]
ok - moved and templatized the rsRoundToInt function. compiles now without warning over here

**Comment by elanhickler** [comment]
ok, only issue is the setPreferredBusArrangement  now

**Comment by RobinSchmidt** [comment]
this is really a weirdo. the function is clearly declared in juce::AudioProcessor...even implemented - i even call the baseclass implementation from my overriden implementation. ...so you say, the error goes away, when i just remove the "override" tag from the declaration?

**Comment by elanhickler** [comment]
remove override and remove the class namespace in the function call

**Comment by RobinSchmidt** [comment]
as i told you above: the baseclass qualifier in the function call is important. without it, it could run into an infinite recursion

**Comment by RobinSchmidt** [comment]
not only "could" it, it actually does - i just tried it

**Comment by RobinSchmidt** [comment]
is there something ifdeffed in the baseclass or something? i just looked but found nothing

**Comment by RobinSchmidt** [comment]
what does the compiler error actually say?

**Comment by elanhickler** [comment]
going out now, will see if i can poke at it tomorrow.

**Comment by elanhickler** [comment]
says function does not override anything

**Comment by elanhickler** [comment]
I know the issue. You have an old JUCE copy in RS-MET that doesn't include AU. So I cannot build AU. So I switched to a newer version of JUCE, JUCE 5. But that has an issue with setPreferredBusArrangement

How do you get AU into your RS-MET version of JUCE? I don't know. Please fix asap. I need to get Spiral Generator out.

**Comment by RobinSchmidt** [comment]
it's juce 4.something - i did not yet migrate to 5.x ...but why should that be an issue? juce supports AU since ever. even version 1.something already supported AU

...wait...how are you using a newer version juce together with my library?...did you replace the module folders? or did you direct your projects to some other directory to grab the juce modules?

**Comment by elanhickler** [comment]
it's just a matter of getting some AU files.

**Comment by elanhickler** [comment]
oh hmm... robin, try this, update RS-MET JUCER to the 4.2.4 tag/commit/version of JUCE.

That's the last commit before setPreferredBusArrangement disappears from JUCE. Also, os x and windows is able to build spiral generator with that.

**Comment by elanhickler** [comment]
yes i redirected the to the newer modules.

juce supports AU but it didn't include the files until a certain version so I don't know how to deal with this. not sure what files need to go where

**Comment by elanhickler** [comment]
alright I am ready to release spiral generator! all problems solved... except that I need a function to get the correct phase for my LFOs when in tempo mode based on project playhead. I'll create a new issue for a series of tempo based functions I need.

**Comment by RobinSchmidt** [comment]
actually, 4.2.4 is the version, i'm currently using. i should probably use a version after which the function disappeared. maybe i should just update to the latest version...and hope that this won't produce a ton of issues. however, with version 5.0, a new licensing scheme was introduced - so i'm not sure

**Comment by RobinSchmidt** [comment]
...but if you are already using a newer version without problems, i will perhaps be a smooth update

**Comment by elanhickler** [comment]
like i said, I'm on 4.2.4, no idea why the specific commit is different than the one you are using in RS-MET.

Juce version 4.2.4
16 Sep 2016 9:03 
680d75807accebce075850cbdd302ccf6c56e8f2

maybe somehow your RS-MET version of JUCE lacks AU files.
