### ISSUE TITLE
License is not practical for OS X until we have a "choose location" dialog

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#37]
This has to be addressed.

**Comment by elanhickler** [comment]
after choosing location, copy the file to the location of our choice.

**Comment by RobinSchmidt** [comment]
where should this dialog be embedded? a button on the gui that opens it? the user would still have to download the file manually first (perhaps download it to some temporary download folder). why is it impractical to tell the user where to put the file on osx but not on pc?

**Comment by elanhickler** [comment]
Because on PC you can put the license file next to the dll. On Mac you have to put the license file in a specific place. Ultimately we need both PC and Mac to have the same solution.

We should have a preferences/settings button on all products for this.

Also, we need to revamp the "annoyance" part of the demo version. I'd like to see a 5 second popup every time you open the GUI and... what else... I forget.

**Comment by elanhickler** [comment]
the reason you can't put the license file next to the vst on mac is two things:

1. different formats, VST and AU need to be placed in different places
2. the places that those VST and AU files go, there should not be any other file type.
3. mac suks.

**Comment by elanhickler** [comment]
3. GarageBand (I think?) adds on its own read path or something, regardless of what we do. Copying the file to that path solves this problem.

**Comment by RobinSchmidt** [comment]
> Apple suks. :)

haha, yeah. i'm not a great fan either. a general preferences dialog is good. there, the user could also specify preset folders (user, factory), sample-library folders (where applicable), etc. in some of my old freebies, i actually have a "Setup" button - which currently opens a color-scheme dialog (which is the only thing that's currently customizable in my plugins) - but that could certainly be extended and/or modified to set up other things

**Comment by elanhickler** [comment]
I also want some text in the appropriate places for example "PrettyScope registered to Elan Hickler", maybe just on the preference/settings page or whatever, or maybe if we have a status/help bar, it can be the default text when nothing is being hovered.

**Comment by elanhickler** [comment]
we also need a button to open the manual.

**Comment by elanhickler** [comment]
solved this for myself.
