### ISSUE TITLE
I need to set colormap folder location

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#38]
jura_ColorMapLoader.cpp

```CPP
LoadableColorMap::LoadableColorMap()
{
  setActiveDirectory(getApplicationDirectory() + "/ColorMaps");
}
```

I need to set that path differently for Mac/Linux/Windows

**Comment by RobinSchmidt** [comment]
i think, you can just call `setActiveDirectory` on the colormap member (somewhere in your constructor of the class that contains the colormap) and set it to anything you want
