### ISSUE TITLE
Preset path is not working

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#39]
```CPP
SpiralGeneratorModule::SpiralGeneratorModule(CriticalSection *lockToUse)
  : AudioModuleWithMidiIn(lockToUse)
{
  ScopedLock scopedLock(*lock);

	moduleName = JucePlugin_Name; // correct name is vital for licensing system
	moduleVendor = JucePlugin_Manufacturer;
	String desktopPath = juce::File::getSpecialLocation(juce::File::userDesktopDirectory).getFullPathName();

#ifdef _WIN32
	presetPath     = getApplicationDirectory() + "/Presets";
#elif __APPLE__
	presetPath     = "/Library/Audio/Presets/"+moduleVendor+"/"+moduleName+"/Presets";
#elif __linux__ 
	presetPath     = getApplicationDirectory() + "/Presets";
#endif

	setActiveDirectory(presetPath);
  createParameters();
}
```

presetPath gets the correct value yet when you click the load button on spiral generator to load a preset, it still defaults to the "application directory"

**Comment by elanhickler** [comment]
this is a problem on windows as well

**Comment by elanhickler** [comment]
im going to send betas out for now, but please test this as soon as possible. We're still dealing with fundamental problems with your framework and it's pretty annoying while I'm trying to build a business.

**Comment by elanhickler** [comment]
If it's a matter of directory not existing, then create the directory.

**Comment by RobinSchmidt** [comment]
i just tried it on windows. it seems to be indeed an issue of the directory not existing - i.e. it works, when the directory exists but when it doesn't, it falls back to the application directory. can you confirm this?

creating the directory, if it doesn't exist - what's the use of this? i mean, if it doesn't exist, it means your installer failed to create it, so something has gone wrong with the installation process. creating an empty directory does not seem to be the right way to deal with such an error condition. popping up an error message seems more suiatable, no?

**Comment by elanhickler** [comment]
I CANT INSTALL USER FOLDERS ON MAC. 😡

**Comment by elanhickler** [comment]
please test this on mac now do that you have a mac running. I still have to have an apology message to my mac users because presets around found automatically, very annoying.

**Comment by elanhickler** [comment]
make sure the factory preset location works.
