### ISSUE TITLE
Spiral Generator does not work on linux

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#40]
please investigate if you have time: https://gitlab.com/Hickler/Chaosfly/issues/46

Did you test any plugins on linux yet? This should not be a spiral generator only problem, sounds like a problem with the framework unless you already tested your plugins on linux.

**Comment by RobinSchmidt** [comment]
i only did some quick tests in the juce plugin host with my chainer and it seemed to work fine (when i built it with the makefile - the codeblocks build crashed immediately). i will do some more testing tomorrow

**Comment by RobinSchmidt** [comment]
ok - i just tried my chainer and your spiralgenerator in juce plugin host. it happens over here to - with spiralgenerator, but not with chainer - so it sounds more like a problem specific to spiralgenerator. it even freezes the host (i can't plug out the plugin anymore, once it's frozen - i need to kill the process)

**Comment by elanhickler** [comment]
no longer relevant
