### ISSUE TITLE
Annoyance: Changing parameter causes "StateAsRequestedByHost"

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#41]
This is really annoying. You don't know what patch you are editing as soon as you change a parameter. The patch name must be remembered and displayed at all times.

**Comment by RobinSchmidt** [comment]
which host? i don't see this behavior in the juce host.

**Comment by RobinSchmidt** [comment]
ok - i see it in reaper

**Comment by RobinSchmidt** [comment]
ok - try now

**Comment by elanhickler** [comment]
thanks!
