### ISSUE TITLE
new Mac build errors

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#42]
Line 49 to 54 in updateCoeffs() in Ellipse.cpp
`A B C D E F "Use of undeclared identifier"`
you need to declare those variables.

`inline bool isPointOutside(T x, T y) {return this->evaluate(x, y) > 0; }`
you need to add `this->`

**Comment by RobinSchmidt** [comment]
ok, thanks. done. weird. the "this" pointer should be implicit inside member functions.

**Comment by RobinSchmidt** [comment]
..well -  i added the this pointer. declare variables? noo - they are inherited from rsConicSection

**Comment by elanhickler** [comment]
do you have a mac yet? i can only say what removes errors, not what makes the code work 👍

**Comment by RobinSchmidt** [comment]
the solution was to add this pointers there too:
```
  this->A = a2*s*s + b2*c*c;
  this->B = 2*(b2-a2)*s*c;
  this->C = a2*c*c + b2*s*s;
  this->D = -2*this->A*xc - this->B*yc;
  this->E = -2*this->C*yc - this->B*xc;
  this->F = this->A*xc*xc + this->B*xc*yc + this->C*yc*yc - a2*b2;
```
i found some explanation here:
https://stackoverflow.com/questions/4643074/why-do-i-have-to-access-template-base-class-members-through-the-this-pointer
what a great uglification of my code :-(

**Comment by RobinSchmidt** [comment]
you may see now, why i'm so insistent to review changes to my library

**Comment by elanhickler** [comment]
good, now please get preset system to work. Even on windows its very annoying because the plugin doesn't remember last location.
