### ISSUE TITLE
Spiral Generator/PrettyScope/Chaosfly does not function in FL Studio

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#44]
You can load spiral generator into FL studio, you can play it, but the audio comes out completely distorted.

**Comment by elanhickler** [comment]
None of my plugins work in FL Studios.

**Comment by elanhickler** [comment]
THIS IS REALLY BAD. This is an emergency problem. There is a contest happening now and FL Studio is a very popular host for music. I'll run the VS debugger now.

**Comment by elanhickler** [comment]
RayBouncer exhibits the same issue as Spiral Generator.

Please test in FL Studio and fix it! Maybe it will fix Spiral Generator as well.

By the way I just played with RayBouncer, it is very strange that it exhibits analog-like soft sync when modulating parameters, but as soon as parameters are not modulated, the effect goes away.

**Comment by RobinSchmidt** [comment]
ok - i will look into this tomorrow. FL is known for its idiosynchrasies...like wildly varying blocksizes between callbacks - although that shouldn't pose a problem for the framework. we'll see

the RayBouncer sync thing: to you have the AutoReset active? when it's on, it will automatically reset the internal state (current position and velocity)  on any parameter change. because i found that the produced sound is highly sensitive to initial conditions, so it makes sense to reset these during sounddesign (otherwise the patch will sound somehow, you save the preset, reload it and it will sound totally different)

**Comment by RobinSchmidt** [comment]
to be honest, i'm a bit disappointed by the raybouncer. it may look nice but somehow it sounds bad. maybe when i modulate the ellipse parameters, it gets more interesting, but i don't know

**Comment by elanhickler** [comment]
raybouncer is a good start. Great for prettyscope.

now you need to add the secret sauce, some kind of stabilization or chaotic element.

I would start by thinking of how to stabilize the sound. Well the first obvious thing is to ALWAYS do soft or hard sync based on frequency. Sync is boring though. You should think of a stabilization that is emergent, self-running, self-dependent, not perfect. Gravity, attractors, filter. OOH, if you add a filter to affect the max rate of change of the particle, then it will slow down and speed up as it bounces around.

There's a lot you can do, but definitely you shouldn't be disappointed. You need to take the next step.

**Comment by RobinSchmidt** [comment]
thanks for encouragement.  i just played a bit with it again, and yes, maybe it has potential. i think, it can do a pretty god job for the foundation of drone'ish sounds - but it needs more high-frequency "texture". i was considering ways of making the lines wiggle/zigzag a bit...but don't really know how.

what do you mean by "stabilize"? in which way do you consider it unstable?

gravity is another thing to consider. maybe i could have multiple particle that interact with each other by forces (but then you probably wouldn't get pretty pictures anymore). gravity, but maybe also repulsion like charged particles with the same charge. and/or let the user place fixed attractors.

**Comment by RobinSchmidt** [comment]
that would quickly become chaotic. already 3 particles would give rise to a chaotic system

**Comment by RobinSchmidt** [comment]
https://en.wikipedia.org/wiki/N-body_problem

**Comment by elanhickler** [comment]
when I say unstable I mean it is unstable because the harmonic structure is not multiples of the fundamental, it's very FMy sounding.

> (but then you probably wouldn't get pretty pictures anymore).
be careful of assumptions! I am confident this is false. Just gotta play around with variables and settings and you will get something good.

**Comment by RobinSchmidt** [comment]
yes - it's mostly inharmonic, which is why it doesn't really sound good, mostly - to me, at least. maybe some folks like inharmonic sounds, though

**Comment by elanhickler** [comment]
inharmonic is useful. harmonic is usually more useful. keep both.

**Comment by elanhickler** [comment]
another idea: a resonant filter that affects some part of the algorithm.

**Comment by RobinSchmidt** [comment]
i found something that helps a lot - with both harmonicity and chaos: just add some amount of the products  dx*dx, dy*dy, dx*dy of the velocity components dx, dy to the velocity components (and then renormalize to keep the speed). i need to include user parameters for that. with that addition, i'm getting more useful sounds out of it. yeah, i could also experiment with filtering the velocity

**Comment by RobinSchmidt** [comment]
i highpass could be interesting: it should have the effect of changing the direction. it would be unable to keep the velocity vector constant for a long time

**Comment by RobinSchmidt** [comment]
OK - i think, i fixed it. it was indeed related to variable buffer sizes. i had a bug in dealing with them.

**Comment by elanhickler** [comment]
To increase analog soft sync effect, try adding a "limit the number of bounces" control, so when you sweep frequency you get different harmonic locking efffects.

**Comment by RobinSchmidt** [comment]
maybe we can discuss this further in a separate thread, if you are interested. i don't understand how i could possibly limit the number of bounces. what should happen after the limit has been reached? ....ah, or maybe i see - maybe it should reset then to the initial position/velocity? i have included a NonLinearity slider now. it currently affects, how much of dx * dy gets added to dy and dy. i think, i need, more sliders for dx^2, dy^2 terms....but maybe the cross-term is even sufficient, i'll see

**Comment by elanhickler** [comment]
yes, after x bounces, reset.
