### ISSUE TITLE
Need fast sin approximation (lookup table?)

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#45]
This is a feature needed immediately! Please get on this quickly if you can.

I got some links form Hansi Raber and some info on what I need for Spiral Generator to lower the CPU.

**Hansi Raber:**

> there are two approaches to improving the speed of sin/cos. One is to create lookup tables, the implementations are often trivial, something along the lines of this: https://stackoverflow.com/a/13042227/347508
> 
> The other way out is to use approximations, it's a bit trickier, but other people have done the work already. Here's a great SO post: https://stackoverflow.com/questions/345085/how-do-trigonometric-functions-work/394512#394512

Please use whichever approach you want, just need it done quickly! Thanks! I might also need cos. I may need a few others but cos and sin are pretty good for now.
-Elan

**Comment by RobinSchmidt** [comment]
is the frequency fixed? in this case, you could use trigonometric recursion. i have implemented it it SineOscillator. the per sample operations are just:

```
  INLINE double SineOscillator::getSample()
  {
    double tmp = a1*s1 - s2;
    s2         = s1;
    s1         = tmp;
    return tmp;
  }
```

it doesn't get any faster than that for a fixed frequency sine and it's not even an approximation. however, frequency- and/or phase modulation will be expensive

**Comment by RobinSchmidt** [comment]
i have used this technique in our sinc-interpolator as well (it needs to compute lots and lots of fixed frequency sines and cosines)

**Comment by elanhickler** [comment]
uhhhhh... is it fixed frequency? i dunno??? spiral generator is a synthesizer.

**Comment by elanhickler** [comment]
are you sure this will work? I feel like maybe it wouldn't. I think we need a lookup table or the suggestion in the stackoverflow.

```CPP
void spiral_rotate(double in_x, double in_y, double in_z, double rot_x, double rot_y, double& out_x, double& out_y, double& out_z) 
{
	double cos_rotx = cos(rot_x); /*optimization*/
	double cos_roty = cos(rot_y); /*optimization*/
	double sin_rotx = sin(rot_x); /*optimization*/
	double sin_roty = sin(rot_y); /*optimization*/

	double help_11 = in_x*cos_rotx - in_y*sin_rotx;
	double help_12 = in_x*sin_rotx + in_y*cos_rotx;

	double help_21 = help_11*cos_roty - in_z*sin_roty;
	double help_22 = help_11*sin_roty + in_z*cos_roty;

	out_x = help_12;
	out_y = help_21;
	out_z = help_22;
}

void render(double in_x, double in_y, double in_z, double zdepth, double& out_l, double& out_r) 
{
	double formula = zdepth*1.25*(in_z / 2 + 0.5);  /*optimization*/
	double L = in_x - formula*in_x;
	double R = in_y - formula*in_y;

	double m = 1 + zdepth;

	out_l = L*m;
	out_r = R*m;
}

void spiral(double lophas, double phasor, double dense, double div, double morph, double& x_out, double& y_out, double& z_out)
{
	double clip_morph_0c1 = clip(morph, 0.0, 1.0);/*optimization*/
	double clip_morph_0c2 = clip(morph, 0.0, 2.0);/*optimization*/

	double formula_001 = PI_z_2 * (lophas - .5)*clip_morph_0c2 + PI_z_4; /*optimization*/
	double losin = sin(formula_001);
	double locos = cos(formula_001);
	double lo_x = 0;
	double formula_002 = pow(clip(morph, 0, 1), 2); /*optimization*/
	double one_z_div = 1 / div; /*optimization*/
	double lo_y = formula_002*(1 - one_z_div*losin);
	double lo_z = formula_002*(1 - one_z_div*locos);

	double formula_003 = PI / (2 + 6 * (1 - clip_morph_0c1))*(lophas - .5)*clip_morph_0c2 + PI_z_4; /*optimization*/
	losin = sin(formula_003);
	locos = cos(formula_003);

	double PI_x_2_x_phasor = PI_x_2*phasor; /*optimization*/
	double sp0sin = sin(PI_x_2_x_phasor);
	double sp0cos = cos(PI_x_2_x_phasor);
	double spiral0_x = sp0sin;
	double spiral0_y = sp0cos*losin;
	double spiral0_z = sp0cos*locos;

	double dense_x_PI_x_2_x_phasor_m_PI_z_2 = dense * PI_x_2_x_phasor - PI_z_2; /*optimization*/
	double sp1sin = -sin(dense_x_PI_x_2_x_phasor_m_PI_z_2);
	double sp1cos =  cos(dense_x_PI_x_2_x_phasor_m_PI_z_2);
	double sp1sin_x_sp01in = sp1sin*sp0sin;
	double spiral1_x = div*sp1sin_x_sp01in;
	double spiral1_y = div*((sp1sin*sp0cos)*losin + sp1cos*locos);
	double spiral1_z = div*(sp1cos*-losin + (sp1sin*sp0cos)*locos);

	double dense_x_dense_x_PI_x_2_x_phasor = dense*dense * PI_x_2*(phasor);  /*optimization*/
	double sp2sin =  cos(dense_x_dense_x_PI_x_2_x_phasor);
	double sp2cos = -sin(dense_x_dense_x_PI_x_2_x_phasor);
	double div_x_div = div*div;  /*optimization*/
	double spiral2_x = div_x_div*(sp2cos*sp0cos + sp2sin*sp1sin_x_sp01in);
	double spiral2_y = div_x_div*((sp2cos*-sp0sin + sp2sin*sp1sin*sp0cos)*losin + (sp2sin*sp1cos)*locos);
	double spiral2_z = div_x_div*((sp2sin*sp1cos)*-losin + (sp2cos*-sp0sin + sp2sin*sp1sin*sp0cos)*locos);

	double wave_x = (1 * lo_x + 1 * spiral0_x + 1 * spiral1_x + 1 * spiral2_x);
	double wave_y = (1 * lo_y + 1 * spiral0_y + 1 * spiral1_y + 1 * spiral2_y);
	double wave_z = (1 * lo_z + 1 * spiral0_z + 1 * spiral1_z + 1 * spiral2_z);

	double x = exp((morph)*log(div));
	wave_x *= x;
	wave_y *= x;
	wave_z *= x;

	double y = 0;
	double formula_004 = exp(morph*log(dense)) / 4; /*optimization*/
	if (formula_004 < 1)
		y = pow(1 - formula_004, 2);

	x = x*sin(PI_z_4)*y;
	wave_x -= x;
	wave_y += x;

	spiral_rotate(wave_x, wave_y, wave_z, 0, 0, x_out, y_out, z_out);
}
```

**Comment by elanhickler** [comment]
Hansi said it would be better to use a smaller table (1024 index or 4096) and use linear inteprolation when you are between indexes? maybe linear is good, I dunno. I don't know what interpolation one should use.

**Comment by RobinSchmidt** [comment]
i would probably favor linear interpolation as well.

**Comment by RobinSchmidt** [comment]
can i assume that the input value is always 0 <= input < 2*PI? that would save some wraparound code

**Comment by elanhickler** [comment]
i think it is -TAU to +TAU

tau = 2*pi btw

**Comment by RobinSchmidt** [comment]
if this is the code that produces the phase:
```
inline void phaseIncrement(double &phase, double increment)
{
  phase += increment;
  while(phase > PI_x_2)
    phase -= PI_x_2;
  while(phase < 0.0)
    phase += PI_x_2;
}
```
then it should be in 0 <= phase <= 2*PI. there's a new class in rapt calles rsSinCosTable (and a typedef'd template instantiation rsSinCosTableD for double that you can directly use). i'd recommend to use either linear interpolation (getValuesLinear) or rounding (getValuesRounded)

**Comment by RobinSchmidt** [comment]
ah, and it always produces a pair of sin/cos values, in order to do the common index computations just once. sin/cos pairs is exactly what you need (and, in fact, something that's quite commonly needed)

**Comment by RobinSchmidt** [comment]
> tau = 2*pi

aaahh - i see! :-)
https://tauday.com/tau-manifesto

**Comment by elanhickler** [comment]
ok i got it working but... why does linear have to give more error in the negative? Couldn't you just have some kind of dedicated negative approximation function? All my sin/cos functions go negative.

**Comment by elanhickler** [comment]
uhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh

i think your rsSinCosTable takes more CPU than the sin/cos functions I am replacing, by a small amount. Doesn't seem to reduce CPU at all. :(

**Comment by RobinSchmidt** [comment]
> why does linear have to give more error in the negative?

because i cast a double to int for indexing the table. this truncates towards zero where i actually would want the floor. but i want to avoid to actually call floor for efficiency

> your rsSinCosTable takes more CPU than the sin/cos functions I am replacing

really? then there's probably not much more you can do for optimizing these. hmm..or maybe we should try polynomials? don't know.

**Comment by elanhickler** [comment]
ok I don't need you to continue to work on this issue. I say it's up to the original author of this code to figure it out.

**Comment by elanhickler** [comment]
edit: but it's kinda cool to use really low number of tables and get quantization effects.

**Comment by elanhickler** [comment]
ultimately I'd say we should reduce the number of sin/cos calls by inventing a completely new algorithm that generates spirals via a not-perfect-but-efficient sinusoid generator.

**Comment by RobinSchmidt** [comment]
> it's kinda cool to use really low number of tables and get quantization effects.

yeah. but you could also use quant or quantToBits for this

**Comment by RobinSchmidt** [comment]
> Couldn't you just have some kind of dedicated negative approximation function?

yes, i could - but all of that introduces more code and hence more computations - which is not good if avoiding computations is the whole point

**Comment by RobinSchmidt** [comment]
are you sure you tested in a release build? i just added a performance test and in my test the table is much more efficient than the standard library functions. if you run the TestsRosicAndRapt.sln solution, you can try it yourself. ...although, i'm testing with float not double there. should that make such a big difference. i guess, i should try double, too.

**Comment by RobinSchmidt** [comment]
or maybe i need to update my tests? i'm using this:
https://en.wikipedia.org/wiki/Time_Stamp_Counter
which is said to be not reliable anymore. but i get very reproducible results.....hmm...

**Comment by elanhickler** [comment]
yes, I tested a lot. I replaced all sin/cos functions with your fast function, tried all kinds of settings, tried release and debug mode. 

so... i dunno... I don't have time for this.

**Comment by RobinSchmidt** [comment]
it's really weird. in my test setup, i get a boost by a factor of order 100. but maybe i missed some condition that occurs in more practical setups. dunno either.

**Comment by RobinSchmidt** [comment]
just for fun (probably not practically relevant), i added cubic interpolation because the math is rather neat: i can use the cosine table for the derivatives for the sine and the negative sine table as derivatives for the cosine. :-) i get a pretty good approximation (for positive inputs) with a table as small as 8. ...but yeah, that probably was a pointless math exercise since the standard library functions seem more efficient. i also think that my test results must be somehow flawed. they indicate to take less than 1 cycle per sin/cos pair, which seems impossible. i just wonder why.

**Comment by elanhickler** [comment]
ok, well if I ever figure out why my spiral generator is not more efficient with your fast sin functions... it would be nice to have a smoothing function for negative numbers perhaps... there are glitches when using truncation and becomes more obvious in lower frequencies.

**Comment by RobinSchmidt** [comment]
just don't feed in negative values. there's no need for that. just add 2*PI to the input, whenever its < 0. if it's still <0, add it again. that's actually precisely what the phase wraparound code already does. as said - my measurements are probably unreal. yours are probably more realistic. there must be some flaw in my test

**Comment by elanhickler** [comment]
ok ill try that.

Ultimately maybe you just have to play around with Spiral Generator and... do you know how to use visual studio profiler? Maybe I should try that.

**Comment by RobinSchmidt** [comment]
so far, i haven't used the profiler because i figured, in audio-dsp, we know anyway what part of the code has to be fast (anything within audio callbacks) and measured these things manually using my ProcessorCycleCounter class (in the test project). but maybe i should update it using this (maybe optionally):

https://msdn.microsoft.com/en-us/library/windows/desktop/dn553408(v=vs.85).aspx

but i think, i should familiarize myself with the profiler, too
