### ISSUE TITLE
Remove (if newPeakScale > 0) from AnalogEnvelop setPeakScale

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#5]
rosic_AnalogEnvelope.cpp
```
void AnalogEnvelope::setPeakScale(double newPeakScale)
{
  if( newPeakScale > 0 )
    peakScale = newPeakScale;
}
```

That can be confusing, randomly getting no effect on getting peak scale. It's a gotcha.

**Comment by RobinSchmidt** [comment]
hmm - you mean, the envelope should allow negative values, i.e. be a bipolar envelope?

**Comment by elanhickler** [comment]
sure, but the real problem is the difference between 0.000000 and 0.000001, one is 100% effective, the other is 0% effective.

Let's say I want to actually set peak scale to 0. Nothing happens. Oh but setting peak scale to 0.5 works... WHAT?

I dunno, maybe I don't know what setPeakScale is for. I thought it was for velocity, but it doesn't work as expected.

**Comment by RobinSchmidt** [comment]
it just literally scales the peak value, i.e. multiplies it. well, of course, i assume that the peak value is the value that will be approached in the attack phase (i think it's possible to set "peak" below "sustain" - i guess in this case, the envelope will just continue to rise during "decay" (just with a possibly different time constant) - but i never actually tried that). "peak" is just the constant value that goes into the RC-filter during attack. ...but it is actually not only "peak", but peak*peakScale. peakScale is 1 by default, in a neutral setting

**Comment by RobinSchmidt** [comment]
i think, i need a proper testbed for the new codebase where i can make plots and stuff

**Comment by RobinSchmidt** [comment]
peakScale is actually supposed to be >= 1. with 1, it's neutral, with values > 1, the peak goes higher

**Comment by elanhickler** [comment]
look, that's all very confusing. I just wrote my own code to scale points all by velocity for now. Finally it works. So do your test bed, figure out if there really is a bug with scaling by velocity, otherwise make it straightforward!

// velocityinfluence is how much velocity affects the envelope
scaleEnvelopeByVelocity(velocity, velocityinfluence = 1.0)

simple.

**Comment by RobinSchmidt** [comment]
damn - i just realized that i have a lot of redundant envelope implementations there anyway. i need to purge them and settle for one. as said, the whole library still needs lots of clean up and testing
