### ISSUE TITLE
compile error, need to disambiguate Rectangle

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#51]
### Jura_GraphicsTool.h
```
 -   Graphics &g, Rectangle<int> r,
 +   Graphics &g, juce::Rectangle<int> r,
```

### Jura_RSlider.h
```
 - JUCE_API void fillRectWithDefaultBackground(Graphics &g, Rectangle<int> r);
 + JUCE_API void fillRectWithDefaultBackground(Graphics &g, juce::Rectangle<int> r);

 -   Rectangle<int> handleRectangle;
 +   juce::Rectangle<int> handleRectangle;
```

**Comment by RobinSchmidt** [comment]
done. why didn't this trigger before?

**Comment by elanhickler** [comment]
Those errors happen whenever I fail to overwrite the dll when building a new version of something. So, they don't prevent compiling, but they get in the way of the errors that matter to me, such as failing to overwrite the dll. It's good to get rid of those errors. There are probably more of these as well.
