### ISSUE TITLE
need to store string for parameter modulation connection

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#52]
Have you worked on a modulation system? If not, I need something so that changing number of destination modulation options does not break presets.

Currently I use a dropdown widget which stores an integer based on the menu item chosen. I then translate that int to a modulation destination. If I add a new modulation destination in the list (but add it somewhere in the middle for organization purposes) it breaks patches.

I need to store and lookup destination via string so it will say "modulation destination is LowPassFilterFreq" or something.

I just got done creating a modulation class, where each modulator(lfo/adsr/env) has a bass class of Modulator (better name could actually be SignalOutput). Each parameter has an std::set of modulator. When you add a modulator to a parameter, you store it in the set, then go through the set and call "Modulator's" getValue, add that up, and that's the final parameter value.

A parameter is like a constant modulator itself connected to a slider so it could also be a Modulator (or SignalOutput) that could be added to something else, like a metaparameter system.

MetaParameter:
a parameter's SignalOutput --> std::set<SignalOutput> thisObject'sModConnections

MetaParameter + Macro Control (needed for Chaosfly and FMD)
SignalOutput --> Macro Control Modifier --> std::set<SignalOutput> thisObject'sModConnections

Come on Robin, this can all be done.

**Comment by elanhickler** [comment]
I feel like your MetaParameter system should have been made like how I am suggesting doing modulation where a slider is no different than an LFO or ADSR. The slider can simply send modulation to another slider.

Oh I see, if a parameter sends to an object's mod connection you have to normalize the range from 0 to 1 so it can be ranged correctly for the destination.

MetaParameter (with normalization):
a parameter's SignalOutput --> 
--> parameter's own normalization -->
std::set<SignalOutput> thisObject'sModConnections

**Comment by elanhickler** [comment]
Slider = gui component
Parameter = constant modulator object

Simple connection (hard-coded):
Slider --> Parameter --> synthesizer's dsp algorithm variable.

Meta-parameter
Slider --> Parameter --> Paramater's own normalize function --> other Parameter's rangify function --> other parameter

Macro Control
Slider --> Parameter --> Paramater's own normalize function --> Modifier object --> other Parameter's rangify function --> other parameter

**Comment by elanhickler** [comment]
What happens if you do

Slider --> Parameter --> Other Parameter
Slider --> Other Parameter --> Parameter

Of course, bad things will happen. So have some logic for the GUI, do not allow param <--> param connection.

**Comment by elanhickler** [comment]
Right now you have:
Meta Parameter 1 --> GUI Slider A --> Parameter A
Meta Parameter 1 --> GUI Slider B --> Parameter B

For a macro system we need:
Meta Parameter 1 --> Macro 1: Modifier A --> GUI Slider A --> Parameter A
Meta Parameter 1 --> Macro 1: Modifier B --> GUI Slider B --> Parameter B

With my system it would look like this:
GUI Slider A --> Parameter A
GUI Slider B --> Parameter B
Parameter A --> Macro 1: Modifier B --> Parameter B

**Comment by elanhickler** [comment]
In my system, Parameter A becomes a master parameter of other slave parameters just by having that connection. I can send Parameter A to multiple destinations.

I feel like my system is more simple and easier to implement.

**Comment by elanhickler** [comment]
Example real-world usage of my system:
* Send `FilterFreq` to `Macro 1`
* Send `Macro 1: Channel 1` to `Tune`
* Set `Macro 1: Channel 1` to `Log Curve`

* Send `Macro 1: Channel 2` to `ModAmt`
* Set `Macro 1: Channel 2` to `Multipoint`

Oh, that just gave me an idea...

**Comment by elanhickler** [comment]
This is one way we could allow for easy exp/linear/log of macro control scalings per destination... if it's easier, maybe it's not.

Macro Control --> Multipoint modulator --> Position curve --> Out

Position curve could be exp/log/lin. Position curve means we offset the position at which the final value is derived. But this would actually be confusing from a user/gui standpoint.

It would be better to have the option of exp/lin/log/multipoint or something... I'm probably confusing you by now...

**Comment by elanhickler** [comment]
robin, what if I paid you in royalties for the kickstarter? take what you think is fair, and that can pay for you getting my business really going. i mean, polishing your framework, adding macro system, adding modulation system, better gui.

I'm desperate here man.

**Comment by elanhickler** [comment]
I think we need to have a meeting.

**Comment by elanhickler** [comment]
Robin, I am going all in. So talk to me, let's get this done. I have a proposal.

**Comment by RobinSchmidt** [comment]
whoa. this is a lot to digest. i'm currently a bit busy with tax stuff. 

i would probably make a subclass ModulatableParameter of Parameter that can subscribe to any number of Modulators (using some kind of ModulationManager object). these modulators would have to be computed once for each sample before anything else gets computed, then the ModulatableParameter objects gather their inputs, form a weighted sum and then do their callback, like calling setCutoff on some filter. but yeah...it has to be decided whether modulation signals should be interpreted as being in the normalized 0..1 domain or not. perhaps better yes.

**Comment by RobinSchmidt** [comment]
...or maybe not? i think, it might be rather expensive to do all the required conversions (possibly calling exp, log functions per sample).

**Comment by elanhickler** [comment]
We could have multiple options on how to send and signals, some efficient, some not.

Let's have a meeting! I'd like to make an offer on helping me get the kickstarter instruments done.

**Comment by elanhickler** [comment]
How about making an approximation value array when connecting/changing scaling? You can do this because connections won't be automated, everything can be prewritten.

If you want to sweeten the deal I have a "simplify array" function from Jim Credland where we can make the array as big/small as we want. Oh but then we still need crossfading between indexes. So a the linear-ish part of a log or exp function will have less.

**Comment by RobinSchmidt** [comment]
ok, let's meet tomorrow (i'm not at home today). i think, using lookup tables for exp/log will probably give the same amount of "improvement" like it did for sin/cos. there's some other thing in my code, that i could optimize, though. the conversion now reads:

```
double Parameter::proportionToValue(double prop)
{
  switch( scaling )
  {
  case EXPONENTIAL: return minValue * exp(prop*(log(maxValue/minValue)));
  default:          return minValue + (maxValue - minValue) * prop;
  }
}
```
where `log(maxValue/minValue)` is independent of `value` and thus, could be precomputed. it's the classical space/time tradeoff. store more data / compute less on the fly - increase memory usage / reduce cpu usage

**Comment by RobinSchmidt** [comment]
how about setting up the modulation amount as relative value (relative to the nominal basis value). like when modulation is set to 0.1 or 10% and and lfo oscillates between -1 and +1, a 1000 Hz cutoff would be modulated between 900 and 1100? and a 2000 Hz cutoff would with the same settings be modulated between 1800 and 2200. i think, the formula would just be:

modulatedValue = baseValue + modAmount * modulatorOutput * baseValue

**Comment by elanhickler** [comment]
sometimes I might need to have linear frequency relation, sometimes exponential. For example

oscillator frequency vs filter frequency (filter frequency might need to keep itself 1 octave higher than the oscillator)

**Comment by RobinSchmidt** [comment]
wouldn't that just correspond to a +100% setting? 1000 + (100% of 1000) is 2000. 2000 + (100% of 2000) is 4000

**Comment by RobinSchmidt** [comment]
i mean, it already would be a relative value then. just the shape between the end-values might not be what you want (linear instead of exponential). but wouldn't it be more convenient to bake that shape into the modulation signal anyway?

**Comment by elanhickler** [comment]
If we can have custom shape between end values on top of that it would be nice, but may not be crucial. Not sure if I'll ever need to put in some "corrections" or "creative bumps" into the curve.

**Comment by elanhickler** [comment]
QUESTION: Does your macro parameter system allow for an LFO to modulate the macro parameter? I don't need this now because I am using the macro parameter system just as a way to experiment to later hard code something. But in the future, for Chaosfly, macro-parameter system will be a feature of the synthesizer.

Use case is, for example, connecting filter frequency and tuning like the above example, then... now I want vibrato. LFO must go through the macro parameter to maintain the sound perfectly as intended.

**Comment by elanhickler** [comment]
If your answer is NO, then I have a proposal for the future.
