### ISSUE TITLE
AU plugin crashes

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#53]
reported here: https://www.kvraudio.com/forum/viewtopic.php?p=6834084#p6834084

> Architeuthis:
> 
> The AU version has been consistently crashing validation in Logic Pro X since the beginning - I wonder if it is the same problem as here:
> https://forum.juce.com/t/plugin-not-validating-in-logic-pro-x-10-2-0/16449/2
> 
> In which case just returning more than 0 from getNumPrograms could fix it. Maybe?

**Comment by RobinSchmidt** [comment]
in jura:AudioPlugin, i have:

`virtual int getNumPrograms() override { return 1; }                // 1, because 0 is not allowed`
