### ISSUE TITLE
spiral generator failed AU validation

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#59]
posted on juce forum: https://forum.juce.com/t/au-failed-validation-in-logic-why/23719

**Comment by RobinSchmidt** [comment]
hmm - looks like you are getting an access violation. do you think, it's a bug in my framework? does it happen with your other plugins and/or my chainer, too or only in spiralgenerator?

**Comment by elanhickler** [comment]
I don't know, I'm guessing you don't have Logic to test it?

**Comment by RobinSchmidt** [comment]
no, i don't have logic. so you don't have it either and this is a bug report from a user? ...but if it's an access violation, shouldn't it occur in other hosts, too? maybe it has to do with unexpected audio buffer sizes passed to the processing callback? i'm just guessing. this was the problem in my framework with FL. maybe you have something similar? can you ask the user, if he has the same problem with PrettyScope?

**Comment by elanhickler** [comment]
I think we don't need logic, we just need avaultool which I think comes with Mac? keep watching the thread.

**Comment by elanhickler** [comment]
Anote user reports prettyScope fails at the same point, processBlock

**Comment by elanhickler** [comment]
I just ran auvaltool, couldn't make sense of it but I bet you would have more luck than me. I couldn't get the AU version to build, XCode can't find AUResources file. god damnit. I can't tell if maybe it's because I need to be building AU version, not VST version, for auvaltool to work.

If you need help getting to work, I know how.

**Comment by elanhickler** [comment]
Robin, you cannot assume inOutAudioBuffer** is valid

you have to do, in the sample loop:

if (inOutAudioBuffer[0]) acccesTheBuffer = inOutAudioBuffer[0][n]

If you assume it is valid, you will fail for mono tests in AU plugins, because audiobuffer[1] (right channel) will be invalid.

**Comment by RobinSchmidt** [comment]
yes, the plugins assume stereo input. i often have a `jassert(numChannels == 2)` - of course, that doesn't help in a release build. you can throw in an  `if(numChannels != 2) return;` or something like that

**Comment by elanhickler** [comment]
numchannels is reported by auval?

**Comment by RobinSchmidt** [comment]
yes, in the processing callback, you always get a numChannels variable passed

**Comment by RobinSchmidt** [comment]
this is independent from the host. the sdk prescribes this, so the host must adhere to it

**Comment by elanhickler** [comment]
which SDK? vst AND au? because we're dealing with AU here.

**Comment by RobinSchmidt** [comment]
well, we are dealing only with juce. that is, i'm dealing with juce (which passes me these things) and you are dealing with jura - where i pass them through to you, too. juce itself must somehow get this value from the au or vst sdk - but we are not really concerned with this. in case of the vst-sdk, which i also used raw, i know that the numChannels variable is passed to every "process" call.

**Comment by RobinSchmidt** [comment]
the processing callbacks are, if i'm not mistaken, all very similar in the different plugin apis. pointer-to-pointer to samples, numSamples, numChannels - that's pretty much standard, i think

**Comment by RobinSchmidt** [comment]
juce actually wraps that into a juce::AudioBuffer object that gets passed. but that, internally, has the same structure

**Comment by RobinSchmidt** [comment]
but wherevere it comes from, in

`processBlock(double **inOutBuffer, int numChannels, int numSamples)`

which is the audio processing callback function, you override, you have this value available (i get it from juce - i don't care where *it* it has from)
