### ISSUE TITLE
I asked about getting value of slider, you said I shouldn't?

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#61]
What is wrong with:
```javascript
AutomatableSlider * mySlider; // somewhere in the code declare slider
double storedValue = mySlider->getValue(); // somewhere in the code I need the value
```
You said it's better to store the value in a separate variable as part of the valueChangeCallback and do not call `getValue()`

Is this true? Maybe I misheard and you are talking about something else

**Comment by RobinSchmidt** [comment]
i think, i said, if you want to retrieve the value, it might be better to retrieve it from the underlying parameter instead of from the widget. but it depends on the context. the parameter is the more basic object and also available to code that doesn't need to be concerned with gui stuff

**Comment by elanhickler** [comment]
```javascript
Parameter * p myParameter
double storedValue = myParameter.getValue()
```

that's what I meant to write originally

**Comment by RobinSchmidt** [comment]
i don't see any problem with that

**Comment by elanhickler** [comment]
k
