### ISSUE TITLE
For some reason I have to invert the bool of setVisible(bool)

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#62]
![image](https://user-images.githubusercontent.com/9116575/29476827-a0febd0c-841a-11e7-8353-caa77912ad2e.png)

when showNumCycles is true, the slider is hidden, so i invert the bool.

prettyScope->SyncMode.ptr is a jura::Parameter
prettyScope->SyncNumCycles.slider is an AutomatableSlider

Please take a look when you get a chance. You can put your time on my tab.

**Comment by RobinSchmidt** [comment]
did you solve this? what was it?

**Comment by elanhickler** [comment]
No longer relevant, not solved, code is removed. Not going to think about it! If it comes up again I'll report it.
