### ISSUE TITLE
I want to make an LFO module

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#69]
You have not yet explained how to create a module, such as an LFO, that I can instantiate into my other plugins, like your Breakpoint Modulator, which has a GUI build in. Then you just instantiate it into a plugin like Chaosfly.

I want to design an LFO for PrettyScope and then instantiate 6 of them.

LFO controls:
1pole highpass
1pole lowpass
phase
frequency
shapes: sine, tri, square, saw, noise, random square, random linear
self-feedback amount (amount of signal sent to frequency control)

+ an LFO visual (update the display for changes to phase and shape)

you could use this idea for when you make an LFO for your chainer.

extra features:
delay/attack/decay/sustain/release for output amplitude

**Comment by elanhickler** [comment]
my ultimate LFO design:

![image](https://user-images.githubusercontent.com/9116575/30007796-7f0c102e-90cb-11e7-95fd-aaea1fcef761.png)
update visual for: phase, bias, clip+, clip-, lowpass, highpass, or whatever is easy to do. Ultimately it'd be even nice to update the visual for feedback, but not sure how you can calculate the resulting shape of that.

Would be cool if you could reorder those "modules" visually, maybe in the future you could create a "reorderer" gui object where you can easily attach to any class, give it some parameters, and boom, you can reorder components of anything. Also, you could enable/disable by clicking on the module.

**Comment by RobinSchmidt** [comment]
> You have not yet explained how to create a module, such as an LFO, that I can instantiate into my other plugins

yes, i should make another wiki page for that. to create your own modules, you must subclass my AudioModule baseclass. to make the LFO also available for the modulation system, it must also be a subclass of ModulationSource, so you would do
```
class MyLFO : public jura::AudioModule, public jura::ModulationSource
{
  // stuff
};
```
for a GUI, you must subclass AudioModuleEditor:
```
class MyLFOEditor : public jura::AudioModuleEditor
{
  // stuff
  MyLFO* editedLFO; // editors have pointers to their editees
};
```
to use the LFO, you would have to add it as child-module to your synth (which is itself also an AudioModule)
```
MySynth::MySynth()
{
  lfo1 = new MyLFO;
  addChildAudioModule(lfo1);
}
```

**Comment by RobinSchmidt** [comment]
hey - why has your code syntax highlighting but mine doesn't? :-O

**Comment by elanhickler** [comment]
```
```cpp
//my code has highlighting
```
```

**Comment by RobinSchmidt** [comment]
aaaaahhh! :-)

**Comment by elanhickler** [comment]
I'll wait for you to create your LFO then maybe I'll steal it for my own purposes and add/edit it? If I make an LFO I might be copying most of what you're doing already.

**Comment by elanhickler** [comment]
I designed this sub section for Spiral Generator:
![image](https://user-images.githubusercontent.com/9116575/30038963-975b3240-917f-11e7-81eb-49689d0bcdfa.png)

**Comment by elanhickler** [comment]
heehee I did exactly this for Mushroom generator... minus the visual.
