### ISSUE TITLE
Please add tension based scaling to parameter scaling options

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#7]
see this:

http://www.mathopenref.com/graphfunctions.html?fx=(a*x-x)/(2*a*x-a-1)&sg=f&sh=f&xh=1&xl=0&yh=1&yl=0&ah=1&al=-1&a=-0.7340425531914894

**Comment by RobinSchmidt** [comment]
i was considering to make the scaling options of the Parameter class totally customizable by letting the user pass some kind of "ParameterMapper" object. you could then do things like:
`myParameter->setMapper(myParameterMapper) ` ...or something like that

**Comment by elanhickler** [comment]
yes. std::function time?

**Comment by RobinSchmidt** [comment]
i was actually more thinking about providing an abstract baseclass
`ParameterMapper
{
public:
  double map(double value) = 0;
  double unmap(double value) = 0;
};
`
and client code could then create various subclasses and pass objects of their subclasses into the Parameter object. the mapper needs to implement both mappings - forward and backward (to make Parameter::setValue and Parameter::setProportionalValue work - the former needs the forward mapping and latter needs the backward mapping)

**Comment by RobinSchmidt** [comment]
no...the other way around

**Comment by elanhickler** [comment]
Sounds good

On May 12, 2017 11:00 AM, "Robin Schmidt" <notifications@github.com> wrote:

i was actually more thinking about providing an abstract baseclass
ParameterMapper { public: double map(double value) = 0; double unmap(double
value) = 0; };
and client code could then create various subclasses and pass objects of
their subclasses into the Parameter object. the mapper needs to implement
both mappings - forward and backward (to make Parameter::setValue and
Parameter::setProportionalValue work - the former needs the forward mapping
and latter needs the backward mapping)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/RobinSchmidt/RS-MET/issues/7#issuecomment-301145150>,
or mute the thread

**Comment by elanhickler** [comment]
fulfilled
