### ISSUE TITLE
Midi Modulation Source

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#70]
Just like you can add an LFO to the modulator system, you should also make a midi source that has a set of controls.

LFO module
![image](https://user-images.githubusercontent.com/9116575/30038510-3a1a785c-917a-11e7-824d-0ce883757cfe.png)

Midi src module
![image](https://user-images.githubusercontent.com/9116575/30038506-30980718-917a-11e7-9148-82648871e567.png)

the problem is that midi sources have such few controls, it would be nice to be able to add multiple midi sources on the same module / same page. I came up with this design:

![image](https://user-images.githubusercontent.com/9116575/30038520-5de28a90-917a-11e7-89fa-253dd69f92db.png)

**Comment by RobinSchmidt** [comment]
yeah - right. you mean, i should have some ModulationSource objects available that reflect the current midi state. ...like one that reflects the current note, the current velocity, pitch-wheel, ...maybe controllers. i was already thinking about this myself and i want to add that to chainer.

oooh... well. you mean "add midi src" should be an additional button? i think, i would rather include midi-note, midi-velocity, etc. in the existing menu of mod sources

**Comment by elanhickler** [comment]
No, I'm simply saying treat these exactly like you treat LFOs. You have to make a midi object to have it available as a mod source... because it's too limit to just have amplitude as your only parameter. I need smoothing and offset.

**Comment by elanhickler** [comment]
It may not be so useful to have multiple midi objects that get its output value from the same midi source (multiple pitchwheels) unless somehow you really want to have different smoothing amounts or offsets.... anyway, my main point is midi sources need smoothing and offset.

**Comment by elanhickler** [comment]
oh, and the reason you will want t have an "add" button for midi sources is when someone wants to add CC30, CC56, CCwhatever. Do you really want to have 127 entries in your mod source list by default?

**Comment by RobinSchmidt** [comment]
ahaaaa!!! yes! i think that's a good idea. maybe a module that receives the midi input data and allows the user to define arbitrary outputs based on that data. like:

modOutput1 = smoothingFilter(pitchToFreq(currentMidiNote));

maybe i could use my expression evaluator (like in func-shaper) for that

**Comment by elanhickler** [comment]
woah, where did this idea of functions come in for mod sources?

Are you saying you would create a "modulation source object" that is an expression evaluator? That would be pretty sweet. I could throw a few of those into spiral generator.

**Comment by elanhickler** [comment]
Oh but how do you set smoothingFilter smoothing speed?

**Comment by RobinSchmidt** [comment]
yes. an expression evaluator that has access to the midi state.

> how do you set smoothingFilter smoothing speed?

yes, that's a good question. currently, the expression evaluator handles only instantaneous mappings. it would have to be extended to handle filtering operations. i don't know if that's easy or even possible. but from a user's point of view, it could be as simple as:

smoothedOutput = smoothingFilter(someInput, smoothAmount);

where "someInput" could be the midi-note or some expression based on it and "smoothAmount" is the trasition time. ...well....this is only brainstorming. but it could be possible

**Comment by RobinSchmidt** [comment]
> Do you really want to have 127 entries in your mod source list by default?

nnnaaaaaahhhhh!!!! i was about thinking about creating a single midi source module (in some slot in the chainer) and there you define the number of mod-outputs and the values of the outputs via expressions (and maybe also the names). and only these defined outputs would the appear in the source menu

**Comment by RobinSchmidt** [comment]
the midi source module would have full access to all controller values, note, pitch-wheel state, etc.

**Comment by elanhickler** [comment]
i will have to ask about adding/removing LFOs / modulation sources during runtime to have a truly wireless modular synth.
