### ISSUE TITLE
spiral generator build fails with latest commit

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#72]
to get spiral generator to build I have to use an earlier version of RS-MET library, the error is:
```
Error	C2661	'SpiralGeneratorModule::SpiralGeneratorModule': no overloaded function takes 2 arguments (compiling source file ..\..\Source\SpiralGeneratorPlugin.cpp)	SpiralGenerator	278	d:\_programming\rs-met\libraries\juce\modules\jura_framework\audio\jura_AudioPlugin.h	

d:\_programming\rs-met\libraries\juce\modules\jura_framework\audio/jura_AudioPlugin.h(278): 
error C2661: 
'SpiralGeneratorModule::SpiralGeneratorModule': no overloaded function takes 2 arguments (compiling source file ..\..\Source\SpiralGeneratorPlugin.cpp)

..\..\Source\SpiralGeneratorPlugin.cpp(357): note: see reference to function template instantiation 

'jura::AudioPluginWithMidiIn *jura::createPluginWithMidi<SpiralGeneratorModule>(AudioModuleType *,int)' being compiled
        with
        [
            AudioModuleType=SpiralGeneratorModule
        ]
```

**Comment by elanhickler** [comment]
robin, could you get the spiral generator modulation manager working and solve this build issue today? probably only take you 10 minutes.

**Comment by RobinSchmidt** [comment]
i fixed the build issue but debugging the mod-manager integration seems to be a bit tricky. i'll keep trying

**Comment by RobinSchmidt** [comment]
btw.: how could you run into the crash issuer if you couldn't even build it?

i now have a hunch. in chainer, the modulation sources and targets are all created later than the chainer module itself - they are all submodules of the chainer and the modulators only modulate parameters of their sibling modules. in your case, the modulators should modulate parameters of their parent-module. maybe there's something about the order in which the constructors are called. i'll look into this. your code looks actually right - the way i intended it to be used

**Comment by RobinSchmidt** [comment]
ok, try now. it seems the mod-sources are now available for the parameters and it doesn't crash in destructor anymore. ..but i hear no sound - but i don't think that has to do with my recent changes, or has it?

**Comment by RobinSchmidt** [comment]
the crash was a quite subtle thing about destruction order of baseclasses and members, where the baseclasses get passed a pointer to a member of the subclass. ...maybe i should rethink this design

**Comment by elanhickler** [comment]
im in the middle of trying to implement jerobeam algorithms, kinda difficult to translate some of this stuff, you have to pay attention to all the stupid max patch wires.

**Comment by elanhickler** [comment]
oh, i just changed the RS-MET code locally to make it build.

**Comment by elanhickler** [comment]
Are you going to make an LFO or should I?

**Comment by RobinSchmidt** [comment]
i want to make one based on a wavetable, i.e. loading single cycle waveforms like straightliner's oscs - that seems to quite different from what you proposed. but i'm not sure what to do first - figure out the smoothing filter scaling, make the lfo or the value mapper

**Comment by RobinSchmidt** [comment]
btw - you are aware that the BreakpointModulator can be used as LFO as well, right?

**Comment by elanhickler** [comment]
Ok, i should make my own LFO. How do you intend to do loading single cycle waveforms? Also can we stop calling it an LFO and call it a general purpose oscillator? LOL. I'm not going to use it like an LFO at all. I'm going to use it has LFO/HFO/chaos generator/etc.

Yes, I'm aware that breakpoint modulator can be used as an LFO, but it's annoying to use. You have to work on that junk!

I personally wouldn't waste my time with wavetables. I'm all about generating interesting shapes algorithmically and via emergent behaviors. Wavetables are inflexible.

Check out these waveform shapes that all can be made with one algorithm and a few sliders. This is made by xoxos and he's offered to give me the math for it.
![lfo5](https://user-images.githubusercontent.com/9116575/30241523-dea52904-9539-11e7-8c57-9d697b15e087.png)

**Comment by elanhickler** [comment]
oh wait, no, this algorithm more to my liking:

source: https://www.kvraudio.com/forum/viewtopic.php?p=6718763#p6718763

![normalisationsynthesis](https://user-images.githubusercontent.com/9116575/30241679-17334b36-953d-11e7-80d9-23211c03cda8.png)

**Comment by RobinSchmidt** [comment]
hey - that's pretty cool! :-)

**Comment by elanhickler** [comment]
I say I wouldn't waste my time with wavetables, keep in mind I wouldn't waste my time with traditional subtractive synthesis... so take that with a grain of salt. If you like wavetables, do it! Don't let me discourage you. But if you can make wavetables flexible (i.e. realtime morphable) then that's something interesting.

**Comment by RobinSchmidt** [comment]
we could do time-variant phase-shaping

**Comment by elanhickler** [comment]
It would be nice for you to look at my Jerobeam code and make suggestions on what you'd do to the code before implementing in your library. I don't mind doing some of that for you.

**Comment by elanhickler** [comment]
JerobeamSpiral (finished)
JerobeamTorus (almost finished)
JerobeamBoing (almost finished)
JerobeamRadar (cannot finish without help)

Would be nice for you to experiment with more efficient sine algorithms or if you see any way to make it more efficient! Last time I tried your more efficient sine algorithms it didn't work. *shrug*

**Comment by elanhickler** [comment]
solved
