### ISSUE TITLE
Oscillator that responds correctly to negative phase?

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#77]
Robin, here is code that allows the oscillator to respond correctly to negative phase:

```cpp
	static double saw(double phase) 
	{
		while (phase > TAU)
			phase -= TAU;
		while (phase < 0.0)
			phase += TAU;
		if (phase < PI)
			return phase/PI;
		else
			return (phase/PI)-2.0;
	}
```

Is there any way to simply it?

**Comment by elanhickler** [comment]
this works

```cpp
	static double saw(double phase) 
	{
		double value = phase - TAU * floor(phase / TAU);
		if (value < PI)
			return value/PI;
		else
			return (value/PI)-2.0;
	}
```

**Comment by RobinSchmidt** [comment]
did you measure performance. the division and call to floor might be expensive. i'd also recommend to replace divisions by multiplications. maybe the compiler will do that optimization anyway, but who knows

**Comment by elanhickler** [comment]
how would you replace the division with multiplication? is the while loop faster?

**Comment by elanhickler** [comment]
also consider your original saw wave uses fmod, soooo...?

**Comment by RobinSchmidt** [comment]
> how would you replace the division with multiplication? 

replace `value/PI` by `value*PI_INV` where PI_INV is the reciprocal of PI (i just added a definition for that to rapt)

> is the while loop faster?

i don't know. this would have to be measured

**Comment by RobinSchmidt** [comment]
> your original saw wave uses fmod, soooo...?

yeah, i figured, may it's more precise than doing repeated adds/subs (each with a rounding error), but i'm really not sure

**Comment by elanhickler** [comment]
ok i will use PI_INV. Closing topic because I don't care to do speed tests at the moment! We can do speed tests when I have a working synth that uses too much CPU.
