### ISSUE TITLE
How does RayBouncer stay in tune?

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#82]
I see RayBouncer as essentially a 2D triangle genereator with some options to make it not a triangle.

You increment the particle position every sample and when it hits a wall you reflect it.

If you do that in 1D where you just have a ceiling and a floor, you get a triangle, right?

I would thing that doing this every sample:

```cpp
position += secondsPerSample * speed
if (position >= target)
{
   secondsPerSampe *= -1;
   target *= -1;
}
```

would not be in tune depending on the samplerate and frequency, you'd get rounding errors.

Do you do something more complex with RayBouncer? It stays in tune across all octaves.

**Comment by elanhickler** [comment]
omg i just had a random brilliant idea. what if you implemented a hard sync except when you reset the slave oscillator, you do our "Slow Reset" idea, where it moves toward 0 phase. That could sound analog... or... it could sound physical/natural.

**Comment by elanhickler** [comment]
results : https://youtu.be/ah8ZGdGbFLM

No example of this in the video, but filtering the phase during hard sync event ended up creating very analog-esque soft sync.

**Comment by RobinSchmidt** [comment]
> [something] would not be in tune depending on the samplerate and frequency, you'd get rounding errors.

indeed. you have to compute, how much it overshoots the target with the sample instant and re-initialize the new. conceptually, something like:
```
if(position > target)
{
  overshoot = position - target;
  position = target - overshoot;
  // the stuff, you said
}
```

**Comment by RobinSchmidt** [comment]
this reflects the overshoot at the target values, so to speak. but i do that in more complicated ways by reflecting at a tanget line to the ellipse in 2D

**Comment by RobinSchmidt** [comment]
> filtering the phase during hard sync event ended up creating very analog-esque soft sync!

ahaa. interisting. but then, you can't really create high-frequency oscillations anymore, because the speed your phasor is always slowed down by the lowpass. hmm...maybe the lowpass should somehow track the pitch of slave osc or something

**Comment by elanhickler** [comment]
nonono, you filter the phase only during phase reset... or just... trying something like 

if (phaseIsResetting)
incPhaseTowardZero()

if (phase == 0)
phaseIsResetting = false;

**Comment by RobinSchmidt** [comment]
hmmm...i have no idea how that would work together with the regular phase update that you also do per sample. would you just stop doing that during reset?

**Comment by elanhickler** [comment]
Yes, that's what I did, I stopped the phase incrementor during the gradual phase reset.

**Comment by elanhickler** [comment]
I don't get how you calculate position and target.

**Comment by elanhickler** [comment]
```cpp
position = 0
inc = (1/44100) / (1/440) // secondsPerSample / secondsPerCycle  = 0.00997732426303854875
position + (inc*100) = 1.00000515357658214801
if (position > 1) // 1 = target, happens after 100 samples
{
    overshoot = position - target; // overshoot = 0.00000515357658214801
    position = target - overshoot; // position = 0.99999484642341785199
}
```

**Comment by RobinSchmidt** [comment]
well, to be sure, i'd actually ha to try it in code. the idea is: when you overshoot the target within the sample you reach it (which is almost always the case), then the amount you have overshot it, should be reflected at the target value. let's say your per-sample increment is 2.4, target is 100 and you are at 99. then, in the next sample, you land at 99+2.4 = 101.4. the overshoot is 1.4. that means, within the sample, you traveled to 100, got reflected at 100 and end up at 100-1.4 = 98.6. so from 99 you go to 98.6 with increment 2.4 and 100 as target. within one sample, you traveled one step forward and 1.4 back, because you encountered a reflection within that sample

**Comment by elanhickler** [comment]
I need to factor out, but doing timer - 1 for overshoot is going to explode the value if your timer increment is above 0.5, so I made this code (will turn into a dedicated timer class)

```cpp
// timer NEED TO FACTOR OUT
	double current_sampled_noise_val = 0.0;
	double timer = 1.0;
	double timerInc = 0.0;
	double sampleRate = 44100.0;
	double sampleRateInv = 1/44100.0;
	void updateTimerInc()
	{
		timerInc = sampleRateInv * frequency;
	}

	void incrememt() { timer += timerInc; }

	void triggerEvent()
	{
		timer = jmin(timer - 1, 0.5); // calculate overshoot
		current_sampled_noise_val = noise.getSample();
	}

	double do_RAND_SQUARE_stuff()
	{
		incrememt();
		if (timer >= 1)
			triggerEvent();
		return current_sampled_noise_val;
	}
```

I have now learned the ways of the timer and keeping frequency regardless of samplerate

**Comment by RobinSchmidt** [comment]
i think, if the increment is larger than the range between min and max, you actually would have to account for two (or more) reflections within one sample (at the top and once again at the bottom). and if you fail to do that properly, things go out of hand.

**Comment by elanhickler** [comment]
I'd rather limit the frequency to sane values (i.e. half the samplerate). If you user wants more reflections per second then user should use oversampling.
