### ISSUE TITLE
Let's talk about pull requests.

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#86]
I just forked your repository so I can actually make changes. I've already created a pull request.

I can do pull requests for you.

I want to integrate Jerobeam algorithms. Where should I put them, how should I organize them? I will be making changes still to the algorithms to make them more efficient and easier to use so there will continue to be pull requests.

I may want to add more jura_StringTools functions.

We can work on your library together and get more accomplished. I don't need any credit for anything I do for your library.

**Comment by elanhickler** [comment]
and omg this code is horrible, I could improve this:
```cpp
String midiNoteToString(double midiNoteNumber)
{
  // This is stupid! We should use a StringArray!

  int intNoteNumber = (int) midiNoteNumber;
  switch( intNoteNumber )
  {
  case   0: return String("C-1");
  case   1: return String("C#-1");
  case   2: return String("D-1");
  case   3: return String("D#-1");
  case   4: return String("E-1");
  case   5: return String("F-1");
  case   6: return String("F#-1");
  case   7: return String("G-1");
  case   8: return String("G#-1");
  case   9: return String("A-1");
  case  10: return String("A#-1");
  case  11: return String("B-1");

  case  12: return String("C0");
  case  13: return String("C#0");
  case  14: return String("D0");
  case  15: return String("D#0");
  case  16: return String("E0");
  case  17: return String("F0");
  case  18: return String("F#0");
  case  19: return String("G0");
  case  20: return String("G#0");
  case  21: return String("A0");
  case  22: return String("A#0");
  case  23: return String("B0");
...etc.
```

**Comment by elanhickler** [comment]
scratch that, my changes still don't all me to use jura_StringTools, wtf.

**Comment by RobinSchmidt** [comment]
yes - that code is horrible - as i said myself in the comment. soo...should i not pull in your change? does it not work?

**Comment by elanhickler** [comment]
it all works, it's just I can't access your string functions for some reason from my code base. so yes pull, but I dunno why *I* can't use it.

**Comment by elanhickler** [comment]
ok, you successfully pulled my requests, closing this thread. This issue has fulfilled its purpose.
