### ISSUE TITLE
need scrollbar for dropdown! 

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#89]
where's the scrollbar at!?!?

![image](https://user-images.githubusercontent.com/9116575/30947236-5c89e3b4-a3bd-11e7-910b-a475e1057950.png)

**Comment by elanhickler** [comment]
and how do I do this lovelyness!!!!!! 
![image](https://user-images.githubusercontent.com/9116575/30948267-8bdf5440-a3c3-11e7-8655-97f63ca6933d.png)

**Comment by elanhickler** [comment]
just finished the midi modulator, you should steal it and put it in your library. 👍 

![image](https://user-images.githubusercontent.com/9116575/30949567-0fae4602-a3cc-11e7-99b4-087ff26ef504.png)
![image](https://user-images.githubusercontent.com/9116575/30949576-1be58c0a-a3cc-11e7-9d45-fd2cd279c00c.png)
![image](https://user-images.githubusercontent.com/9116575/30949579-2196f116-a3cc-11e7-8792-30f84c29b469.png)
![image](https://user-images.githubusercontent.com/9116575/30949584-29d89924-a3cc-11e7-85e6-0c696eabf958.png)

**Comment by elanhickler** [comment]
I just had a frikkin brilliant idea for Liberty. So, i created this little midi module, right? It would be sweet to have that in Liberty, but when you put it in liberty you get a box with sliders instead of the ambiguous box with a bunch of inputs and outputs. It would be super convenient to have the option of having sliders right on the object. This should be optional as it's would not always be desired. It would help in creating a GUI with liberty... out of little synthesizer components like the midi mod source. Anyway, just some thoughts.

**Comment by elanhickler** [comment]
robin plz tell me how to deal with my midi mod src list, where is there no scrollbar?

**Comment by RobinSchmidt** [comment]
yeah...the combobox was so far not really equipped to deal with such long lists of options - it just adjusted its height such that all options fit in. i have no introduced a setMaxPopUpSize function for RComboBox. call it to limit the size and then the scrollbar should appear when the options don't fit into the given max-size

**Comment by RobinSchmidt** [comment]
as for the treeview: hmm...currently also the combobox assumes a linear list. when i create treeview-boxes, i do so by subclassing and creating the treeview directly in my subclass. do you want treeview dropdown menus. maybe i can integrate it. i must think about it

**Comment by RobinSchmidt** [comment]
in liberty, you already have the various "event" modules. the idea here is to not have a generic midi module that handles all events but specific modules for specific events. for example, there's the NoteFrequency module that always outputs the frequency of the current note in Hz

**Comment by RobinSchmidt** [comment]
sliders on the object? like, the parameter module should *be* a slider?

**Comment by elanhickler** [comment]
> sliders on the object? like, the parameter module should be a slider?

no, just imagine my midi object inside liberty, except instead of a generic box in the liberty module wiring section, you actually see the sliders right there on the module.

**Comment by elanhickler** [comment]
so... your parameter module has sliders in the GUI/slider window.

Oh yeah, your parameter module should probably also appear as a slider too... or a knob.
