### ISSUE TITLE
How do you set minimum width/height for editor?

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#96]
need minimum width height for my plugins.

**Comment by RobinSchmidt** [comment]
ok, i'll add something to the framework for this

**Comment by RobinSchmidt** [comment]
OK, after you do "createPluginWithMidi" (or whatever function you use to assign this "dummy" pointer in the plugin creation code), call "setEditorSizeLimits" on the object. let me know, if it works - i didn't test yet, but it was so simple, it should just work ...hopefully

**Comment by elanhickler** [comment]
works. close.
