### ISSUE TITLE
oversampling filter with subdivision of 1 costs CPU?

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#98]
Will I save CPU if I bypass the antialias filters if oversampling is 1?

![image](https://user-images.githubusercontent.com/9116575/31409777-dc146790-adc1-11e7-8926-7f4186912fed.png)

**Comment by RobinSchmidt** [comment]
yes. and you will also get a cleaner signal, i guess. the filter does change the signal a bit - because the transition band begins slightly below 0.5*sampleRate/oversamplingFactor. i'm currently using 0.9 as factor, so you actually get a lowpass at around 20kHz at 44100

**Comment by RobinSchmidt** [comment]
rosic_EllipticSubBandFilter.cpp, line 51 ff
```cpp
  // calculate the desired cutoff frequency of the denormalized analog filter
  double wd = (0.9*PI)/subDivision;        
   // normalized digital radian frequency - this factor of 0.9 is kinda arbitrary, ideally we 
   // would want to set a factor such that the stopband begins exactly at PI/subDivision (whereas 
   // here we are dealing with the end of the passband)
```

**Comment by RobinSchmidt** [comment]
if you wonder, why i don't do this check-and-bypass myself in the filter class, i think it is because of the overhead of the additional conditional which i like to avoid when using the filter in a context with a fixed oversampling factor
